### ISSUE TITLE
Debian packaging: i3ipcpp and xpp

### ISSUE THREAD

**Issue by jpleau** [polybar/polybar#1054]
Hi.

I'm starting to pickup my work at packaging polybar for Debian/Ubuntu. The one issue I have at the moment is the embedded libraries in the lib/ directory. I would like to package them separately (i3ipcpp and xpp). I saw that both are forked, and have more code than the original repositories (drmgc/i3ipcpp and jotrk/xpp)

I have a few options:

A) Use your forks (and point to your repos as upstream)
B) Use the original repos, but we wouldn't have the changes needed to make polybar work at 100% likely
C) Use the original repos and carry the diff from your repos as patches (I don't like this suggestion at all)
D) Ask here if it's possible to merge every back to the original repos (I highly doubt this can happen)

What of the above is the one I should pick? I'm open to other suggestions as well.

**Comment by NBonaparte** [comment]
A is the best option. I don't think B and D would work either, and C just looks like a mess.

Is what you said in #447 still relevant?

**Comment by jpleau** [comment]
Hi.

Yes it's still relevant, but once I package i3ipcpp and xpp (using your forked repos), all should work fine.

I might need a bit of help to make sure I use the installed libraries on the system (instead of the ones shipped in the tarball), but I'll ask when the time comes :)

**Comment by patrick96** [comment]
Hmm, the jsoncpp tarball in the repo is totally useless, I've opened a PR to remove it.

Why do you want to package xpp and i3ipcpp separately? I understand that you can't download anything during the build process, but couldn't you provide the whole polybar repo (including the submodules) to the build servers? I don't know anything about the build process for official debian (or ubuntu for that matter) packages, so what I proposed could not work at all. 
Can you give me a quick run through? Are there any constraints on what type of files you can put on the build server or where they come from?

I agree with @NBonaparte that A would work best, if you want to package them separately.
Option D is unfeasible because the turnaround rate for PRs would be way to low. The original xpp is unmaintained and i3ipcpp has barely seen any activity in the last year. Option B probably also won't work, as the original xpp uses Makefiles instead of cmake. As for using upstream i3ipcpp, this one might actually work, however I see that debian has jsoncpp version 1.7.4, in our i3ipcpp fork, we build jsoncpp 1.7.7, if a more recent version is not available, so it is possible that there is some functionality that i3ipcpp uses but that isn't in 1.7.4 (I wasn't able to determine what that would be, but it is possible that jaagr discovered that there is).

**Comment by jpleau** [comment]
@patrick96 

I've considered using the embedded copies of i3ipcpp and xpp, however, in the case where another piece of software eventually used any of those, we'd have the same code twice in the repos. In an ideal world, both would be available as a shared library (I might work on that if you're open to it). 

The main reason though is security. If there is any vulnerability found, it's easier to patch one library than to patch every program that uses the library. (Obviously this isn't the case with static libraries..)

I'll try to get in touch with the folks maintaining jsoncpp to see if an update is planned soon, thanks for the tip.

**Comment by patrick96** [comment]
Does debian store both the .deb package and the sources it was built from in the repos? Then I understand why you want to avoid duplication.

>The main reason though is security. If there is any vulnerability found, it's easier to patch one library than to patch every program that uses the library. (Obviously this isn't the case with static libraries..)

I didn't think about that, but I guess it makes sense that you need to worry about security a lot more than we do in the official repos ;)
However, xpp is a header only library, so any security fix would require the recompilation of all dependent packages anyways. Also i3ipcpp only builds a static library and I don't know how much effort it would be to make it also build a dynamic one that you could then package.

You can check, if polybar compiles with the older jsoncpp version, by changing the following line in the `lib/i3ipcpp/CMakeLists.txt`:
```cmake
pkg_check_modules(JSONCPP jsoncpp>=1.7.7)
```
to
```cmake
pkg_check_modules(JSONCPP jsoncpp)
```

**Comment by jpleau** [comment]
Yes both the .deb and source are uploaded. The sources aren't installed on the end-user machines, but are available to anyone who wants them (apt-get source, or via https;//sources.debian.org)

I'll be starting work on those this week and let you know how it goes!

Thanks very much for your time and answers

**Comment by patrick96** [comment]
Glad to help, would be great to have polybar in the official debian repos (and maybe even ubuntu 😉)

If you have anymore questions or problems building, we're here to help

**Comment by jpleau** [comment]
Hi again.

I've started work on i3ipcpp, and so far I have a working package (builds and install the headers and static lib, I will send a PR for that for the 'install' target).

One of the remaining things to do is the copyright file. The "Debian Free Software Guidelines (DFSG)" requires that every file in the source has a license and authors / copyright. Now usually this is easy, but this is the first time working with a fork of a project.

How would you like me to approach this? If I had picked the original repo for example, I would have done:

```
Files: *
Copyright: Copyright (c) 2015 Sergey Naumov
License: Expat (for MIT)
```

There were probably different people sending PRs in your own repos, to different files, I'm just unsure how to approach this.

**Comment by NBonaparte** [comment]
From what I understand about copyright authorship, each contributor has the rights to his or her contributions, so this would theoretically mean that all trivial and non-trivial commits would have to be taken into account.

However, I've looked at the i3 and bspwm Debian packages and they only list the original author despite having numerous contributors.

In that case, I'd probably have drmgc and jaagr for i3ipcpp, and jotrk and jaagr for xpp, so the upstream and the fork creator would have the copyright.

Also, since I'm not too familiar with Debian packaging standards: are all contributors credited or is it usually just the owner, like i3 and bspwm?

**Comment by jpleau** [comment]
It's usually what is contained in the LICENSE file that is shipped. Sometimes though files contain copyright headers with different names, that's when we have to take that into account.

Maybe it could be a good idea to update the License file on both projects to reflect that

**Comment by patrick96** [comment]
I will open two PRs to update the license file with an additional copyright notice, as described in this [Stackexchange answer](https://softwareengineering.stackexchange.com/a/158011)

**Comment by jpleau** [comment]
Just a small update.

I have working packages for both xpp and i3ipcpp. Last time I worked on polybar I wasn't able to get it to work with a "system installed" version of xpp.

Will work a bit more this weekend on it and will ask here if I can't find a solution

**Comment by jpleau** [comment]
Update: I now have packages for i3ipcpp, xpp and polybar that build separately in chroots, and are used together.

I am working with another Debian developer to fix the remaining issues. So far I had to create a patch for polybar to use the system libraries.

**Comment by patrick96** [comment]
That's great to hear.

Just so you know, I'm not sure yet, if we'll want to add the ability for polybar to build against i3ipcpp and xpp packages instead of the submodules to mainline polybar. You may need to add the patches to the source code you upload to debian instead. Because this would just add another way the build process could go wrong when people have mismatched library version or something like this. Also we would now need to keep track of the SONAMEs for the shared libraries and actually have proper release processes for the two submodules. Would this be a problem for your packaging efforts?

Let us know, if we can help you with anything.

**Comment by jpleau** [comment]
Hi.

> Would this be a problem for your packaging efforts?

Not really, the patches I made are quite simple (mainly to the CMakeLists.txt files).

I'm still debating if I want to maintain 3 packages over one (with everything included). I had a script made that repacked the tarball with the submodules, but it was quite ugly (was hoping #1120 would be a solution!)

Still waiting on reviews from other Debian folks, but so far so good on my side.

Patches I have so far:

https://salsa.debian.org/jpleau-guest/polybar/blob/split_pkg/debian/patches/use_system_libs.patch
https://salsa.debian.org/jpleau-guest/i3ipcpp/blob/master/debian/patches/adjust_cmake.patch
https://salsa.debian.org/jpleau-guest/i3ipcpp/blob/master/debian/patches/build_shared_lib.patch

**Comment by patrick96** [comment]
A single package would certainly be easier to manage.

As for the script, the following four lines should be everything you need to get a tarball with all the sources.
```bash
set -e
git clone --branch 3.1.0 --recursive git://github.com/jaagr/polybar.git
find polybar -name ".git" -exec rm -rf {} \+
tar cf polybar.tar polybar
```

**Comment by patrick96** [comment]
Hey @jpleau are you still waiting on reviews from the Debian folks?

**Comment by jpleau** [comment]
Hi @patrick96 

Yes I am. However even if I was suggested by developers to split up the package, I probably don't have the time to manage all this split whenever a new polybar version comes out, I will definitely try to push for the "one package for everything" approach.

**Comment by patrick96** [comment]
> Yes I am.

Alright, just wanted to check in :)

> I will definitely try to push for the "one package for everything" approach.

For the sake of your sanity, I am glad you went this route.

**Comment by jpleau** [comment]
I actually haven't had the time to follow up, and to be honest the way it was suggested I package it would put a big burden on me.

I will probably go back to a single package, and upload it to a PPA for the time being..

I'll try to work on that in a not-so-long-future

**Comment by dannycolin** [comment]
Eh @jpleau I'm actually learning how to package for Debian and I'll be glad to help in the near future to maintain the package. 

Eh btw, are you the *jpleau* in #debian-quebec on IRC? FYI, my user is *sdk*.

**Comment by jpleau** [comment]
@dannycolin yes I'm in #debian-quebec :)

For info, the ITP is here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856179

**Comment by patrick96** [comment]
That would be awesome!

Just FYI, for distributed binaries the only optional dependency will be i3, all others (alsa, pulse, mpd, curl, libnl) will become hard dependencies, if polybar is compiled against them. This was discussed in #1406.

**Comment by jpleau** [comment]
Small update, I will have time to pursue this once again, I will first be creating an Ubuntu PPA (For 18.04, and 16.04 if it builds correctly), and move forward for an upload to Debian later on.

Sorry for the delays.

**Comment by patrick96** [comment]
That's cool :D

We're happy for everyone helping out, you really don't have to feel obligated to do this fast or even at all.

**Comment by KM4YRI** [comment]
@jpleau any update on this issue?

**Comment by jpleau** [comment]
I started clearing my backlog last weekend, polybar should be getting some attention soon. I've hit a few issues in the last couple months with different stuff, I had to put all my debian/ubuntu work on the burner for a bit. Sorry about that.

**Comment by samueloph** [comment]
I'm interested in helping with the Debian package, just pinged @jpleau and the ITP at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856179

**Comment by utkarsh2102** [comment]
Now we're fairly near to upload the package to the archive \o/

**Comment by iot-resister** [comment]
on raspbian I'm getting 

```
dpkg: warning: old libc6:armhf package post-removal script subprocess was killed by signal (Illegal instruc
tion)                                                                                                      
dpkg: trying script from the new package instead ...                                                       
dpkg: error processing archive /var/cache/apt/archives/libc6_2.30-4_armhf.deb (--unpack):                  
 new libc6:armhf package post-removal script subprocess was killed by signal (Illegal instruction)         
dpkg: error while cleaning up:                                                                             
 installed libc6:armh
Errors were encountered while processing:                                                                  
 /var/cache/apt/archives/libc6_2.30-4_armhf.deb                                                            
E: Sub-process /usr/bin/dpkg returned an error code (1)    
```


dmesg
```
[   19.009693] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1         
[   19.010217] usbcore: registered new interface driver brcmfmac                                           
[   19.347355] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1         
[   19.347586] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited 
channels available                                                                                         
[   19.351361] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 22 2019 01:59:28 version 7.45
.98.94 (r723000 CY) FWID 01-3b33decd 
```

**Comment by patrick96** [comment]
@iot-resister What does this have to do with polybar?
