### ISSUE TITLE
Show total of %upspeed% and %downspeed% as %netspeed%  in network module

### ISSUE THREAD

**Issue by udiboy1209** [polybar/polybar#1083]
I would like to see a single speed value for my wireless connection instead of having to display both speeds, which is possibly similar to %linkspeed% for wired connection. I can't figure out a way to do it currently using the network module, and I don't want to shift to a custom script implementation. A new label token called  `%netspeed% = %upspeed%+%downspeed%` would be nice.

Also, is it possible to display two different prefixes based on whichever is higher (upspeed vs. downspeed) when %netspeed% is used?

**Comment by patrick96** [comment]
I think `%linkspeed%` actually is the max speed of your interface, not the current rate. There is currently no way to do this inside polybar, but I see why it can be useful. I have added it to our list.

> Also, is it possible to display two different prefixes based on whichever is higher (upspeed vs. downspeed) when %netspeed% is used?

Why would you want that?

**Comment by patrick96** [comment]
Ah, you actually want a label that has two variants depending on which direction has a higher rate. I don't think this is something, we'll implement as, it's something extremely specific and most likely not something, a lot of people are going to use.

**Comment by prateekmedia** [comment]
Hi @patrick96 @udiboy1209, I have created a PR (#2590) for fixing this.
