### ISSUE TITLE
New module for gpu utilization

### ISSUE THREAD

**Issue by mirobertod** [polybar/polybar#1119]
Hi,
there isn't currently a module to show GPU utilization. It would be nice if there was.
Thank you

**Comment by patrick96** [comment]
Getting the GPU utilization is extremely difficult. Each gpu manufacturer has their own software that is needed to get that information (or even several pieces of software depending on the GPU model), also many of those tools require root privileges to run. While this would be a *very* nice feature to have, building such a module would take quite a long time and I'm not sure how we get around requiring root. I will leave this open as a feature request in case we want to come back to this, once we get some more time on our hands.

**Comment by x70b1** [comment]
We have [system-gpu-intel](https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/system-gpu-intel) in `polybar-scripts` now.

**Comment by x70b1** [comment]
And now [system-nvidia-smi](https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/system-nvidia-smi) in `polybar-scripts`.

**Comment by patrick96** [comment]
Closing this. We will not implement this inside polybar as there is no standardized way to get at this information without root.
