### ISSUE TITLE
Network module: failed to query interface

### ISSUE THREAD

**Issue by ArcticXWolf** [polybar/polybar#1211]
Hey,

I have a problem with the network module not working for my USB network interface.

This is a simple version config:
```
[colors]
background = #00000000
foreground = #ccffffff
dark-transparent = #40000000
focused-background = #99ffffff
focused-foreground = #cc000000
urgent-background = #99ff3333

[globalbars]
width = 100%
height = 50
radius = 0
fixed-center = true
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 0
border-color =
padding = 0
padding-right = 2
module-margin = 2
font-0 = "Source Code Pro Semibold:pixelsize=12;5"

[bar/top]
inherit = globalbars
padding-left = 0
background = ${colors.dark-transparent}
modules-left = network1
modules-center =
modules-right =
tray-position =

[module/network1]
type = internal/network
interface = enx949aa984ea97
unknown-as-up = true
interval = 3.0

format-connected-padding = 2
format-connected-prefix = " "
label-connected = %local_ip%

label-disconnected = "test"

[settings]
screenchange-reload = true

[global/wm]
margin-top = 0
margin-bottom = 0
```

The output of polybar top -s:
```
warn: No monitor specified, using "eDP1"
warn: module/network1: Failed to query interface 'enx949aa984ea97'
warn: module/network1: Failed to query interface 'enx949aa984ea97'
error: Disabling tray manager (reason: Invalid position "")
%{l}test
warn: module/network1: Failed to query interface 'enx949aa984ea97'
warn: module/network1: Failed to query interface 'enx949aa984ea97'
warn: Termination signal received, shutting down...
```

I debugged a bit myself and identified [the IOCTL call](https://github.com/jaagr/polybar/blob/095d68fad08c223bc924e63ce9ac1021bcbc2feb/src/adapters/net.cpp#L230) as the issue, the parsed errno is always "Operation not supported".

Now my question: Is this an issue with my driver or do I just lack some package dependency? Or is this a bug within ethtool or polybar?
I'm using Ubuntu 17.10.

Thanks!

**Comment by patrick96** [comment]
We had a similar issue in #351. The problem seems to be that `wireless_tools`, the tool we use for wireless support, doesn't support some USB interfaces. There is a PR in the pipeline to move to a newer tool (#1009), but it seems to have gone stale.

I don't know when this will be fixed, this is quite a big change.

**Comment by su8** [comment]
>the tool we use for wireless support

>There is a PR in the pipeline to move to a newer tool

The library :D

**Comment by patrick96** [comment]
Oh, I didn't look that closely at where the ioctl call was made. No, then this shouldn't have to do anything with wireless_tools
Then I suspect it has something to do with ethtool, what does `ethtool enx949aa984ea97` give you?

**Comment by ArcticXWolf** [comment]
Okay:
```
$ ethtool enx949aa984ea97
Settings for enx949aa984ea97:
Cannot get wake-on-lan settings: Operation not permitted
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes

$ sudo ethtool enx949aa984ea97
Settings for enx949aa984ea97:
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes
```

I then tried to run polybar with sudo, but the error remains.

**Comment by su8** [comment]
**linux/ethtool.h**:

```c
/* CMDs currently supported */
#define ETHTOOL_GSET		0x00000001 /* DEPRECATED, Get settings.
					    * Please use ETHTOOL_GLINKSETTINGS
					    */
```

@ArcticXWolf  can you replace the following line

https://github.com/jaagr/polybar/blob/095d68fad08c223bc924e63ce9ac1021bcbc2feb/src/adapters/net.cpp#L227

to `data.cmd = ETHTOOL_GLINKSETTINGS;`

**Comment by patrick96** [comment]
Good catch @su8, maybe we should change that.
I'm not sure if that's actually the cause of the problems @ArcticXWolf has because the output of `ethtool` on his system looks like the interface doesn't have many of those property accessible anyway. But please try to change that line and recompile anyway @ArcticXWolf.

For reference, when I run `ethtool` on my machine I get the following:
```
ethtool eno1
--------------------------------------------------------
Cannot get wake-on-lan settings: Operation not permitted
Settings for eno1:
	Supported ports: [ TP ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Full 
	Advertised pause frame use: No
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Speed: 1000Mb/s
	Duplex: Full
	Port: Twisted Pair
	PHYAD: 1
	Transceiver: internal
	Auto-negotiation: on
	MDI-X: on (auto)
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes
```

**Comment by ArcticXWolf** [comment]
I make this change, but as @patrick96 predicted, it does not change anything for me. So if I'm understanding it right, it is just the driver of the card not supporting ethtool?

**Comment by patrick96** [comment]
Yeah, it's either your driver or even some limitation on the hardware of your dongle.
The line that causes the failure is only used to detect the linkspeed for the `%linkspeed%` token. Maybe we can just skip that check and continue on normally, I don't know if the rest of the module will work properly though. Can you please try to change the `query` method to return true, even when the query fails:
```cpp
  bool wired_network::query(bool accumulate) {
...
    if (ioctl(*m_socketfd, SIOCETHTOOL, &request) == -1) {
      m_linkspeed = -1;
      return true;
    }
```

**Comment by ArcticXWolf** [comment]
Yes, that works. The error message is gone and it correctly displays my interface + ip + up/down status.

Shall I make a pull request? It might also be a good idea to throw a warning in this case here, so it is visible in the log, that you cannot grab the linkspeed on such an interface.

**Comment by patrick96** [comment]
I think it should even be a config option, something like `linkspeed-optional` which defaults to `false`, but if it's true, then even if the ioctl call fails, the module doesn't crash. If you have the time, I'd appreciate a PR. As for the warning, I agree, however query gets called periodically, so people's logs would get spammed with warnings, so we should maybe add a flag to the `wired_network` class so that we only display the query warning the first time.

**Comment by linosgian** [comment]
I ran into the same exact issue. Some useful info:
```
# lgian[~] → uname -a 
Linux lgian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
# lgian[~] → sudo ethtool -i enx3ce1a151496d
driver: cdc_ether
version: 22-Aug-2005
firmware-version: CDC Ethernet Device
# lgian → polybar --version
polybar 3.3.0-81-gf1061e1-dev
```
I am on a ThinkPad X1 Carbon 6th and a type-C docking station, with the ethernet cable on the docking station. The interface's driver does not expose any information, hence `ethtool` cannot list any details on the interface and the ioctl fails.

I was thinking about opening a PR for this. How would you want to handle ioctl's failure? I could also add the `linkspeed-optional` option

**Comment by patrick96** [comment]
@linosgian The more I think about it, the more I believe we should just set `%linkspeed%` to `N/A` or something like that if we can't query it, instead of crashing the module. A PR would be great :smiley: 

https://github.com/polybar/polybar/blob/b03f14400ae840f1b1057a4b9db2c3fbfe43a905/src/adapters/net.cpp#L272-L276

**Comment by DrSensor** [comment]
My USB tethering network interface still displayed as disconnected.
Are there any additional dependencies that I need to install?

```posh
$ polybar --version
polybar 3.5.4

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```
```posh
$ cat /sys/class/net/enp0s20f0u2/operstate
unknown
```
```posh
$ cat /sys/class/net/enp0s20f0u2/wireless
cat: /sys/class/net/enp0s20f0u2/wireless: No such file or directory
```
```posh
$ sudo ethtool enp0s20f0u2
Settings for enp0s20f0u2:
        Current message level: 0x00000007 (7)
                               drv probe link
	Link detected: yes
```
```posh
$ iw dev enp0s20f0u2 link
Not connected.
```
```posh
$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s20f0u2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether b6:b2:de:01:24:de brd ff:ff:ff:ff:ff:ff
    inet 192.168.42.56/24 brd 192.168.42.255 scope global dynamic noprefixroute enp0s20f0u2
       valid_lft 2078sec preferred_lft 2078sec
    inet6 fe80::9463:3da5:cd38:9add/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

**Comment by patrick96** [comment]
I think you need to set `unknown-as-up = true` in your network module

**Comment by xtccc** [comment]
> I think you need to set `unknown-as-up = true` in your network module

Thank you very much , It resovle  my usb interface not show in the polybar
