### ISSUE TITLE
[module/date] Zone and UTC feature support request

### ISSUE THREAD

**Issue by Dentrax** [polybar/polybar#1293]
Hello,

That's why I request to:

- Each user may want to see their own time zone. (Like I would like to see the time of Turkey and my brother may want to see Germany time.)
- We don't have to change the `zoneinfo` information from `/usr/share/` specially
- What time zone do we want to see ? LocalTime, UTC, Network Synched, etc...
- TimeZone offset support? UTC+1, UTC+2 like that.

Edit: Oh I forgot that trick, each user can have their own time zone. :)

Currently only localtime support is available with the [date] architecture. When we do `timedatectl`, there are few outputs:

```
Local time: Wed 2018-06-20 14:02:29 +03
Universal time: Wed 2018-06-20 11:02:29 UTC
RTC time: Wed 2018-06-20 14:02:29
Time zone: Europe/Istanbul (+03, +0300)
System clock synchronized: no
```

But Polybar uses localtime everytime as long as I do not sync with localtime to network time using timezones from mentioned here https://wiki.archlinux.org/index.php/Time#Time_zone

I don't think that's a rational solution for Polybar. The time module should be further improved. The module I designed in my mind is:

```
[module/date]
type = internal/date

; New date features
timezone = Europe/Istanbul ; from /usr/share/zoneinfo
timezoneoffset = +3, +2, 0, bla bla...
datetype = UTC, RTC, Local, Universal etc...
autosync = true ; Possibility of system time not synced


; Seconds to sleep between updates
interval = 1.0

; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %Y-%m-%d%

; Optional time format
time = %H:%M

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
date-alt = %A, %d %B %Y
time-alt = %H:%M:%S
```

All comments are welcomed. Thanks in advance! :)

**Comment by metinUr** [comment]
Yes, it could be better. Should be considered.

**Comment by Dentrax** [comment]
It is bad that this feature became inactive. But it could be a very life-saver feature. ;)

**Comment by Dentrax** [comment]
@NBonaparte The Polybar's time is always showing wrong. Although we use GMT+3, it shows 3 hours ahead.

My current time: 03.59
Should be: 00.59

`date && sudo hwclock --verbose && timedatectl status && ls -l /etc/localtime` output:

```
hwclock from util-linux 2.32
System Time: 1531702722.892406
Trying to open: /dev/rtc0
Using the rtc interface to the clock.
Last drift adjustment done at 1531701822 seconds after 1969
Last calibration done at 1531701822 seconds after 1969
Hardware clock is on local time
Assuming hardware clock is kept in local time.
Waiting for clock tick...
...got clock tick
Time read from Hardware Clock: 2018/07/16 03:58:43
Hw clock time : 2018/07/16 03:58:43 = 1531702723 seconds since 1969
Time since last adjustment is 901 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2018-07-16 03:58:42.499374+03:00
               Local time: Mon 2018-07-16 03:58:43 +03
           Universal time: Mon 2018-07-16 00:58:43 UTC
                 RTC time: Mon 2018-07-16 03:58:43
                Time zone: Europe/Istanbul (+03, +0300)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: yes

Warning: The system is configured to read the RTC time in the local time zone.
         This mode cannot be fully supported. It will create various problems
         with time zone changes and daylight saving time adjustments. The RTC
         time is never updated, it relies on external facilities to maintain it.
         If at all possible, use RTC in UTC by calling
         'timedatectl set-local-rtc 0'.
lrwxrwxrwx 1 root root 35 Jul 16 03:55 /etc/localtime -> /usr/share/zoneinfo/Europe/Istanbul

```

**Comment by duckie** [comment]
I workaround this by just setting the `TZ` env variable for polybar. Each user can have his/her own this way.

**Comment by patrick96** [comment]
Closing as @duckie's workaround is the best solution for the original issue.

**Comment by hatkidchan** [comment]
It's not a perfect workaround. For example, I really want to have two clocks with different timezones (I have a friend in different timezone and I don't want to offset it in my head every time). What works for me *for now* is [this](https://github.com/polybar/polybar/pull/1684#issuecomment-774757108) snippet

**Comment by VanillaViking** [comment]
Hi, I'm not sure if this is useful to you, but you could write a custom script like [this](https://github.com/VanillaViking/polybar-timezone-switcher-script), that basically runs the `date` command with a different TZ variable every time the module is clicked
