### ISSUE TITLE
Error when running launch.sh

### ISSUE THREAD

**Issue by kas** [polybar/polybar#1346]
Hello:

I get this error when running the `launch.sh` file:

`pgrep: invalid user name: -x`

Any ideas?

This is from i3-gaps running on Kubuntu 18.04.

Both i3-gaps and polybar were compiled instead of being installed from a .deb.

**Comment by su8** [comment]
Where is this script located @kas ? I couldn't find any **launch.sh** script.

**Comment by kas** [comment]
It is located near the top of the wiki homepage.

**Comment by su8** [comment]
On some systems **sh** is true shell , on others it's symbolic link to **bash**. You can check this out by typing `readlink /bin/sh`. Can you try changing the head of your script to:

>#!/bin/bash

and try running it again ?

**Comment by patrick96** [comment]
For some reason your the `$UID` environment variable isn't set when you run the script and that's why you get that error. Does that happen when you run the launch.sh script from the terminal?
