### ISSUE TITLE
Alsa is not working as it should with headphones

### ISSUE THREAD

**Issue by avently** [polybar/polybar#1397]
I have some issues related to Alsa. I'll describe what I do and what I'm getting

**Expected behavior:**

Module should enable/disable sound after one press on the volume icon; should show actual volume and state (muted or not) for current source (headphones or speaker) and current volume

**Actual behavior:**

It works randomly. Let's see what actually happens.

First, making a clean state of Alsa
`alsactl restore`

Then I see in Polybar actual volume (no headphones) and can change it via mouse wheel
Then I'm pressing on the volume icon
No sound
Pressing again
Sound appears. Everything is fine

Attaching headphones
Music is working and I can change volume, label the same as ramp-headphones-0
Pressing on the icon
No sound and label the same as `label-muted`
Pressing again. NO SOUND and label the same as `label-muted`
Mouse wheel doesn't help - no sound
Pressing again on the icon
Label now from `ramp-volume` with number % but HEADPHONES are attached
Detaching headphones

Sound is playing but icon shows muted state and I CAN adjust the volume with mouse wheel
Pressing on icon
Shows ramp-headphones-0 label with wrong volume and sound is playing
Pressing again and sound muted and label from muted state. Ok.

Attaching headphones again
No sound, icon shows muted state
Impossible to change volume. Icon after a few presses shows ramp-headphones-0 label with 0%

Detaching headphones. Sound appears.

To enable sound in headphones I should restart Alsa since without that action sound will never work.

## Polybar Config
```dosini
[module/alsa]
type = internal/alsa

master-soundcard = hw:0
speaker-soundcard = hw:0
headphone-soundcard = hw:0

master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 4

; the same issue with  = false
mapped = true
interval = 5

format-volume = <ramp-volume> <label-volume>

label-muted = 

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

ramp-headphones-0 = 
ramp-headphones-1 = 
```

## Environment:
polybar 3.1.0-140-g067aac1

Features: +alsa +curl +i3 +mpd +network +pulseaudio

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

**Comment by albakham** [comment]
Exact same problem, it would be great to have a fix
