### ISSUE TITLE
Configurable double-click timeout

### ISSUE THREAD

**Issue by dkasak** [polybar/polybar#1441]
It's sometimes hard for me to trigger the double-click consistently due to the short timeout. If I'm reading the code right, it seems it's currently set to 150ms? It would be nice if this was configurable.

**Comment by rien333** [comment]
Still, this would be nice to have. I miss the time frame window more than half the time because it seems to be ridiculously fast.

**Comment by dkasak** [comment]
@rien333 I agree. I just encountered this again in a situation where the left-click is set to a somewhat destructive but common operation and the double-click to a less common, but non-destructive one. I'm reopening the issue.

**Comment by jaredmcqueen** [comment]
would love to increase the double-click delay.  You have to be lightning fast to get it.
