### ISSUE TITLE
Transparency only when one window is open ?

### ISSUE THREAD

**Issue by marie-bnl** [polybar/polybar#1468]
## Is your feature request related to a problem? Please describe.
No

## Why does polybar need this feature?
It's more beautiful and sweet

## Describe the solution you'd like
I'd like to have the transparency only when one window is open because that's weird to see my background above the window and not around. Also I'd like to have trnasparency when no window are open because it's beautiful and when two windows or more are open because I have smart_gaps between the windows (on i3)

## Screenshot
I edited the config between the screenshot 
![screenshot](https://user-images.githubusercontent.com/39555268/46920459-d5be8880-cfee-11e8-9838-d615a5662cfd.png)
![screenshot](https://user-images.githubusercontent.com/39555268/46920468-f8e93800-cfee-11e8-81fc-b020b4af12c0.png)
![screenshot](https://user-images.githubusercontent.com/39555268/46920477-10282580-cfef-11e8-9bc1-6c0ad1c0038d.png)

**Comment by NBonaparte** [comment]
TBH I don't see this feature being regularly used. Couldn't you write a script or program that draws a window (blank bar or plain X11 window) the same size as the bar behind it, or even have two different wallpapers?

**Comment by TheDevKiller** [comment]
Thank for your solutions, I'll try this but I think later it can be very cool if you add the functionality. And it's regularly used on Gnome, the default bar is transparent on the desktop (I think 50% of opacity) and when there is a full-screen windows the bar is Grey like the title bar.
In a nutshell, I think the best is add this functionality to polybar
