### ISSUE TITLE
Packaging for Manjaro

### ISSUE THREAD

**Issue by fhdk** [polybar/polybar#1509]
Thank you for your excellent work

@patrick96 
As you know I am packaging polybar compiled with all dependencies.

The PKGBUILD is located at Manjaro Gitlab
https://gitlab.manjaro.org/packages/community/openbox/polybar.git

Per recommendation it includes all libraries as dependencies.
As per your suggestion you would keep me in the loop for breaking changes in dependencies.

**Comment by patrick96** [comment]
Thank you very much for managing the manjaro package. We will inform you about dependency changes on every release.

Please also use this issue for any packaging problems you run into.

**Comment by patrick96** [comment]
@fhdk we have released polybar version [3.3.0](https://github.com/jaagr/polybar/releases/tag/3.3.0).

Nothing about the build process has changed. We have added libxcb-composite as a dependency, but in most systems (in manjaro as well) it's part of libxcb (The only exception so far being systems using apt).

**Comment by fhdk** [comment]
Thank you. Rebuild and release to unstable branch.

**Comment by patrick96** [comment]
@fhdk We have released version [3.4.0](https://github.com/polybar/polybar/releases/tag/3.4.0). There are no new dependencies. But we have fixed a compilation issue with gcc9 and also removed `-Werror` from the release flags so that new compiler warnings don't break builds in the future, so if you added something like `-Wno-deprecated-copy` to the compiler flags to temporarily fix the build you can remove it now.

**Comment by fhdk** [comment]
@patrick96 
Thanks - Is is now in Manjaro unstable

**Comment by patrick96** [comment]
Something I forgot to mention, this new release now requires `python-sphinx` as a build dependency to build the manpages and documentation

**Comment by patrick96** [comment]
@fhdk We have just released version [3.4.1](https://github.com/polybar/polybar/releases/tag/3.4.1).

The main change for you is that we have now dropped python2 as a build dependency.

**Comment by patrick96** [comment]
@fhdk I have created a pinned issue where we will from now on inform packagers about new versions. Please subscribe to #1971.

I will close this issue. But feel free to comment here if you experience any problems packaging polybar in the future.
