### ISSUE TITLE
Separate hard and soft dependencies in cmake

### ISSUE THREAD

**Issue by patrick96** [polybar/polybar#1536]
hard dependencies like xcb-randr or xcb-composite shoud be impossible to disable or cmake itself should fail when you try (as opposed to the compilation failing when `randr.hpp` is included).

Soft dependencies should work as before.

With this we can give more informative error messages instead of the user hitting
```
 #error "X Composite extension is disabled..."
```
10 times during compilation.

I don't think we should remove the `WITH_XRANDR`, `WITH_XCOMPOSITE`, etc. `#define`s entirely but still use them for `polybar -vvv`.

Ref #1430

**Comment by Lomadriel** [comment]
I tried to address this problem in #1807.

**Comment by J-J-Chiarella** [comment]
Note: the title should be "separate." The misspelling makes this issue unsearchable if one types in "separate hard and soft."

**Comment by J-J-Chiarella** [comment]
Well, it is searchable now because of my comment. After the title is fixed, I will delete my comment (and this one, too).

**Comment by patrick96** [comment]
@J-J-Chiarella Thanks, I automatically write it like this if I don't think about it, it's a bit annoying :smile:
