### ISSUE TITLE
Battery never marked as full

### ISSUE THREAD

**Issue by howardjohn** [polybar/polybar#1622]
## Describe the issue
Using the battery module and `full-at`, the `format-full` format is never used.

**Expected behavior:**
When the battery level passes the `full-at`, `format-full` format should be used.

**Actual behavior:**
The `format-full` format is never used.

**Was it working before?**
Never worked for me.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 90

format-charging = charging
format-discharging = discharging
format-full = full
```

## Polybar Log
No errors.

## Environment:
* WM: i3
* Output of `polybar -vvv`:
```polybar 3.3.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
```
$ cat /sys/class/power_supply/BAT0/status
Unknown
```
I have a two battery setup (Thinkpad t450s)

**Comment by patrick96** [comment]
> **Actual behavior:**
The format-full format is never used.

What format is displayed?

There are a few PRs that tackle this issue I think (#1286, #725, and #1438), we will need to reconcile all those changes. This will probably take some time becaue we're all quite busy and I don't experience this issue on my laptop which is why I can't just test the changes.

**Comment by howardjohn** [comment]
The `format-discharging` is used.

**Comment by patrick96** [comment]
So the battery is actually connected to a power source but `format-discharging` is used?
Does your laptop have two batteries?

**Comment by howardjohn** [comment]
Yes. The state will be set to unknown at least some of the time which is probably related

**Comment by patrick96** [comment]
> Yes.

To which of my two questions does this belong?

**Comment by howardjohn** [comment]
Sorry that wasn't clear. I have 2 battery's (Thinkpad) and if I am connected it uses the connected format fine
When I am not connected but full battery it uses discharging, not format-full.

**Comment by dkrieger** [comment]
This also applies when setting an upper threshold for battery charging using tlp (may be a thinkpad-only feature). Mine is set to stop charging at 85%, which puts the battery in Unknown state. If there could be a `format-unknown` option, both cases could be handled.

**Comment by mrquincle** [comment]
Confirm. Lenovo Yoga 3 displays Unknown when it is fully charged and AC is still attached.

```
➜  ~ cat /sys/class/power_supply/BAT1/uevent
POWER_SUPPLY_NAME=BAT1
POWER_SUPPLY_STATUS=Unknown
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-poly
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=7600000
POWER_SUPPLY_VOLTAGE_NOW=8438000
POWER_SUPPLY_POWER_NOW=0
POWER_SUPPLY_ENERGY_FULL_DESIGN=66000000
POWER_SUPPLY_ENERGY_FULL=51670000
POWER_SUPPLY_ENERGY_NOW=51580000
POWER_SUPPLY_CAPACITY=99
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=BASE-BAT
POWER_SUPPLY_MANUFACTURER=LGC
POWER_SUPPLY_SERIAL_NUMBER=123456789
```

Just adding `format-unknown` would be perfect.

**Comment by ThomasLachaux** [comment]
I have a lenovo ideapad and I have the same problem. It would be great to add this functionnality

**Comment by pottom** [comment]
I have almost same problem on my laptop. I have Dell Latitude 5491.
When the battery is in full state my polybar showing label-discharge and not the label-full. As you can see the only difference from your experience my POWER_SUPPLY_STATUS=Full

`$ cat /sys/class/power_supply/BAT0/uevent                                                       130 ↵
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Full
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=7600000
POWER_SUPPLY_VOLTAGE_NOW=8668000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=8947000
POWER_SUPPLY_CHARGE_FULL=8947000
POWER_SUPPLY_CHARGE_NOW=8947000
POWER_SUPPLY_CAPACITY=100
POWER_SUPPLY_CAPACITY_LEVEL=Full
POWER_SUPPLY_MODEL_NAME=DELL MT31P91
POWER_SUPPLY_MANUFACTURER=Samsung SDI
POWER_SUPPLY_SERIAL_NUMBER=34339`

Polybar config
`[module/battery]
type = internal/battery
full-at = 99
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1
poll-interval = 5
format-discharging = <ramp-capacity> <label-discharging>
label-charging =  %percentage%%
label-discharging = %percentage%%                                                                       
label-full =  
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = bar-capacity-width = 10`

**Comment by asparagii** [comment]
I have the same problem with a Dell XPS15, and I have only 1 battery.
Polybar displays the battery status as  "discharging"

```
$ cat /sys/class/power_supply/BAT0/uevent 
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Full
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11400000
POWER_SUPPLY_VOLTAGE_NOW=13035000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=8509000
POWER_SUPPLY_CHARGE_FULL=8273000
POWER_SUPPLY_CHARGE_NOW=8273000
POWER_SUPPLY_CAPACITY=100
POWER_SUPPLY_CAPACITY_LEVEL=Full
POWER_SUPPLY_MODEL_NAME=DELL GPM0365
POWER_SUPPLY_MANUFACTURER=SMP
POWER_SUPPLY_SERIAL_NUMBER=1584
```
Polybar config (the most minimal)
```ini
[bar/main]
width = 100%
height = 27
modules-right = battery
separator = " | "

[module/battery]
type = internal/battery
battery = BAT0
format-charging = Charging
format-full = Full
format-discharging = Discharging
```

**Comment by andrewzah** [comment]
I have the same issue on debian 10 / dell xps 13. Battery is full & connected (100%) but state shows discharging.

**Comment by FranciscoDumont** [comment]
> I have the same issue on debian 10 / dell xps 13. Battery is full & connected (100%) but state shows discharging.

I'm having the same issue on Manjaro / Thinkpad T470
