### ISSUE TITLE
Set bar to bottom of window stack

### ISSUE THREAD

**Issue by rogierreerink** [polybar/polybar#1657]
The problem is that a window that's under a transparent bar is not visible through the transparent bar. To solve this problem AND just because I think it would look cool, I would like to have the option to stack the bar to the bottom of the window stack. Just like is possible with tint2.

I don't know exactly how many people would like to see this feature. But if I think of all the r/unixporn people I've seen that generate a background image containing status-like information every second, I guess more than just me!

Solution: option like "panel_layer = bottom || top" in the bar config.
Technically, I wouldn't know how to implement this exactly. It might have something to do with "bar::restack_window()" in "src/components/bar.cpp"? XCB_CONFIGURE_WINDOW lets you set the window stacking order. Again, I don't really know.

![polybar](https://user-images.githubusercontent.com/15676084/53052204-59591c00-349e-11e9-88c1-2fd03ee07bec.png)
![tint2](https://user-images.githubusercontent.com/15676084/53052205-59591c00-349e-11e9-99d1-6fd80d24e30f.png)

**Comment by patrick96** [comment]
As far as I can tell, restacking to the bottom of the window stack is specific to the window manager. We already offer such restacking for i3 and bspwm with the `wm-restack` option. So what you are asking is a `wm-restack` option for your WM. What WM are you using?

You mentioned that tint2 provides this feature. I will have to look at the source code to see if they have found a general way to do restacking.

**Comment by patrick96** [comment]
From reading the [EWMH spec](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#STACKINGORDER), I think we could set `_NET_WM_STATE_BELOW` (this is also what tint2 does). I need to toy with this a little bit, maybe this could partially replace `wm-restack`.

**Comment by rogierreerink** [comment]
Awesome! I use OpenBox, if that's still relevant.

**Comment by patrick96** [comment]
You can define the stacking behavior inside openbox. See [this](https://www.reddit.com/r/Polybar/comments/8mtirz/can_i_make_polybar_go_below_windows) reddit post.

**Comment by rogierreerink** [comment]
Thanks! This solution works except for the system tray, which stays on top of all windows. I've tried 'obxprop'-ing it, but it doesn't have a window ID.

**Comment by patrick96** [comment]
We are working on correcting the stacking behavior of the tray. But it should have a window id, try running`xwininfo -root -tree`

**Comment by rogierreerink** [comment]
That works! The tray does not have OB properties, though. I've tried setting it manually, configuring OpenBox to lower it on the stack and restarting OpenBox.

`xprop -name "Polybar tray window" -f _OB_APP_CLASS 8u -set _OB_APP_CLASS "Polytray"`

_rc.xml_
`<application class="Polytray">
    <layer>below</layer>
</application>`

`openbox --restart`

I don't get it to work, but it would be a messy solution anyway.

**Comment by patrick96** [comment]
Oh, I see. I thought `<application>` matches things like `WM_CLASS` and not openbox's built-in properties. The reason for this is that the tray always has `override-redirect` enabled which causes openbox to ignore it. We'll have to wait for me to finish #1615
