### ISSUE TITLE
Offset tag doesn't work as indicated in the documentation

### ISSUE THREAD

**Issue by Lomadriel** [polybar/polybar#1700]
## Describe the issue

When I use the `%{O}` tag it moves the whole block and not only the text to its right.

**Expected behavior:**

The `%{O}` tag only move the text to its right as the documentation said:

> ## Offset `%{O}`
> %{O10} pushed 10 pixels to the right %{O-5} 5 pixels to the left

**Actual behavior:**

The whole block is moved. By example if I use `"%{O10} move right %{O-5} move left"`, the whole block is moved 5 pixels to the right (10-5).

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar? Don't know
* If no, what was the last version where this worked correctly? Don't know

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/example]
width = 100%
height = 27

font-1 = fixed:pixelsize=10;1
font-0 = Inconsolata:style=Bold:pixelsize=13;2
font-2 = siji:pixelsize=10;1

modules-left = label_test
modules-center =
modules-right =

[module/label_test]
type = custom/text
content = %{O10} pushed 10 pixels to the right %{O-5} 5 pixels to the left

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

```
## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
* Loading config: /home/loma/Code/repositories/polybar/doc/config
- config: Current bar section: [bar/example]
* Loaded monitor eDP-1 (1920x1080+0+0)
* Bar geometry: 1920x27+0+0; Borders: 0,0,0,0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules
* Starting application
- controller: Main thread id = 1
* Starting module/label_test
- module/label_test: Thread id = 2
* Eventqueue worker (thread-id=3)
* Entering event loop (thread-id=1)
- bar: Create renderer
- controller: Attach config watch
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- renderer: Load fonts
* Configured DPI = 96x96
* Loaded font "Inconsolata:style=Bold:pixelsize=13" (name=Inconsolata, offset=2, file=/usr/share/fonts/TTF/Inconsolata-Bold.ttf)
* Loaded font "fixed:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "siji:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Bar window: 0x3a00001
- bar: Reconfigure window
- bar: Set window WM_NAME
- bar: Set window _NET_WM_WINDOW_TYPE
- bar: Set window _NET_WM_STATE
- bar: Set window _NET_WM_DESKTOP
- bar: Set window _NET_WM_PID
- bar: Map window
- bar: Draw empty bar
- bar: Setup tray manager
* Disabling tray manager (reason: missing `tray-position`)
* module/label_test: Rebuilding cache
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=473x27+0+0, falloff=0)
- bar: Received expose event
```

## Screenshots
![polybar](https://user-images.githubusercontent.com/10365269/54577744-5ab13200-49d3-11e9-9f2b-2c2dce360b61.png)

## Environment:
* WM: i3 version 4.16.1 (2019-01-27)
* Distro: ArchLinux 5.0.2-arch1-1-ARCH x86_64
* Output of `polybar -vvv`:
```
polybar 3.3.0

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```
or (current master)
```
polybar 3.3.0-44-gded7a4f-git

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: Debug
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: 
```
 
## Additional context
While this problem isn't resolves #1671 is blocked. If this is really a bug and not the standard behavior, I can try to fix this bug in #1671 (since I need to modify the `%{O}` tag to add pt support)

**Comment by patrick96** [comment]
I don't see anything wrong with your example, consider:

`%{O100} move right %{O-100} move left`, here the block itself is moved to the right 100px while `move left` is moved back again 100px making it overlap with `move right`. This seems to be consistent with what lemonbar does.

But the `O` tag does have some problems, mainly that it doesn't use the current background color but rather the bar background color.

With the following string:

```
%{O100}Filler%{B#ff0000 O100}First%{O200}Second%{O-100}
```

I get this with polybar:
![bg](https://user-images.githubusercontent.com/2452038/54704203-96b2d700-4b3a-11e9-9d05-3cc89f2f946b.png)

but it should actually look like this (as it does with lemonbar):
![bg_lemonbar](https://user-images.githubusercontent.com/2452038/54704242-a4685c80-4b3a-11e9-94e1-72f00e4649fd.png)

This happens because polybar just advances the render position instead of rendering a solid square.

**Comment by Lomadriel** [comment]
Hum, my bad I figured the problem, I also noticed the problem with the color. I'll try something.
