### ISSUE TITLE
ramp and animation stage weights

### ISSUE THREAD

**Issue by kkhan01** [polybar/polybar#1750]
## Is your feature request related to a problem? Please describe.
The main module I encountered this to report by was battery, but I can see this as a helpful feature in general. I was getting frustrated at writing out the same bit of line 20 times in order to accomplish what I wanted. Eg, I currently have 
```
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-0-foreground = ${color.red}
ramp-capacity-1-foreground = ${color.yellow}
ramp-capacity-2-foreground = ${color.lgreen}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-0-foreground = ${color.blue}
animation-charging-1-foreground = ${color.blue}
animation-charging-2-foreground = ${color.blue}
animation-charging-framerate = 750
```
The effect I want to achieve is likely going to be that <= 5% should be red, 5 - 25 yellow, 25 - 85 green, and 85+ a different shade of green (the colors aren't support important, I'm still playing with them). The current status quo for ranges seems to be from issue https://github.com/jaagr/polybar/issues/63 where we would have to define at least 20 different ramp capacities and each one's foreground color. 

## Why does polybar need this feature?
There are times when we have a lot of repetitive code that could've been written in exponentially shorter number of lines. In addition, it provides for more... dynamic code. Eg, the battery solution could be written as:
```
for i in range(5):
    ramp-capacity-$i$ = 
    ramp-capacity-0-foreground = ${color.red}
for i in range(5, 25):
    ramp-capacity-$i$ = 
    ramp-capacity-0-foreground = ${color.yellow}
for i in range(25, 85):
    ramp-capacity-$i$ = 
    ramp-capacity-0-foreground = ${color.lgreen}
for i in range(85, 100):
    ramp-capacity-$i$ = 
    ramp-capacity-0-foreground = ${color.green}
```
Now, we'd only have to change one line to change a whole range's values. (this could have been done with 2 loops admittedly for actually 20 ramps, but I did it for uniformity for the example)
## Describe the solution you'd like
I discuss these in the other headings :upside_down_face: 

## Describe alternatives you've considered
The easiest solution would be to just write my statements out 20 times and use regex replaces. I've considered possibly a custom script, but that sort of defeats the purpose of various modules (like battery). My other solution was writing a python program or of the sort and having it output the lines we can replace. These are obviously less attractive than actual loop functionality.

## Additional context
I realize this feature could be fatally flawed. It would be best to limit the loops to be `for loops`, iterating over only over ranges. A normal loop like `for(int i = 0; i < 5; i++)` or while loop could hold potential to have flawed logic and fail horribly (eg `for(int i = 0; i > 5; i++)`). These should probably be interpreted statically (ie if it makes sense that the loop creates 5 lines, then the loop *always* has those 5 lines, and not 10 in a different minute or something).

**Comment by dannycolin** [comment]
> this could have been done with 2 loops admittedly for actually 20 ramps

FYI, You could achieve it in 6/7 lines 

```
ramp-capacity-1 = red
ramp-capacity-2 = yellow
ramp-capacity-3 = yellow
ramp-capacity-4 = light green
ramp-capacity-5 = light green
ramp-capacity-6 = green
```

Granted it's hard to divide 100 by 15 but you could use 10 or 20 :).

If the maintainers think it's a nice to have feature, I think to use a more INI format syntax the following code could be used instead of the `for` loop : 

```
ramp-capacity[0][5]    = ...
ramp-capacity[5][25]   = ...
ramp-capacity[25][85]  = ...
ramp-capacity[85][100] = ...

ramp-capacity-foreground[0][5] = ...
...

**Comment by kkhan01** [comment]
Mhm, i can see this working with 6/7 for my usecase though I wouldn't like the math (OCD like that hehe). 
> FYI, You could achieve it in 6/7 lines

But, you'd still have double the lines actually, since we need to set the icons too. I like that syntax though. Goes well with my additional context portion, taking out the logic to ensure some degree of safety. I may add in using some more delimiters like `$$` or something, to make it clear that "this region will get expanded over ranges". Just a few thoughts, I'd love it if this got implemented, rather than having to use janky solutions :weary:

**Comment by dannycolin** [comment]
> But, you'd still have double the lines actually

Your example has 12 lines and mine would have 12 too with the `-foreground`. That's why I've proposed a version with `[n][n]`. Like I said, it respect the current polybar config syntax and it's shorter :).

See: 

```
ramp-capacity-1 = icon
ramp-capacity-2 = icon
ramp-capacity-3 = icon
ramp-capacity-4 = icon
ramp-capacity-5 = icon
ramp-capacity-6 = icon
ramp-capacity-1-foreground = red
ramp-capacity-2-foreground = yellow
ramp-capacity-3-foreground = yellow
ramp-capacity-4-foreground = light green
ramp-capacity-5-foreground = light green
ramp-capacity-6-foreground = green
```

**Comment by patrick96** [comment]
I understand the underlying issue that it's tedious to write out ramps. But I don't think loops are the solution. While adding them would give the user a lot of flexibility to dynamically define configs, it would fundamentally change how the config works. Right now configs are processed line-by-line and are static, this would make them dynamic and we can no longer rely on every line being independent. It would also add more complexity to writing configs since it would be more like a program than a file that defines key-value pairs.

The main reason why you requested this feature seems to be having a gradient-like behavior in ramps. This could also be achieved by for example adding the ability to give different "weights" to the ramp stages which define the size of the interval of that ramp stage. This would be similar to @dannycolin's suggestion but could be applied to an entire ramp stage and we wouldn't need to do a lot of math to get the intervals right. Example:

```dosini
ramp-capacity-0-foreground = red
ramp-capacity-0-weight = 1
ramp-capacity-1-foreground = yellow
ramp-capacity-1-weight = 2 ; This stage will be displayed for twice as long as stages with weight 1
ramp-capacity-2-foreground = light green
ramp-capacity-2-weight = 4
ramp-capacity-3-foreground = green
ramp-capacity-3-weight = 1
```

Weights would be relative, so in this example red would be shown in `[0, 12.5]`, yellow in `[12.5, 37.5]`, light green in `[37.5, 87.5]` and green in `[87.5, 100]`

**Comment by kkhan01** [comment]
Sounds good, I'm not too familiar with the polybar code (I recently got into configing it afterall), but this seems to accomplish what I want and since you seem to be a solid contributor, I trust this is more doable and practical with the code base.

Should I make this a feature request issue?

**Comment by Lomadriel** [comment]
No need I think.

**Comment by TheDoctor314** [comment]
Hi! Is it okay if I work on this?

**Comment by patrick96** [comment]
@TheDoctor314 Yes! That would be great :)

There are some things to keep in mind. Also in the next proper relase (3.6.0), will be slight changes to the ranges of the individual ramp elements. The first ramp element covers everything at and below the start of the ramp range and the last element covers everything at and above the end of the ramp range. The remaining ramp elements in between evenly divide up the ramp range itself. For example in the temperature module, the first ramp element will be display for all temperatures `<= base-temperature`, the last element for everything `>= warn-temperature`, and one of the other ramp elements is displayed for all temperatures `base-temperature < x < warn-temperature`

So for these two "special" ramp elements, ramp-weights don't really make sense.

Also make sure that your changes don't change existing behavior or at least only in a small way that will not completely break someone's config.
