### ISSUE TITLE
"Expanding" modules?

### ISSUE THREAD

**Issue by 403-html** [polybar/polybar#1763]
I'm wondering, how to "replace" modules with others? I mean instantly after clicking them.

for example I have `cog` icon and after clicking on it I want it to disappear and instead of it I want to show three more icons (modules). And in that stack of modules I will have one icon to go back into only one `cog` icon.
Actually I only managed how to "use" clicking setting.
I know that [inheritance](https://github.com/polybar/polybar/wiki/Configuration#inheritance) works only for variables, what about whole modules?
```
[module/cog]
type = custom/text
# Red content
content = "%{F#ff6666}%{F-}"
click-left = shutdown now
```
I was searching for bars online which use that "technique" but I can't find one

**Comment by Lomadriel** [comment]
Maybe you can achieve what you want with the menu module
https://github.com/polybar/polybar/wiki/Module:-menu

**Comment by patrick96** [comment]
The issue tracker is meant for bug reports and feature requests. Please don't ask support questions here, read our [Support page](https://github.com/jaagr/polybar/blob/master/SUPPORT.md) for a list of resources where you can ask questions. We are more than happy to help you there.

As @Lomadriel mentioned, the menu options is the closest you can get. There is no built-in way to substitute entire modules.
