### ISSUE TITLE
Dual monitors, module/xworkspaces, bspwm and pin-workspaces

### ISSUE THREAD

**Issue by nicentra** [polybar/polybar#1764]
## Describe the issue
**Expected behavior:**

My setup is 1080p monitor + 2160p Monitor/TV over HDMI, I use bspwm on Arch and polybar-git from the AUR, when I use the xworkspaces and set pin-workspaces to true, it doesn't show the workspaces on the right monitor, instead the xworkspace module on monitor 1 shows half of the WSs and the one on monitor 2 the rest

WS 1-11 on Monitor 1 as defined in my bspwmrc
WS 12 on Monitor 2 as defined in my bspwmrc

**Actual behavior:**

xworkspace module on monitor 1 shows WS 1-6
xworkspace module on monitor 2 shows WS 7-12

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true

enable-click = true

enable-scroll = true

icon-0 = 一
icon-1 = 二
icon-2 = 三
icon-3 = 四
icon-4 = 五
icon-5 = 六
icon-6 = 七
icon-7 = 八
icon-8 = 九
icon-9 = 十
icon-10 = 十一
icon-11 = 〇
icon-default = 一

format = <label-state>
format-padding = 0

label-monitor = %name%

label-active = %name%
label-active-foreground = ${color.ac}
label-active-background = ${color.bg}
label-active-overline = ${color.ac}

label-occupied = %name%
label-occupied-underline = ${color.fg}

label-urgent = %name%
label-urgent-foreground = ${color.red}
label-urgent-background = ${color.bg}

label-empty = %name%
label-empty-foreground = ${color.fg}

label-active-padding = 2
label-urgent-padding = 2
label-occupied-padding = 2
label-empty-padding = 2
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
https://i.imgur.com/sTtaAJs.png
## Environment:
* WM: bspwm
* Distro: Arch
* Output of `polybar -vvv`:

polybar 3.3.0-85-g9103d232

Features: +alsa +curl -i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 

Am I doing anything wrong is that a bug? It seems like on a multimonitor setup polybar/xworkspaces doesn't recognise which workspace belongs on what monitor and just assumes a 50:50 split

**Comment by patrick96** [comment]
Hmm, xworkspaces generally uses what your wm announces to the xserver. Could you post the output of `xprop -root`.

Btw there is a module specifically for bspwm ;)

**Comment by nicentra** [comment]
Hi! Yes I know there's a module specifically for bspwm :) I just found [this post on reddit](https://www.reddit.com/r/unixporn/comments/bi8xoq/oc_polybar_polybar_v7_polybar_themes_its_been_a/) with templates for polybar configs and thought I could use them with a bit of custom modifications. He used the xworkspace thingy setup with the theme and I noticed this "bug" or w/e this and I want to find out what caused it. Currently transferring his theming on the xworkspaces to bspwm so it is the same \^\^

Anyway here's the output

```
_NET_WM_ICON_NAME(UTF8_STRING) = 
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x280000b
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0xc00006, 0x3200039, 0x1800010, 0x520000b, 0x500000b, 0x4600001, 0x3200003, 0x280000b
_NET_CLIENT_LIST(WINDOW): window id # 0x280000b, 0x3200003, 0x4600001, 0x500000b, 0x520000b, 0xc00006, 0x1800010, 0x3200039
AT_SPI_BUS(STRING) = "unix:abstract=/tmp/dbus-DzNAvGgHQI,guid=d5ddc02613e3fce4e55493745cd4167d"
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x5c00001
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x5c00001
GDK_VISUALS(INTEGER) = 43, 130
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1920, 0
_NET_DESKTOP_NAMES(UTF8_STRING) = "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "〇"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 12
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x400000
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_DESKTOP_NAMES, _NET_DESKTOP_VIEWPORT, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_CLIENT_LIST, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW, _NET_WM_STRUT_PARTIAL, _NET_WM_DESKTOP, _NET_WM_STATE, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_BELOW, _NET_WM_STATE_ABOVE, _NET_WM_STATE_STICKY, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_TOOLBAR
RESOURCE_MANAGER(STRING) = "*background:\t#181818\n*color0:\t#181818\n*color1:\t#ab4642\n*color10:\t#a1b56c\n*color11:\t#f7ca88\n*color12:\t#7cafc2\n*color13:\t#ba8baf\n*color14:\t#86c1b9\n*color15:\t#f8f8f8\n*color16:\t#dc9656\n*color17:\t#a16946\n*color18:\t#282828\n*color19:\t#383838\n*color2:\t#a1b56c\n*color20:\t#b8b8b8\n*color21:\t#e8e8e8\n*color3:\t#f7ca88\n*color4:\t#7cafc2\n*color5:\t#ba8baf\n*color6:\t#86c1b9\n*color7:\t#d8d8d8\n*color8:\t#585858\n*color9:\t#ab4642\n*cursorColor:\t#ba8baf\n*foreground:\t#ba8baf\nURxvt.depth:\t32\nURxvt.font:\txft:Roboto Mono for Powerline:pixelsize=15:antialias:true\nURxvt.scrollBar:\tfalse\nXcursor.size:\t20\nXcursor.theme:\txcursor-breeze-neutral\n"
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us,us", ",intl", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7
Xorg_Seat(STRING) = "seat0"
```
