### ISSUE TITLE
Example config is missing

### ISSUE THREAD

**Issue by Merith-TK** [polybar/polybar#1766]
Litterally just compiled for archlinux with the intent to use

and i get this error 
```bash
[merith@archlinux polybar]$ install -Dm644 /usr/local/share/doc/polybar/config $HOME/.config/polybar/config
install: cannot stat '/usr/local/share/doc/polybar/config': No such file or directory
```

pretty sure this issue is self explanitory

**Comment by patrick96** [comment]
The file is at `/usr/share/doc/polybar/config`

See the note at https://github.com/polybar/polybar/wiki#where-to-start

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/57721225-8ac62b80-7638-11e9-897a-d83d1814c5b8.png)

The wiki states in in `/usr/local/share/doc/polybar/config`

**Comment by patrick96** [comment]
![2019-05-14-202510_694x308_scrot](https://user-images.githubusercontent.com/2452038/57722303-66913b80-7686-11e9-9ddb-fb808f4e9c3f.png)

The note addresses this.
