### ISSUE TITLE
i3 module: can only see the current workspace

### ISSUE THREAD

**Issue by BigfootN** [polybar/polybar#1775]
Hello,

I am currently trying to show my i3 workspaces on my bar, but unfortunately without any success. I am only seeing the current workspace (icon). 

My polybar version:

```
polybar 3.3.0-89-gcb75857f

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

My i3 module config:

```ini
[module/i3]
type = internal/i3

format = <label-state>
format-offset = -20

label-focused = %icon%
label-occupied = %icon%
label-visible = %icon%
label-focused-padding = 2
label-occupied-padding = 2
label-visible-padding = 2
label-focused-font = 3
label-occupied-font = 3
label-visible-font = 3

label-focused-underline = #ea3520
label-focused-background = #db6060

pin-workspaces = false
enable-scroll = false
reverse-scroll = false

ws-icon-0 = code;
ws-icon-1 = terminal;
ws-icon-2 = firefox;
ws-icon-3 = music;
ws-icon-4 = dl;
```

I tried to debug my config with `polybar -l info` and `polybar -l trace` but I didn't see any errors.

Thank you very much in advance for any help.

**Comment by patrick96** [comment]
Can you post a screenshot of your bar as well as a screenshot of the i3bar (comes with i3) so we can see how the module should look like

**Comment by BigfootN** [comment]
Here is what my bar looks like: 
![2019-05-19-150040_2486x69_scrot](https://user-images.githubusercontent.com/1183923/57982585-8ee2b680-7a47-11e9-8d58-a6c9a2ddc4f9.png)

Here is what my i3bar looks like:
![2019-05-19-151731_2559x25_scrot](https://user-images.githubusercontent.com/1183923/57982704-52b05580-7a49-11e9-8bcb-9a635bf93ffa.png)

My i3bar only has this config:

```
bar {
}
```

**Comment by Lomadriel** [comment]
I can't see the problem here, your two bars show the same workspaces.
Don't forget that i3wm destroys workspaces if they are empty

**Comment by BigfootN** [comment]
> Don't forget that i3wm destroys workspaces if they are empty.

Okay, now I understand, thank you
