### ISSUE TITLE
Ghost bar on boot?

### ISSUE THREAD

**Issue by fwanky** [polybar/polybar#1785]
When I put my exec argument in my i3 config, which is literally just the launch.sh script, my bar seems to not launch properly on boot? If I start it anywhere else it works perfectly fine, just seems to be completely broken for me on boot?

https://0x0.st/zaIB.png

video of me starting the bar; https://0x0.st/zaIu.gif

**Comment by patrick96** [comment]
What is the log message printed by the `launch.sh` when running it in the i3 config?

**Comment by fwanky** [comment]
Sadly nothing that relates to the issue, or not that I know of 

```
~ % polybarstart 
Bars launched...
warn: No monitor specified, using "HDMI-0"
warn: module/temperature: The token `%temperature%` is deprecated, use `%temperature-c%` instead.
~ % 
```

**Comment by fwanky** [comment]
also this is the inside of the launch script 

```
#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 5; done

# Launch bar1 and bar2
polybar bar1 & 
# polybar bar2 &

```

**Comment by Lomadriel** [comment]
You could use `polybarstart > log.txt 2>&1`
If you can also run polybar with the `-l trace` argument.

**Comment by fwanky** [comment]
added $E_A polybarstart -l > log.txt 2>&1 ($e_a; exec_always) Whenver I reboot i'll post the output onto here.

**Comment by fwanky** [comment]
Seems to be that this is an issue relating to https://github.com/dylanaraps/pywal rather than polybar, my fault.

**Comment by fwanky** [comment]
Under more investigation it seems that` pkill -USR1 polybar` seems to also freeze the bar, which is odd

**Comment by Lomadriel** [comment]
Could you please post your config and your logs.
Without your config and the logs we can't really figure why this is happening.

**Comment by fwanky** [comment]
Here's the logs when I added trace to my i3 conf
as I said, nothing special
```
Bars launched...
polybar|warn:  No monitor specified, using "HDMI-0"
polybar|warn:  module/temperature: The token `%temperature%` is deprecated, use `%temperature-c%` instead.
```
Here's my polybar conf
https://0x0.st/zah0.txt

**Comment by patrick96** [comment]
I see you have `override-redirect = true` set. This means i3 no longer reserves space for the bar. How did you get the reserved space in the video?

**Comment by fwanky** [comment]
I didn't. I just purposefully have it hide the tabs.

**Comment by patrick96** [comment]
I'm confused. What exactly is the issue right now?
