### ISSUE TITLE
Multiple bars in one line

### ISSUE THREAD

**Issue by loeschzwerg** [polybar/polybar#1786]
## Is your feature request related to a problem? Please describe.
I want to have multiple bars in a row, visually separated from each other through transparent gaps.
Currently you can put modules into 3 separate spaces: left, center, right.
However they are not fixed, so if I use the i3 module, the workspaces wouldn't align with the center of the screen if you add a module, resulting in such an image:
![2019-05-31-121629_3840x2160_scrot](https://user-images.githubusercontent.com/24317401/58700037-4c9e6b00-839f-11e9-8513-910edc20442b.png)
![2019-05-31-122053_3840x2160_scrot](https://user-images.githubusercontent.com/24317401/58700040-5031f200-839f-11e9-8805-e726f8f3ad9f.png)

## Why does polybar need this feature?
Currently, if you add a new bar to the top, it just makes this:

> ---- bar1----

> ---- bar2 ----

How I want it to behave would be:

> -- barleft -- -- barright --

Or even better:

> -barl- -barc- -barr-

Such that the bar would be visually split into several parts, producing gaps in between.
Currently the only way to visually split them would be to make the background transparent, which would interfere with some wallpapers.

## Describe the solution you'd like
Probably the easiest config solution would be a new bar property, which would automatically inherit it's properties to the children like so:
```
[bar/root] or [root/top]
children = left center right
```
The new config option would be a list of bars, that should go into the line.
Polybar handles stretching and gives each bar the same amount of space in the line, so that they wouldn't change, even if the modules exceed the size.
This would result in a nicely arranged triple bar, which you could visually split from each other:

> (date eth volume)     [i3 windows]    (keyboard cpu ram)

So in one line you could have visually split modules with different visual behavior.
Together with `width = ` one could set the size of one bar module, resulting in a smaller size, making it visually more differentiated.

The only problem would be different sizes / padding in height, which would result in strange visual behavior. However there could be rules for root bars, that the children's max height would be overwritten by the root module.

## Describe alternatives you've considered
You could also make the modules or alignment position fixed and then set extra rules for the gaps, but I guess this is less flexible than the suggested solution.
However the first part would probably be no problem.

**Comment by patrick96** [comment]
Have you considered starting three bars that have their `width` and `offset-y` tweaked so that they do exactly what you want here?

Also `fixed-center = true` in the bar section may help with the alignment issue.

I think everything you want can be achieved with either of the two solutions above, so we won't implement this.

**Comment by loeschzwerg** [comment]
Ok, I achieved a working solution:
![2019-06-02-203315_3840x2160_scrot](https://user-images.githubusercontent.com/24317401/58765690-d6a02c80-8575-11e9-9df6-c695bcda027b.png)

```
[bar/root]
width = 10%
height = 1%
override-redirect = true

[bar/back]
; empty bar to achieve the needed space, without this, the modules 'float on top of the windows'
; You can spot the 1 px sized bar on the left if you insist to try.
inherit = bar/root
width = 1
override-redirect = false
modules-left = i3

[bar/left]
inherit = bar/root
modules-center = date
offset-x = 20%

[bar/center]
width = 14%
inherit = bar/root
modules-center = i3
offset-x = 43%

[bar/right]
inherit = bar/root
modules-center = date
offset-x = 70%
```

However, in the process of getting there, I encountered another issue:
If you start multiple bars, it is random which bar will be rendered on which level.
I had the 3 bars, `left` `center` `right` started with a `sleep 1` in between, but the position was random.
This was before I enabled `override-redirect = true`

Is there  a solution for this yet?

**Comment by patrick96** [comment]
In i3 if you don't have `override-redirect = true`, i3 will just position the bars itself and ignore the bar positions you set in the config. So `override-redirect = true` is kind of necessary with i3 unfortunately. But if you use i3-gaps you can set top gaps to reserve space for the bar.

**Comment by loeschzwerg** [comment]
Oh.. The issue is that the bars leveling is randomized. So if I do:
```
polybar bar1 &
sleep 1
polybar bar2 &
sleep 1
polybar bar3 &
```
The expected order on the screen would be
> --- bar1---
> --- bar2 ---
> --- bar3 ---

but the actual result could be
> --- bar1---
> --- bar3 ---
> --- bar2 ---

**Comment by patrick96** [comment]
But aren't the bars supposed to be next to each other instead of above?
