### ISSUE TITLE
Battery threshold

### ISSUE THREAD

**Issue by laferuben** [polybar/polybar#1795]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I do not see when will my battery fully discharge. I could use `ramp` options but it would not fit my config where I use GTK urgent colored overlines to indicate a problem.

## Why does polybar need this feature?
Because polybar should be extensible and flexible.

## Describe the solution you'd like
A solution I would like would add `label-overline-threshold-%d` to the battery module options where `%d` stands for the upper limit. If the battery charge percentage reaches it or goes down further, the overline should become visible.

## Describe alternatives you've considered
`ramp` options do not suit my config well.

## Additional context
I've also seen https://github.com/polybar/polybar/issues/63, where I found that `ramp` solution.

**Comment by Lomadriel** [comment]
I think you can achieve what you want with the format tags:
Something like this:
```ini
[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 98

format-charging = <ramp-capacity>
format-discharging = <ramp-capacity>
format-full = <ramp-capacity>

ramp-capacity-0 = %{o#ff0000}Low Battery !!!!!%{-o}
ramp-capacity-1 = icon 2
ramp-capacity-2 = icon 3
ramp-capacity-3 = icon 4
ramp-capacity-4 = %{o#ff9900}Battery Full%{-o}

```

**Comment by patrick96** [comment]
I think you would need

```dosini
ramp-capacity-0 = %{o#ff0000 +o}Low Battery !!!!!%{-o o-}
```

because the overline would also need to be enabled.

But even easier than that, each ramp stage behaves like a label, so you can set
```dosini
ramp-capacity-0 = Low Battery !!!!!
ramp-capacity-0-overline = #ff0000
```

This together with the planned weights for ramps (#1750), should make this easily achievable. I don't see a reason to further bloat the battery module.

**Comment by laferuben** [comment]
I do not use icons, I use percentage and I want an overline. That's not the solution.

**Comment by Lomadriel** [comment]
Hum, that's not really pretty but in the absence of a better solution you can use this:
```ini
[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 98

format-charging = <ramp-capacity><label-full>%{-o o-}
format-discharging = <ramp-capacity><label-full>%{-o o-}
format-full = <ramp-capacity><label-full>%{-o o-}
format-full = <ramp-capacity><label-full>%{-o o-}


ramp-capacity-0 = %{o#ff0000 +o}
ramp-capacity-1 =
ramp-capacity-2 =
ramp-capacity-3 =
ramp-capacity-4 =

```

**Comment by laferuben** [comment]
Looks like what I need, thanks.
