### ISSUE TITLE
i3 workspace switching doesn't work with a comma

### ISSUE THREAD

**Issue by raku-cat** [polybar/polybar#1797]
## Describe the issue
When is a comma, it shows up properly in the bar
![image](https://user-images.githubusercontent.com/1125449/58846426-c0ad6d00-8644-11e9-8139-166c91263f5c.png)
But clicking it does nothing

**Expected behavior:**

To be able to switch workspaces by clicking it as with when they workspaces are numbers or letters or other symbols

**Actual behavior:**

Nothing happens, if I run polybar with `-l trace` I get
```
- Found matching input area
* module/i3: Sending workspace focus command to ipc handler
```
when I click the workspace button for the comma workspace.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```
[bar/default]
modules-left = i3
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
Run i3, open a workspace for `,`, then another for `.` or anything else, try to switch between them by clicking.

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3
* Distro: Arch
* Output of `polybar -vvv`: 
```
polybar 3.3.0-92-g7724c4dc

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/lib/ccache/bin/c++
Compiler flags: -march=native -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```
## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by Lomadriel** [comment]
Could you post the config of your i3 module please.
Without it I can't really try to debug this ;)
Moreover how do you create a "," workspace because when I tried to run `i3 workspace ','` I just get an error message :/

**Comment by raku-cat** [comment]
I think you need to do double quotes, I have it in my i3 config like this
`bindsym $mod+comma workspace ","`

Here's the module config
```
[module/i3]
type = internal/i3
format = <label-state><label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true
pin-workspaces = true

label-unfocused-background = ${colors.my_background}
label-unfocused-foreground = ${colors.my_foreground}

label-mode = %name%
label-mode-padding = 2
label-mode-background = #ff0000

label-focused = %name%
label-focused-foreground = ${colors.my_foreground}
label-focused-background = ${colors.my_background}
label-focused-underline = #0088CC
label-focused-padding = 2

label-unfocused = %name%
label-unfocused-padding = 2

label-visible = %name%
label-visible-underline = ${colors.my_foreground}
label-visible-padding = 2

label-urgent = %index%
label-urgent-foreground = ${colors.my_foreground}
label-urgent-background = ${colors.my_background}
label-urgent-underline = #900000
label-urgent-padding = 2
```

**Comment by Lomadriel** [comment]
Thanks problem fixed ;)
You just need to wait the review of my PR.

**Comment by raku-cat** [comment]
Can confirm the PR fixes the bug for me :)

**Comment by Lomadriel** [comment]
Ok nice but I'll leave the issue open until the PR is merged ;)
