### ISSUE TITLE
Polybar says is running, but does not display.

### ISSUE THREAD

**Issue by StarrKiss** [polybar/polybar#1804]
When I run polybar 'polybar main' the messages in config say it should be running normally, but it doesnt show anything. This just happened suddenly for no apparent reason after a restart.
[polybarconfig.txt](https://github.com/polybar/polybar/files/3258828/polybarconfig.txt)

[i3config.txt](https://github.com/polybar/polybar/files/3258836/i3config.txt)

i3-gaps, Manjaro. I have no damn clue why this has happened, it just happened randomly.
![ayy](https://user-images.githubusercontent.com/13007697/58986291-b4d7bd00-87a2-11e9-96d5-dc2e7250c3e9.png)

The termination is from me pressing ctrl+c

**Comment by patrick96** [comment]
You know, there is an edit button ;)

Can you run

```bash
FC_DEBUG=1 polybar -l info main
```

and paste the entire output here. This looks like something to do with the fonts.

**Comment by StarrKiss** [comment]
* Loading config: /home/gregorystarr/.config/polybar/config
warn: No monitor specified, using "eDP1"
* Loaded monitor eDP1 (2560x1600+0+0)
* Bar geometry: 2560x40+51+32
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1b.0.analog-stereo
* Starting application
* Starting module/arch
* Starting module/workspaces
* Starting module/google
* Starting module/github
* Starting module/reddit
* Starting module/pulseaudio
* Starting module/battery
* Starting module/network
* Starting module/date
* Starting module/powermenu
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=12)
* Configured DPI = 96x96
FC_DEBUG=1
Match Pattern has 22 elts (size 32)
	family: "Fantasque Sans Mono"(s) "Bitstream Vera Sans"(w) "DejaVu Sans"(w) "Verdana"(w) "Arial"(w) "Albany AMT"(w) "Luxi Sans"(w) "Nimbus Sans L"(w) "Nimbus Sans"(w) "Nimbus Sans"(w) "Helvetica"(w) "Nimbus Sans"(w) "Nimbus Sans L"(w) "Lucida Sans Unicode"(w) "BPG Glaho International"(w) "Tahoma"(w) "Nachlieli"(w) "Lucida Sans Unicode"(w) "Yudit Unicode"(w) "Kerkis"(w) "ArmNet Helvetica"(w) "Artsounk"(w) "BPG UTF8 M"(w) "Waree"(w) "Loma"(w) "Garuda"(w) "Umpush"(w) "Saysettha Unicode"(w) "JG Lao Old Arial"(w) "GF Zemen Unicode"(w) "Pigiarniq"(w) "B Davat"(w) "B Compset"(w) "Kacst-Qr"(w) "Urdu Nastaliq Unicode"(w) "Raghindi"(w) "Mukti Narrow"(w) "malayalam"(w) "Sampige"(w) "padmaa"(w) "Hapax Berbère"(w) "MS Gothic"(w) "UmePlus P Gothic"(w) "Microsoft YaHei"(w) "Microsoft JhengHei"(w) "WenQuanYi Zen Hei"(w) "WenQuanYi Bitmap Song"(w) "AR PL ShanHeiSun Uni"(w) "AR PL New Sung"(w) "MgOpen Modata"(w) "VL Gothic"(w) "IPAMonaGothic"(w) "IPAGothic"(w) "Sazanami Gothic"(w) "Kochi Gothic"(w) "AR PL KaitiM GB"(w) "AR PL KaitiM Big5"(w) "AR PL ShanHeiSun Uni"(w) "AR PL SungtiL GB"(w) "AR PL Mingti2L Big5"(w) "ＭＳ ゴシック"(w) "ZYSong18030"(w) "TSCu_Paranar"(w) "NanumGothic"(w) "UnDotum"(w) "Baekmuk Dotum"(w) "Baekmuk Gulim"(w) "KacstQura"(w) "Lohit Bengali"(w) "Lohit Gujarati"(w) "Lohit Hindi"(w) "Lohit Marathi"(w) "Lohit Maithili"(w) "Lohit Kashmiri"(w) "Lohit Konkani"(w) "Lohit Nepali"(w) "Lohit Sindhi"(w) "Lohit Punjabi"(w) "Lohit Tamil"(w) "Meera"(w) "Lohit Malayalam"(w) "Lohit Kannada"(w) "Lohit Telugu"(w) "Lohit Oriya"(w) "LKLUG"(w) "FreeSans"(w) "Arial Unicode MS"(w) "Arial Unicode"(w) "Code2000"(w) "Code2001"(w) "URW Gothic"(w) "Nimbus Sans"(w) "Nimbus Sans Narrow"(w) "sans-serif"(w) "Roya"(w) "Koodak"(w) "Terafik"(w) "Helvetica"(w) "sans-serif"(w) "ITC Avant Garde Gothic"(w) "URW Gothic"(w) "sans-serif"(w) "sans-serif"(w) "Helvetica"(w) "Helvetica Narrow"(w) "Nimbus Sans Narrow"(w)
	familylang: "en"(s) "en-us"(w)
	stylelang: "en"(s) "en-us"(w)
	fullnamelang: "en"(s) "en-us"(w)
	slant: 0(i)(s)
	weight: 80(i)(s)
	width: 100(i)(s)
	size: 17.28(f)(s)
	pixelsize: 18(f)(s)
	hintstyle: 3(i)(s) 1(i)(w)
	hinting: True(s)
	verticallayout: False(s)
	autohint: False(s)
	globaladvance: True(s)
	lang: "en"(w)
	fontversion: 2147483647(i)(s)
	embeddedbitmap: True(s)
	decorative: False(s)
	namelang: "en"(s)
	prgname: "polybar"(s)
	symbol: False(s)
	variable: False(s)

Best score 0 0 0 0 0 0 0 0 0 0 1001 0 0 0 0 0 0 0 0 0 0 0 0 0 2.14737e+12
Pattern has 25 elts (size 25)
	family: "Fantasque Sans Mono"(w)
	familylang: "en"(w)
	style: "Regular"(w)
	stylelang: "en"(w)
	fullname: "Fantasque Sans Mono Regular"(w)
	fullnamelang: "en"(w)
	slant: 0(i)(w)
	weight: 80(f)(w)
	width: 100(f)(w)
	spacing: 100(i)(w)
	foundry: "PfEd"(w)
	file: "/usr/share/fonts/FantasqueSansMono-Regular.ttf"(w)
	index: 0(i)(w)
	outline: True(w)
	scalable: True(w)
	charset: 
	0000: 00000000 ffffffff ffffffff 7fffffff 00000000 ffffffff ffffffff ffffffff
	0001: ffffffff ffffffff fffffdff ffffffff 00070001 00000010 dfffe000 ff313fcf
	0002: cfffffff 008fffc0 00000000 00000000 00000000 00000000 0c000000 00000000
	0003: 001fffff 000001c0 00000000 00000000 ffffd7f0 fffffffb 3fffffff 00000000
	0004: fffffffe ffffffff ffffffff 003c000f fffffc00 ffffffff ffffffff 33ffffff
	0005: 300f0000 00000070 00000000 00000000 00000000 00000000 00000000 00000000
	0020: ffff0000 360000ff 00000380 00110000 0000001f 00001000 00000000 00000000
	0021: 00400000 00000000 00000000 00000000 003f0000 00000000 000007f0 00000000
	0022: 00000000 00000000 00000000 00000001 00000000 00000000 00000000 00000000
	0023: 00000000 00000000 00000000 00000000 00000000 03000000 00000000 00000000
	0024: 00000000 00000008 00000000 00000000 00000000 00000000 00000000 00000000
	0025: ffffffff ffffffff ffffffff ffffffff ffffffff 00000001 00000000 00000000
	00e0: 000000ff 00000000 00000000 00000000 00000000 000f0007 00000000 00000000
(w)
	lang: aa|ab|av|ay|ba|be|bg|bi|br|bs|bua|ca|ce|ch|chm|co|cs|cv|da|de|el|en|eo|es|et|eu|fi|fj|fo|fr|fur|fy|gd|gl|gv|ho|hr|hu|ia|id|ie|ik|io|is|it|kaa|ki|kk|kl|kum|kv|kw|ky|la|lb|lez|lt|lv|mg|mh|mo|mt|nb|nds|nl|nn|no|nr|nso|ny|oc|om|os|pl|pt|rm|ro|ru|sah|se|sel|sh|shs|sk|sl|sma|smj|smn|so|sq|sr|ss|st|sv|sw|tg|tk|tl|tn|tr|ts|tt|tyv|uk|uz|vo|vot|wa|wen|wo|xh|yap|zu|an|crh|csb|fil|hsb|ht|jv|kj|ku-tr|kwm|lg|li|mn-mn|ms|na|ng|pap-an|pap-aw|rn|rw|sc|sg|sn|su|za(w)
	fontversion: 111411(i)(w)
	capability: "otlayout:DFLT otlayout:cyrl otlayout:grek otlayout:latn"(w)
	fontformat: "TrueType"(w)
	decorative: False(w)
	postscriptname: "FantasqueSansMono-Regular"(w)
	color: False(w)
	symbol: False(w)
	variable: False(w)

* Loaded font "Fantasque Sans Mono:pixelsize=18" (name=Fantasque Sans Mono, offset=3, file=/usr/share/fonts/FantasqueSansMono-Regular.ttf)
Match Pattern has 22 elts (size 32)
	family: "Iosevka Nerd Font"(s) "Bitstream Vera Sans"(w) "DejaVu Sans"(w) "Verdana"(w) "Arial"(w) "Albany AMT"(w) "Luxi Sans"(w) "Nimbus Sans L"(w) "Nimbus Sans"(w) "Nimbus Sans"(w) "Helvetica"(w) "Nimbus Sans"(w) "Nimbus Sans L"(w) "Lucida Sans Unicode"(w) "BPG Glaho International"(w) "Tahoma"(w) "Nachlieli"(w) "Lucida Sans Unicode"(w) "Yudit Unicode"(w) "Kerkis"(w) "ArmNet Helvetica"(w) "Artsounk"(w) "BPG UTF8 M"(w) "Waree"(w) "Loma"(w) "Garuda"(w) "Umpush"(w) "Saysettha Unicode"(w) "JG Lao Old Arial"(w) "GF Zemen Unicode"(w) "Pigiarniq"(w) "B Davat"(w) "B Compset"(w) "Kacst-Qr"(w) "Urdu Nastaliq Unicode"(w) "Raghindi"(w) "Mukti Narrow"(w) "malayalam"(w) "Sampige"(w) "padmaa"(w) "Hapax Berbère"(w) "MS Gothic"(w) "UmePlus P Gothic"(w) "Microsoft YaHei"(w) "Microsoft JhengHei"(w) "WenQuanYi Zen Hei"(w) "WenQuanYi Bitmap Song"(w) "AR PL ShanHeiSun Uni"(w) "AR PL New Sung"(w) "MgOpen Modata"(w) "VL Gothic"(w) "IPAMonaGothic"(w) "IPAGothic"(w) "Sazanami Gothic"(w) "Kochi Gothic"(w) "AR PL KaitiM GB"(w) "AR PL KaitiM Big5"(w) "AR PL ShanHeiSun Uni"(w) "AR PL SungtiL GB"(w) "AR PL Mingti2L Big5"(w) "ＭＳ ゴシック"(w) "ZYSong18030"(w) "TSCu_Paranar"(w) "NanumGothic"(w) "UnDotum"(w) "Baekmuk Dotum"(w) "Baekmuk Gulim"(w) "KacstQura"(w) "Lohit Bengali"(w) "Lohit Gujarati"(w) "Lohit Hindi"(w) "Lohit Marathi"(w) "Lohit Maithili"(w) "Lohit Kashmiri"(w) "Lohit Konkani"(w) "Lohit Nepali"(w) "Lohit Sindhi"(w) "Lohit Punjabi"(w) "Lohit Tamil"(w) "Meera"(w) "Lohit Malayalam"(w) "Lohit Kannada"(w) "Lohit Telugu"(w) "Lohit Oriya"(w) "LKLUG"(w) "FreeSans"(w) "Arial Unicode MS"(w) "Arial Unicode"(w) "Code2000"(w) "Code2001"(w) "URW Gothic"(w) "Nimbus Sans"(w) "Nimbus Sans Narrow"(w) "sans-serif"(w) "Roya"(w) "Koodak"(w) "Terafik"(w) "Helvetica"(w) "sans-serif"(w) "ITC Avant Garde Gothic"(w) "URW Gothic"(w) "sans-serif"(w) "sans-serif"(w) "Helvetica"(w) "Helvetica Narrow"(w) "Nimbus Sans Narrow"(w)
	familylang: "en"(s) "en-us"(w)
	stylelang: "en"(s) "en-us"(w)
	fullnamelang: "en"(s) "en-us"(w)
	slant: 0(i)(s)
	weight: 80(i)(s)
	width: 100(i)(s)
	size: 23.04(f)(s)
	pixelsize: 24(f)(s)
	hintstyle: 3(i)(s) 1(i)(w)
	hinting: True(s)
	verticallayout: False(s)
	autohint: False(s)
	globaladvance: True(s)
	lang: "en"(w)
	fontversion: 2147483647(i)(s)
	embeddedbitmap: True(s)
	decorative: False(s)
	namelang: "en"(s)
	prgname: "polybar"(s)
	symbol: False(s)
	variable: False(s)

Best score 0 0 0 0 0 0 0 0 0 0 1001 0 0 0 0 0 0 0 0 0 0 0 0 0 2.14742e+12
Pattern has 24 elts (size 24)
	family: "Iosevka"(w) "Iosevka Nerd Font"(w)
	familylang: "en"(w) "en"(w)
	style: "Regular"(w) "Book"(w)
	stylelang: "en"(w) "en"(w)
	fullname: "Iosevka Nerd Font Complete"(w)
	fullnamelang: "en"(w)
	slant: 0(i)(w)
	weight: 80(f)(w)
	width: 100(f)(w)
	foundry: "CYEL"(w)
	file: "/usr/share/fonts/Iosevka Nerd Font Complete.ttf"(w)
	index: 0(i)(w)
	outline: True(w)
	scalable: True(w)
	charset: 
	0000: 00000000 ffffffff ffffffff 7fffffff 00000000 ffffffff ffffffff ffffffff
	0001: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0002: ffffffff ffffffff ffffffff ffffffff ffffffff 3fffffff ffffffc3 008833ff
	0003: ffffffff ffffffff f5bf7fff fc00ffff ffffd7f0 fffffffb 00607fff e39c0000
	0004: ffffffff ffffffff ffffffff 03f00cc0 0fcf0000 0fcffc0c ffff8007 033fffff
	0005: 3c000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
	001a: 00000000 00000000 00000000 00000000 00000000 00040000 00000000 00000000
	001d: 1ff1ffff ffffffff fdffffff b98007ff fa038000 fffffbff ff9000f0 401fcfff
	001e: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff 03ffffff
	001f: 3f3fffff ffffffff aaff3f3f 3fffffff ffffffff ffdfffff efcfffdf 7fdcffff
	0020: ff3f08ff 7eff00f7 00000810 fff30000 1fff7fff 20001398 00000000 00000000
	0021: 00c80268 00004ac5 7fff0000 00000000 cfff0200 f300400f 03fff87f 1fa003f0
	0022: 678f9ffd 30f07ff9 00041fba 03ffcfff ffe00ffc 800031ff 0000004f 01000000
	0023: 00000f00 ffc00600 ffffffff 07ffffff 00200000 00000000 00000000 78000000
	0024: 00000000 00000000 00000000 ffffffff ffffffff ffffffff ffffffff ffffffff
	0025: ffffffff ffffffff ffffffff ffffffff ffffffff f3ffffff 003fdfcf 0000807c
	0026: 00000060 00000000 00000007 0000feff 00030000 00000002 00000000 00000000
	0027: 05f80000 00000000 00000000 ffc3f000 00000000 00000000 00000004 00000f00
	0028: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0029: 00000000 00000006 00000000 00000000 00000000 00000000 00000000 00000800
	002a: 00000000 80000000 00000000 60000000 00000000 00000000 00000000 00000000
	002b: 80000000 0000000f 01180000 00000000 00000000 00000000 00000000 00000000
	002c: 00000000 00000000 00000000 fa8fb800 00000000 00000000 00000000 00000000
	0032: 00000000 00000000 fffe0000 00000000 00000000 fffe0000 00000000 00000000
	00a7: 00000000 00030080 0c000000 00000000 000c4003 00030000 00000000 00000000
	00ab: 00000000 00210000 00080000 00000030 00000000 00000000 00000000 00000000
	00e0: 000007ff 00000000 00000000 00000000 c0030000 ffffc00f 0017f5ff 00000000
	00e2: ffffffff ffffffff ffffffff ffffffff ffffffff 000003ff 00000000 00000000
	00e3: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff 0000000f
	00e5: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 fc000000
	00e6: ffffffff 00007fff 00000000 00000000 00000000 00000000 00000000 00000000
	00e7: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff 0000003f 00000000
	00f0: 7fff7fff 7ffffffe 7fff7fff 7fff7fff 7fff7fff 00077fff 7fff7fff 7fff7fff
	00f1: 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff
	00f2: 7fff7fff 7ffffffe 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff 00000001
	00f3: 1fffffff 00000000 00000000 00000000 00000000 00000000 00000000 00000000
	00f4: ffffffff ffffffff ffffffff ffffffff ffffffff 000003ff 00000000 00000000
	00f5: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00f6: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00f7: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00f8: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00f9: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00fa: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00fb: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00fc: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00fd: ffffffff ffffffff 0000007f 00000000 00000000 00000000 00000000 00000000
	01f1: ffff0001 000003ff 00000000 00000000 00000000 00000000 00000000 00000000
(w)
	lang: aa|af|ast|av|ay|az-az|bm|be|bg|bi|bin|br|bs|bua|ca|ce|ch|co|cs|cv|cy|da|de|el|en|eo|es|et|eu|fi|fj|fo|fr|ff|fur|fy|ga|gd|gl|gn|gv|ha|haw|ho|hr|hu|ia|ig|id|ie|ik|io|is|it|kaa|ki|kk|kl|ku-am|kum|kv|kw|ky|la|lb|lez|ln|lt|lv|mg|mh|mi|mk|mo|mt|nb|nds|nl|nn|no|nr|nso|ny|oc|om|os|pl|pt|rm|ro|ru|sco|se|sel|shs|sk|sl|sm|sma|smj|smn|sms|so|sq|sr|ss|st|sv|sw|tg|tk|tl|tn|to|tr|ts|tt|tw|tyv|uk|uz|ve|vi|vo|vot|wa|wen|wo|xh|yap|yo|zu|ak|an|ber-dz|crh|csb|ee|fat|fil|hsb|ht|hz|jv|kab|kj|kr|ku-tr|kwm|lg|li|mn-mn|ms|na|ng|nv|pap-an|pap-aw|qu|quz|rn|rw|sc|sg|sn|su|ty|za(w)
	fontversion: 65536(i)(w)
	capability: "otlayout:DFLT otlayout:cyrl otlayout:grek otlayout:hani otlayout:kana otlayout:latn"(w)
	fontformat: "TrueType"(w)
	decorative: False(w)
	postscriptname: "IosevkaNerdFontComplete-"(w)
	color: False(w)
	symbol: False(w)
	variable: False(w)


Here. I dont think its a font issue because the entire bar is imssing, not just the fonts/bad glyphs

**Comment by patrick96** [comment]
Definitely a font issue. Polybar gets stuck somewhere between font matching and printing that it loaded the font for `Iosevka Nerd Font:pixelsize=24`. Don't know exactly what is going wrong or what polybar is doing wrong. Is this happening every time? Could you try to remove `font-1` and run it again.

Can you also run `fc-match "Iosevka Nerd Font:pixelsize=24"`

Also I dug into the error displayed in your screenshot:
```
polybar: fccache.c:820: FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed.
```

It should actually be impossible to get this error within polybar because the function that gives that error is never called (not even indirectly) by polybar. What is the version of your `fontconfig`  package? And the output of `polybar -vvv`?

**Comment by StarrKiss** [comment]
result of fc-match:
Iosevka Nerd Font Complete.ttf: "Iosevka" "Regular"

polybar -vvv:

polybar 3.3.0
Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now


fc version is: 2.13.1 
If I comment out font 1 it works, but my glyphs are gone. Also, why dould this error start now, instead of when using it the past 2 days?

**Comment by StarrKiss** [comment]
Was able to fix by reinstalling font
