### ISSUE TITLE
Workspace icons not working.

### ISSUE THREAD

**Issue by StarrKiss** [polybar/polybar#1805]
When the bar should display just the workspace icons i set up, it instead displays name and the default icon.

![why](https://user-images.githubusercontent.com/13007697/58994890-b2cc2900-87b7-11e9-88d1-9965c853a8aa.png)

This is the section in question in my polybar config:

[module/workspaces]
type = internal/i3
pin-workspaces = false
enable-click = true
enable-scroll = true
format-padding = 1

ws-icon-0 = "1:main";喇
ws-icon-1 = "2:Work #1"❷
ws-icon-2 = "3:Work #2";❸
ws-icon-3 = "4:Work #3;❹
ws-icon-4 = "5:work #4";❺
ws-icon-5 = "6:Media";❻
ws-icon-6 = "7:Communication";
ws-icon-7 = "8:Presentation";❽

ws-icon-default = 

format = <label-state>
format-background = ${color.shade2}
label-active = %icon%
label-occupied = %icon%
label-urgent = %icon%

label-empty-padding = 1
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1

label-empty-foreground = ${color.fg}
label-active-foreground = ${color.acolor}
label-urgent-foreground = ${color.curgent}
label-occupied-foreground = ${color.coccupied}

The names are all correct, (as it shows the name) but it doesnt work correctly. Why?

**Comment by Lomadriel** [comment]
`label-active = %icon%` doesn't exist, you need to use:
```
label-focused = %icon%
label-visible = %icon%`
```

**Comment by StarrKiss** [comment]
Still doesn't work, it still uses the default icon on all of them even though the name is gone( if I open 2 workspaces it still has the name"

**Comment by Lomadriel** [comment]
Are you sure that the names exactly match?
If you don't use the name of your workspaces, I recommend you to only use numbers as workspace names.

**Comment by StarrKiss** [comment]
They exactly match, the problem is that it shows the name of the workspace after the icon.

**Comment by Lomadriel** [comment]
Does it works with this config:

```
[module/workspaces]
type = internal/i3
pin-workspaces = false
enable-click = true
enable-scroll = true
format-padding = 1

ws-icon-0 = "1:main";喇
ws-icon-1 = "2:Work #1"❷
ws-icon-2 = "3:Work #2";❸
ws-icon-3 = "4:Work #3;❹
ws-icon-4 = "5:work #4";❺
ws-icon-5 = "6:Media";❻
ws-icon-6 = "7:Communication";
ws-icon-7 = "8:Presentation";❽

ws-icon-default = 

format = <label-state>
format-background = ${color.shade2}

label-focused = %icon%
label-focused-padding = 1
label-focused-foreground = ${color.acolor}

label-unfocused = %icon%
label-unfocused-padding = 1
label-unfocused-foreground = ${color.coccupied}

label-visible = %icon%
label-visible-padding = 1
label-visible-foreground = ${color.acolor}

label-urgent = %icon%
label-urgent-padding = 1
label-urgent-foreground = ${color.curgent}

```

**Comment by StarrKiss** [comment]
yes, thank you so much!

**Comment by LucasMazei** [comment]
I'd like some help too. It doesn't matter what I do, it always use the default icon. 
This is my i3 module:
```
[module/i3]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = true
index-sort = true

enable-click = true
enable-scroll = true

wrapping-scroll = false
reverse-scroll = false

ws-icon-0 = "2:Terminals";
ws-icon-1 = "3:Browser";
ws-icon-2 = "4:Files";
ws-icon-3 = "5:Dev";
ws-icon-default = 

format = <label-state>
label-focused = %name%
label-focused-foreground = ${color.fg}
label-focused-background = ${color.ac}
label-focused-underline = ${color.ac}
label-focused-padding = 1

label-unfocused = %name% %icon%
label-unfocused-foreground = ${color.fg}
label-unfocused-background = ${color.mf}
label-unfocused-underline = ${color.mf}
label-unfocused-padding = 1

label-visible = %name%
label-visible-underline = #555555
label-visible-padding = 1

label-urgent = %name%
label-urgent-foreground = ${color.fg}
label-urgent-background = ${color.red}
label-urgent-padding = 1

````
My i3 config:
```
set $ws2 "2:Terminals"
set $ws3 "3:Browser"
set $ws4 "4:Files"
set $ws5 "5:Dev"
```
And my fonts:

```
font-0 = "Hack Nerd Font:style=Regular:pixelsize=8"
font-1 = "Misc Termsyn:size=12;2"
font-2 = "Wuncon Siji:size=12;2"
font-3 = "xos4 Terminus:size=12;2"

```

**Comment by patrick96** [comment]
@LucasMazei 

```
ws-icon-0 = "2:Terminals";
```
->

```
ws-icon-0 = "2:Terminals;"
```

Otherwise polybar will try match your workspace names to the literal `"2:Terminals"`.

**Comment by LucasMazei** [comment]
I just removed all the " and it worked haha. Thanks anyway.

**Comment by madipietro** [comment]
Hello guys!, i'm facing the same problem i cant make it work.

`# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws0 "10"

# switch to workspace
bindsym $mod+1 workspace  $ws1
bindsym $mod+2 workspace  $ws2
bindsym $mod+3 workspace  $ws3
bindsym $mod+4 workspace  $ws4
bindsym $mod+5 workspace  $ws5
bindsym $mod+6 workspace  $ws6
bindsym $mod+7 workspace  $ws7
bindsym $mod+8 workspace  $ws8
bindsym $mod+9 workspace  $ws9
bindsym $mod+0 workspace  $ws10
`
That is the desktop labeling on my .config/i3/config


And the i3 module of my polybar. 

`[module/i3]
type = internal/i3
; ws-icon-[0-9]+ = <label>;<icon>
; NOTE: The <label> needs to match the name of the i3 workspace
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1;♚
ws-icon-1 = 2;♛
ws-icon-2 = 3;♜
ws-icon-3 = 4;♝
ws-icon-4 = 5;♞
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;
ws-icon-default = ♟


; Available tags:
;   <label-state> (default) - gets replaced with <label-(focused|unfocused|visible|urgent)>
;   <label-mode> (default)
format = <label-state> <label-mode>
;<label-mode>
; Available tokens:
;   %mode%
; Default: %mode%
label-mode = %mode%
label-mode-padding = 2
label-mode-background = #e60053
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon%  %name%

label-focused = %icon% %name%
label-focused-foreground = #ffffff
label-focused-background = #3f3f3f
label-focused-underline = #fba922
label-focused-padding = 4

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon%  %name%
label-unfocused = %icon%  %name%
label-unfocused-padding = 4
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon%  %name%
label-visible = %icon% %name%
label-visible-underline = #555555
label-visible-padding = 4
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon%  %name%
label-urgent =  %icon%  %name%
 label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 4
; Separator in between workspaces
label-separator = |
label-separator-padding = 2
label-separator-foreground = #ffb51a
`
Any suggestion ? thxs in advance!.

**Comment by Super-Botman** [comment]
Hello, i have the same problen but a litlle bit different. I've configured my ws name like this:

```ini
set $ws1 "1:Terminal"
set $ws2 "2:Firefox"
set $ws3 "3:KeepassXC"
set $ws4 "4:Discord"
```
and polybar like this:

```ini
ws-icon-0 = 1:Terminal;
ws-icon-1 = 2:Firefox;󰈹
ws-icon-3 = 3:KeepassXC;
ws-icon-4 = 4:Discord;󰙯
ws-icon-default = 
```
