### ISSUE TITLE
error module/mpd: connected refused

### ISSUE THREAD

**Issue by michaeltarab** [polybar/polybar#1806]
I just got polybar and i ran polybar example into terminal and this error came up: error module/mpd: connected refused 
```
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
error: module/mpd: Connection refused
```

**Comment by Lomadriel** [comment]
```
warn: Dropping unmatched character  (U+e26f)
```
These warnings mean that a font doesn't have the characters that you want to print:
See https://github.com/polybar/polybar/wiki/Fonts, in particular this [paragraph](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues).

```
error: module/mpd: Connection refused
```
This error means that polybar is unable to connect to [mpd](https://www.musicpd.org/), if you are using mdp please check that your config is correct https://github.com/polybar/polybar/wiki/Module:-mpd.
If you aren't using mdp, then this error is normal. You should just remove this module from the modules list.

If I'm not wrong this is not an issue. If you need more help to configure your polybar, please read: https://github.com/polybar/polybar/blob/master/SUPPORT.md
It's easier to help you on the IRC/reddit/etc...
