### ISSUE TITLE
Support for GitHub Enterprise in github module

### ISSUE THREAD

**Issue by vaygr** [polybar/polybar#1812]
It would be great to have that work offloaded to github module instead of using curl scripts.

I guess the only change would be a URL string, pointing to github enterprise installation.

So https://github.com/polybar/polybar/blob/3f9f2dc37fd8a82b7f7c7688d9bc633c67e55738/src/modules/github.cpp#L44

would become

```c++
 string content{m_http->get("https://hub.domain.tld/api/v3/notifications?access_token=" + m_accesstoken)}; 
```

**Comment by patrick96** [comment]
We could add a key `api-url` with the default value `https://api.github.com/`, and users could add their github enterprise endpoints there. We would appreciate a PR ;)

**Comment by Lomadriel** [comment]
I'm working on it.

**Comment by Lomadriel** [comment]
Hello @vaygr.
Can you test my PR #1841. I don't have an access to the github of an enterprise. I just want to know if this work correctly.

**Comment by vaygr** [comment]
This is superb. Works fine for me.

I have one subsequent feature request for this. It'd be great to alter color when the number is non-zero (I have mine in red). So with a custom script it's super easy, but not here.

Can we add an option for that real quick?

**Comment by Lomadriel** [comment]
> This is superb. Works fine for me.

Nice

> I have one subsequent feature request for this. It'd be great to alter color when the number is non-zero (I have mine in red). So with a custom script it's super easy, but not here.
> 
> Can we add an option for that real quick?

I don't really like the idea of introducing an exception just for that but maybe we could try to introduce a sort of conditional syntax but I don't know how to do it.

I was thinking about something like that, I took the inspiration from beamer:
`%notifications:<0>% // only display if 0`
`%notifications:<1-2>% // display if the number is 1 or 2`
`%notifications:<0->% // 0 to infinity`

**Comment by vaygr** [comment]
Maybe not overcomplicate things. As it usually mostly matters whether this value is zero or not (like with zero inbox for e-mail).

I was going through the modules, and it seems we kinda favor specific settings with split config options, i.e. `format-connected-...` + `format-disconnected-...`, etc. So maybe this could be achieved with adding something like:

```dosini
format-empty = <label-empty>
label-empty-foreground = ${colors.alert}
```

given we already have `empty-notifications` setting. And refactor that later if need be.

**Comment by Lomadriel** [comment]
That's make sense indeed. So we just have to deprecate `empty-notifications` and replace it by a formatter.

**Comment by Lomadriel** [comment]
@vaygr 
The code for the `empty` formatter is (almost) ready but I have a lot of conflicts with https://github.com/polybar/polybar/pull/1825. So I'll wait until this is merged to publish my PR (I also need to clean the code). If I forgot to publish the PR don't hesitate to notify me. ^^

**Comment by vaygr** [comment]
Cool, I put this on my list, thanks.

**Comment by vaygr** [comment]
@Lomadriel I think #1825 was just merged. Just pinging you here.
