### ISSUE TITLE
internal/battery: separate ramps for charging and discharging

### ISSUE THREAD

**Issue by tremby** [polybar/polybar#1819]
I'd like to use separate ramps for the battery charging and discharging rates, since Material Design Icons has nice glyphs for each state.

## Describe the solution you'd like

Perhaps separate `ramp-discharging-capacity` and `ramp-charging-capacity`?

Would a pull request for this be considered? I hacked together a solution, providing the above two ramps.

**Comment by patrick96** [comment]
This will be possible to do once we implement #1752.

Adding these two keys right now would only add more bloat to the module and we would also need to go through the process of deprecating `ramp-discharging-capacity`.

**Comment by tremby** [comment]
Ok. I'll roll with my hack for now, and subscribe to the other ticket.
Should we leave this one open as a feature request?

**Comment by patrick96** [comment]
No, I think it would only clutter up the already bursting issue list.

**Comment by shasherazi** [comment]
I checked the wiki and couldn't find documentation for this. Is this implemented yet?
