### ISSUE TITLE
Tray posistion is off

### ISSUE THREAD

**Issue by StarrKiss** [polybar/polybar#1820]
The tray (tray-posistion) is off, under the bar. If i add override-redirect = true as suggested in a closed issue, the entire bar moves. How do If fix this?

**Comment by patrick96** [comment]
Are you using i3?

**Comment by StarrKiss** [comment]
Yes, and no.

**Comment by StarrKiss** [comment]
Yes to i3,  no to the bar offset.

**Comment by patrick96** [comment]
Can you post your polybar config then. Generally this happens when an offset is set and i3 is used.

**Comment by StarrKiss** [comment]
;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   Created By Aditya Shakya.
;
;==========================================================

[color]

trans = #00000000
white = #FFFFFF
black = #000000

bg = #3B4252
fg = #FFFFFF
fg-alt = #A9ABB0

acolor = #FFFFFF
curgent = #EF5350
coccupied = #42A5F5

shade1 = #7D9DBC
shade2 = #7D9DBC
shade3 = #7D9DBC
shade4 = #7D9DBC
shade5 = #7D9DBC
shade6 = #7D9DBC
shade7 = #7D9DBC
shade8 = #7D9DBC
ashade8 = #7D9DBC

## Material Colors

red = #e53935
pink = #d81b60
purple = #8e24aa
deep-purple = #5e35b1
indigo = #3949ab
blue = #1e88e5
light-blue = #039be5
cyan = #00acc1
teal = #00897b
green = #43a047
light-green = #7cb342
lime = #c0ca33
yellow = #fdd835
amber = #ffb300
orange = #fb8c00
deep-orange = #f4511e
brown = #6d4c41
grey = #757575
blue-gray = #546e7a

;==========================================================

[bar/main]
width = 100%
height = 40
offset-x = 2%
offset-y = 2%
bottom = false
fixed-center = false
line-size = 2
background = ${color.bg}
foreground = ${color.fg}
override-redirect = true
tray-position = center
;==========================================================

font-0 = "Fantasque Sans Mono:pixelsize=18;3"
font-2 = "Iosevka Nerd Font:pixelsize=24;3"
font-1 = "Material Icons:pixelsize=24;6.5"
;==========================================================

cursor-click = pointer
cursor-scroll = ns-resize

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev


	
;== Module Location ========================================================

modules-left = arch workspaces google github reddit
modules-right =  pulseaudio network battery date powermenu 
 date powermenu

;== Modules ========================================================

[module/arch]
type = custom/text
content = 
;alt icons = 
content-padding = 1
content-background = ${color.shade1}
content-foreground = ${color.fg}
click-left = exec ulauncher
click-right = rmenu_wi_1

[module/workspaces]
type = internal/i3
pin-workspaces = false
enable-click = true
enable-scroll = true
format-padding = 1

ws-icon-0 = 1:main;
ws-icon-1 = 2:Work #1;
ws-icon-2 = 3:Work #2;
ws-icon-3 = 4:Work #3;
ws-icon-4 = 5:Work #4;
ws-icon-5 = 6:Media;
ws-icon-6 = 7:Communication;
ws-icon-7 = 8:Presentation;

ws-icon-default = 

format = <label-state> <label-mode>
format-background = ${color.shade2}
label-focused = %icon%
label-unfocused = %icon%
label-visible = %icon%
label-occupied = %icon%
label-urgent = %icon%
label-empty = %icon%

label-focused-padding = 1
label-unfocused-padding = 1
label-visible-padding = 1
label-occupied-padding = 1
label-urgent-padding = 1
label-empty-padding = 1
label-mode = %mode%
label-focused-underline = #FFFFFF
label-mode-padding = 1

label-empty-foreground = ${color.fg}
label-active-foreground = ${color.acolor}
label-urgent-foreground = ${color.curgent}
label-occupied-foreground = ${color.coccupied}


[module/google]
type = custom/text
content = 
content-padding = 2
content-foreground = ${color.fg-alt}
click-left = xdg-open https://www.google.com/ 

[module/github]
type = custom/text
content = 
content-padding = 2
content-foreground = ${color.fg-alt}
click-left = xdg-open https://www.github.com/ 

[module/reddit]
type = custom/text
content = 
content-padding = 2
content-foreground = ${color.fg-alt}
click-left = xdg-open https://www.reddit.com/

[module/facebook]
type = custom/text
content = 
content-padding = 2
content-foreground = ${color.fg-alt}
click-left = xdg-open https://www.facebook.com/

[module/youtube]
type = custom/text
content = 
content-padding = 2
content-foreground = ${color.fg-alt}
click-left = xdg-open https://www.youtube.com/

;==========================================================


;==========================================================

[module/pkg]
type = custom/script
exec = updates.sh
format-background = ${color.shade7}
format-padding = 2
tail = true

[module/battery]
type = internal/battery
full-at = 99
time-format = %H:%M
battery = BAT0
adapter = ADP1
format-charging = <label-charging>
format-charging-background = ${color.shade1}
format-charging-padding = 2
label-charging =  %percentage%% Charging
format-full-background = ${color.shade1}
format-discharging =  <label-discharging>
format-discharging-background = ${color.shade1}
format-discharging-padding = 2
label-discharging =  %percentage%% 
format-full = <label-full>
format-full-padding = 2
format-background = ${color.shade}
label-full =  Full
format-full-prefix = 

bar-capacity-width = 10



[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
format-volume-padding = 2
format-volume-background = ${color.shade6}
label-volume = %percentage%%
label-muted = ""
label-muted-background = ${color.shade6}
label-muted-padding = 2
use-ui-max = true

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/network]
type = internal/network
interface = wlp3s0
format-background = ${color.shade5}
format-padding = 2
label-connected =   %{A1:nm-connection-editor:}%essid%%{A}
label-connected-padding = 1
label-connected-foreground = #eefafafa
label-connected-background = ${color.shade1}
label-disconnected-background = ${color.shade1}
label-disconnected =   %{A1:nm-connection-editor:}No network%{A}
tail = true

[module/date]
type = internal/date
interval = 30
label =  %time%
label-padding = 2
label-background = ${color.shade3}
time =   %I:%M %p
time-alt =   %Y-%m-%d

[module/powermenu]
type = custom/text
content =  
content-padding = 2
content-background = ${color.shade2}
content-foreground = ${color.fg}
click-left = i3-msg exit
click-right = pmenu_1

;== EOF ========================================================

**Comment by patrick96** [comment]
> offset-x = 2%
offset-y = 2%

You do have a bar offset. Remove them and it will work.
