### ISSUE TITLE
Date module doesn't support padding format strings

### ISSUE THREAD

**Issue by trevorgunn** [polybar/polybar#1821]
## Description
The date module doesn't support the padding and case formating flags that you can see in `man date`:

```
       By  default, date pads numeric fields with zeroes.  The following optional flags may
       follow '%':

       -      (hyphen) do not pad the field

       _      (underscore) pad with spaces

       0      (zero) pad with zeros

       +      pad with zeros, and put '+' before future years with >4 digits

       ^      use upper case if possible

       #      use opposite case if possible
```
## Expected/Actual behaviour
For example, using `time = %-I:%M` displays as  `%-I:55` rather than `3:55`. I would like to be able to display the 12-hour time unpadded using `%-I`. The best you can do currently is either `%I` which is 0-padded or `%l` which is space-padded.

## Additional context
I'm not super familiar with C++ but I did a bit of research and tests and it seems like `std::put_time` does not support these formats but other C++ functions such as `std::strftime` do.

MWE:
```C++
#include <iostream>
#include <iomanip>
#include <ctime>
 
int main(void)
{
    char format[] = "%-I:%M %#p";
    char buffer[100];
    std::time_t t = std::time(nullptr);

    std::strftime(buffer, sizeof(buffer), format, std::localtime(&t));

    std::cout << "With strftime: " << buffer << std::endl;
    std::cout << "With put_time: " << std::put_time(std::localtime(&t), format) << std::endl; 
}
```
Output:
```
With strftime: 5:30 pm
With put_time: %-I:30 %#p
```

Polybar verision: 3.3.1 on Arch Linux
GCC version: 9.1.0

**Comment by patrick96** [comment]
We actually switched from `strftime` to `put_time` in #745 because we had issues with the buffer size for `strftime`. So unfortunately the date module only supports options listed [here](https://en.cppreference.com/w/cpp/io/manip/get_time). But one can easily write a custom script module that uses the `date` command that supports the other formats as well.

**Comment by trevorgunn** [comment]
I see. Thank you. I'll try to update the wiki page to explain this.
