### ISSUE TITLE
BSPWM dual monitor workspace 6 not working

### ISSUE THREAD

**Issue by ChuckD3ath** [polybar/polybar#1824]
Hello, I made two polybars on two monitors (1-5 and 6-0 workspaces) and it goes through first 5 fine but when I go to 6th workspace neither bar is active and window is showing outside any workspace and when I continue to 7th, 8th and so on it activates workspaces 6, 7 and so on on second bar. 
Is there any simple fix for this?

My bspwmrc file:

> $HOME/.config/polybar/launch.sh
polybar popo1 &
polybar popo2 &
bspc monitor DP2 -d VI VII VIII IX X
bspc monitor HDMI1 -d I II III IV V

Thanks in advance!

**Comment by patrick96** [comment]
If you think this is a bug, please edit your post and use the [Bug report template](https://github.com/polybar/polybar/issues/new?template=bug_report.md), you are missing lots of information that are crucial for us to help troubleshoot the issue. I will close this issue and you can reopen it once you have edited your post and used the template.

If you think this is a configuration error, have a look at our [Support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) for places where you can get help with that (the issue tracker is for polybar bugs). Note: If you are going to ask for help on reddit or IRC (or any other place), people will also require much of the same information listed in the template.
