### ISSUE TITLE
internal/i3 add option to replace workspace list with mode name when in mode

### ISSUE THREAD

**Issue by absolutelynothelix** [polybar/polybar#1829]
## Is your feature request related to a problem? Please describe.
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

currently i3 module format string has only two tags: `label-state` and `label-mode`, thus you have only two ways to format its output (state-mode (default), mode-state). if you have a lot of workspaces active (especially named) and long mode names its output won't look good and will take a lot of space (in my case about 1/4 of bar)

## Why does polybar need this feature?
*Describe why this feature would be useful to a large percentage of users (You need to convince us).*

this feature will be useful for people who has small monitors or busy bars or just for clean setups

## Describe the solution you'd like
*A clear and concise description of how your solution would work. This includes possible config options that should be added.*

i would like to see a way to enable overriding label-state when you entering a mode. it can be achieved either by adding option (`override-state-with-mode` or something like that) or by adding a universal tag (`<label-universal>` or something like that)

## Describe alternatives you've considered
*A clear and concise description of any alternative solutions or features you've considered, if any.*

## Additional context
*Add any other context or screenshots about the feature request here.*

**Comment by patrick96** [comment]
How do you imagine `label-universal` working?

**Comment by mighty9245** [comment]
@patrick96, according to the wiki:
```
; Available tags:
;   <label-state> (default) - gets replaced with <label-(focused|unfocused|visible|urgent)>
;   <label-mode> (default)
format = <label-state> <label-mode>
```

it represents `<label-state>` by default, but when you enter a mode it becomes `<label-mode>`

**Comment by mighty9245** [comment]
another way to implement this is to add option for hiding all workspaces except active one, so if you have it enabled with `format = <label-state> <label-mode>` you'll get `2 ...mode description goes here...` instead of `1 2 3 4 5 6 7 8 ...mode description goes here` when you enter a mode on second workspace

**Comment by absolutelynothelix** [comment]
i still think that it's not a bad idea, but
1) i'm not using i3 anymore,
2) i'm not using polybar anymore,
3) no one else said that they want this to be implemented,
so i'm closing this to reduce the amount of open issues.
