### ISSUE TITLE
How to set separator color?

### ISSUE THREAD

**Issue by Vista1nik** [polybar/polybar#1832]
Hello. There is `separator =` in polybar config. But there is nor `separator-color` nor `separator-foreground`. How I can set color for separator?

**Comment by patrick96** [comment]
You can use [Formatting Tags](https://github.com/polybar/polybar/wiki/Formatting)

Next time, please don't ask support questions here, the issue tracker is meant for bugs. Read our [Support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) for a list of resources where you can ask questions.
