### ISSUE TITLE
Network module signal inconsistent with iwconfig

### ISSUE THREAD

**Issue by binshengliu** [polybar/polybar#1834]
## Describe the issue
I was a bit confused that the value of `signal` variable of `network` section is not good when I have a good WiFi reception.

For example, when the output from `iwconfig` is
```
Link Quality=62/70  Signal level=-48 dBm
```

I expect `signal` to be consistent with this output like showing `88` `(from 62 * 10 / 7)` but the real value is `57` which indicates a not so good reception intuitively.

In the code, I found `signal` is calculated based on a range from `-90` to `-20`. ([code](https://github.com/polybar/polybar/blob/f0c65e6cf08012d10bde88b2caee39ad938b40fe/src/adapters/net_nl.cpp#L220))

I believe there was a reason for this. But have things changed because of the transition to libnl and now the signal range is between `-110` to `-40`? ([some discussion](https://superuser.com/a/1360447/304002), [code](https://git.openwrt.org/?p=project/iwinfo.git;a=blob;f=iwinfo_nl80211.c;hb=HEAD#l1435)). It seems the `Link Quality` of `iwconfig` is simply calculated based on this `(62 = -48 + 110)`.

**Expected behavior:**
WiFi signal value be consistent with other tools, for example, iwconfig.

**Actual behavior:**
The `signal` is not consistent with other tools.

**Was it working before?**
N/A

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/primary_bar]
modules-right = wlan

[module/wlan]
type = internal/network
interface = ${env:WIFI:}
interval = 1
format-connected = <label-connected>
label-connected = %signal%
```

## Polybar Log
N/A

## Screenshots
N/A

## Environment:
* WM: N/A
* Distro: N/A
* Output of `polybar -vvv`:
```
$ polybar -vvv
polybar 3.3.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/clang++
Compiler flags:  -Wall -Wextra -Werror -pedantic -pedantic-errors -Wno-error=parentheses-equality -Wno-zero-length-array
Linker flags:
```
## Additional context
N/A

**Comment by patrick96** [comment]
As far as I can tell there is no "right" way to get a percentage from your signal level. `iwconfig`, polybar, `iwinfo` that you linked, [i3status](https://github.com/i3/i3status/blob/master/src/print_wireless_info.c#L122) and [NetworkManager](https://github.com/NetworkManager/NetworkManager/blob/master/src/platform/wifi/nm-wifi-utils-nl80211.c#L372)  all use linear interpolation.

`iwconfig` and `iwinfo` go from `-110` to `-40`, `i3status` and NetworkManager go from `-120` to `-20`.

There is no way to be consistent with all of these. Also, if we set the max at `-40dBm`, you would get numbers over 100% when you are close to the access point. If you set the min as low as `-110` or `-120` you still get relatively percentage (around 30%) for `-90dBm`, where you generally barely even can connect ([1](https://www.metageek.com/training/resources/wifi-signal-strength-basics.html), [2](https://eyesaas.com/wi-fi-signal-strength/)).
