### ISSUE TITLE
Pulse audio click to mute uses default sink instead of specified sink

### ISSUE THREAD

**Issue by karlpvoss** [polybar/polybar#1835]
## Describe the issue
When two pulseaudio modules are present and one is clicked, the default sink is muted instead of the specified sink for that module.

**Expected behavior:**
When the module is clicked, the specified sink for that module should be muted.

**Actual behavior:**
The Pulse Audio default sink is muted instead.

**Was it working before?**
I have only just started using polybar.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/bugreport]
modules-left = speakers headphones

[module/speakers]
type = internal/pulseaudio
sink = alsa_output.pci-0000_00_1b.0.analog-stereo

[module/headphones]
type = internal/pulseaudio
sink = alsa_output.usb-Logitech_Logitech_G930_Headset-00.analog-stereo
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
The machine must have two sinks connected. The sink names in the above config should be changed to reflect the names of the sinks on the test machine.

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
polybar -c builds/polybar-config bugreport
warn: No monitor specified, using "DVI-1"
warn: No fonts specified, using fallback font "fixed"
warn: Termination signal received, shutting down...
```

## Environment: 
* WM: i3-gaps
* Distro: Linux 5.2.0-arch2-1-ARCH #1 SMP PREEMPT Mon Jul 8 18:18:54 UTC 2019 x86_64 GNU/Linux
* Output of `polybar -vvv`:
```
polybar 3.3.1

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -Wno-deprecated-copy -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by karlpvoss** [comment]
In addition to this, scrolling on a module also increments or decrements the volume of the default sink instead of the associated sink.

**Comment by patrick96** [comment]
This is a [known issue](https://github.com/polybar/polybar/wiki/Known-Issues#with-multiple-modules-of-the-same-type-actions-on-those-modules-control-the-leftmost-module), when you have multiple modules of the same type, all clicks go to the same module (the leftmost generally). There is unfortunately no fix for this yet.
