### ISSUE TITLE
Hide second battery while first is empty

### ISSUE THREAD

**Issue by StarrKiss** [polybar/polybar#1844]
I have a ThinkPad with a removable battery, and I was wondering if it is possible to A: Hide the internal battery until the external one is empty B: Swithch between batteries displayed when the external one is empty. Right now I have two modules right next to each other for that purpose.

**Comment by x70b1** [comment]
Have you seen [`polybar-scripts`](https://github.com/polybar/polybar-scripts)?

I have the same use case and this is my solution:
[polybar-scripts/battery-combined-udev](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/battery-combined-udev)

**Comment by patrick96** [comment]
This is not possible with built-in modules, the modules can't influence each other. I'd suggest using an external script like @x70b1 suggested.
