### ISSUE TITLE
Blinking format tag

### ISSUE THREAD

**Issue by vaygr** [polybar/polybar#1845]
## Is your feature request related to a problem? Please describe.

Sometimes there's a need in more visibility where different color is not enough.

Blinking seems like a good idea, besides there are already modules ([network](https://github.com/polybar/polybar/wiki/Module:-network), [battery](https://github.com/polybar/polybar/wiki/Module:-battery)) that support animation.

## Why does polybar need this feature?

This could attract more attention to the values that need immediate action (like high CPU usage, changed IP address returned from a script, some other unexpected value, etc.).

I'm wondering if it's going to have any significant performance impact on the bar though.

## Describe the solution you'd like

I see it as a tag, maybe `%{b}` with optional framerate in ms, defaulting to 500? So an example could look like this:

```dosini
VPN IP changed: %{b:2000}$IP%{b-}
```

It could also have double framerate option (`%{b:M:N}`), with one for when the value is visible and another one when it's hidden during the cycle.

**Comment by Lomadriel** [comment]
I don't know if this is doable since the renderer can't really identify the tags between each render pass.

Dev note:
In the case we want to implement this, one solution that come to my mind is to surround these tags by another tag `%{PID[actual generated id]}` to be able to identify the tag between each render pass and so we can switch the state if needed.

**Comment by Lomadriel** [comment]
Question on the feature.
I think you expect a blank that have the same size as the text when the it isn't displayed?

**Comment by vaygr** [comment]
Yeah, that is right. So we have to calculate dimensions in advance.

**Comment by Lomadriel** [comment]
> Yeah, that is right. So we have to calculate dimensions in advance.

This part is quite simple. We just need to use [ ```cairo_text_extents```](https://www.cairographics.org/manual/cairo-text.html#cairo-text-extents).
The main problem is really keeping trace of each tag. The second problem is where and how this should be processed.

In my opinion, this logic should be added before the parser but this require the addition of a new piece of logic.
However, it might be a good opportunity to incorporate the animations into this new piece of logic, this would allow global sync and we can also fix #568 at the same time.
What do you think of that @patrick96?

**Comment by patrick96** [comment]
I think a blinking tag has most of the same issues as #1787.

If we ever do a complete rewrite of how polybar passes display information to the renderer, this may be worth considering. Doing it like we do animations, only works if we don't let users specify blinking tags but have it as a label property or something similar. But even then it will have the same framerate issues as existing animations already have.

I'm not even sure if we want to keep on adding new features to the formatting tags. I don't want things to get bloated.

Seeing as this isn't really a critical feature, I'll put it on our backlog and close this issue. We may come back to it in the future.
