### ISSUE TITLE
xworkspaces missing monitor

### ISSUE THREAD

**Issue by Lomadriel** [polybar/polybar#1849]
## Describe the issue
Some workspaces aren't displayed by polybar.

**Expected behavior:**

All workspaces should be displayed.

**Actual behavior:**

Some workspaces aren't displayed.

* Did you also experience this bug in an earlier version of polybar? Yes
* If no, what was the last version where this worked correctly? Don't know

## To Reproduce
Config:
```dosini
[bar/example]
modules-center = ewmh

[module/ewmh]
type = internal/xworkspaces

```
xrandr output:
```
Screen 0: minimum 8 x 8, current 5360 x 1440, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 380mm x 210mm
   1920x1080     60.04*+  59.93  
   [...]
DP1 connected 3440x1440+1920+0 (normal left inverted right x axis y axis) 800mm x 330mm
   3440x1440     59.97 +  74.98*
   [...]
```

Open one workspace on the left screen.
Open two workspaces on the right screen.
The last one isn't displayed.

## Polybar Log
Nothing relevant in logs.

## Screenshots

![polybar](https://user-images.githubusercontent.com/10365269/62492192-2ac1ca00-b7ce-11e9-8283-47b1e3c12d0f.png)

## Environment:
* WM: i3-gaps version 4.16.1
* Distro: Linux 5.2.5-arch1-1-ARCH x86_64 GNU/Linux
* Output of `polybar -vvv`:
```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
The problem comes from this code block:
https://github.com/polybar/polybar/blob/58d72c4f1939ae1af4e853c19b9e1cd1be3de8db/src/modules/xworkspaces.cpp#L168-L173

In my example I have three workspaces, `bounds.size()=3` and `m_desktop_names.size()=3` so `step=1` then when we enter into the following loop, there is only one workspace registered for each viewport.
https://github.com/polybar/polybar/blob/58d72c4f1939ae1af4e853c19b9e1cd1be3de8db/src/modules/xworkspaces.cpp#L198-L200

**Comment by Lomadriel** [comment]
Hum, It might be quite hard to fix that.
I don't understand how the assignment is done. That's really strange :/

**Comment by patrick96** [comment]
I also never understood why this is done this way. We may just need to rewrite this part of the module, it doesn't make sense to me either.

**Comment by Lomadriel** [comment]
Okay but I don't know if I can do that without forcing `m_monitorsupport` to true :/
I'll see what I can do when I'll finish what I'm doing (updating my PRs because of the conflicts :cry:, …)

**Comment by Angel418** [comment]
Any updates on this? I'm dealing with the same issue; it appears that xworkspaces is unable to display more than 3 workspaces on each monitor (I have two). When more than 3 on each monitor are open, active workspaces overwrite the ones previously displayed by the module, instead of occupying more space on the bar (which is the expected behavior).

I normally use >15 workspaces at any one time, and this is rather inconvenient.

**Comment by Lomadriel** [comment]
I tried two or three things, I think I might have a way to solve this problem. I'll try to work on that.

**Comment by patrick96** [comment]
> Okay but I don't know if I can do that without forcing m_monitorsupport to true :/

Why can't we assume that `_NET_DESKTOP_VIEWPORT` is `0, 0` if it's not supported? In that case all desktops would be on the same monitor.

**Comment by tincotema** [comment]
Hi, any update on this problem?
