### ISSUE TITLE
bspwm module under Plasma 5 displays wrong desktops

### ISSUE THREAD

**Issue by MiltFra** [polybar/polybar#1855]
## Describe the issue

I am using bspwm as the window manager of my KDE Plasma desktop. Here I have a simple bar with a bspwm module. When I set `pin-workspaces = true` the bar only shows the first/left screen, no matter on which monitor the bar has been placed.

**Expected behavior:**

The bar should display the desktops that are on the same screen as itself.

**Actual behavior:**

The bar always displays the desktops from only one screen, no matter where it is positioned.

**Was it working before?**

It's working without Plasma, I've tested that. I have not used this feature before.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[colors]
background = #1435 
foreground = #fff
primary = #f00
secondary = #0f0

[bar/right]
monitor = primary
width = 100%
height = 27
radius = 0.0
fixed-center = true
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3
line-color = #f00
border-size = 0
border-color = #00000000
padding-left = 0
padding-right = 0
module-margin-left = 0
module-margin-right = 0

font-0 = Iosevka:size=12:style=bold;1

modules-left = 
modules-center = bspwm
modules-right =

wm-restack = bspwm
cursor-click = pointer
cursor-scroll = ns-resize


[module/bspwm]
type = internal/bspwm

label-focused = A
label-occupied = B
label-urgent = C
label-empty =  D

pin-workspaces = true
```
Install Plasma, install bspwm. Have two monitors (HDMI-A-1, left; HDMI-A-0, right).

In my bspwmrc:
```bash
bspc monitor HDMI-A-0 -n R
bspc monitor HDMI-A-1 -n L
bspc monitor L -d 1 2 3 4
bspc monitor R -d 5 6 7 8
```
Change Plasma window manager to bspwm: https://userbase.kde.org/Tutorials/Using_Other_Window_Managers_with_Plasma

## Polybar Log
`polybar -c <config> right` produces no output.

## Screenshots
Explanation:
On the left screen you can see my actual bar (the one I am using, without `pin-workspaces`). So you can see, what's happening. The desktops in that module are ordered by screen (L:^{1-4}, R:^{1-4}).

On the right screen you can see the demo bar from the config you can see above.

The screenshots (https://imgur.com/a/cZHeZ3v) are in the wrong order for some reason... but you can see the order by looking at the comments.

## Environment:
* DE: KDE Plasma 5
* WM: bspwm
* Distro: Arch Linux 
* Output of `polybar -vvv`:
```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by patrick96** [comment]
Sorry, this must have slipped through the cracks.

From the [Wiki](https://github.com/polybar/polybar/wiki/Module:-bspwm):
```dosini
; Only show workspaces defined on the same output as the bar
; NOTE: The bspwm and XRandR monitor names must match, which they do by default.
; Default: true
pin-workspaces = true
```

`pin-workspaces` doesn't work if you rename your monitors in bspwm, so the following two lines in your bspwm config conflict with `pin-workspaces`:

> bspc monitor HDMI-A-0 -n R
bspc monitor HDMI-A-1 -n L
