### ISSUE TITLE
No man pages

### ISSUE THREAD

**Issue by sysek** [polybar/polybar#1859]
Hi, 

Is there any reason why there's no man pages with new release? Before `3.4.0` there was no issue with building now after the building got error that there's man pages

```
error: File not found: /home/abuild/rpmbuild/BUILDROOT/polybar-3.4.0-lp151.1.1.x86_64/usr/share/man/man1/polybar.1.gz
```

**Comment by Lomadriel** [comment]
We use `spinx` to build the doc and the man page. If you haven't installed this package when compiling polybar, the man page isn't generated.
See [this page](https://github.com/polybar/polybar/wiki/Compiling) for more information.

**Comment by patrick96** [comment]
I have added the new sphinx dependency to the release page.
