### ISSUE TITLE
Suddenly polybar fail to display chinese character 

### ISSUE THREAD

**Issue by klesh** [polybar/polybar#1860]
## Describe the issue

Suddenly polybar fail to display chinese character.
Must be caused by some update on my system...

**Expected behavior:**

Chinese character should be displayed correctly when using 'Droid Sans'

**Actual behavior:**

Chinese character not displaying at all

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
Yes, it was.
* If no, what was the last version where this worked correctly?
The latest version clearly not working correctly

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/example]
font-0 = Droid Sans:style=Regular
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
* Loading config: /home/klesh/.config/polybar/config-internal
* Environment var ${MONITOR} is undefined, using defined fallback value "eDP-1"
* Loaded monitor eDP1 (1920x1080+1920+120)
* Bar geometry: 1920x40+1920+120
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
* Starting application
* Starting module/i3
* Starting module/mpd
* Starting module/xbacklight
* Starting module/pulseaudio
* Starting module/cpu
* Starting module/memory
* Starting module/wlan
* Starting module/eth
* Starting module/battery
* Starting module/temperature
* Starting module/date
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=12)
* Configured DPI = 96x96
* Loaded font "Droid Sans:style=Regular" (name=Droid Sans, offset=0, file=/usr/share/fonts/droid/DroidSans.ttf)
* Bar window: 0x1400003
* Activating tray manager
* Tray window: 0x140000f
error: tray: Failed to put tray above 0x1400003 in the stack (XCB_MATCH (8))
warn: Systray selection already managed (window=0x220001e)
* Deactivating tray manager
* module/i3: Rebuilding cache
* module/mpd: Rebuilding cache
* module/xbacklight: Rebuilding cache
* module/pulseaudio: Rebuilding cache
* module/cpu: Rebuilding cache
* module/memory: Rebuilding cache
* module/wlan: Rebuilding cache
* module/eth: Rebuilding cache
* module/battery: Rebuilding cache
* module/temperature: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character 许 (U+8bb8)
warn: Dropping unmatched character 嵩 (U+5d69)
warn: Dropping unmatched character 今 (U+4eca)
warn: Dropping unmatched character 年 (U+5e74)
warn: Dropping unmatched character 勇 (U+52c7)
w
```

## Screenshots
[Imgur](https://imgur.com/P0X0BZk)

## Environment:
* WM: i3wm-gap
* Distro: archlinux
* Output of `polybar -vvv`:
polybar 3.3.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -Wno-deprecated-copy -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

## Additional context
It was woking fine maybe month ago, I use 'Droid Sans' which certainly contains all Chinese characters I need.
It must be caused by some update, but I dont know which one...

**Comment by Lomadriel** [comment]
I have installed `community/ttf-droid` and I opened the font in `Gucharmap` and the `Han` section (where I can find `许 (U+8bb8)`) is empty. Don't forget to check the `View -> Show only glyphs from this font` option if you want to check by yourself.

It seems that the archlinux package doesn't contain Chinese characters.
