### ISSUE TITLE
Not an issue :)

### ISSUE THREAD

**Issue by Myrkonianin** [polybar/polybar#1862]
This is stupid question. How you with xcb\xlib maked space for window on top or bottom of screen?

You can provide a simple example?

with love,
Myrkonianin

**Comment by patrick96** [comment]
Hi. We use [struts](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#NETWMSTRUTPARTIAL) to tell WMs how much space to reserve.

You can configure this in the `global/wm` section.
```
[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL top value
;   Used for top aligned bars
margin-bottom = 0

; Adjust the _NET_WM_STRUT_PARTIAL bottom value
;   Used for bottom aligned bars
margin-top = 0
```
