### ISSUE TITLE
New added icons are missing

### ISSUE THREAD

**Issue by b3nsh4** [polybar/polybar#1867]
I have few icons that I added from rofi-fontawesome. One is battery, and a 'leaf' icon which shows different things. But, now when I add new icons, it's not displaying it there. I reloaded i3 everytime after Changing. displaying fine. And, fontawesome is also declared.   I can change existing icons and those are displaying too. But, extra icons other than these aren't displaying. Currently, it's only 4 icons. And I have enough space there in the bar. So, what's going on? I've linked my polybar config. The Music and Uptime are those which are not showing. Config: https://github.com/b3nsh4/i3stuff/blob/master/polybar_config

**Comment by Lomadriel** [comment]
See: [this](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues) and [that](https://github.com/polybar/polybar/wiki/Fonts#gnome-character-map).

Please also note that the bug tracker is only for bug report. See [this page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) for more information.
