### ISSUE TITLE
Probably not a bug, noob problem - Could not connect pulseaudio context.

### ISSUE THREAD

**Issue by Romyeo** [polybar/polybar#1868]
## Describe the issue
Hello everyone. 

My pulseaudio volume control is not showing on my polybar. If i run polybar i have a log message saying - `Could not connect pulseaudio context.`

**Expected behavior:**
Should be showing, already installed pulseaudio. Already read the dependency on the wiki page.

**Actual behavior:**
Unfortunately its not showing

**Was it working before?**
Yep, same latest version, but after restarting my machine it is gone.

## To Reproduce
```
modules-left = user i3 spotify
modules-center =
modules-right = pulseaudio cpu downspeed ipinfo date time

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
interval = 5

label-volume = %percentage%%
label-muted =   Muted
label-muted-foreground = #666

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

format-volume = <ramp-volume>  <label-volume>
format-muted = <label-muted>
```

## Polybar Log
```
warn: No monitor specified, using "HDMI-A-0"
error: Disabling module "pulseaudio" (reason: Could not connect pulseaudio context.)
error: tray: Failed to put tray above 0x1200002 in the stack (XCB_MATCH (8))
warn: Systray selection already managed (window=0x1000006)
```
P.S Don't mind the warn of systray, currently have a running instance of polybar

## Environment:
* WM: i3-Gaps
* Distro: Manjaro
* Output of `polybar -vvv`: 
```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

P.S

Is there a way i could use my media controls? Currently I am using Corsair Rapidfire keyboard and it have this volume wheel along with a mute key. Unfortunately it's not currently working on the pulseaudio, I mean before when pulseaudio was still showing.

Thanks

**Comment by Romyeo** [comment]
It's the pulse audio, it seems that its having a problem on start-up. I had to restart it manually for it to work. Might as well fix this on my own.

P.S OH MY GOD! I ACCIDENTALLY DELETED THE PULSE AUDIO WIKI! HALP!

**Comment by Lomadriel** [comment]
> P.S OH MY GOD! I ACCIDENTALLY DELETED THE PULSE AUDIO WIKI! HALP!

Restored, please be careful next time.

**Comment by hasufell** [comment]
I have a similar problem. Applications and everything works fine and has sound. Polybar doesn't seem to work well with it. It was compiled with pulseaudio support. I'm getting the same

> error: Disabling module "pulseaudio" (reason: Could not connect pulseaudio context.)

@viinxent how did you solve it?

**Comment by viinxent** [comment]
@hasufell 

If i remember correctly, i have to disable auto-start config on i3wm for `pulseaudio`. Since `pulseaudio` already starts on start-up.
