### ISSUE TITLE
backlight: wrong brightness percentage for amdgpu_bl0

### ISSUE THREAD

**Issue by EntityCuber** [polybar/polybar#1870]
I am getting wrong brightness percentage for my amdgpu_bl0

config:

[module/backlight]
type = internal/backlight
card = amdgpu_bl0
label = %percentage%%

Polybar currently is showing brightness is 25098% and it doesnt change when i change my brightness

I think this might be related to same issue  found in here:
https://github.com/Alexays/Waybar/pull/336

**Comment by patrick96** [comment]
Please check out the fix at #1900
