### ISSUE TITLE
filesystem: warn mode below threshold

### ISSUE THREAD

**Issue by petrmanek** [polybar/polybar#1871]
## Is your feature request related to a problem? Please describe.
Nope. Just switched to polybar and miss this particular feature.

## Why does polybar need this feature?
Currently, filesystem modules have only 2 modes: _mounted_ or _unmounted_. This is useful in some cases (e.g. network or USB storage mounts), but doesn't capture a more frequent issue when a mount runs out of free space. Other bars support some variants of conditioned appearance in such cases. It would be cool if Polybar caught up.

## Describe the solution you'd like
I propose to replicate the scheme used in the _temperature_ module:

 1. add a new _warn_ mode to allow appearance customization when the free space is low,
 2. add a new _warn-space_ attribute to control when the _warn_ mode is activated; its value could either be a 0-1 float (percentage of the total capacity) or a value in bytes, if the value is negative (which could be the default for compatibility reasons), the _warn_ mode would be permanently disabled

## Describe alternatives you've considered
The same can be done with a custom shell script, but that in my opinion introduces too much overhead. It would be nice to have the same thing along with the low memory footprint of Polybar.

## Additional context
N/A

**Comment by patrick96** [comment]
We will consider this when we rework the module state machines.

**Comment by patrick96** [comment]
This has now been implemented in #2199
