### ISSUE TITLE
tray: system tray disappears randomly and reappears only on mouse hover

### ISSUE THREAD

**Issue by pcb060** [polybar/polybar#1872]
## Describe the issue
The system tray disappears at (apparently) random times and reappears only after I move my mouse over the empty space where it should be. This behaviour doesn't stop after the first time but keeps repeating.

**Expected behavior:**

Tray should stay where it is, visible at all times.

**Actual behavior:**
Tray disappears at random.
Log says ```error: tray: Failed to put tray above 0x4800001 in the stack (XCB_MATCH (8))``` but same issues I found outputting this error couldn't help me.

**Was it working before?**
I have no idea. I have started using polybar again only recently, last time I used it (probably one year~ ago) with the same wm (i3-gaps) I had no issues of this kind.

## To Reproduce
You can find my current config [here](https://github.com/pcb060/dotfiles/blob/master/.config/polybar/miami/topbar_config).
Notice i used ```tray-reparent = true``` in hopes it would help with this problem (I found something similar in the issues some time ago) and even tried every kind of ```wm-restack``` and ```ovverride-redirect``` combination, but had no success.

## Polybar Log
```
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
warn: Ignoring restack of i3 window (not needed when `override-redirect = false`)
error: tray: Failed to put tray above 0x4800001 in the stack (XCB_MATCH (8))
```

## Screenshots
![Working](https://i.imgur.com/j3UZkPL.png)
![Not working](https://i.imgur.com/8M5Bg4z.png)

## Environment:
* WM: i3-gaps
* Distro: Arch Linux
* Output of `polybar -vvv`:
```➜ ~ polybar -vvv
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now ```

**Comment by chrissnell-okta** [comment]
I am seeing this, too.  The bar will not appear during hover, though.  It stays blanked-out.  I'm also using i3-gaps and haven't touched my i3 or polybar configurations in many months.

![2019-10-23-29_658x93](https://user-images.githubusercontent.com/54363132/67420123-fde6ad00-f59b-11e9-9fda-a3e3907f2215.png)

**Comment by pcb060** [comment]
It may be just a coincidence, but after excluding Polybar from compton it seems to have stopped

**Comment by patrick96** [comment]
That could be it. Try adding `"window_type = 'dock'"` in all the `*-exclude` settings.

**Comment by pcb060** [comment]
Unfortunately that didn't work. I tried excluding ```"name = 'Polybar tray window'" but that didn't work either.

**Comment by patrick96** [comment]
Hmm. I don't myself use compton anymore so I don't really know.

**Comment by patrick96** [comment]
Closing this as this is either a compositor issue or the same underlying issue as #425.
