### ISSUE TITLE
polybar fails to load after updating jsoncpp to version 1.9.1-1

### ISSUE THREAD

**Issue by PureArtistry** [polybar/polybar#1873]
Just got the new update for jsoncpp on Arch, after which polybar fails to load:

polybar: error while loading shared libraries: libjsoncpp.so.20: cannot open shared object file: No such file or directory

I've gone back to version 1.8 of jsoncpp and it works fine again.

edit, I should also mention I'm using I3wm

**Comment by PistaMista** [comment]
I had the same issue and reinstalling polybar fixed it

**Comment by PureArtistry** [comment]
I just re-installed polybar (cleanbuild) and it works fine now, thanks.

**Comment by Lomadriel** [comment]
Yeah that's a known issue: https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp

**Comment by PureArtistry** [comment]
I really should have checked there first, sorry about that.
