### ISSUE TITLE
MPD doesn't update on hidden bars

### ISSUE THREAD

**Issue by mcarlton00** [polybar/polybar#1875]
## Describe the issue
If the mpd module is active on a bar that's been hidden with `echo 'cmd:hide' > /tmp/polybar_mqueue.$PID`, it doesn't update.  When the bar is shown again, it has out of date now playing info until the playing file changes.

**Expected behavior:**
The mpd module is always kept up to date regardless of whether it's currently shown

**Actual behavior:**
The mpd module doesn't update unless that bar is displayed when the song changes

**Was it working before?**
Unknown, this is the first time I've used hidden bars

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/music]
enable-ipc = true
override-redirect = true
modules-left = title
width = 25%
height = 27
offset-y = 27
border-size = 0

[module/mpd]
type = internal/mpd
label-song = %title% - %artist%
format-online = <label-song>
interval = 2
host = 127.0.0.1
port = 6600
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
1. Launch with `polybar music`
2. Hide bar with `echo 'cmd:hide' > /tmp/polybar_mqueue.$PID`
3. Change song playing in mpd
4. Show bar with echo `'cmd:show' > /tmp/polybar_mqueue.$PID`

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
% polybar music
warn: No fonts specified, using fallback font "fixed"
```

## Environment:
* WM: i3
* Distro: Arch Linux
* Output of `polybar -vvv`: 
```
% polybar -vv
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
I don't think it matters in this case, but I'm using Mopidy, not straight mpd

**Comment by patrick96** [comment]
Thanks for reporting :)
