### ISSUE TITLE
format-underline does not work with mpd module

### ISSUE THREAD

**Issue by flexibeast** [polybar/polybar#1879]
Context: Void Linux, polybar 3.4.0, installed via the package system

The `format-underline` setting does not seem to work with the `mpd` module; no underline is displayed at all.

**Comment by Lomadriel** [comment]
That's totally normal since there is no default formatter for the MDP module.
Your should use `format-online-underline` for example.
More information on this page: https://github.com/polybar/polybar/wiki/Module:-mpd

**Comment by flexibeast** [comment]
Ah okay, thanks!

**Comment by Lomadriel** [comment]
Yeah that's might be tricky at the beginning.
