### ISSUE TITLE
string_util::split_into ignores final delimiter

### ISSUE THREAD

**Issue by ratorx** [polybar/polybar#1881]
## Describe the issue
**Expected behavior:**

string_util::split_into should not ignore the final delimiter.

The string `foo;bar;` should be split into `["foo", "bar", ""]`

**Actual behavior:**

The string `foo;bar;` is split into `["foo", "bar"]`

**Was it working before?**
I don't think this is a regression. It may even be the intended behaviour. There are a couple of reasons why I think this should be changed:

1. This is not consistent with some other string splitting functions. I have tested the Python string.split as well as boost::split.

2. Declaring an empty i3 (and possibly others? - I only checked i3) workspace icon does not use the expected syntax. I.e. using `ws-icon-0 = foo;` will cause workspaces called foo to use `ws-icon-default` rather than an empty value. My current workaround is to do `ws-icon-0 = foo;;`

## Environment:
* WM: i3-gaps
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

If you accept this as a bug, I can submit a PR to fix it.

**Comment by Lomadriel** [comment]
I'll see why this is like this but I think this might be a bug.

**Comment by Lomadriel** [comment]
I just opened a new PR to fix this problem. If you can test if it works as intended.
