### ISSUE TITLE
[qtile/polybar] After click on polybar mouse interaction no longer possible.

### ISSUE THREAD

**Issue by tamis-laan** [polybar/polybar#1887]
I just installed and configured polybar, I'm using it in conjunction with the qtile window manager. When I start polybar everything works fine, I can use the mouse wheel to change the volume of the pulseaudio module. However when I click on any region of the polybar I can no longer interact with the bar using my mouse. Scrolling on the pulseaudio module to change the volume no longer works. The click does work the first time you click as I can mute the audio by clicking on the pulseaudio module in the first click. However thereafter I can no longer unmute by clicking or change the volume level by scrolling. After restarting polybar it works again for just the first click. Is this a known issue? I havn't been able to find a solution so far.

**Comment by patrick96** [comment]
Where you able to solve this?
