### ISSUE TITLE
python2 will be unmaintaned soon

### ISSUE THREAD

**Issue by g4s8** [polybar/polybar#1892]
## Is your feature request related to a problem? Please describe.
Python 2.7 will not be maintained past 2020, see: https://pythonclock.org/
A lot of packages also drop `python2.7` support: https://python3statement.org/

## Why does polybar need this feature?
Some critical bug can be found in `python2.7` which will not be fixed. Also, many users will remove `python2.7` from their machines.

## Describe the solution you'd like
User `python3.*` instead and `python3` libraries & dependencies.

## Describe alternatives you've considered
Stop using python (it seems, this project doesn't have a lot of python code)

## Additional context
I can't remove `python2.7`from Gentoo right now only because `polybar` requires it:
```
!!! The ebuild selected to satisfy "x11-misc/polybar" has unmet requirements.
- x11-misc/polybar-3.2.1::gentoo USE="alsa curl ipc network -i3wm -mpd -pulseaudio" ABI_X86="(64)" PYTHON_TARGETS="-python2_7"

  The following REQUIRED_USE flag constraints are unsatisfied:
    python_targets_python2_7
```

**Comment by Lomadriel** [comment]
I totally agree with you, we should remove python2.7 from our codebase.
However we don't use python 2 in polybar but in one of our dependency xpp :/
We didn't write this dependency and personally I don't know how this dependency works…

I already tried to remove the python code from this dependency but my knowledge of python is quite limited...
If someone want to help me with that, I'll be extremely grateful.

**Comment by g4s8** [comment]
@Lomadriel I've found that python is used here to generate documentation with [Sphinx](https://www.sphinx-doc.org) - just one `.py` file in `./doc/conf.py`. I cloned this repo, installed sphinx for python3 and run documentation builder from `./doc` dir:
```bash
git clone git@github.com:polybar/polybar.git && cd ./polybar
pip3 install sphinx --user
mkdir ./build && cd ./build
cmake ../doc/
make
```
and sphinx successfully generated documentation in `./build` dir  using python3. So I'd just update requirements on the README page that python3 can be used for building docs.

---

Also, I've found in the wiki, that `python3-sphinx` should be used for that: https://github.com/polybar/polybar/wiki/Compiling#build-dependencies

**Comment by Lomadriel** [comment]
Oh, I didn't see that, I was thinking we were using python3 for that !

**Comment by patrick96** [comment]
The only place polybar uses python2 is in the generators in the `xpp` dependency [here](https://github.com/polybar/xpp/tree/master/generators). Unfortunately, as @Lomadriel already mentioned none of us actually wrote that code and it's a few thousand lines of python2 code that doesn't run under python3.

I have considered two ways to deal with this:

* Drop the entire xpp submodule. `xpp` is mainly a utility library that makes it easier for us to interact with the X server. Removing it would take away that ease of programming and would require us to change all existing code to directly use `xcb`. xpp is used all over so this would basically mean we would have to change almost every file in the repo.
* Invest A LOT of time figuring out how to port the code to python3.

Dropping xpp would have other benefits as well like shorter compilation times but I don't know if it's worth the extra effort and the thousands of lines of new code to do the same thing in plain xcb. We should probably look more into porting it may turn out not to be as bad as we think.

**Comment by patrick96** [comment]
Welp, I highly overestimated the time it would take to port this. Was basically only fixing the errors thrown with the new python version and afterwards it worked. Of course there could still be some bugs that don't happen on my setup.

**Comment by patrick96** [comment]
Oops, the issue will only be fixed once we update the submodule

**Comment by g4s8** [comment]
@patrick96 thanks! Can you please make new tag & release with this change?

**Comment by patrick96** [comment]
Sure, I'll try to put out 3.4.1 this week.
