### ISSUE TITLE
why i can't build with i3 module?

### ISSUE THREAD

**Issue by guoe2005** [polybar/polybar#1895]
my system is gentoo, i emerged libsigc++, and jsoncpp, but i can't emerge x11-wm/i3 because i am using i3-gaps
and i emerge USE="i3" everytime but my polybar ,--version always shows "-
i3" can some one help me?

**Comment by patrick96** [comment]
The `USE` flag in the gentoo ebuild is called `i3wm`. If you still have problems with gentoo specifically, you best contact the ebuild maintainer since normally i3 supported is enabled if i3 and jsoncpp is installed.

**Comment by guoe2005** [comment]
thanks
