### ISSUE TITLE
Unicode in menu items not displayed

### ISSUE THREAD

**Issue by stevensonmt** [polybar/polybar#1902]
**Expected behavior:**
Unicode characters display correctly in menu items.

**Actual behavior:**
Some unicode displayed but not all even though loaded fonts do cover the characters in question. (In this case Fira Sans and Fantasque Sans Mono both provide the missing glyph.)
```
[module/powermenu]
type = custom/menu

expand-right = false

format-spacing = 1

label-open = ⏻
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = ↻
menu-0-0-exec = menu-open-1
menu-0-1 = ⏻
menu-0-1-exec = menu-open-2
menu-0-2 = ⏾
menu-0-2-exec = menu-open-3

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = ↻ reboot
menu-1-1-exec = sudo systemctl reboot

menu-2-0 = power off
menu-2-0-exec = sudo systemctl poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0
```
![Screenshot_2019-10-16_22-36-36](https://user-images.githubusercontent.com/8891908/66980608-40712c80-f066-11e9-8545-f9f90a67ec57.png)

In the screenshot, you can see top right corner the missing "reboot" icon that is visible in vim.

**Comment by patrick96** [comment]
Do you get "Dropping unmatched character" warnings in the polybar output?

Please also post your bar section and the entire polybar output when you run it with the `info` loglevel (`-l info`).

**Comment by stevensonmt** [comment]
```
* Loaded font "Fantasque Sans Mono:style=Bold:size=12" (name=Fantasque Sans Mono, offset=0, file=/usr/share/fonts/TTF/FantasqueSansMono-Bold.ttf)
* Loaded font "Fira Sans:style=Regular:size=12" (name=Fira Sans, offset=0, file=/usr/share/fonts/TTF/FiraSans-Regular.ttf)
* Loaded font "Font Awesome 5 Free Solid:style=Solid:size=12" (name=Font Awesome 5 Free, offset=0, file=/usr/share/fonts/TTF/fa-solid-900.ttf)
* Loaded font "Source Sans Pro:style=Regular:size=12" (name=Source Sans Pro, offset=0, file=/usr/share/fonts/adobe-source-sans-pro/SourceSansPro-Regular.otf)
...
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e924)
warn: Dropping unmatched character ↻ (U+21bb)
warn: Dropping unmatched character  (U+e065)
```
bar section of config:
```
width = ${env:width}
offset-x = ${env:offsetx}
monitor = ${env:monitor}
;offset-y = ${env:y}
;width = 100%
height = 27
fixed-center = false
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3
line-color = #f00
border-size = 0
border-color = #00000000
padding-left = 0
padding-right = 2
module-margin-left = 1
module-margin-right = 2
font-0 = Fantasque Sans Mono:style=Bold:size=12;0
font-1 = Fira Sans:style=Regular:size=12;0
font-2 = Font Awesome 5 Free Solid:style=Solid:size=12;0
font-3 = Source Sans Pro:style=Regular:size=12;0
modules-center =
modules-right = filesystem xbacklight pulseaudio memory cpu wlan
eth battery temperature date powermenu
tray-position = right
tray-padding = 2
cursor-click = pointer
cursor-scroll = ns-resize
```

https://www.fileformat.info/info/unicode/font/fontlist.htm?text=%E2%86%BB+-+CLOCKWISE+OPEN+CIRCLE+ARROW+%28U%2B21BB%29
shows at least two of the loaded fonts on my system should provide the glyph.
![Screenshot_2019-10-17_21-53-57](https://user-images.githubusercontent.com/8891908/67066751-b76ef980-f128-11e9-9110-3bd132a68e18.png)

**Comment by patrick96** [comment]
I don't know where that website gets its information but (at least on my system), neither `Fira Sans` nor `Fantasque Sans Mono` provide that glyph.

I would recommend using `gucharmap` to see which glyphs are provided by a certain font (step 2 of our [debugging font issues guide](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues)).
There is also a [perl script](https://github.com/polybar/polybar/wiki/Fonts#find-fonts-for-glyphs) on the wiki that will tell you all fonts that provide a certain glyph.

On my system both dejavu and Unifont provide that glyph, so adding one of them should fix this.

**Comment by stevensonmt** [comment]
Bad information from that website then. Thanks for your help.
