### ISSUE TITLE
--reload flag doesn't work for included files

### ISSUE THREAD

**Issue by nathanchere** [polybar/polybar#1909]
## Describe the issue

When splitting configuration into multiple files and loading them using `include-file` directives, the `--reload` flag only picks up changes at the top config level. 

**Expected behavior:**
Polybar should also reload when any files referenced with `include-file` are changed,.

## To Reproduce
The simplest way is to create an empty file and reference it from your polybar config, e.g.:

```
[settings]
margin-top = 0
margin-bottom = 0
include-file = ~/.config/polybar/extra.config
```

Whenever you run Polybar with  `--reload` and then save changes to `extra.config`, Polybar should reload.

## Additional context

The file system watchers are set in [main.cpp](https://github.com/polybar/polybar/blob/56e24992dfe2fba32b1f6b07fc37ab7d0a7c6aba/src/main.cpp#L142): 

https://github.com/polybar/polybar/blob/56e24992dfe2fba32b1f6b07fc37ab7d0a7c6aba/src/main.cpp#L142

```cpp
   if (cli->has("reload")) {
      config_watch = inotify_util::make_watch(conf.filepath());
    }
```

Fortunately this already happens after configuration is loaded, and it looks like a fairly straight-forward task to keep track of `include-file` calls and create a watcher for each one.

**Comment by nathanchere** [comment]
I don't see a way of assigning it to myself, but I'll try and get it done this weekend.

**Comment by patrick96** [comment]
Hi, this was already suggested in #675. Let's track that over there, unfortunately it seems you cannot assign non-members to issues.

Yeah that should not take that much work because we already have a list of all included files in `m_included` in the config.

Thanks for tackling this :)
