### ISSUE TITLE
Separator with a different foreground

### ISSUE THREAD

**Issue by infokiller** [polybar/polybar#1913]
I want to configure polybar to use a module separator with a foreground that's different from the regular bar foreground. Example:
![image](https://user-images.githubusercontent.com/10516814/67459837-22956000-f642-11e9-8461-8f630b99fde4.png)

I tried to use the following in my bar section but that didn't work:
```ini
separator = "|"
separator-padding = 1
separator-foreground = ${colors.foreground-alt}
```

So, as a workaround, I added the following simple text module:
```ini
; Workaround for using a module separator with a different foreground color than
; the one defined for the whole bar.
[module/sep]
type = custom/text
content = |
content-foreground = ${colors.foreground-alt}
content-padding = 1
```

And then I add the `sep` module between every pair of modules, for example:
```ini
modules-right = filesystem sep memory sep cpu sep keyboard-layout sep
```

This worked fine for some time, but recently after upgrading polybar it started printing this error:
```
error: The module "module/sep" appears multiple times in your modules list. This is deprecated and should be avoided, as it can lead to inconsistent behavior. Both modules will be displayed for now.
```

I traced this back to #1534 

I don't want my config to break in a future upgrade, hence I opened this issue to ask how to handle this.

Thanks!

CC @patrick96

**Comment by pcb060** [comment]
I do this by simply setting ```separator = %{F#RRGGBB}|%{F-}```

**Comment by infokiller** [comment]
Thanks @pcb060 that works well!

**Comment by patrick96** [comment]
That is an interesting usecase that I didn't think about when I wrote #1534. I now made the module separator a label, so that `separator-foreground` and so on work. I will upload that shortly.
