### ISSUE TITLE
xworkspaces does not display workspace as occupied when using send_to_workspace

### ISSUE THREAD

**Issue by ronniedroid** [polybar/polybar#1922]
## Describe the issue
when you sent a window to a workspace using send_to_workspace the xworkspaces module doesn't show said workspace as occupied, but when you go to the said workspace and open a window on it, then leave the workspace, it shows it as occupied (displays the label-occupied-background and label-occupied-foreground). 

**Expected behavior:**
being in a workspace (for example 0) sending a window to another workspace (for example 4)
the xworkspaces should display the label-occupied-background and label-occupied-foreground for the workspace the window was sent to (workspace 4)

**Actual behavior:**
The xworkspaces does not display the abel-occupied-background and label-occupied-foreground for the workspace the window was sent to.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```[module/ewmh]
type = internal/xworkspaces
pin-workspaces = true
format = <label-state>

label-active = %name%
label-active-foreground = #3b4252 
label-active-background = #88c0d0
label-active-padding = 2
label-active-margin = 1
label-occupied = %name%
label-occupied-background = #5e81ac
label-occupied-padding = 2
label-empty = %name%
label-empty-background = #3b4252
label-empty-foreground = #81a1c1
label-empty-padding = 2
label-urgent = %name%
label-urgent-background = #bf616a
label-urgent-padding = 2

```
**to reproduce**

Open a window on a workspace, send the window to another workspace 

## Environment:
* WM: Berry
* Distro: Linux Mint
* Output of `polybar -vvv`:

polybar 3.4.0-24-g2b31a3f

Features: +alsa -curl -i3 -mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm -xcursor

Build type: Release
Compiler: /usr/bin/clang++
Compiler flags:  -Wall -Wextra -Wpedantic -Wno-error=parentheses-equality -Wno-zero-length-array 
Linker flags:

**Comment by Lomadriel** [comment]
Just to be sure, `send_to_workspace` is a cmd from your window manager?

**Comment by ronniedroid** [comment]
> Just to be sure, `send_to_workspace` is a cmd from your window manager?

yes, it is.

**Comment by Lomadriel** [comment]
I'll try to recheck this week-end but it seems that polybar doesn't receive the event from Xorg when a window is moved to another workspace using `berry`.

**Comment by patrick96** [comment]
I actually explicitly tested this behavior on herbstluft, so either berry is not sending an event in this case or we don't listen to the right events.

**Comment by kronn** [comment]
I also remember testing this for xmonad. Then again: xmonad emits a lot of events for everything.

**Comment by JLErvin** [comment]
I'm the `berry` developer - this was an issue on our end and fixed as of https://github.com/JLErvin/berry/pull/78/commits/5ab590cea3bcb7282108ee837e131d514389747c. Should have nothing to do with polybar.

**Comment by patrick96** [comment]
@JLErvin Thanks for letting us know :smiley: 

@ronniedroid Please let us know if you still have this issue and I will reopen this again.
