### ISSUE TITLE
incorrect display of telegram tray icon

### ISSUE THREAD

**Issue by Feresey** [polybar/polybar#1924]
## Describe the issue

I noticed this error only for the telegram-desktop application. More smart people say that the problem is transparency, but various settings did not help solve the problem.
The fact that the telegram icon is non-standard is an attempt to solve the problem. On standard, the problem is exactly the same. (I use a translator, so the text may be incomprehensible)

**Expected behavior:**

It **must** displays correctly

**Actual behavior:**

It displays **not** correctly

**Was it working before?**
Nope.
* Did you also experience this bug in an earlier version of polybar?
Yep.
* If no, what was the last version where this worked correctly?
No one.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
tray-position = right # or left
```

## Polybar Log
[poly.log](https://github.com/polybar/polybar/files/3780523/poly.log)

## Screenshots
![image](https://user-images.githubusercontent.com/33696249/67714318-b8c9dd00-f9d8-11e9-8b52-57cbf2fba646.png)
![image](https://user-images.githubusercontent.com/33696249/67714336-c2ebdb80-f9d8-11e9-898f-25e11941ba4f.png)
![image](https://user-images.githubusercontent.com/33696249/67714356-cd0dda00-f9d8-11e9-8d01-cdec7fa9e371.png)

## Environment:
* WM: i3
* Distro: Arch Linux x86_64
* Output of `polybar -vvv`: 
```
polybar 3.4.0-20-g4ab251f3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -m64 -flto -funroll-loops -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
main config
[config.txt](https://github.com/polybar/polybar/files/3780527/config.txt)

**Comment by patrick96** [comment]
Does this always happen?

It looks like this is the same issue as #1603 and #591

We haven't been able to reliably reproduce this, so we have no idea how to fix this. Which telegram application are you using?

**Comment by Feresey** [comment]
> Does this always happen?
in 19 of 20 cases
> Which telegram application are you using?
Latest release from official github. On older versions of the telegram the error was the same
https://github.com/telegramdesktop/tdesktop/releases

**Comment by Feresey** [comment]
when I moved the tray to the middle of the bar the problem disappeared
![image](https://user-images.githubusercontent.com/33696249/68087282-4daf5900-fe65-11e9-8a34-6c5508fa10d5.png)
I think now to divide the bar into two parts: with a tray in center and without

**Comment by Feresey** [comment]
After the last telegram update everything works as it should
