### ISSUE TITLE
pin-workspaces not working with i3-gaps

### ISSUE THREAD

**Issue by marcospb19** [polybar/polybar#1925]
## Description
I have a 2-monitor setup
pin-workspaces isn't hiding workspaces at the other monitor from the bar.

**Expected behavior:**
Workspaces at monitor 1 only appear to the bar 1
Workspaces at monitor 2 only appear to the bar 2

**Actual behavior:**
All workspaces appear in all bars

**Was it working before?**
pin-workspaces never worked to me

## To Reproduce

```dosini
pin-workspaces = true
```
Having a 2-monitor setup, open a workspace at each monitor

## Polybar Log
```
error: tray: Failed to put tray above 0x0a00001 in the stack (XCB_MATCH (8))                                               
error: tray: Failed to put tray above 0x1000001 in the stack (XCB_MATCH (8))
warn: Systray selection already managed (window=0x0a00005)                                                                          
```

## Screenshots
Workspaces 1 and 2 are located on the left monitor
Workspaces 3 and 4 are located on the right monitor
This is how the bar looks on each monitor:
"3412"
![image](https://user-images.githubusercontent.com/38900226/67827309-62c76900-faae-11e9-9b65-f37073dd6b7f.png)

It should only show 1,2 and 3,4 for each one
(for some reason the workspaces at the left monitor appear at the right, it's flipped)

## Environment:
* WM: i3-Gaps
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.0-29-g6849b8a5

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
I already tried to compile Polybar

**Comment by Lomadriel** [comment]
Can you post your config.

**Comment by ronniedroid** [comment]
@marcospb19 you have a mistake in your comment

> Workspaces 1 and 2 are located on the left monitor
> Workspaces 3 and 4 are located on the left monitor

it should be left and right. 

best

**Comment by marcospb19** [comment]
> @marcospb19 you have a mistake in your comment

Thanks for pointing that out, now it is correct, and I added more explanation. Please read it again

**Comment by marcospb19** [comment]
Let me try removing useless stuff from my configuration file, then I'll edit this message posting it

**Comment by patrick96** [comment]
Could you please try the fix in https://github.com/polybar/polybar/pull/1929

**Comment by marcospb19** [comment]
> Could you please try the fix in #1929

Didn't work

Compiled from your branch, (commit 7bb3529), then I replaced `/usr/bin/polybar` and `/usr/bin/polybar-msg` with the new objects from `build/bin/`, killed the polybar process and ran it again. The problem persists.

**Comment by patrick96** [comment]
Hmm, seems I missed something along the way. Thanks for testing

**Comment by patrick96** [comment]
Oh wow, I didn't read your post thoroughly enough, I though you were using the xworkspaces module.

`pin-workspaces` is a property of the i3 module, setting in the bar section doesn't do anything.

**Comment by marcospb19** [comment]
Thanks for all the help :+1: , and sorry for the dumb confusion here :disappointed:.
