### ISSUE TITLE
incorrect time after unhibernating

### ISSUE THREAD

**Issue by jw0k** [polybar/polybar#1932]
## Describe the issue
After unhibernating the computer, the display time is wrong.

## To Reproduce
- hibernate
- wait some time
- unhibernate

## Environment:
* WM: i3
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now```

**Comment by patrick96** [comment]
The date module updates every `interval` seconds, is the time wrong even after it updates? Does the module even update?

**Comment by jw0k** [comment]
@patrick96 Looks like it does not update at all after unhibernating. It just shows, say, 16:03 and it stays that way forever (until I click on it). My interval is set to 5 seconds like that:

```
[module/date]
type = internal/date
interval = 5
```

After I click on the time it immediately corrects itself and starts updating again.

**Comment by patrick96** [comment]
The symptoms seem to be consistent with the ones described in https://github.com/polybar/polybar/issues/857. Any chance that your system clock moves backwards when your system wakes up?

If you can, try out the PR https://github.com/polybar/polybar/pull/1725 which should contain a fix for this. Alternatively compile the current version of polybar with clang instead of gcc (add `-DCMAKE_CXX_COMPILER=clang++` to the first `cmake` call in the PKGBUILD).

If you want to, try both solutions separately, we're interested to hear if both work.

**Comment by jw0k** [comment]
@patrick96 Yes, actually my system clock does move backwards after Linux wakes up. I dual-boot with Windows, which overwrites hardware clock with the local time. Linux uses UTC and since I'm in the +1 time zone after I wake up Linux the systemd-timesyncd will correct it after about 1 minute by moving it back one hour. I'm planning to fix it soon by modifying a registry setting in Windows so that it sets UTC time in the hardware clock.

I've compiled polybar with clang as you suggested and retried the scenario but it still does not work correctly. I'll try the patch you mentioned at a later time.

**Comment by jw0k** [comment]
@patrick96 OK, I've checked the patch and it works. Although it didn't compile at first since `check_symbol_exists` cmake function used in `cmake/03-libs.cmake` was not found. But I easily fixed it by adding `include(CheckSymbolExists)` in the line above.

Thanks for help :)

**Comment by Lomadriel** [comment]
> If you can, try out the PR #1725 which should contain a fix for this. Alternatively compile the current version of polybar with clang instead of gcc (add -DCMAKE_CXX_COMPILER=clang++ to the first cmake call in the PKGBUILD).

Alone this won't work since clang is using gcc's c++ library (`libstdc++`) by default.
I think you also need to add the following flag to the cmake command:
`-DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -lc++abi"`

However, I don't know if the behavior of the library of clang is correct.

> @patrick96 OK, I've checked the patch and it works. Although it didn't compile at first since `check_symbol_exists` cmake function used in `cmake/03-libs.cmake` was not found. But I easily fixed it by adding `include(CheckSymbolExists)` in the line 

Hum strange, I'll check that.

**Comment by patrick96** [comment]
@Lomadriel do you think the patch worked because we started using `steady_clock` everywhere or because of the custom `condition_variable` implementation?

**Comment by Lomadriel** [comment]
> @Lomadriel do you think the patch worked because we started using `steady_clock` everywhere or because of the custom `condition_variable` implementation?

Nop, with gcc it is needed to use my implementation and the a `steady_clock`.

**Comment by patrick96** [comment]
Yes, I see. The module `sleep` method uses the `m_sleephandler` condition variable.

That sucks, I really don't want to have to maintain our own version of `condition_variable` in polybar. Maybe we should switch to clang for a while and use `libc++`?
