### ISSUE TITLE
Polybar giving 'Dropped  Characters' error, none of suggested fixes working

### ISSUE THREAD

**Issue by pradyungn** [polybar/polybar#1933]
I'm using polybar's MPD module, and for some reason it's dropping all of the japanese characters that appear in the module. I've put in all my fonts properly, tried using wuncon siji, the whole shebang. Fc-match returns my fonts perfectly. I checked my unicode tables locally, and it shows the characters properly. Any idea what's happening?

**Comment by Lomadriel** [comment]
Config please

**Comment by pradyungn** [comment]
Oops, my bad!

font-0 = "Ubuntu Condensed:size=10;2"
font-1 = "icomoon\-feather:size=10;2"
font-2 = "xos4 Terminus:size=12;2"

**Comment by patrick96** [comment]
Which characters are getting dropped?

Which of the fonts you listed are supposed to provide japanese characters? Because on my system none of them do. Did you enable `Show only glyphs from this font` in gucharmap?

**Comment by pradyungn** [comment]
You're right, upon further inspection none of the fonts contain japanese characters. It was supposed to be ubuntu condensed though. Do I just find a font with the given characters and assign it to font-3?

**Comment by patrick96** [comment]
That's the idea. Unifont has some japanese glyphs (though not good quality I think) and noto sans cjk is probably the go-to.
