### ISSUE TITLE
More customization with tray icons

### ISSUE THREAD

**Issue by LukasP46** [polybar/polybar#1935]
It would be awesome, if there would be more visual options to the tray aspect of polybar.

Two things in mind:
 grey scaling or coloring the symbols
 hide some icons in a separate menu, like in Windows.

The coloring would be nice, if you try to achieve a one colored design.
Hiding some icons helps with for example messengers witch, should run in the background just for notification.

**Comment by patrick96** [comment]
We will probably never have a tray like on windows where you can click on an arrow and it pops up the other icons. But something like tray blacklist is maybe possible (it was also requested in #1360)

**Comment by patrick96** [comment]
We will not implement this for current tray implementation.
