### ISSUE TITLE
xworkspaces | configurable mouse keys to cycle desktops

### ISSUE THREAD

**Issue by Shamaoke** [polybar/polybar#1942]
The xworkspaces module allows cycling desktops by using the mouse wheel. However, there are no means to configure the direction that will be used for moving to the next/previous desktop (which is “up“ for the next and “down“ for the previous desktop by default). There should be a setting which allows a user to configure this function according to his convenience (e. g. change “up“  for the previous and “down” for the next desktop).

**Comment by patrick96** [comment]
Hi, this will be possible once we implement #1524. I added a reference this this over there.
