### ISSUE TITLE
include multiple files with wildcard

### ISSUE THREAD

**Issue by eoli3n** [polybar/polybar#1946]
## Is your feature request related to a problem? Please describe.
We only can declare static path, this is not modular.

## Why does polybar need this feature?
Make configuration more modular.

## Describe the solution you'd like
It would be great to create file per module in a ``modules.d`` and add in config
```
include-files = modules.d/*
```

**Comment by patrick96** [comment]
I don't think we'll do wildcards, so no `include-file = modules.d/*.conf` but maybe if `include-file` points to a folder, we include all its contents.

**Comment by GuilhermeJSilva** [comment]
I'm looking to tackle this issue, but I think it would be batter if instead we created the `include-directory` keyword @patrick96

**Comment by patrick96** [comment]
@GuilhermeJSilva Cool :smiley:! Looking forward to it. Yes, `include-directory` is probably better.

**Comment by GideonWolfe** [comment]
I'm just now attempting to break up my polybar with one file per module, and stumbled across this issue. I would love to see this implemented!!
