### ISSUE TITLE
CMake uses Python 2 instead of Python 3

### ISSUE THREAD

**Issue by fliiiix** [polybar/polybar#1950]
## Build Process
CMake is unable to find the correct python version.

Python 3 is installed and the default version. 
```
$ python --version
Python 3.7.5
```
```
$ ls -la /usr/bin/python*
lrwxrwxrwx. 1 root root     9 Oct 17 13:54 /usr/bin/python -> ./python3
lrwxrwxrwx. 1 root root     9 Oct 21 15:13 /usr/bin/python2 -> python2.7
-rwxr-xr-x. 1 root root 16072 Oct 21 15:13 /usr/bin/python2.7
lrwxrwxrwx. 1 root root     9 Oct 17 14:21 /usr/bin/python3 -> python3.7
-rwxr-xr-x. 2 root root 15440 Oct 17 14:21 /usr/bin/python3.7
-rwxr-xr-x. 2 root root 15440 Oct 17 14:21 /usr/bin/python3.7m
-rwxr-xr-x. 1 root root   396 Sep  3 20:03 /usr/bin/python3-mako-render
-rwxr-xr-x. 1 root root  2558 Jul 25 16:14 /usr/bin/python-argcomplete-check-easy-install-script
-rwxr-xr-x. 1 root root   318 Jul 25 16:14 /usr/bin/python-argcomplete-tcsh
```

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:  3.4.1

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```
$ cmake --version
cmake version 3.14.5

cmake -DCMAKE_C_COMPILER="clang" \
              -DCMAKE_CXX_COMPILER="clang++" \
              -DCMAKE_BUILD_TYPE="RELEASE" \
              -DENABLE_ALSA:BOOL="ON" \
              -DENABLE_I3:BOOL="ON" \
              -DENABLE_MPD:BOOL="OFF" \
              -DENABLE_NETWORK:BOOL="ON"  \
              -DENABLE_CURL:BOOL="ON" \
              -DBUILD_IPC_MSG:BOOL="ON" ..

-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- Using supported compiler Clang-9.0.0
--  Build:
--    Version: 3.4.1
--    Type: RELEASE
--    CXX: /usr/bin/clang++  -Wall -Wextra -Wpedantic -Wno-error=parentheses-equality -Wno-zero-length-array -O2 -DNDEBUG
--    LD: /usr/bin/ld  
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [ ]   documentation
--  Module support:
-- [X]   alsa (1.2.1.2)
-- [X]   curl (7.66.0)
-- [X]   i3
-- [ ]   mpd
-- [X]   network (libnl) (3.5.0)
-- [X]   pulseaudio (13.0-rebootstrapped)
-- [X]   xkeyboard (1.13.1)
--  X extensions:
-- [X]   xcb-randr (1.13.1)
-- [X]   xcb-randr (monitor support) (1.13.1)
-- [X]   xcb-composite (1.13.1)
-- [X]   xcb-xkb (1.13.1)
-- [ ]   xcb-xrm
-- [X]   xcb-cursor (0.1.3)
--  Log options:
-- [X]   Trace logging
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "2.7.17", but
  required is at least "3.5" (found /usr/bin/python2.7)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPythonInterp.cmake:160 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  lib/xpp/CMakeLists.txt:27 (find_package)


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/polybar/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/polybar/build/CMakeFiles/CMakeError.log".
```

## Environment:
* Distro (with Version): Fedora 31

**Comment by patrick96** [comment]
Try deleting the build directory and build again. This sometimes happens when you ran cmake before we dropped python2

**Comment by fliiiix** [comment]
> when you ran cmake before we dropped python2

I didn't but deleting `CMakeCache.txt` and building again worked. :confused: 

Thanks :tada:

**Comment by patrick96** [comment]
That's strange, so this was a fresh clone?

Because the cmake should never pick up python 2 with polybar 3.4.1

**Comment by fliiiix** [comment]
Very strange indeed. I run this ansible playbook on a fresh installed Fedora 31 https://github.com/fliiiix/dotfiles/blob/master/functions/polybar.yml

**Comment by patrick96** [comment]
Yeah this all looks good, not really sure why this happened. I don't think we missed anything in the code. Let's see if anyone else experiences the same issue.

**Comment by gigavinyl** [comment]
I'm getting this error as well on the latest release.

**Comment by patrick96** [comment]
@gigavinyl did you delete the `build` directory?

**Comment by gigavinyl** [comment]
@patrick96 no :thinking:

**Comment by patrick96** [comment]
@gigavinyl When you built polybar, is it possible that the build directory from a previous build was still there? If so, that build directory would have used python2 but the new version no longer allows this. Try to delete the build directory and build again.

**Comment by gigavinyl** [comment]
Hmm this is a fresh copy. I'm switching from NetBSD to OpenBSD rn and they have a port for polybar

**Comment by patrick96** [comment]
@gigavinyl Do you get this error on every fresh copy of the repository/release archive? In a completely fresh copy (no caches of the build directory, etc.) there should be no way for polybar (or rather xpp) to pick up python2 for any reason.

**Comment by fliiiix** [comment]
@patrick96 I mean I don't see at the moment how it can happen but I'm fairly confident that this is exatly what happened to me as well new fedora, new checkout and then it failed

**Comment by patrick96** [comment]
@fliiiix And you have not seen the issue since? Can you take me through the steps you took to build polybar the first time?

**Comment by fliiiix** [comment]
I just double checked and even in a fresh VM I couldn't reproduce the issue 
here is more or less what I did:

```
git clone https://github.com/fliiiix/dotfiles.git
cd dotfiles
sudo dnf install -y ansible python3-dnf
ansible-playbook -i localhost, -c local --ask-become-pass functions/polybar.yml
```

**Comment by patrick96** [comment]
> I just double checked and even in a fresh VM I couldn't reproduce the issue

So there probably was something cached somewhere (even though it was a new system :thinking:). I don't really see where that could have been, but I also don't completely understand your setup. 

In any case, let us know if the issue comes back, but I don't think it will.

**Comment by gigavinyl** [comment]
Hmm just tried a fresh recursive clone and still got the error :/

**Comment by patrick96** [comment]
@gigavinyl Does the OpenBSD port somehow force python2? And do you have python3 installed?

**Comment by gigavinyl** [comment]
Oop! I fixed it by symlinking python3.7 to /usr/local/bin/python and that fixed it :)

**Comment by gmindflow** [comment]
when using the cmake command adding the tag "`-DPYTHON_EXECUTABLE=$(which python3)`" is also a solution too.
