### ISSUE TITLE
Polybar Debian Package

### ISSUE THREAD

**Issue by LCRERGO** [polybar/polybar#1959]
As I see from the installation instructions there are no specific way to install polybar in Debian based distros, which gives me the following question:
Will polybar be packaged under Debian format? If not can I try to do something about it?

**Comment by patrick96** [comment]
*We* the polybar team will probably not package polybar for Debian. I don't even know if one of our team members actually uses Debian.

In general you don't need our permission to package polybar for another distro 😉
There has been an effort already by @jpleau in #1054, but I don't know what the current status is. Maybe contact them first and see what they've already got.

If you decide to package for debian, please let us know and feel free to ask for help in this thread.

**Comment by LCRERGO** [comment]
Thanks for the info, I've already contacted him, hope to make some progress at it.

**Comment by ayosec** [comment]
I have a Debian package for Polybar in <https://github.com/ayosec/polybar-debian>.

The repository includes a script to download the source and generate the package. Please let me know if the instructions in the README need to be improved.

There are compiled packages for Debian Buster, Ubuntu 18.04, and Ubuntu 19.10 in the [releases page](https://github.com/ayosec/polybar-debian/releases). These packages are built with GitHub Actions.

**Comment by patrick96** [comment]
@ayosec Oh wow, that's really cool. Github actions seem to really make this very easy.

**Comment by kronn** [comment]
I noticed that there are two patches in the repo. They seem like something that could be put into the main-repo.

@patrick96 what do you think of these?

https://github.com/ayosec/polybar-debian/blob/master/patches/0001-Show-full-contents-when-an-unmatched-character-is-fo.patch
https://github.com/ayosec/polybar-debian/blob/master/patches/0002-Set-precision-for-network-speedrate-to-1.patch

**Comment by patrick96** [comment]
@kronn If think the patch for the unmatched character warning would be nice for debugging.

I think my plan in #1063 covers the second one.

**Comment by mnet-repo** [comment]
I found debian builds here... worked on bullseye(currently sid)

**Comment by jaimet** [comment]
And, just to add to the pile, there are also working builds here:

https://build.opensuse.org/package/show/home:stevenpusser:polybar/polybar
