### ISSUE TITLE
Make -j in the build.sh

### ISSUE THREAD

**Issue by Nicholas-Baron** [polybar/polybar#1960]
## Is your feature request related to a problem? Please describe.
The speed of the installation is slow if `./build.sh --all-features` is used. I noticed that CPU usage was focusing on one core and that the build script has no way to specify `make -j`

## Why does polybar need this feature?
The speed of installing from the `build.sh` script will greatly improve both the development speed and installation process of polybar. 

## Describe the solution you'd like
`-j` is not used in the `build.sh` for anything, so `./build.sh -j` should be used to explicitly invoke `make -j`. 

## Describe alternatives you've considered
Another option is to have `make -j` as the default and use `-s` to force single core `make`

## Additional context
Most computers are multi core now.

**Comment by Lomadriel** [comment]
You can use the `MAKEFLAGS` environment variable to achieve that:
```
MAKEFLAGS=-j8 ./build.sh
```

**Comment by patrick96** [comment]
I think @Lomadriel's workaround work be fine. But if someone wants to tackle this, they're more than welcome. It should only require `bash` and (a little) `make` knowledge

**Comment by Nicholas-Baron** [comment]
Which option should be used: the `-j` option to ask for make jobs or `-s` to force single core?

**Comment by Lomadriel** [comment]
I think using the `-j` option is preferable to keep the coherence with `make`. An opinion @patrick96 ?

**Comment by Nicholas-Baron** [comment]
@patrick96 @Lomadriel I have a branch ready for review which simply adds `-j` and `--jobs` to build.sh
