### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 1m-N00b** [polybar/polybar#1969]
## Build Process
`yay -Syu`
aur/polybar                3.4.1-1  -> 3.4.1-3

## Build Log
[Error Log](https://pastebin.com/BK6HLdiE)

## Environment:
* Distro :Arch Linux x86_64(5.4.6-arch3-1)

**Comment by patrick96** [comment]
Make sure you are doing a clean build (delete any yay build caches for polybar) and also make sure that you have python installed and in your `PATH` (preferably system python from the `python` package).

I don't really know your setup so I can't help any more than that.
