### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 1m-N00b** [polybar/polybar#1973]
## Build Process
`yay -Syu`
aur/polybar  3.4.1-1 -> 3.4.1-3

## Build Log
[Build Log](https://pastebin.com/2XGpvhFZ)
## Environment:
* Distro (with Version):Arch Linux x86_64(5.4.6-arch3-1)

**Comment by patrick96** [comment]
Duplicate of #1969

**Comment by patrick96** [comment]
Please don't spam issues like this. At the very least use a single issue. Though in your case it looks like you need help installing polybar, in that case I'd rather you look at our [Support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) and ask at one of the links provided there.
