### ISSUE TITLE
Wrong reference

### ISSUE THREAD

**Issue by xgqt** [polybar/polybar#1980]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*

git clone --recursive https://github.com/polybar/polybar

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:

3.4.0-55-g85721d3

*List exactly where you are building from and which version you are building.*

my home folder; git (commit 85721d3d109e29decc3fc1d4185ae63d5afa20d6)

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```
Cloning into 'polybar'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 14170 (delta 2), reused 7 (delta 0), pack-reused 14154
Receiving objects: 100% (14170/14170), 7.28 MiB | 6.62 MiB/s, done.
Resolving deltas: 100% (10514/10514), done.
Submodule 'lib/i3ipcpp' (https://github.com/polybar/i3ipcpp) registered for path 'lib/i3ipcpp'
Submodule 'lib/xpp' (https://github.com/polybar/xpp) registered for path 'lib/xpp'
Cloning into '/home/us/polybar/lib/i3ipcpp'...
remote: Enumerating objects: 762, done.        
remote: Total 762 (delta 0), reused 0 (delta 0), pack-reused 762        
Receiving objects: 100% (762/762), 299.42 KiB | 985.00 KiB/s, done.
Resolving deltas: 100% (243/243), done.
Cloning into '/home/us/polybar/lib/xpp'...
remote: Enumerating objects: 53, done.        
remote: Counting objects: 100% (53/53), done.        
remote: Compressing objects: 100% (35/35), done.        
remote: Total 2660 (delta 28), reused 22 (delta 17), pack-reused 2607        
Receiving objects: 100% (2660/2660), 494.69 KiB | 1.26 MiB/s, done.
Resolving deltas: 100% (1843/1843), done.
Submodule path 'lib/i3ipcpp': checked out '21ce9060ac7c502225fdbd2f200b1cbdd8eca08d'
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/polybar/xpp
 * branch            f70dd8bb50944ab64ab902d9d8ab555599249dc1 -> FETCH_HEAD
Submodule path 'lib/xpp': checked out 'f70dd8bb50944ab64ab902d9d8ab555599249dc1'
```

## Environment:
* Distro (with Version):

Gentoo (Head commit of repository gentoo: f73c1995cbc9ba20295b2d6c47107620ff81ae85)

## Additional context
*Add any other context that you think is necessary about the problem here.*

Technically this won't stop anybody from building polybar form git... but it fails while used in an ebuild on Gentoo (it fails to fetch the referenced repo)

**Comment by Lomadriel** [comment]
I am surely missing something but I can't spot the error you are reporting.

**Comment by xgqt** [comment]
> I am surely missing something but I can't spot the error you are reporting.
```
From https://github.com/polybar/xpp
 * branch            f70dd8bb50944ab64ab902d9d8ab555599249dc1 -> FETCH_HEAD
Submodule path 'lib/xpp': checked out 'f70dd8bb50944ab64ab902d9d8ab555599249dc1'
```
f70dd8bb50944ab64ab902d9d8ab555599249dc1 doesn't exist

**Comment by patrick96** [comment]
Strange that git was even able to check it out then. What is inside the lib/xpp folder when this happens?

**Comment by Lomadriel** [comment]
That's strange because, this hash doesn't exist in my repo but it exists on [github](https://github.com/polybar/xpp/tree/f70dd8bb50944ab64ab902d9d8ab555599249dc1).

On my repo, the hash is `8c019e6d7fefd2468791bc1cbf90d68ff7c1ba33`

**Comment by Lomadriel** [comment]
Okay, I just found the problem, this hash is indeed the wrong one, this hash refers to the hash of @jeremyong but not to the hash of our repo. We should update that.

**Comment by xgqt** [comment]
i went to lib/xpp and did git checkout master - it reverts to "8c019e6d7fefd2468791bc1cbf90d68ff7c1ba33 (HEAD -> master, origin/master, origin/HEAD)"
before that it says "f70dd8bb50944ab64ab902d9d8ab555599249dc1 (HEAD)"

**Comment by xgqt** [comment]
> Okay, I just found the problem, this hash is indeed the wrong one, this hash refers to the hash of @jeremyong but not to the hash of our repo. We should update that.

Thanks for cooperation

**Comment by jeremyong** [comment]
Yup that was my fault (should have paid more attention to the `.gitmodule` file). Thanks for addressing it and sorry :(

**Comment by Lomadriel** [comment]
No problems ;)
