### ISSUE TITLE
network module does not work with tun device

### ISSUE THREAD

**Issue by g3n35i5** [polybar/polybar#1986]
## Describe the issue
I use the network module for my ethernet, my wifi and my vpn. Both ethernet and wifi work fine. However, the tun interface is not displayed and there is no information about errors in the log. The configurations (below) are identical except for the name of the interface.

**Expected behavior:**

The network module should work with my tun device.

**Actual behavior:**

It doesn't appear in my bar.

**Was it working before?**

I just started using polybar.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[colors]
background = #222
background-alt = #444
foreground = #dfdfdf
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/main]
width = 100%
height = 27
radius = 6.0
fixed-center = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 4
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = Roboto Mono:pixelsize=12;1

modules-left =
modules-center = wlan eth vpn
modules-right =

cursor-click = pointer
cursor-scroll = ns-resize

[module/vpn]
type = internal/network
interface = tun0
interval = 3.0

label-connected = %local_ip%
label-disconnected = N/A
format-connected-prefix = "vpn: "
format-disconnected-prefix = "vpn: "

[module/wlan]
type = internal/network
interface = wlp4s0
interval = 3.0

label-connected = %local_ip%
label-disconnected = N/A
format-connected-prefix = "wlan: "
format-disconnected-prefix = "wlan: "


[module/eth]
type = internal/network
interface = enp0s31f6
interval = 3.0

label-connected = %local_ip%
label-disconnected = N/A
format-connected-prefix = "eth: "
format-disconnected-prefix = "eth: "


[settings]
screenchange-reload = true

[global/wm]
margin-top = 5
margin-bottom = 5

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
Output of `ip route`:
```
$ ip route
10.56.0.0/16 dev tun0 proto kernel scope link src 10.56.0.3 
10.172.64.0/18 dev wlp4s0 proto kernel scope link src 10.172.115.163 metric 600 
172.24.0.0/16 dev enp0s31f6 proto kernel scope link src 172.24.179.221 metric 100 
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
* Parsing config file: /home/g3n35i5/.config/polybar/config.ini
* Loaded monitor eDP-1 (1920x1080+1433+1080)
* Bar geometry: 1920x35+1433+1080; Borders: 4,4,4,4
* Starting application
* Starting module/eth
* Starting module/vpn
* Starting module/wlan
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=5)
* Configured DPI = 96x96
* Loaded font "Roboto Mono:pixelsize=12" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Bar window: 0x0800002
* Disabling tray manager (reason: missing `tray-position`)
* module/wlan: Rebuilding cache
* module/eth: Rebuilding cache
* module/vpn: Rebuilding cache
* Redrawing bar window
* module/wlan: Rebuilding cache
* module/eth: Rebuilding cache
* module/vpn: Rebuilding cache
* module/wlan: Rebuilding cache
* module/eth: Rebuilding cache
* module/vpn: Rebuilding cache
```

## Screenshots
![vpn_not_appearing](https://user-images.githubusercontent.com/17593457/71999548-ea192180-3241-11ea-831c-dcfb72e57264.png)

## Environment:
* WM: i3wm
* Distro: ArchLinux (Linux 5.4.8-arch1-1 x86_64)
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
Maybe this is a similar issue, but at least the label is displayed there: #1877

**Comment by patrick96** [comment]
This is really strange. I went through the code to see what could be going on and the only thing I could think of is that `label-connected = %local_ip%` actually evaluates to an empty string because we fail to get the local ip for some reason. In that case the entire module is not displayed because the format prefix is only applied if the rest of the module is not empty. Could you try to add some text to `label-connected`. For example `label-connected = IP: %local_ip%`

**Comment by g3n35i5** [comment]
@patrick96 I'm also in the process of examining the code at the appropriate place. Your assumption is correct, the IP of the tun interface cannot be determined for some reason, with your workaround at least the module is shown in the bar.
Furthermore I found out that the tun interface is interpreted as a wired network, but the query method is not executed, but it doesn't fail either. However, it is also possible that I miss something...

**Comment by patrick96** [comment]
The issue is that for tun devices the entire query method is skipped and it just returns true. Because of that the IP is never queried. I'm working on a fix.

**Comment by g3n35i5** [comment]
Ah, that explains a lot. Can you tell me where this skipping is defined?

**Comment by patrick96** [comment]
In the `wired_network::query` method.

**Comment by g3n35i5** [comment]
Thanks!

**Comment by patrick96** [comment]
Could you please test #1990

**Comment by g3n35i5** [comment]
Works perfectly, thank you very much!

**Comment by patrick96** [comment]
Great!
