### ISSUE TITLE
Script module click-left execution differs from command execution via sh -c

### ISSUE THREAD

**Issue by ximpr** [polybar/polybar#1987]
## Describe the issue
The Wiki entry [for script modules](https://github.com/polybar/polybar/wiki/Module:-script) states that ```click-left will be executed using "/usr/bin/env sh -c [command]"```.

In my custom script I use a specific command (that kills the application `redshift` when it runs or starts it if it is not running) that works without problems when running it from the command line:
```$ /usr/bin/env sh -c "pgrep redshift > /dev/null && pkill redshift || redshift 2>&1 /dev/null &"```
alternatingly kills and starts redshift on each execution.

Using the same command in a custom polybar script module with `click-left` however does _not_ work the same, it does kill `redshift` when left-clicking but it does not start it again on the next left-click.

**Expected behavior:**
`redshift` should be started on left-clicking the custom module in case it does not run, and be killed in case it does run.

**Actual behavior:**
When `redshift` is running, a left-click correctly kills the process (indicated via label "off"). However when `redshift` is not running, a left-click does not start it again (which would be indicated both by a screen color change and by a label display like "6500K"), the label stays "off". Note that the label does change when I manually start `redshift` again.

**Was it working before?**
I did not use polybar before, so I am not sure whether this was at any time working before.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/example]
modules-center = redshift-temp
[module/redshift-temp]
type = custom/script
exec = pgrep redshift > /dev/null && redshift -p 2> /dev/null | grep temp | cut -d ":" -f2 || echo " off"
interval = 3
click-left = pgrep redshift > /dev/null && pkill redshift || redshift 2>&1 /dev/null &
```
It may help to install the ~100kb package [redshift](https://packages.debian.org/buster/redshift) (adjusts the color of your screen), e.g. with `sudo apt install redshift`, to understand the issue.

## Polybar Log
No output appears (besides the expected "Termination signal received, shutting down..." when I manually close polybar).

## Environment:
* WM: i3 with i3-gaps
* Distro: Debian buster
* Output of `polybar -vvv`:

```
polybar 3.4.1-dev

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/g++
Compiler flags: -g -O2 -fdebug-prefix-map=/tmp/tmp.ww3wZM3ZKt/polybar=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-z,relro 
```

**Comment by patrick96** [comment]
The click command is not executed at all because it produces output (see [this](https://github.com/polybar/polybar/wiki/Known-Issues#click-commands-are-not-executed) known issue).

This was probably unintentional on your part because you explicitly redirect the output, however you are missing a redirect before the last `/dev/null`:

```
pgrep redshift > /dev/null && pkill redshift || redshift 2>&1 > /dev/null &
                                                              ^
```

**Comment by ximpr** [comment]
Thank you for your answer, that was indeed unintentional. I assumed that because running the command worked there was no problem with it. Besides missing the `>`, I also redirected `stderr` to `stdout` too early. Like this it works as expected:
```dosini
...
exec = pgrep redshift > /dev/null && pkill redshift || redshift > /dev/null 2>&1 &
...
```
