### ISSUE TITLE
Add disabling workspace wrap

### ISSUE THREAD

**Issue by tsujp** [polybar/polybar#1988]
I am unsure to which project the exact scope of this lies, so I am linking the issue I have made in i3's repo itself: https://github.com/i3/i3/issues/3900

**Comment by patrick96** [comment]
This is purely about i3. The i3 module in polybar already has the `wrapping-scroll` key with which you can control this.

**Comment by tsujp** [comment]
`wrapping-scroll` is for the mouse only, not for key commands.

**Comment by patrick96** [comment]
Polybar has nothing to do with your keybindings. That's all on the i3 side (or whatever mechanism you use for keybindings)

**Comment by tsujp** [comment]
Whoops, correct indeed. More coffee for me.
