### ISSUE TITLE
error: Duplicate key name "; label-focused-underline" defined on line 183

### ISSUE THREAD

**Issue by yadex** [polybar/polybar#1989]
## Describe the issue

l got this error message when i launched my polybar, but i 've commented out this line.

**Expected behavior:**

**Actual behavior:**

*What actually happens*

**Was it working before?**

Yes, it works well in my another Arch Linux

* Did you also experience this bug in an earlier version of polybar?

 No

* If no, what was the last version where this worked correctly?

3.4.0

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosnis
[module/i3]
  type = internal/i3
  format = <label-state> <label-mode>
  index-sort = true
  wrapping-scroll = false
  strip-wsnumbers = true
  pin-workspaces = true
  
  label-mode = %mode%
  label-separator = |
  label-mode-padding = 3
  label-mode-background = #e60053
  
  label-focused = %name%
  label-focused-background = ${colors.background-alt}
  ; label-focused-underline =  #f3f99d
  ; label-focused-underline =  #7a7ab8
  label-focused-underline =  #baacff
  label-focused-padding = 3
  
  label-unfocused = %name%
  label-unfocused-padding = 3
  
  label-urgent = %name%!
  label-urgent-background = ${colors.alert}
  label-urgent-padding = 3
  
  label-visible = %name%
  lable-visible-padding = 3
  label-visible-background = ${self.label-focused-background}
  label-visible-underline = ${self.label-focused-underline}
  label-visible-padding = ${self.label-focused-padding}
  

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3-gaps
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by yadex** [comment]
just delete the duplicate lines

**Comment by patrick96** [comment]
The reason this happened is because comment lines can't start with a whitespace. This is no longer the case i the development version and will be part of 3.5.0.
