### ISSUE TITLE
Multiple bars appear on the same monitor

### ISSUE THREAD

**Issue by Kruhlmann** [polybar/polybar#1992]
## Describe the issue

Multiple bars appear on the same monitor, when they are passed different outputs.

**Expected behavior:**
Expected The bars to show up on different monitors.

**Actual behavior:**
Every bar shows up underneath one another on a single monitor.

**Was it working before?**
This works on a different PC with a different monitor setup.

## To Reproduce
```dosini
[bar/tmp]
width = 100%
height = 27
radius = 0
fixed-center = false

background = #000
foreground = #fff 
modules-left = date


[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = ${colors.foreground}

label = %date% %time%
```

launch_polybar
```bash
#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar tmp &
done
```

## Screenshots
![image](https://user-images.githubusercontent.com/3380818/72826191-ab8b5a00-3c78-11ea-9e5e-c66d76231f83.png)

## Environment:
* WM: i3
* Distro: Arch
* Output of `polybar -vvv`:

```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context

The issue persists even if I run the bar with the monitor outputs hardcoded.

My outputs are **DP-1.1** and **DP-1.2**

**Comment by patrick96** [comment]
The `MONITOR` variable doesn't do anything in polybar. Polybar uses the `monitor` key in your config to place itself and that key is not set in your config, so it will always place itself on the primary monitor. Use something like `monitor = ${MONITOR}`

**Comment by Kruhlmann** [comment]
There was a trailing comma in my bar configuration, removing it fixed the issue.

`monitor = ${env:MONITOR:}`
