### ISSUE TITLE
[internal/backlight] Scrolling to change brightness doesn't work 

### ISSUE THREAD

**Issue by tadly** [polybar/polybar#1996]
## Describe the issue
Changing the backlight  for `internal/backlight` does not work when scrolling.

**Expected behavior:**
Brightness should change.

**Actual behavior:**
Brightness does not change. Instead I see the following in the log:
Scrolling down:
```
...
* No matching input area found (btn=5)
* No matching input area found (btn=5)
...
```
Scrolling up:
```
...
* No matching input area found (btn=4)
* No matching input area found (btn=4)
...
```

**Was it working before?**
First time using this module as I'm migrating from `xf86-video-intel` to `modesetting` and xbacklight does not support `modesetting`

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/backlight]
type = internal/backlight
card = intel_backlight
enable-scroll = true
```

## Polybar Log
https://pastebin.com/9cZzp84q

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3-gaps
* Distro: archlinux
* Output of `polybar -vvv`:
```
polybar view-aur/polybar-1-g79e2f62

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
Yes, I did add my user to the `video` group and changing the brightness from cli works

**Comment by saber-nyan** [comment]
Also does not work for me.
Scrooling up/down logs:
```
- bar: Ignoring update (unchanged)
- bar: Received button press: 5 at pos(1347, 2)
- Found matching fallback handler
- bar: Received button press: 6 at pos(1347, 2)
* No matching input area found (btn=6)
- bar: Received button press: 6 at pos(1347, 2)
* No matching input area found (btn=6)
- bar: Received button press: 6 at pos(1347, 2)
* No matching input area found (btn=6)
- bar: Received button press: 6 at pos(1347, 2)
* No matching input area found (btn=6)
- bar: Received button press: 5 at pos(1347, 2)
- Found matching fallback handler
- bar: Received button press: 6 at pos(1347, 2)
```

Config:
```
[module/backlight]
type = internal/backlight
card = intel_backlight

enable-scroll = true
```
Polybar version: 
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=native -O2 -pipe -fno-stack-protector -fomit-frame-pointer -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
Oh, I forgot to add the note that this feature is unreleased in the wiki. So polybar version 3.4.2 doesn't yet have that feature, it will only arrive with 3.5.0.


@tadly How exactly did you build polybar? I have no idea how you got the version string `view-aur/polybar-1-g79e2f62`. What version of polybar is that?

**Comment by tadly** [comment]
@patrick96 That's good to know. Is there an ETA for 3.5.0?

On archlinux it's only available through the AUR and [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=polybar) is how it's built.

**Comment by patrick96** [comment]
@tadly And you just ran makepkg? Because there should be no way to get this version string, especially if you use release archive.

>  Is there an ETA for 3.5.0?

Not really.
The [milestone](https://github.com/polybar/polybar/milestone/7) for 3.5.0 still has quite a lot of open issues, but we may need to push back a few of them.

**Comment by DrSensor** [comment]
@patrick96, does inheriting enable-scroll from `module/xbacklight` work?
something like
```ini
[module/xbacklight]
type = internal/xbacklight
enable-scroll = true
.
.

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight
```

**Comment by patrick96** [comment]
@DrSensor It should, yes.
