### ISSUE TITLE
Having Dynamic Interfaces, Sinks, Cards etc.

### ISSUE THREAD

**Issue by Arszilla** [polybar/polybar#1997]
## Build Process
I build the via a chroot and a binary hook that installs all the dependencies (optional included). Then the bari launched via a script that calls the config after terminating the current bar. The script is as follows.

```
#!/bin/sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar
polybar bar &
```

## Polybar Information
```
$ polybar --version
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

## Environment:
Kali Linux i3-gaps Rolling

## Additional Context
I am developing a Kali Linux i3-gaps ISO that will (hopefully) be used in live mode/installed on various machines. With that being said, I am testing the bar currently on my Kali i3-gaps where I built the current settings according to my machine. Sadly this raises some issues where some parts need to be dynamic. Following modules need dynamic parts and I cannot figure out how to:

```
[module/wired-network]
type = internal/network
interface = eth0
interval = 3.0

label-connected = LAN: %essid%
label-disconnected = LAN: Disconnected

[module/wireless-network]
type = internal/network
interface = wlan0
interval = 3.0

label-connected = Wifi: %essid%
label-disconnected = Wifi: Disconnected

[module/volume]
type = internal/pulseaudio

sink = alsa_output.pci-0000_00_1b.0.analog-stereo
use-ui-max = false

format-volume = Volume: <label-volume>

label-muted = Volume: Muted

[module/backlight]
type = internal/xbacklight
card = intel_backlight
format = Brightness: <label>

label = %percentage%%

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
poll-interval = 5

format-discharging = Battery: <label-discharging>
format-charging = Charging: <label-charging>

label-discharging = %percentage%%
label-charging = %percentage%%
label-full = %percentage%%
```

As this bar is going to be installed/used in various machines, `wired-network`/`wireless-network`'s `interface`, `volume`'s `sink` and `backlight`'s `card` might differ from machine to machine. I cannot find a way to make polybar detect said parts automatically and name them in the system. 

An example of this would be how `wlan0` from my laptop is `wlp39s0` on my desktop. Or how `eth0` from my laptop is `enp35s0`on my desktop. 

Is there a way to make polybar detect these automatically to a certain extent? I've seen #339 but sadly it's no use for me as I am displying both LAN and WiFi on the bar.

Do note that the ISO builds polybar flawlessly and it works with no issues. If you are curious about the ISO, take a look [here](https://github.com/Arszilla/kali-i3-gaps).

**Comment by patrick96** [comment]
Polybar doesn't really automatically detect a default interface or adaptor (except in the pulseaudio module). I have some ideas in the back of my head to add more sane defaults, but nothing concrete and even there we would probably take the approach from #339.

I am also running my config on multiple machines (only 2 though). And I have extended my launch script to gather this kind of information. For example for the network interfaces I have the following bash code:

```bash
while read -r iface
do
    case $iface in
        w*)
            if [ -z "$IFACE_WIFI" ]
            then
                export IFACE_WIFI="$iface"
            fi
            ;;
        e*)
            if [ -z "$IFACE_ETH" ]
            then
                export IFACE_ETH="$iface"
            fi
            ;;
    esac
done <<< "$(ip link | grep '^[0-9]\+:' | awk -F ': ' '{print $2}' | \grep -v "^lo$")"
```

And then later I have:

```bash
if [ -n "$IFACE_ETH" ]; then
    BAR_MODULES_TOP_RIGHT="$BAR_MODULES_TOP_RIGHT wired"
fi

if [ -n "$IFACE_WIFI" ]; then
    BAR_MODULES_TOP_RIGHT="$BAR_MODULES_TOP_RIGHT wireless"
fi
```

The polybar config file itself uses lots of `${env:...}` variables to access those environment variables.

For configs that are supposed to run on many different machines it makes sense to have a launch script anyway, for example for only adding a backlight module if the machine has a backlight and so on.

**Comment by Arszilla** [comment]
> For configs that are supposed to run on many different machines it makes sense to have a launch script anyway, for example for only adding a backlight module if the machine has a backlight and so on.

What do you mean with a launch script? Like the first bash script you've shared? I am unsure how can I call the bash script within polybar, but I presume polybar has such a capability so I can get the module/interface names; which then could be applied to backlight and battery as well; like you've stated. Although I am curious if backlight and battery needs some sort of fetching like I need for networking; since I am mostly testing this script/polybar on Kali on various Kali VMs on my desktop. Any information regarding that? Perhaps it's automated like audio/pulseaudio?

**Comment by patrick96** [comment]
No, it's the other way around. The launch script runs polybar and inside the polybar config you can reference the environment variables you exported in the launch script.

For backlight and battery you also need to fetch the adapter names by yourself, polybar doesn't do that.
