### ISSUE TITLE
GitHub API deprecating authentication via URL query parameters

### ISSUE THREAD

**Issue by jonhoo** [polybar/polybar#2002]
The [`internal/github` module](https://github.com/polybar/polybar/wiki/Module:-github) currently authenticates its requests to the GitHub API using a query parameter. That authentication method is [being deprecated](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters), and will stop working in not too long. Instead, the personal access token needs to be presented using [HTTP Authentication](https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens) (which is luckily also supported by curl).

**Comment by jonhoo** [comment]
Specifically, this call
https://github.com/polybar/polybar/blob/8d07f2aa2307f51027ac60fbee81d82aecd6e4cd/src/modules/github.cpp#L49
which currently invokes this method
https://github.com/polybar/polybar/blob/51184c7eadc688d3193b7783ff04de3db3dc25a7/src/utils/http.cpp#L26
needs to be augmented to pass in the `username` (which may need to be a new config parameter for the module) and `token`. If those are passed, it then needs to use [`curl_easy_setopt`](https://curl.haxx.se/libcurl/c/curl_easy_setopt.html) to set [`CURLOPT_USERNAME`](https://curl.haxx.se/libcurl/c/CURLOPT_USERNAME.html) and [`CURLOPT_PASSWORD`](https://curl.haxx.se/libcurl/c/CURLOPT_PASSWORD.html) for the request.

**Comment by x70b1** [comment]
I fixed that for `polybar-scripts`. Maybe this will help as an example: https://github.com/polybar/polybar-scripts/commit/7282f7069274a66a705d4a6a82f953f15726245e

**Comment by jonhoo** [comment]
@x70b1 is it not necessary to include a username in the header (I see you left it blank)?

**Comment by x70b1** [comment]
> @x70b1 is it not necessary to include a username in the header (I see you left it blank)?

Where did you see it? Because thats not true :wink: 

`curl` use the HTTP basic auth, thats encoded in the HTTP header.

**Comment by jonhoo** [comment]
Well, the [GitHub API authentication section](https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens) says that a `username` should be included. But the code you linked just sets `USER=""`?

**Comment by x70b1** [comment]
Yes, but in the HTTP header thats are just placeholders. And `USER` is the `curl` term for this. 

Look at the HTTP header with `tcpdump -vvv`, run `echo "user = SUPERUSER:SUPERSECRETTOKEN" | curl -K- 1.1.1.1` and you will get something like:
```
	GET / HTTP/1.1
	Host: 1.1.1.1
	Authorization: Basic U1VQRVJVU0VSOlNVUEVSU0VDUkVUVE9LRU4=
	User-Agent: curl/7.68.0
	Accept: */*	
```

The auth string is base64, this mean we can decode it. The result is:
`SUPERUSER:SUPERSECRETTOKEN`

There is no magic. The only requirement is probably that both parts are separated by a colon. But how you name the placeholders doesn't matter.

**Comment by nekiter** [comment]
I'll work on that issue, it looks well describe, any other information that u guys think that is important?

**Comment by Nate-Wilkins** [comment]
For anyone looking for the script it can be found here:
https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/notification-github

The builtin one still uses the `access_token` query param.
