### ISSUE TITLE
Set image as background

### ISSUE THREAD

**Issue by malyutinegor** [polybar/polybar#2007]
Hello! Can I set image as background of the bar?
I think it would be very useful. For example, we can have blurred pseude-transparent background with this.

**Comment by patrick96** [comment]
No, you can't.

> For example, we can have blurred pseude-transparent background with this.

I'm not sure how an image as background can achieve this. If you want a blurred transparent background, you should use a compositor that does this for you.

**Comment by malyutinegor** [comment]
> I'm not sure how an image as background can achieve this.

Just prepare blurred backround image and set it as background of the bar

> If you want a blurred transparent background, you should use a compositor that does this for you.

But why then polybar has pseudo-transparent option? What if I just don't want to use compositor?

**Comment by patrick96** [comment]
> But why then polybar has pseudo-transparent option?

For people that want transparency without using a compositor. But you can't have everything without a compositor. For fancy things like blurring, shadows and fading effects you generally need one.

> What if I just don't want to use compositor?

You could blur the background image in the region where polybar is and have a pseudo-transparent polybar.

**Comment by malyutinegor** [comment]
> For fancy things like blurring, shadows and fading effects you generally need one.

I know :D

> You could blur the background image in the region where polybar is and have a pseudo-transparent polybar.

Ok, thanks. But actually I was using video wallpaper set with xwinwrap. So I will try to blur this part video region

**Comment by patrick96** [comment]
Does polybar's pseudo-transparency work with the video wallpaper?

**Comment by malyutinegor** [comment]
> Does polybar's pseudo-transparency work with the video wallpaper?

Nope

**Comment by patrick96** [comment]
Yeah, I thought so.
