### ISSUE TITLE
CMake Error /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake

### ISSUE THREAD

**Issue by huseynovv** [polybar/polybar#2011]
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  cmake/common/utils.cmake:108 (find_package)
  cmake/02-opts.cmake:10 (checklib)
  CMakeLists.txt:52 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/Desktop/polybar/build/CMakeFiles/CMakeOutput.log".
** Failed to generate build... read output to get a hint of what went wrong

**Comment by huseynovv** [comment]
fixed: https://gist.github.com/kuznero/f4e983c708cd2bdcadc97be695baacf8

**Comment by patrick96** [comment]
All that info is also on the [wiki](https://github.com/polybar/polybar/wiki/Compiling) btw ;)
