### ISSUE TITLE
tor-icons font loaded, but symbols not displayed correctly

### ISSUE THREAD

**Issue by 0rb677** [polybar/polybar#2017]
https://www.torproject.org/static/fonts/TorIcons/tor-icons.ttf

![bug3](https://user-images.githubusercontent.com/60626673/75114195-245d4780-5665-11ea-8ed2-30005009c270.png)

polybar -l info , wrong path, why?
```
* Loaded font ""tor\-icons":style=Regular:size=12" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/dejavu/DejaVuSans.ttf)
```
```
gucharmap -> U+F112 <Private Use>
```

polybar when font loaded
![icons-p](https://user-images.githubusercontent.com/60626673/75114229-874ede80-5665-11ea-9df3-145f8c43a683.png)

**Comment by patrick96** [comment]
You seem to use the wrong font name, or the font isn't installed correctly, please follow step 1 of our [font debugging guide](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues).
