### ISSUE TITLE
Latest git still listed as 3.4.0

### ISSUE THREAD

**Issue by vaskark** [polybar/polybar#2018]
When I run `polybar -v` it gives:

`polybar 3.4.0`

Can we have this updated to reflect that git builds are ahead of stable builds?
Not much of an issue as it doesn't affect anything. Just a thought.
Keep up the great work!

**Comment by patrick96** [comment]
How are you building polybar? The version string should look like this: `polybar 3.4.0-52-g34e742e0`. This is of course still no perfect, but it at least tells you which commit you have built.

But I agree, it should use the latest version number, this is not possible right now, but will be once we finally get going on #1780

**Comment by patrick96** [comment]
How are you building polybar? The version string should look like this: `polybar 3.4.0-52-g34e742e0`. This is of course still no perfect, but it at least tells you which commit you have built.

But I agree, it should use the latest version number, this is not possible right now, but will be once we finally get going on #1780

**Comment by vaskark** [comment]
@patrick96 Thanks for responding!
I'm just using the build.sh script (on Ubuntu 19.10). And, yeah, my version does look like it's supposed to in your example. It was just a small thing that I wondered about :)

**Comment by patrick96** [comment]
Ah, so your version string isn't `polybar 3.4.0` but also has some more information after it?

**Comment by vaskark** [comment]
`polybar -v` produces:

```
polybar 3.4.0
Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

**Comment by patrick96** [comment]
How did you download the polybar sources? This kind of version string should only appear if you are literally building version 3.4.0.

**Comment by vaskark** [comment]
From here. I'm building from git.

`git clone https://github.com/polybar/polybar`

**Comment by vaskark** [comment]
K, I checked the wiki and tried building again:

`git clone --recursive  https://github.com/polybar/polybar
`

Now I'm getting:

`polybar 3.4.0-77-gf02fb67
`

**Comment by patrick96** [comment]
Strange. There must have been something else going on. Either you were actually building 3.4.0 or maybe you deleted the `.git` folder.
