### ISSUE TITLE
Xworkspace don't show occupied label with xmonad.

### ISSUE THREAD

**Issue by Sumi-Sumi** [polybar/polybar#2020]
## Describe the issue
**A clear and concise description of what the bug is.**
I use polybar with xmonad.
I want to show workspace using xworkspace module.
This module show current workspace and empty workspace but occupied workspace show as empty workspace.

**Expected behavior:**
occupied workspace label will become defined occupied-foreground-color.

**Actual behavior:**
Occupied workspace label became defined empty-foreground-color.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?

I use polybar and xmonad for the first time.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
* config
```dosini
[module/ewmh]
type = internal/xworkspaces

pin-workspaces = false
enable-click = true
enable-scroll = false

format = <label-monitor> <label-state>
label-monitor = %name%
label-monitor-underline = ${colors.cyan}

label-active = %name%
label-active-foreground = ${colors.green}
label-active-underline =  ${colors.cyan}
label-active-padding = 1

label-occupied = %name%
label-occupied-foreground = ${colors.blue}
label-occupied-underline = ${colors.cyan}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-foreground = ${colors.red}
label-urgent-underline = ${colors.cyan}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.fg}
label-empty-underline = ${colors.cyan}
label-empty-padding = 1
```
* xmonad.hs
```haskell
import  XMonad 
import  XMonad.Hooks.DynamicLog 
import XMonad.Hooks.EwmhDesktops
import XMonad.Hooks.ManageDocks
import  XMonad.Util.Run
import XMonad.Util.Run (spawnPipe) 
import  System.IO

main  =  do 
    xmonad $ ewmh defaultConfig
        {
          logHook = ewmhDesktopsLogHook
        , terminal = "alacritty"
        , startupHook = myStartupHook
        , manageHook = manageDocks
        }

myStartupHook = do
  spawn "bash .config/polybar/launch.sh"
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
Bars launched...

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
* Workspace 1 (ws icons is "code". This ws exist window)
<img width="240" alt="2020-02-25_13-18" src="https://user-images.githubusercontent.com/24451978/75214620-83d86600-57d1-11ea-94fa-9cb87752e1c5.png">

* Workspace 2 (ws icons is "firefox". workspace 1 occupied but label color is empty color.)
<img width="340" alt="2020-02-25_13-19" src="https://user-images.githubusercontent.com/24451978/75214695-c26e2080-57d1-11ea-8e6c-fc2e76670008.png">

## Environment:
* WM: xmonad
* Distro: arch linux
* Output of `polybar -vvv`: polybar -3.4.2

## Additional context
**Add any other context that you think is necessary about the problem here.**
Screenshot different minimal code but I checked same problem with it.
There are no errors in the log, so it appears to be running properly.
I read #882 and believe that the occupied label has already been added.
Am i right?

**Comment by kronn** [comment]
I vaguely remember that I had to use a recent version of xmonad for the ewmh-integration to work. Older versions would only show visible workspaces as occupied to please some gnome-shell integration. I think I ended up backporting the change manually, so that xmonad emits the right events.

Which version of xmonad and xmonad-contrib do you use?

**Comment by Sumi-Sumi** [comment]
Sorry, I forgot wiriting info of api version.
I use
* Xmonad: 0.15
* Xmonad-contrib: 0.16
Maybe, there are current release.

**Comment by patrick96** [comment]
Hmm, the occupied label is not supported in 3.4.2, it will be in 3.5.0

**Comment by kronn** [comment]
Thanks, @patrick96.

I was trying to debug this, but couldn't because I compiled from source (git master). It works there. I tested the xmonad-code from a current xmonad-contrib. So, with 3.5.0 the integration works, @Sumi-Sumi.

**Comment by Sumi-Sumi** [comment]
Hi.
Thank you your great work !
I'll check it.

**Comment by patrick96** [comment]
@kronn Yeah, I always thought this was already in 3.4 but a bunch of people had this issue recently so I went back and checked.
