### ISSUE TITLE
Unable to set workspace icons in Fluxbox after 3.4.2 upgrade

### ISSUE THREAD

**Issue by vaygr** [polybar/polybar#2024]
## Describe the issue
*A clear and concise description of what the bug is.*

I have a pretty specific workspace naming, but I'm sure it has something to do with #1893. After bumping polybar to 3.4.2, my workspace icons for 3 workspaces now default to the default icon set.

**Expected behavior:**

![shot-2020-02-28_190522](https://user-images.githubusercontent.com/8810597/75599813-66b7c780-5a5d-11ea-8e54-e78a6519d126.png)

*A clear and concise description of what you expected to happen.*

Icons/labels are displayed correctly in polybar.

**Actual behavior:**

![shot-2020-02-28_190506](https://user-images.githubusercontent.com/8810597/75599823-7a632e00-5a5d-11ea-8f9f-40b8e6677937.png)

*What actually happens*

Icons/labels fallback to the default icon (also notice the "monitor" icon is different – I set it for better distinction).

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar? **No**
* If no, what was the last version where this worked correctly? **3.4.1**

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/ewmh]
type = internal/xworkspaces

pin-workspaces = true

enable-click = true

enable-scroll = false

icon-0 = ▰ ▱ ▱;    Base   ;
icon-1 =  ▱ ▰ ▱ ;     Lab    ;
icon-2 =  ▱ ▱ ▰ ;   Factory  ;
icon-default = 
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

None

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
* Loading config: /home/<user>/.config/polybar/config
* Loaded monitor eDP1 (1920x1080+0+0)
* Bar geometry: 1920x25+0+0; Borders: 0,0,0,0
* File reference "/home/<user>/.config/github/polybar.token" found
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
* Starting application
* Starting module/lock
* Starting module/smgl
* Starting module/ewmh
* module/lock: Invoking shell command: "..."
* Starting module/monitor
* Starting module/backup
* Starting module/notifyd
* Starting module/stopwatch
* Starting module/redshift
* Starting module/mpris
* Starting module/github
* Starting module/github-enterprise
* Starting module/asana
* Starting module/xbacklight
* Starting module/mic
* Starting module/headset
* Starting module/speaker
* Starting module/volume
* Starting module/pavolume
* Starting module/memory
* Starting module/cpu
* Starting module/temperature
* Starting module/wireless
* Starting module/vpn
* Starting module/bluetooth
* Starting module/xkeyboard
* Starting module/battery
* Starting module/powermenu
* module/github-enterprise: Invoking shell command: "..."
* module/bluetooth: Invoking shell command: "..."
* module/mic: Invoking shell command: "..."
* module/redshift: Invoking shell command: "..."
* module/notifyd: Invoking shell command: "..."
* module/backup: Invoking shell command: "..."
* module/monitor: Invoking shell command: "..."
* module/stopwatch: Invoking shell command: "..."
* module/mpris: Invoking shell command: "..."
* module/headset: Invoking shell command: "..."
* module/speaker: Invoking shell command: "..."
* module/vpn: Invoking shell command: "..."
* module/asana: Invoking shell command: "..."
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=15)
* Configured DPI = 96x96
* Loaded font "fixed:pixelsize=12:lang=ru" (name=Fixed, offset=1, file=/usr/share/fonts/X11/misc/6x12.pcf.gz)
* Loaded font "siji:pixelsize=10" (name=Siji, offset=2, file=/usr/share/fonts/X11/misc/siji.pcf.gz)
* Loaded font "unifont:size=12:antialias=false" (name=Unifont, offset=0, file=/usr/share/fonts/TTF/unifont.ttf)
* Loaded font "terminus:size=12:lang=ru" (name=Terminus, offset=1, file=/usr/share/fonts/X11/misc/ter-x12n.pcf.gz)
* Bar window: 0x3000003
* Disabling tray manager (reason: missing `tray-position`)
* module/lock: Rebuilding cache
* module/smgl: Rebuilding cache
* module/ewmh: Rebuilding cache
* module/monitor: Rebuilding cache
* module/backup: Rebuilding cache
* module/notifyd: Rebuilding cache
* module/stopwatch: Rebuilding cache
* module/redshift: Rebuilding cache
* module/mpris: Rebuilding cache
* module/github: Rebuilding cache
* module/github-enterprise: Rebuilding cache
* module/asana: Rebuilding cache
* module/xbacklight: Rebuilding cache
* module/mic: Rebuilding cache
* module/headset: Rebuilding cache
* module/speaker: Rebuilding cache
* module/volume: Rebuilding cache
* module/pavolume: Rebuilding cache
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* module/temperature: Rebuilding cache
* module/wireless: Rebuilding cache
* module/vpn: Rebuilding cache
* module/bluetooth: Rebuilding cache
* module/xkeyboard: Rebuilding cache
* module/battery: Rebuilding cache
* module/powermenu: Rebuilding cache
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: Fluxbox 1.3.7
* Distro: Source Mage GNU/Linux
* Output of `polybar -vvv`:

```text
polybar 3.4.2

Features: +alsa +curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (-monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/clang++
Compiler flags: -Wno-error=unused-command-line-argument -march=corei7-avx -fPIC -DPIC -pipe -Os -Wall -Wextra -Wpedantic -Wno-error=parentheses-equality -Wno-zero-length-array -stdlib=libc++ -Wno-error=unused-command-line-argument -march=corei7-avx -fPIC -DPIC -pipe -Os
Linker flags: -s -lc++ -lc++abi 
```

## Additional context
*Add any other context that you think is necessary about the problem here.*

`xprop -root _NET_DESKTOP_NAMES` output:

```text
_NET_DESKTOP_NAMES(UTF8_STRING) = "▰ ▱ ▱", " ▱ ▰ ▱ ", " ▱ ▱ ▰ "
```

**Comment by patrick96** [comment]
Please also post your polybar lot. If possible with info logging enabled

**Comment by vaygr** [comment]
Thanks @patrick96. Just did, and also fixed PR reference in the description.

**Comment by patrick96** [comment]
Hmm, my first guess would be the trailing semicolon is tripping up the module. Try this:

```dosini
icon-0 = ▰ ▱ ▱;    Base   ;
icon-1 =  ▱ ▰ ▱ ;     Lab    ;
icon-2 =  ▱ ▱ ▰ ;   Factory  ;
icon-default = 
```

The icon list is a map from workspace names to icons (or any other string), the second semicolon makes it look like it has three entries and that probably causes the module to ignore it.

**Comment by vaygr** [comment]
Yep, that was it. We probably want to add a note for that in [Module:-xworkspaces](https://github.com/polybar/polybar/wiki/Module:-xworkspaces), unless you think it should be fixed in the code.

But as a general rule, this probably applies to many cases where space characters are part of configuration and where quoting is recommended.

**Comment by patrick96** [comment]
So, I'm not totally sure that quoting was the issue, but it may have affected `icon-1` and `icon-2` because there the leading spaces were ignored. But once you remove the trailing semicolons you definitely need the quotes because otherwise the spaces at the end would be ignored. This is already in the documentation (`man 5 polybar`) and on the [Wiki](https://github.com/polybar/polybar/wiki/Configuration#syntax-and-domain-specific-language).

I have added a note on the wiki about the semicolon. I'm not sure what the best way to handle this is though, because if you have two semicolons, we don't know which one is the separator. But I think we should print a warning when this happens and we ignore the entry.
