### ISSUE TITLE
custom script %pid% points to /bin/sh -c instead of my script

### ISSUE THREAD

**Issue by yupswing** [polybar/polybar#2030]
## Describe the issue
A custom script launch its `exec` with `/bin/sh -c` but this way I can't send signals to my script because the `%pid%` points to `sh`

**Expected behavior:**
I expect polybar to give me the actual `%pid%` of the process I choose to launch instead of the `/bin/sh -c` pid.

**Actual behavior:**
It uses `/bin/sh -c [...]` to execute my command so I don't have the correct `%pid%` to communicate to my script as explained in the wiki https://github.com/polybar/polybar/wiki/Module:-script#Examples

**Was it working before?**
I've never used the custom script's `%pid%` before .

## To Reproduce
```dosini
[module/my-ip]
type = custom/script
exec = ruby ~/.config/polybar/scripts/my-ip.rb 30 "#F00" "#FFB52A"
tail = true
click-left = notify-send %pid%
```

## Screenshots
![2020-03-05T09:21:55_3360x1080](https://user-images.githubusercontent.com/10497150/75962087-68511780-5ec3-11ea-8c26-eb32b4981db8.png)
`%pid%` is 22787 (`/bin/sh`) but I would expect to launch `ruby` directly and have its `pid`

## Environment:
* WM: i3wm
* Distro: Ubuntu 19.10
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: 
```

**Comment by Lomadriel** [comment]
As documented:
> Note: %pid% actually refers to the sh process that executes the exec command. The shell will generally relay signals to the exec command. However if the command runs in the background it won't. In those cases you can use pgrep to find the oldest child belonging to %pid% and send the signal to that (child) pid:
`click-left = "kill -USR1 $(pgrep --oldest --parent %pid%)"`

You can use `pgrep --oldest --parent %pid%` to get your child.

For me this isn't an issue, or maybe you are asking us to change this behavior ?

**Comment by yupswing** [comment]
Thank you, I did not see the note on the oldest child, I'm sorry for that.
**Obviously it works now.**

Anyway I tried the same config on Ubuntu and Arch (same polybar version, `3.4.2`).
- On Ubuntu it executes `/bin sh -c COMMAND`
- On Ubuntu it executes `COMMAND` directly

That's ultimately why I opened this issue, because I was confused by the different behaviour.

**Comment by patrick96** [comment]
Polybar can't really give you the pid of the underlying command because polybar executes a command string through a shell, so for example `exec = CMD1 | CMD2 &; CMD3 &` is totally valid and it is not clear which command `%pid%` should refer to. I have made the experience that the shell forwards signals to the command it is currently running.

It is possible that `/bin/sh` on Ubuntu (which is the dash shell) doesn't do that. Can you try setting the environment variable `POLYBAR_SHELL` to `/bin/bash` on Ubuntu before you run polybar and see if sending signals to `%pid%`  works?

> Anyway I tried the same config on Ubuntu and Arch (same polybar version, 3.4.2).

That's not the experience I am having. I'm on arch and it also executes `/bin/sh -c COMMAND`. How did you determine what command is executed?

**Comment by yupswing** [comment]
Yep you got it right.
Using `POLYBAR_SHELL=/bin/bash` I see the exact same behaviour as on Arch.

I was checking with `ps ax | grep -i ruby`, now I understand.

Thanks a lot for the support and sorry I made you waste some time :)

**Comment by patrick96** [comment]
No worries, good to know that `dash` doesn't forward signals.
