### ISSUE TITLE
Refresh xbacklight module when xrandr config

### ISSUE THREAD

**Issue by TheBabu** [polybar/polybar#2034]
Whenever the `xranrdr` configuration changes, the xbacklight module should change accordingly. This way the user does not have to manually refresh the polybar to get the appropriate settings.
This could be enabled as a setting so users who would want to use less memory / CPU could do so.

**Comment by Lomadriel** [comment]
You can use the `screenchange-reload` option to reload the bar whenever your `xrandr` configuration change. See [this page](https://github.com/polybar/polybar/wiki/Configuration#application-settings) for more information.

**Comment by TheBabu** [comment]
Thank you, I didn't see that in the documentation. Worked like a charm, the only issue now is that #2035 still occurs when `screnchange-reload` is induced.
