### ISSUE TITLE
i3 module stops displaying

### ISSUE THREAD

**Issue by magnetophon** [polybar/polybar#2039]
## Describe the issue
Sometimes the i3 module just stops displaying, and the background is shown instead.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
I have only used this version.

## To Reproduce
I have no clear way of reproducing this, sorry.

## Polybar Log
Sorry, I don't have a log yet.

## Environment:
* WM: i3
* Distro: NixOS
* Output of `polybar -vvv`:
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /nix/store/35hd6lq59a4926n6c0rfra8dffkrp2pg-gcc-wrapper-9.2.0/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:

**Comment by patrick96** [comment]
Hi, thansk for reporting. Unfortunately without a log or a way to reproduce this, there is nothing we can do really. I am going to close this for now, but please update your post with a log as soon as you have one and ping us here so we can have another look.

The only thing I can think of that just spontaneously kills the i3 module is reloading i3, though polybar should be able to deal with that.
Does this happen often or at regular intervals? Do you remember doing anything when it happened?

**Comment by magnetophon** [comment]
It happens a few times per month, so not a lot.
 I can't think of anything I do that triggers it, definitely not restarting i3; that's what I do to cure the issue...

**Comment by patrick96** [comment]
Hmm, that's unfortunate. Without the log, there really is now way for is to debug this. Please start redirecting polybar's output to a logfile and the next time it happens post the log here.

**Comment by magnetophon** [comment]
I have the output logged. I'll report back when it happens again.

**Comment by magnetophon** [comment]
I figured it out: it ws happening when I update my distro / my X11.
So not a bug in polybar.

**Comment by patrick96** [comment]
Ok good to know :)
