### ISSUE TITLE
Polybar does not launch with jsoncpp 1.9.2 

### ISSUE THREAD

**Issue by Summerer** [polybar/polybar#2050]
## Describe the issue
After updating to the latest version of jsoncpp on ArchLinux polybar will not start anymore.
The following output is given:
```
polybar example
polybar: error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: No such file or directory
```
Reverting jsoncpp to 1.9.1 is a workaround.
**Expected behavior:**
Polybar should start normally

**Actual behavior:**
Polybar does not start

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
Only tested on polybar 3.4.2 from the AUR.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
example config should be fine
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
update jsoncpp to 1.9.2
## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
polybar: error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: No such file or directory
```

## Environment:
* WM: i3-gaps 4.18
* Distro: ArchLinux
* Output of `polybar -vvv`:
`polybar: error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: No such file or directory`

**Comment by damiiani** [comment]
Same issue here...

**Comment by jmg87** [comment]
I removed polybar and recompiled and it's back working again for me

**Comment by ltoenning** [comment]
Recompiling (in my case the AUR package) also solved this for me.

**Comment by patrick96** [comment]
Duplicate of #885
