### ISSUE TITLE
error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Mnjaro** [polybar/polybar#2051]
## Describe the issue
Updated to the latest version using yay

*What actually happens*
Whenever I try to launch, I get this error message :
`error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: No such file or directory`

## Environment:
* WM: I3
* Distro: Arch
* Output of `polybar -vvv`: error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: No such file or directory

**Comment by jwj1217** [comment]
I am also running Arch and had the same issue. linux 5.6.2 dropped last night. I'm wondering if that is related.

**Comment by masterAllen** [comment]
I also have this problem. It seems be caused by the update of jsoncpp. In my system, libjsoncpp is libjsoncpp.so.22.

**Comment by Cldfire** [comment]
See https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp

**Comment by masterAllen** [comment]
That's right. Using yay to get the latest version is ok...

**Comment by mighty9245** [comment]
this is caused by jsoncpp upgrade. just rebuild the polybar.

if you're on arch this should help no matter what aur helper you're using:
```
# change to polybar-git.git if you're using polybar-git package
git clone https://aur.archlinux.org/polybar.git
cd polybar && makepkg -si
```

**Comment by ChuckD3ath** [comment]
Hello! Experiencing the same issue, however, reinstalling the polybar (archlabs-polybar) and jsoncpp does not fix it. 
Should I just install the original polybar package or there will be an update soon regarding this?

**Comment by mighty9245** [comment]
oh, yeah, if you're using prebuilt polybar binary provided by a some package, then it must be rebuilt by package maintainer i guess...

**Comment by Mnjaro** [comment]
After trying all solutions and a quick look at this [link](https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp), here are the possible solutions for this issue:

- If you are using **polybar-git**, you need to rebuild the package.
`makepkg -si` inside of the polybar repo
- If you are using **polybar arch repo** then you must wait for a rebuild from the package maintainer or install **polybar-git** which leaves you with more possibilities regarding build problems.

Closing the issue and thanking you all for your help :small_airplane:

**Comment by patrick96** [comment]
@Mnjaro There is no polybar package in the arch repo, both `polybar` and `polybar-git` are in the AUR and for both the solution is to rebuild.

**Comment by mighty9245** [comment]
@patrick96, hey, i always wanted to ask you: when we will see polybar in arch repositories? it's so popular but still stays in arch user repository.

**Comment by grravity** [comment]
Same issue, rebuilding from AUR fixed it. Thanks

**Comment by sullyj3** [comment]
Does anyone know of an open issue for this on jsoncpp? I'm having trouble finding one. Perhaps there's a good reason for doing this, but on the face of it, breaking dependents every jsoncpp update seems like really terrible behaviour. Am I missing something?

**Comment by patrick96** [comment]
I'm not aware of any open issues on the jsoncpp side. Also this isn't really a jsoncpp issue. Changing the name of your `.so` file is standard behavior for a library when it can't guarantee binary compatibility between its versions.

Also, this issue only exists for packages not in the official distro repos. For official packages, the repo maintainers take care to rebuild any packages that may be broken this way.

**Comment by vince6794** [comment]
If you're on arch, a comment in the AUR solved for me :

> To solve the libjsoncpp issue you need to recompile polybar (particularly re-link). The easiest way to do that is to use a fresh clone of this AUR repo and run makepkg there. It is probably also possible with your AUR helper by telling it to remove existing build files (or deleting them yourself).

I just cloned the AUR repo, built it with `makepkg` and installed with `makepkg -i`

**Comment by sullyj3** [comment]
That makes sense, thanks.

**Comment by CommanderKronos** [comment]
I got this issue again. But I managed to "fix" it with a very easy symlink:
`ln -s /lib/libjsoncpp.so.25 /lib/libjsoncpp.so.24`

**Comment by patrick96** [comment]
@CommanderKronos No! Never do this unless you want to break your system.

**Comment by CommanderKronos** [comment]
@patrick96 You made me jump a little bit haha. I undid the symlink, and just rebuild polybar with yay (AUR helper). Thanks for the warning!

**Comment by patrick96** [comment]
Yeah, it was meant to sound a bit scary. Probably nothing bad will happen but it's impossible to tell what could happen in the worst case. Even worse if there are other programs out there that also rely on `libjsoncpp.so.24` and would otherwise break, but now use an incompatible `libjsoncpp.so.25`.

**Comment by stiliajohny** [comment]
> ln -s /lib/libjsoncpp.so.25 /lib/libjsoncpp.so.24

after rebuilding from git it didn't work , the library link did the trick

**Comment by RomjanHossain** [comment]
> Even worse if there are other programs out there that also rely on `libjsoncpp.so.24` and would otherwise break, but now use an incompatible `libjsoncpp.so.25`

i had this problem today after updating my system. then, i removed it `sudo pacman -R polybar` and installed it from AUR `yay -S polybar-git` . It solved the problem!!!

**Comment by aTable** [comment]
Echoing the above, I ran into this by upgrading arch but **did not rebuild polybar** as well. The arch wiki has a [troubleshooting section](https://wiki.archlinux.org/title/Polybar#Cannot_open_shared_object_file_libjsoncpp.so) prompting for a reinstall/rebuild that fixes the problem - you can still use main package `polybar` and don't need to change to development version `polybar-git`

**Comment by woenho** [comment]
add path to your env
----------------------
export LD_LIBRARY_PATH=/usr/local/lib64

**Comment by Bug-Reaper** [comment]
Probably a dumb question, is there no way to add a fallback that checks for any version of `libjsoncpp.so` if it can't find the one it was compiled with?

**Comment by patrick96** [comment]
Unfortunately, no. Different versions of `libjsoncpp.so` are not guaranteed to be compatible, that's why they have different names.

Also, polybar has nothing to do with that check. That check is performed in your kernel (I think).
