### ISSUE TITLE
Impossible to uninstall

### ISSUE THREAD

**Issue by Megaman99** [polybar/polybar#2052]
I can't uninstall the program. There isn't an option and the methods I tried aren't working.
The version is the 3.4.1 compiled on ubuntu.
I can not remove the packagese that remains after the uninstallation of the program

**Comment by jallbrit** [comment]
Have you tried following the [wiki](https://github.com/polybar/polybar/wiki/Compiling#uninstalling)?

> If you have manually compiled and installed `polybar`, go into the build folder where you originally ran `make install`. There you can run `sudo make uninstall` to remove all installed files from your system.

**Comment by patrick96** [comment]
>  I can not remove the packagese that remains after the uninstallation of the program

If you manually installed polybar dependencies, you will also need to manually uninstall them

As for uninstalling polybar, read what @jallbrit wrote.
