### ISSUE TITLE
Allow fractional padding/margins

### ISSUE THREAD

**Issue by jallbrit** [polybar/polybar#2056]
## Fractional Padding/Margins

Currently, polybar allows only integer padding/margins. I often find myself wanting something between `1` and `2`, but fractional padding/margins like `1.5` fail.

## Solution

Labels like `label-focused-margin` should allow floats instead of integers, so that fractional padding can be achieved.

**Comment by patrick96** [comment]
Paddings and margins use space characters, so you can't really have half a space. You are probably looking for something like what was requested in #1651. There is a PR for it in #1671. 

I'm going to close this since it basically asks for the same thing as #1651
