### ISSUE TITLE
Add margin between certain module

### ISSUE THREAD

**Issue by paraduxos** [polybar/polybar#2058]
## Is your feature request related to a problem? Please describe.
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

I try to create module like
```ini
modules-right = <icon1><module1>|space|<icon2><module2>|space|...
```

## Why does polybar need this feature?
*Describe why this feature would be useful to a large percentage of users (You need to convince us).*

I try `margin`, `separator`, `format-margin` in both `bar` and `module` section, but none seems to work

## Describe alternatives you've considered
*A clear and concise description of any alternative solutions or features you've considered, if any.*

I finnally met [Polybar-theme 8](https://github.com/adi1090x/polybar-themes#-polybar-8)

which works like
```ini
modules-right = <icon1><module1><separator_module><icon2><module2><separator_module>...
```
And this is their `<separator_module>`
```ini
[module/separator]
type = custom/text

content = |
content-background = ${color.bg}
content-foreground = ${color.bg}
content-padding = 0.5
```

This work and answer what I want

## Describe the solution you'd like
*A clear and concise description of how your solution would work. This includes possible config options that should be added.*

Just wonder are there any other built-in ways??

**Comment by patrick96** [comment]
`separator` in the bar section is a [label](https://github.com/polybar/polybar/wiki/Formatting#label), so you can set `separator-foreground` or `separator-padding = 1` and so on.
