### ISSUE TITLE
Width and offset doesn't work

### ISSUE THREAD

**Issue by GrbavaCigla** [polybar/polybar#2059]
## Describe the issue
Polybar wont float, when i set the width bellow 100%, or offset-x, or offset-y, it doesn't work

Float instead of black color

**Was it working before?**
No, i did not check that, this is my first time using polybar

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[color]
background   = #282a36
current_line = #44475a
foreground   = #f8f8f2
comment      = #6272a4
cyan         = #8be9fd
green        = #50fa7b
orange       = #ffb86c
pink         = #ff79c6
purple       = #bd93f9
red          = #ff5555
yellow       = #f1fa8c

[bar/main]
override-redirect = false 
offset-x = 3%
offset-y = 4
width = 80%
height = 32
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Screenshots
![001](https://user-images.githubusercontent.com/23121814/79066350-8591b680-7cb7-11ea-8ec7-75c05241cf00.jpg)

## Environment:
* WM: i3-gaps
* Distro: archlinux
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```
## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by paraduxos** [comment]
Maybe you need `override-redirect = true`

> override-redirect = true is required with i3 if you want to control the size/position of the bar.

[This related issue](https://github.com/polybar/polybar/issues/293#issuecomment-269902723)

**Comment by GrbavaCigla** [comment]
I tested it before with that, but now it works, wierd. Anyways, thanks for help!

**Comment by GrbavaCigla** [comment]
I have a problem, when I go fullscreen polybar is still there.

**Comment by paraduxos** [comment]
> I have a problem, when I go fullscreen polybar is still there.

Have you try `wm-restack = i3` or read this issue

> Maybe you need `override-redirect = true`
> 
> > override-redirect = true is required with i3 if you want to control the size/position of the bar.
> 
> [This related issue](https://github.com/polybar/polybar/issues/293#issuecomment-269902723)

**Comment by GrbavaCigla** [comment]
Thanks again!
