### ISSUE TITLE
multiple audio players => one module

### ISSUE THREAD

**Issue by prankousky** [polybar/polybar#2060]
## Is your feature request related to a problem? Please describe.
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

I use **both** `mpd` *and* `clementine` as audio players. `mpd` is for particular playlists, `clementine` for random listening. I know, this is not necessary, but it has been like this for a long time now. 

Currently, `polybar` displays the current/most recently played track via the mpd module; however, it would be nice to always just the most recent value; if one plays a song via `mpd`, then switches to another `mpris` player, display the mpris value; if the stop **or pause** mpris, and start/unpause in `mpd`, display that song.

I am sure this can be achieved; unfortunately, I do not know how to do it.

## Why does polybar need this feature?
*Describe why this feature would be useful to a large percentage of users (You need to convince us).*

I cannot be the only person using multiple audio players. Right? .....right?

## Describe alternatives you've considered
*A clear and concise description of any alternative solutions or features you've considered, if any.*

Idea 1: use two different bars with the exact same settings, except for the player module (mpd/mpris). Toggle the bar each time one switches the player

Idea 2: use **both** modules, perhaps one in a top bar and another in a bottom bar; this works fine, but also clutters the screen.

Just an idea :)

**Comment by patrick96** [comment]
I think you are the only one using two audio players or at least the only one that wants to use them in this way.

The mpd module doesn't show the most recently played song, it shows the currently active song (even if it's paused). This is an important distinction, as far as I am aware there is no notion of which song was most recently played.

Also, the mpd module doesn't support mpris players, so I'm really not sure how you want to achieve this.
