### ISSUE TITLE
won't render modules when i3 is listed

### ISSUE THREAD

**Issue by jhonasiv** [polybar/polybar#2061]
I am currently using a fresh manjaro-i3, that comes with i3-gaps installed. 
I just installed polybar and tried the default config, but whenever i run polybar it wont display any modules if i3 is listed, it only shows the bar background and my OS' default bar icons like volume, wifi, etc (i couldnt figure out why they are still showing up). Running `polybar example -r -l info` gives me this:

> * Loading config: /home/jhonas/.config/polybar/config
> warn: No monitor specified, using "eDP-1-1"
> * Loaded monitor eDP-1-1 (1920x1080+0+0)
> * Bar geometry: 1920x35+0+0; Borders: 4,4,4,4
> error: module/xbacklight: Could not get data (err: XCB_NAME (15))
> error: Disabling module "xbacklight" (reason: Not supported for "eDP-1-1")
> error: Disabling module "apulseaudio" (reason: Missing parameter "module/apulseaudio.type")
> error: Disabling module "eth" (reason: Invalid network interface "eno1")
> * Starting application
> * Starting module/i3
> * Starting module/xkeyboard
> * Starting module/memory
> * Starting module/cpu
> * Starting module/wlan
> * Starting module/battery
> * Starting module/temperature
> * Starting module/date
> * Starting module/powermenu
> * Entering event loop (thread-id=1)
> * Eventqueue worker (thread-id=10)
> * Configured DPI = 96x96
> warn: No fonts specified, using fallback font "fixed"
> * Loaded font "fixed" (name=Bitstream Vera Sans, offset=0, file=/usr/share/fonts/TTF/Vera.ttf)
> * Bar window: 0x1a00002
> * Activating tray manager
> * Tray window: 0x1a00009
> warn: Systray selection already managed (window=0x3600009)
> * Deactivating tray manager
> * module/i3: Rebuilding cache
> * module/xkeyboard: Rebuilding cache
> * module/memory: Rebuilding cache
> * module/cpu: Rebuilding cache
> * module/wlan: Rebuilding cache
> * module/battery: Rebuilding cache
> * module/temperature: Rebuilding cache
> * module/date: Rebuilding cache
> * module/powermenu: Rebuilding cache
> * Redrawing bar window
> error: Failed to parse contents (reason: Unrecognized token '3')
> * Redrawing bar window
> error: Failed to parse contents (reason: Unrecognized token '3')
> * module/battery: Rebuilding cache
> * Redrawing bar window
> error: Failed to parse contents (reason: Unrecognized token '3')
> * module/temperature: Rebuilding cache
> * module/battery: Rebuilding cache
> * Redrawing bar window
> error: Failed to parse contents (reason: Unrecognized token '3')
> * module/memory: Rebuilding cache
> * module/cpu: Rebuilding cache
> * module/temperature: Rebuilding cache
> * Redrawing bar window
> error: Failed to parse contents (reason: Unrecognized token '3')
> * module/battery: Rebuilding cache
> * Redrawing bar window
> error: Failed to parse contents (reason: Unrecognized token '3')
> warn: Termination signal received, shutting down...
> * module/i3: Disconnecting from socket
> * module/i3: Stopping
> warn: module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)
> * module/i3: Reconnecting socket succeeded
> * Deconstruction of module/i3 took 1 ms.
> * module/xkeyboard: Stopping
> * Deconstruction of module/xkeyboard took 0 ms.
> * module/memory: Stopping
> * Deconstruction of module/memory took 0 ms.
> * module/cpu: Stopping
> * Deconstruction of module/cpu took 0 ms.
> * module/wlan: Stopping
> * Deconstruction of module/wlan took 0 ms.
> * module/battery: Stopping
> * Deconstruction of module/battery took 69 ms.
> * module/temperature: Stopping
> * Deconstruction of module/temperature took 0 ms.
> * module/date: Stopping
> * Deconstruction of module/date took 0 ms.
> * module/powermenu: Stopping
> * Deconstruction of module/powermenu took 0 ms.
> * Waiting for spawned processes to end
> * Reached end of application...

**`polybar -vvv`** returns:

> polybar 3.4.2
> 
> Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
> 
> X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor
> 
> Build type: Release
> Compiler: /usr/bin/c++
> Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
> Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

It seems that polybar isnt recognizing its own internal/i3 module, because of the token '3'. Is there any dependencies missing or any way to bypass this? I installed it with pacman.

**Comment by patrick96** [comment]
Can you run polybar additionally with the `-s` flag and post that output. There is something generating invalid formatting tags.

**Comment by jhonasiv** [comment]
Here it is:

>  Loading config: /home/jhonas/.config/polybar/configwarn: No monitor specified, using "eDP-1-1"
> * Loaded monitor eDP-1-1 (1920x1080+0+0)
> * Bar geometry: 1920x35+0+0; Borders: 4,4,4,4error: module/xbacklight: Could not get data (err: XCB_NAME (15))error: Disabling module "xbacklight" (reason: Not supported for "eDP-1-1")
> error: Disabling module "apulseaudio" (reason: Missing parameter "module/apulseaudio.type")
> error: Disabling module "eth" (reason: Invalid network interface "eno1")* Starting application* Starting module/i3
> * Starting module/xkeyboard
> * Starting module/memory
> * Starting module/cpu
> * Starting module/wlan
> * Starting module/battery
> * Starting module/temperature
> * Starting module/date* Starting module/powermenu* Entering event loop (thread-id=1)
> * Eventqueue worker (thread-id=8)
> * module/i3: Rebuilding cache* module/xkeyboard: Rebuilding cache* module/memory: Rebuilding cache
> * module/cpu: Rebuilding cache
> * module/wlan: Rebuilding cache* module/battery: Rebuilding cache* module/temperature: Rebuilding cache
> * module/date: Rebuilding cache
> * module/powermenu: Rebuilding cache
> %{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 0%%{-u u-}   %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-} %{u#f50a4d +u u#f50a4d F#555}%{F-} %temperature-c%%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:}%date% %time%%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> * module/wlan: Rebuilding cache
> * module/battery: Rebuilding cache
> * module/temperature: Rebuilding cache
> * module/date: Rebuilding cache
> * module/powermenu: Rebuilding cache
> %{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 0%%{-u u-}   %{u#9f78e1 +u u#9f78e1 F#555}%{F-} CASA%{-u u-}  %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-}   %{u#f50a4d +u u#f50a4d F#555}%{F-} 25°C%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 16:00%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> * module/i3: Rebuilding cache
> * module/temperature: Rebuilding cache
> %{l}%{A1:i3wm-wsfocus-{}: u#ffb52a +u B#044}  -1  %{B- -u A u-}%{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 0%%{-u u-}   %{u#9f78e1 +u u#9f78e1 F#555}%{F-} CASA%{-u u-}   %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-}   %{u#f50a4d +u u#f50a4d F#555}%{F-} 25°C%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 16:00%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> * module/battery: Rebuilding cache
> %{l}%{A1:i3wm-wsfocus-{}: u#ffb52a +u B#044}  -1  %{B- -u A u-}%{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 0%%{-u u-}   %{u#9f78e1 +u u#9f78e1 F#555}%{F-} CASA%{-u u-}   %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-}   %{u#f50a4d +u u#f50a4d F#555}%{F-} 25°C%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 16:00%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> * module/temperature: Rebuilding cache
> %{l}%{A1:i3wm-wsfocus-{}: u#ffb52a +u B#044}  -1  %{B- -u A u-}%{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 0%%{-u u-}   %{u#9f78e1 +u u#9f78e1 F#555}%{F-} CASA%{-u u-}   %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-}   %{u#f50a4d +u u#f50a4d F#555}%{F-} 25°C%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 16:00%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> * module/battery: Rebuilding cache
> %{l}%{A1:i3wm-wsfocus-{}: u#ffb52a +u B#044}  -1  %{B- -u A u-}%{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 0%%{-u u-}   %{u#9f78e1 +u u#9f78e1 F#555}%{F-} CASA%{-u u-}   %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-}   %{u#f50a4d +u u#f50a4d F#555}%{F-} 25°C%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 16:00%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> * module/memory: Rebuilding cache
> * module/cpu: Rebuilding cache
> * module/temperature: Rebuilding cache
> %{l}%{A1:i3wm-wsfocus-{}: u#ffb52a +u B#044}  -1  %{B- -u A u-}%{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 2%%{-u u-}   %{u#9f78e1 +u u#9f78e1 F#555}%{F-} CASA%{-u u-}   %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-}   %{u#f50a4d +u u#f50a4d F#555}%{F-} 25°C%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 16:00%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> * module/battery: Rebuilding cache
> %{l}%{A1:i3wm-wsfocus-{}: u#ffb52a +u B#044}  -1  %{B- -u A u-}%{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 2%%{-u u-}   %{u#9f78e1 +u u#9f78e1 F#555}%{F-} CASA%{-u u-}   %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-}   %{u#f50a4d +u u#f50a4d F#555}%{F-} 25°C%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 16:00%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> * module/wlan: Rebuilding cache
> * module/battery: Rebuilding cache
> * module/temperature: Rebuilding cache
> %{l}%{A1:i3wm-wsfocus-{}: u#ffb52a +u B#044}  -1  %{B- -u A u-}%{r}%{u#e60053 +u F#555} %{F- -u u#e60053 +u}us%{-u} %{u- u-}   %{u#4bffdc +u F#555} %{F- u#4bffdc}9%%{-u u-}   %{u#f90000 +u F#555} %{F- u#f90000} 2%%{-u u-}   %{u#9f78e1 +u u#9f78e1 F#555}%{F-} CASA%{-u u-}   %{u#ffb52a +u u#ffb52a F#555}%{F-} 11%%{-u u-}   %{u#f50a4d +u u#f50a4d F#555}%{F-} 25°C%{-u u-}   %{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 16:00%{A -u u-}   %{A1:menu-open-0: F#e60053}%{F- A}
> warn: Termination signal received, shutting down...
> * module/i3: Disconnecting from socket
> * module/i3: Stopping
> warn: module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)
> * module/i3: Reconnecting socket succeeded
> * Deconstruction of module/i3 took 0 ms.
> * module/xkeyboard: Stopping
> * Deconstruction of module/xkeyboard took 0 ms.
> * module/memory: Stopping
> * Deconstruction of module/memory took 0 ms.
> * module/cpu: Stopping
> * Deconstruction of module/cpu took 0 ms.
> * module/wlan: Stopping
> * Deconstruction of module/wlan took 0 ms.
> * module/battery: Stopping
> * Deconstruction of module/battery took 403 ms.
> * module/temperature: Stopping
> * Deconstruction of module/temperature took 0 ms.
> * module/date: Stopping
> * Deconstruction of module/date took 0 ms.
> * module/powermenu: Stopping
> * Deconstruction of module/powermenu took 0 ms.
> * Waiting for spawned processes to end
> * Reached end of application...

**Comment by patrick96** [comment]
Is the name of your workspace `{}`? Because that confuses polybar.

I think it's the same bug as #2040

**Comment by jhonasiv** [comment]
Yes, that's actually it. It's working now. Thanks for your help!
