### ISSUE TITLE
Formatting sequence in i3 workspace name + click handler fails: unrecognized token

### ISSUE THREAD

**Issue by scrouthtv** [polybar/polybar#2063]
_I think this is related to #887 and maybe #984. The last update on #887 was that this is an unfixable bug, are there any updates?_

## Describe the issue
I am using a script to rename my `i3` workspaces according to the applications in them. The result should be something like ![image](https://user-images.githubusercontent.com/23227405/79564815-a5f2b400-80af-11ea-9382-be2687c155e4.png) if there are 2 chrome windows on this workspace. However, my font does not support subscripts so I did a workaround to **print the subscript numbers in a different font**:

1. `polybar` `config`:
```
[bar/bar]
font-0 = "Hurmit Nerd Font:size=10;3"
font-1 = "Hurmit Nerd Font:size=8;3"
font-2 = "Monaco:size=10;3"
modules-left = i3
tray-position = none

[module/i3]
type = internal/i3
label-focused = "[%name% ] "
label-unfocused = "(%name% ) "
```
2. A workspace would be named (output of `polybar -s`):
```
%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1\: :}(1:  ) %{A A1:i3wm-wsfocus-2\: :}(2:  ) %{A A1:i3wm-wsfocus-3\:  :}(3:   ) %{A A1:i3wm-wsfocus-4\:  :}[4:   ] %{A A1:i3wm-wsfocus-5\: :}(5:  ) %{A A1:i3wm-wsfocus-06\:  *:}(06:  * )
```
This works, if I add `enable-click = false` to the `i3` module. However, if I enable click actions, `polybar` only displays until the first formatting sequence:
```
polybar|error: Failed to parse contents (reason: Unrecognized token '3')
```

 - I think this is related to #887 (maybe even the same problem). Will there be any fix? Last comment on this issue was that it likely won't get fixed.

## Environment:
* WM: `i3 version 4.16.1-186-gf3fffbae (2020-03-01, branch "makepkg") © 2009 Michael Stapelberg and contributors`
* Distro: `Linux archlinux 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux`
* Output of `polybar -vvv`: 
```
polybar 3.4.0-83-g61dfe739

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
It's not related to #887. There, a polybar token is placed inside a user-defined action tag and polybar doesn't know it needs to escape the colons and we will indeed not fix this.
Here polybar knows it has to escape the colons, and it also does so.

The `polybar -s` output you posted, is this from when it works properly or when it doesn't?
I get a

```
error: Failed to parse contents (reason: 3 unclosed action block(s))
```

error when I use that string, so it seems it is incomplete.

Could you poste the entire `polybar -s` output, both for the config where you get the "Unrecognized token" error and where you don't?

Could you also post the portion of your i3 config that specifies your workspace names?

**Comment by scrouthtv** [comment]
With click handlers enabled, does **not** work:
```
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1\: :}(1:  ) %{A A1:i3wm-wsfocus-2\: :}(2:  ) %{A A1:i3wm-wsfocus-3\: %{T3}₂%{T-}:}(3: %{T3}₂%{T-} ) %{A A1:i3wm-wsfocus-4\: %{T3}₂%{T-}:}[4: %{T3}₂%{T-} ] %{A A1:i3wm-wsfocus-5\: :}(5:  ) %{A A1:i3wm-wsfocus-06\:  *:}(06:  * ) %{A A A PR}
```
![image](https://user-images.githubusercontent.com/23227405/79606922-a496ab00-80f2-11ea-940c-56c9342c4114.png)
__Notice how in comparison to my second screenshot there are some ws as well as the active one (marked with `[ ]`) missing.__
With click handlers disabled, does work:
```
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext:}(1:  ) (2:  ) (3: %{T3}₂%{T-} ) [4: %{T3}₂%{T-} ] (5:  ) (06:  * ) %{A A PR}
```
![image](https://user-images.githubusercontent.com/23227405/79606855-8630af80-80f2-11ea-820d-dc8d757f3f97.png)

This requires a Nerd Font.

**Comment by patrick96** [comment]
Ah. That's the same issue as #2061 and #2040. It's a bug in our parser. It happens when your workspace names contain the `}` character. In this case it seems like you have formatting tags in your workspace names defined in the i3 config.

I recommend using just numbers as workspace names in i3 and the `ws-icon-*` keys to map those numbers to other names (here you can use formatting tags no problem).

**Comment by scrouthtv** [comment]
So if I don't want to change my Polybar font to one that supports subscript numbers, I am not able to fix this issue, right?

**Comment by patrick96** [comment]
Oh, I have just noticed that you dynamically change the workspace names. This makes it more difficult. At the moment you cannot use the `}` character in i3 workspace names *and* enable click actions.

But I am curious why you actually need the formatting tags. If your main font does not support subscript characters, polybar will try to use the other fonts in your list to render it, so you shouldn't need to use formatting tags at all.
