### ISSUE TITLE
xworkspaces doesn't work properly with openbox

### ISSUE THREAD

**Issue by A1phaZer0** [polybar/polybar#2069]
## Describe the issue
occupied desktop displayed the same as empty one.

**Was it working before?**
N/A

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/main-bar]                                                                  
monitor = DP-3
width = 100%
height = 32
fixed-center = false
enable-ipc = true

background = #00222222
foreground = #dfdfdf

font-0 = Lekton Nerd Font:fontformat=truetype:size=16:antialias=true;0
modules-center = workspaces

[module/workspaces]
type = internal/xworkspaces

icon-0 = TERM;ﲵ
icon-1 = LAB;﮼
icon-2 = WEB;ﴣ

format = <label-state>

label-active = %icon%
label-active-foreground = #EF626C
label-active-padding = 2

label-occupied = %name%
label-occupied-foreground = #F1AB86
label-occupied-padding = 2

label-empty = %icon%
label-empty-foreground = #93B7BE
label-empty-padding = 2

[settings]
screenchange-reload = true

[global/wm]
margin-top = 0
margin-bottom = 0

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```

```

## Environment:
* WM:openbox 3.6.1
* Distro:ubuntu 18.04
* Output of `polybar -vvv`:

polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:

**Comment by patrick96** [comment]
`label-occupied` is not released yet. It will come with 3.5.0
