### ISSUE TITLE
module/network: Failed to query interface 'wlp2s0'

### ISSUE THREAD

**Issue by tiega** [polybar/polybar#2071]
## Describe the issue
**Expected behavior:**
The network module should detect wifi status accurately. 
**Actual behavior:**
internal/network fails to query my wifi interface.

**Was it working before?**
I've only used version 3.4.2 and its never worked

## To Reproduce
*A minimal but complete config with which the problem occurs:*
I'm not sure if its my config, because I've looked at multiple other user's config files and the network module setup is pretty standard.

```dosini
[bar/top]
module-margin = 2
padding-left = 0
padding-right = 2
line-size = 1
width = 100%
height = 2.5%

modules-right = network

font-0 = Iosevka:style=regular:size=12
font-1 = Font Awesome:style=Regular:size=13

[module/network]
type = internal/network
interface = wlp2s0
interval = 3.0
format-connected =  

format-disconnected = 
format-disconnected-foreground = #bd2c40

[settings]
screenchange-reload = true

[global/wm]
margin-top = 5
margin-bottom = 5
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
~/.config/polybar polybar top -l info
* Loading config: /home/tiger/.config/polybar/config
* Loaded monitor eDP-1 (1920x1080+0+0)
* Bar geometry: 1920x27+0+0; Borders: 0,0,0,0
* Starting application
* Starting module/network
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=3)
warn: module/network: Failed to query interface 'wlp2s0'
warn: module/network: Failed to query interface 'wlp2s0'
* Configured DPI = 96x96
* Loaded font "Iosevka:style=regular:size=12" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
* Loaded font "Font Awesome:style=Regular:size=13" (name=FontAwesome, offset=0, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
* Bar window: 0x3400002
* Disabling tray manager (reason: missing `tray-position`)
* module/network: Rebuilding cache
* Redrawing bar window
warn: module/network: Failed to query interface 'wlp2s0'
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3wm
* Distro: Ubuntu 18.04
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm -xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: 
```

## Additional context

The wlp2s0 interface files seem to be showing correct infomation.
```
/sys/class/net/wlp2s0 cat operstate
up
```
Output of `ip link`
```
~/.config/polybar ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DORMANT group default qlen 1000
    link/ether 60:f2:62:a8:39:32 brd ff:ff:ff:ff:ff:ff
3: gpd0: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 500
    link/none 
4: br-15e76fb81c05: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:39:96:ef:c3 brd ff:ff:ff:ff:ff:ff
5: br-96f5b790e29e: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:99:0f:48:de brd ff:ff:ff:ff:ff:ff
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:c7:76:9f:54 brd ff:ff:ff:ff:ff:ff
```

**Comment by patrick96** [comment]
Does `/sys/class/net/wlp2s0` contain a `wireless` folder?

What kind of wireless interface is this? Built-in, usb dongle, ...

Could you also post the output of `iwconfig`?

**Comment by tiega** [comment]
@patrick96 `/sys/class/net/wlp2s0` has a wireless folder but its empty. It is the built-in wifi interface on a XPS 13. Output of iwconfig:
```
docker0   no wireless extensions.

br-96f5b790e29e  no wireless extensions.

lo        no wireless extensions.

gpd0      no wireless extensions.

br-15e76fb81c05  no wireless extensions.

wlp2s0    no wireless extensions.
```

**Comment by patrick96** [comment]
> wlp2s0    no wireless extensions.

This is the problem, Wireless Extension doesn't support the wireless card. The polybar network module was compiled with `wireless-tools` and because of that it tries to use Wireless Extension to access the card.

Try to recompile polybar with libnl because we have deprecated the wireless extension in polybar. For that you need to install `libnl-genl-3-dev` and rebuild polybar, it should automatically pick up libnl instead of wireless-tools. If it doesn't, add `-DWITH_LIBNL=ON` to the cmake command.

**Comment by tiega** [comment]
@patrick96 That makes sense, thanks! I'll give it a shot
