### ISSUE TITLE
Borders for i3 workspace switcher

### ISSUE THREAD

**Issue by UtkarshVerma** [polybar/polybar#2079]
## Is your feature request related to a problem? Please describe.
Currently, there are no options to enable borders for i3 workspace switcher module. This is what I'm hoping to achieve:
![image](https://user-images.githubusercontent.com/31820255/80443507-03e38f00-892d-11ea-9dab-89963de415c2.png)

## Why does polybar need this feature?
People are used to this appearance since this option is there in `i3-bar` and *plasma panels* etc. Implementing this feature would be give a consistent UX without annoying the user about the tiny missing feature.

## Describe the solution you'd like
A config parameter for `[modules/i3]` name `border=true` would be a good start. Additionally, setting border width and spacing between the workspaces would be very much appreciated.

**Comment by patrick96** [comment]
We will not be adding this feature.

Polybar's goal is not to look like i3bar or plasma panels. In fact, one of polybar's key characteristics is that it is almost entirely based on rendered text (except for the tray), adding such borders would break from this.
