### ISSUE TITLE
I can not seem to get the center module center

### ISSUE THREAD

**Issue by suboxide** [polybar/polybar#2081]
I never really post on github so do not know if this is something I ask here or not. But all morning I have been trying to get the center module center, In the screenshot below I use the default config with just all modules removed except one in the center. I set fixed-center to true and turned of the tray.
In the hopes that the bspwm module would be center but it looks just a bit off still whatever I try.

Or am I missing something? To me the gap is under the 7 and to get it center it should be between 5 and 6?

![Screenshot from 2020-05-01 09-21-42](https://user-images.githubusercontent.com/4404698/80790067-24f6ea80-8b8e-11ea-9a2d-664fc9a02d8c.png)

➜  ~ polybar -v
polybar 3.4.0-96-gfc42da81
Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

**Comment by patrick96** [comment]
Such questions are generally better askes in a different place, unless you think this is a bug in polybar. See our [SUPPORT.md](https://github.com/polybar/polybar/blob/master/SUPPORT.md) or our [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config#ask-for-help-if-needed).

Polybar behaves correctly here, the module is dead center. The left window is larger than the right one so the gap between them is not in the middle of the screen ;)

**Comment by suboxide** [comment]
Sorry for missposting, and yeah I never noticed that was the problem will need to look further into why it is not masking same size windows.
