### ISSUE TITLE
Transparent background tray icon doesn not work correctly when you have a windows below

### ISSUE THREAD

**Issue by alexandrenavarro** [polybar/polybar#2086]
## Describe the issue
*A clear and concise description of what the bug is.*

Transparent background tray icon does not work correctly when you have a window below, it took the color of the wallpaper not the color of the window below.

**Expected behavior:**

Transparent background tray icon does not work correctly when you have a window below, it should take the color of the window below (not the color of the wallpaper).

*A clear and concise description of what you expected to happen.*

**Actual behavior:**

When you the transparent tray background with the configuration
tray-background = #0000000
override-redirect = true
with compton, the tray background works if you have only you wallpaper below (no window).
If you have a window below, **the color of the transparent background of the tray icon is the one of the wallpaper, not the one of the window which is wrong.**
It should be the one of the window, not the one of the wallpaper.

*What actually happens*

When you the transparent tray background with the configuration
tray-background = #0000000
override-redirect = true
with compton, the tray background should work when you have .
**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```
[colors]
background = #00000000
foreground = #ffffff

red = #e53935
pink = #d81b60
purple = #8e24aa
deep-purple = #5e35b1
indigo = #3949ab
blue = #1e88e5
light-blue = #039be5
cyan = #00acc1
teal = #00897b
green = #43a047
light-green = #7cb342
lime = #c0ca33
yellow = #fdd835
amber = #ffb300
orange = #fb8c00
deep-orange = #f4511e
brown = #6d4c41
grey = #757575
blue-gray = #546e7a


[bar/righttopbar]
monitor = DisplayPort-1
override-redirect = true
height = 24
width = 27%
offset-x = 73%
background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

; Must use a font Mono
font-0 = "DejaVuSansMono:pixelsize=11;2"
; for volume, down/up, mem and cpu, date and time.
font-1 = "Material Icons:size=12;4"

cursor-click = pointer
cursor-scroll = ns-resize

; Set to left if you want to use it, caution transparency does not work, change width also if needed.
;tray-position = none
tray-position = left
tray-detached = false
tray-maxsize = 16
tray-background = ${root.background}
tray-offset-x = -16
tray-offset-y = 0
tray-padding = 0

module-margin-left = 1
module-margin-right = 1

; Module set
modules-right = datetime

[module/datetime]
type = internal/date
interval = 1
date =  %Y-%m-%d  %H:%M %p
format-underline = ${colors.blue}
label = %date%

```

*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
Launch compton
Set a dark  wallpaper (like a black wallpaper).
Set a light (light grey) window title bar.
Use the polybar config above
Launch polybar righttopbar
Move your window like your title bar above your polybar.
Launch any application having like IBus Preference to have an icon in the tray.
You will see the background will be dark (black) instead of the color of the windows (grey).

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
Nothink particular in logs.

## Environment:
* WM: OpenBox
* Distro: Debian Buster
* Output of `polybar -vvv`:
Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/c++
Compiler flags: -g -O2 -fdebug-prefix-map=/build/polybar-JaCKjg/polybar-3.4.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-z,relro -Wl,-z,now

Don't hesitate to reply if it is not clear or need more explanation or need to test fixes or custom config.

Thanks for your amazing work of polybar, really great project.

**Comment by patrick96** [comment]
The tray always uses pseudo-transparency (it is always composed against the background instead of possible windows behind it) while the rest of the bar only uses it when explicitly enabled.

This was done deliberately when pseudo-transparency was added to the bar because supporting true transparency in the tray would have been a very involved and invasive change (https://github.com/polybar/polybar/pull/595#issuecomment-403035699).

We won't add true transparency to the tray. The plan is to replace the tray window with a proper module at some point (which will have true transparency).

**Comment by alexandrenavarro** [comment]
Ok, thank you, pretty clear. Did you create a issue on the creation of a proper module to replacet the tray window just to follow it and test it when it is available?

**Comment by patrick96** [comment]
@alexandrenavarro Hmm, I think #913 would be the one
