### ISSUE TITLE
Add a ramp-muted option

### ISSUE THREAD

**Issue by dannycolin** [polybar/polybar#2087]
## Is your feature request related to a problem? Please describe.

If I mute my sound, I lost the indicator (in my `ramp-volume`) to show the volume level.  

## Why does polybar need this feature?

Here's a use case that describe why I think my feature will be a great addition to polybar.

1) I start a playlist of music and do other things on a different workspace
2) I got a call and mute my sound
3) I forgot that my music is still running and unmute my headphone and get blasted by the music

## Describe the solution you'd like

A solution would be to have a `ramp-muted` that would let me use a different muted icon depending on
the volume level.

## Describe alternatives you've considered

I could auto-pause my music when I mute my sound but what if it's a video on youtube or a meeting
on jitsi or any other platform. I would have to configure all of them to auto-mute (if it's possible).
Having an option in polybar would be much simpler.

Currently, as a workaround I use `%percentage%` but I'd really like to have an icon-only config.

Thanks for considering my feature request

**Comment by patrick96** [comment]
You're `sdk` on IRC, right?

When you asked about this, I forgot to mention an idea I came up with that would basically solve this as well: #1752 

Once we implement this you can define your own ramps (even in the muted format).

I am going to close this but I will add a note on that issue.

**Comment by dannycolin** [comment]
> When you asked about this, I forgot to mention an idea I came up with that would basically solve this as well: #1752

Thanks for the link and sorry for the duplicate I didn't know #1752 would also cover things like `ramp-muted`.

**Comment by patrick96** [comment]
No worries.

That approach has a lot of nice side-effects ;)
