### ISSUE TITLE
[Feature request] Environment field in custom scripts

### ISSUE THREAD

**Issue by bbaserdem** [polybar/polybar#2090]
## Is your feature request related to a problem? Please describe.
I have a set of scripts which I use in my polybar config. I have a wrapper script to format them correctly; so i usually call them using the following syntax; `~/.config/sysinfo/sysinfo.sh -n pulseaudio -a cyan`. The reason I do have a wrapper script is I use these scripts across different setups.

Some other tools allow to custom set environment variables; so I do some customization of environment variables. (For example; the `sysinfo.sh -n <name>` is analogous to `name=<name> sysinfo.sh`)

## Why does polybar need this feature?
This would help users organize their custom scripts; as there can be one main block like the following;

```
[module/skeleton]
type = custom/script
tail = true
interval = 0
label = %output%
format = <label>
exec = ~/.config/sysinfo/sysinfo.sh
```

And then each custom script section could be defined like following;

```
[module/clock-script]
inherit = module/skeleton
environment = 'name=clock accent=cyan'
```
Which would make the config file more modular and organized.

## Describe the solution you'd like
Add a config option `environment` to a script that gets parsed to the beginning of a custom script's exec line.

## Describe alternatives you've considered
I currently read command line arguments; but it takes more work to do so.

## Additional context
Not really a vital or needed improvement; but I was thinking it could be trivial to implement.

**Comment by patrick96** [comment]
We've had lots of people asking about something like this before. Most the of their use-cases could be addressed by either adding the env variable to the script or into the polybar launch script.

But this is an interesting use-case.
A workaround for this could be:

```
exec = env name=clock accent=cyan ~/.config/sysinfo/sysinfo.sh
```

But you would still need to write the script path every time.
I am still unsure if we really want this in polybar. It will undoubtedly be useful, but if we add it here, we may also need to add it to the ipc hooks and click actions.

I also don't quite see a good way to implement this. We could execute the command with `/bin/sh -c "env ${environment} ${exec}"`, but this changes how `exec` is executed and won't work for things like `exec = cmd1; cmd2`

The other option would be to parse the `environment` value to extract key value pairs, but this becomes less trivial, as we would need to be able to parse things like 

```dosini
environment = FOO="ab " BAR="\"cd ef\""
```

Which is a bit more difficult than just splitting on each space. I'm not sure if that's worth the hassle.

**Comment by patrick96** [comment]
Someone asked on IRC about this and somehow I missed the most obvious solution to the problem I described in my last comment: Let the user define `env-*` config options. For example, `env-FOO="ab"` would set the `FOO` env variable. We can then set that variable using `setenv()` after forking. This avoids all the issues around shell escaping.

**Comment by TheDoctor314** [comment]
Is this issue taken? I would like to work on this.

**Comment by patrick96** [comment]
I am not aware of anyone working on this. I assigned it to you, go ahead :)

**Comment by davison** [comment]
the feature added in response to this issue works for the custom script when it is called from the `exec` line in the module, however the `env-FOO` vars are NOT passed to the custom script if it's invoked with `click-left`, `click-middle` or `click-right`. Would you consider this an omission / bug in the original implementation or a separate feature request? I think principal of least surprise is that the environment variables are passed from the click events too.

**Comment by patrick96** [comment]
This would definitely be a separate feature. Click commands are handled in a completely different way than the `exec` command.
When a click command is executed, polybar doesn't even know which module it came from, so something like this would require some bigger changes (it would also mean all click commands in all modules could support env variables).
