### ISSUE TITLE
Font issue crashes polybar when string displayed is not valid UTF-8

### ISSUE THREAD

**Issue by SoptikHa2** [polybar/polybar#2091]
## Describe the issue
When one tries to draw particular text with polybar (`𝐒𝐥𝐞𝐞𝐩𝐲 𝐌𝐨𝐮𝐧𝐭𝐚𝐢𝐧 𝐄𝐥𝐟 𝐑𝐞𝐭. on Twitter: "This meme had better planning than Silvercorp's coup did https://t.co/cGnaTIsZqK" / Twitter`, it's title of [this](https://twitter.com/OperatorMaid/status/1258022279906287616)), polybar crashes with `error: cairo_scaled_font_text_to_glyphs()input string not valid UTF-8`

**Expected behavior:**
Polybar drops the problematic string, as it does always when I try to draw text without proper font support, and doesn't display it, but doesn't crash.

**Actual behavior:**
Polybar crashes. Error for anyone searching for this:
```
error: cairo_scaled_font_text_to_glyphs()input string not valid UTF-8
```

**Was it working before?**
No idea, I only tested in this version of polybar.

## To Reproduce
```dosini
[bar/top]
width = 100%
height = 28

monitor = ${env:MONITOR:}

modules-center = window_name

font-0 = DejaVu Sans:pixelsize=12;1
font-1 = FontAwesome:style=Regular:size=12
font-2 = Nerd Font:pixelsize=12;1
font-3 = emoji-font:scale=8;1

line-size = 4

; Show currently focused window name at center of screen
[module/window_name]
type = custom/script
exec = xdotool getwindowfocus getwindowname | cut -c -80
interval = 1
```
The problem occurs [here](https://twitter.com/OperatorMaid/status/1258022279906287616).

## Polybar Log
```
warn: Dropping unmatched character ... (this repeats about 20 times)
error: cairo_scaled_font_text_to_glyphs()input string not valid UTF-8
```

## Environment:
* WM: i3-gaps 4.18.1-1 `i3 version 4.18.1 (2020-04-23) © 2009 Michael Stapelberg and contributors`
* Distro: ArchLinux `Linux yuno 5.6.10-arch1-1 #1 SMP PREEMPT Sat, 02 May 2020 19:11:54 +0000 x86_64 GNU/Linux`
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context

Sometimes, but not always, polybar complains about dropping null byte:
```
warn: Dropping unmatched character  (U+0000)
```

Here is hex dump of the string. Please note that this might not be correct, I have no idea how firefox (or my clipboard, or `echo`) handles invalid UTF-8 and the problematic character might be missing. Please see the link at top of this issue, it points to the problematic website. You can find the text in `<title></title`.
```
0000000 9df0 9290 9df0 a590 9df0 9e90 9df0 9e90
0000010 9df0 a990 9df0 b290 f020 909d f08c 909d
0000020 f0a8 909d f0ae 909d f0a7 909d f0ad 909d
0000030 f09a 909d f0a2 909d 20a7 9df0 8490 9df0
0000040 a590 9df0 9f90 f020 909d f091 909d f09e
0000050 909d 2ead 6f20 206e 7754 7469 6574 3a72
0000060 2220 6854 7369 6d20 6d65 2065 6168 2064
0000070 6562 7474 7265 7020 616c 6e6e 6e69 2067
0000080 6874 6e61 5320 6c69 6576 6372 726f 2770
0000090 2073 6f63 7075 6420 6469 6820 7474 7370
00000a0 2f3a 742f 632e 2f6f 4763 616e 4954 5a73
00000b0 4b71 2022 202f 7754 7469 6574 0a72     
00000be
```

**Comment by patrick96** [comment]
Yeah, this is indeed a bug. Polybar shouldn't crash if it gets invalid utf8 text from the outside. Not too sure what the best way to handle this is though. We need to find some way to only drop the problematic parts and find the next possible valid UTF8 character.

**Comment by SoptikHa2** [comment]
Thank you!
