### ISSUE TITLE
Actions not working in mpd module

### ISSUE THREAD

**Issue by vaskark** [polybar/polybar#2094]
Ive recently upgrade to Ubuntu 20.04 and have noticed a problem with my mpd module wrt actions for the label:

`label-song = %{A1:mpc toggle:}%{A2:termite -e ncmpcpp:}%{A3:mpc next:}%{A8:mpc prev:}%artist%  >>  %title%%{A}%{A}%{A}%{A}`

3/4 actions no longer work.

A1: no
A2: yes
A3: no
A8: no

I did try rebuilding from latest git master before reporting and it builds with no errors, yet the problem persists.

Note: I have mpc prev/toggle/next mapped to keybindings. These no longer work also. Yet at the CLI they work fine. Weird :/

Any help would be appreciated. Thanks.

Ubuntu 20.04
polybar 3.4.0-102-gf016b99

**Comment by patrick96** [comment]
With which polybar version did it work?

Can you post your polybar log (when running with the `info` log level)? This should tell us whether the command is actually executed.

> Note: I have mpc prev/toggle/next mapped to keybindings. These no longer work also. Yet at the CLI they work fine. Weird :/

This may indicate that this is not a polybar issue. How are these keybindings mapped?

**Comment by vaskark** [comment]
I was using an up-to-date checkout of git master. It was working fine until I did a system update earlier today (Ubuntu 19.10 to 20.04).

[Log](https://pastebin.com/WmPLq8bx)

I'm using berry wm which uses sxhkd for keybindings. All my other ones work fine.

**Comment by patrick96** [comment]
So from the log I see that the commands are definitely executed. Maybe you could try redirecting the command output to see whether there is an issue (maybe your mpd server is at a non-standard location): `%{A1:mpc toggle > /tmp/toggle.log:}`

**Comment by vaskark** [comment]
> `%{A1:mpc toggle > /tmp/toggle.log:}`

I took your advice, and all that's being outputed is:

`volume:100%   repeat: off   random: off   single: off   consume: off`

This is less than the usual output from the CLI.
As for mpd, I've always had one problem or another with it. It worked great for the longest time but since I upgraded my distro it's been causing issues again.

Thanks for your help, though. I very much appreciate it.

**Comment by patrick96** [comment]
Oh, I forgot, you also need to redirect stderr: `mpc toggle > /tmp/toggle.log 2>&1`.

Is your volume also 100% when you run it from the terminal?

**Comment by vaskark** [comment]
> Oh, I forgot, you also need to redirect stderr: `mpc toggle > /tmp/toggle.log 2>&1`.

Same results.

> Is your volume also 100% when you run it from the terminal?

Yes it is.

**Comment by patrick96** [comment]
Then I'm out of ideas. But since this is also not working in sxhkd, this does not appear to be a polybar issue.

I will close this for now.
