### ISSUE TITLE
Toggle visibility of a module

### ISSUE THREAD

**Issue by tobeypeters** [polybar/polybar#2108]
## Is your feature request related to a problem? Please describe.

I don't want, in my case, the mpd module to show unless I'm wanting to listen to music

## Why does polybar need this feature?

It'd be nice to have.  There's got to be other scenarios when you might want to do this.  Like, maybe in case you just want a quick glance at memory usage or cpu usage or something and you don't want it in your face 100% of the time.

## Describe the solution you'd like

Be able to send a polybar-msg to it from, in my case, i3 via a key binding.

You could even maybe create a new module _container_ thing, which you'd list the modules you want grouped together.

```
# Create the following containers for me
[container/systemrelated]
# anything after contains are modules you have defined
contains = cpu memory temp
# Default visibility state - true
visible = false
```
or

```
# Define the containers you want
containers = systemrelated anothercontainer yetanothercontainer

# Then, inside of a module, you could assign it to a container
[module/cpu]
type = custom/script

... other cpu settings

container = systemrelated

... other cpu settings

[module/memory]
type = custom/script

... other memory settings

container = systemrelated

... other memory settings

```
Now, in my case i3, I can setup a keybinding which sends a **cmd** to polybar, which would hide or show the modules in the specified _container_.  If it doesn't find the specified _container_, it'd default to looking for a single module with that name.

## Describe alternatives you've considered
None

## Additional context
None

**Comment by patrick96** [comment]
I think that has been asked before, but I can't find any issue that mentions it, so I'm guessing it was asked outside of github.

The toggling individual modules is a good idea. I do want to give more fine grained control over modules during runtime. I don't think containers are feasible right now, but that shouldn't be a problem if users can control individual modules.

We should wait with implementing this until after we finish #1907 because that changes all of the action handling and it would be a good idea to do this with `polybar-msg action` so that it can also be used in click actions.

**Comment by tosti007** [comment]
As of a few days ago #1907 was merged for release 3.5.0.

**Comment by tobeypeters** [comment]
Could you point me to the documentation for this?  So, in 3.5.0 you can toggle the visibility of a module.  I know, there's a toggle. 
 But, from what I can tell, it's not the samething.

**Comment by patrick96** [comment]
@tobeypeters No, visibility of a module still can't be triggered. What tosti007 was referring to was that #1907 was merged, which means that this is now an issue that can be worked on.

**Comment by parmort** [comment]
I'll take a crack at this, if no one else has started. Any tips or pointers?

**Comment by patrick96** [comment]
@parmort Thanks! I assigned the issue to you.

I think the best way is to add new command messages to [ipc](https://github.com/polybar/polybar/wiki/Inter-process-messaging#command-messages-to-control-polybar).

I first thought the best way to do this is to add a module action, but this is a bar-level operation (done in the controller) and not a module-level operation even though it targets a specific module.

An initial implementation could probably adapt `controller::process_update` to ignore modules that are marked as invisible.
This would keep modules running but just not displayed.

But I think the final goal should be to completely pause modules when they're invisible unless there is a good reason to keep modules running in the background.
