### ISSUE TITLE
[SOLVED] Filesystem module shows "not mounted"

### ISSUE THREAD

**Issue by darklord111** [polybar/polybar#2110]
`[module/filesystem2]

type = internal/fs

spacing = 2

fixed-value = true

interval = 30

mount-0 = /home/smee

format-mounted = <label-mounted> <bar-used>

label-mounted = "%mountpoint%" %used% of %total%`

This is the module that doesn't display anything, and says "/home/smee is not mounted."
And that's not possible, as that's my home folder, which has to be mounted for me to operate my computer, isn't it?
Plus, another module which displays disk usage of / correctly displays it, it's working fine, which has the same configu, just instead of mount-0 = /home/smee its mount-0 = /.
And when I check the logs, by doing
`cat /tmp/polybar2.log`
it displays error message
 `polybar|warn:  module/filesystem2: Mountpoint /home/smee is not mounted`
Also, I tried it with just /home, which didn't work either, just displayed the same message.
So,what do I do/what am I doing wrong?

**Comment by patrick96** [comment]
Is your `/home/smee` folder its own partition? The fs module can only display information about mountpoints not arbitrary folders.

**Comment by darklord111** [comment]
Oh. I didn't know that.
After dong so, it works perfectly fine.
Thanks for helping out such a noob like me!
