### ISSUE TITLE
Workspace Indicators with Windows

### ISSUE THREAD

**Issue by frankyyyyyyy** [polybar/polybar#2113]
Hi

Have been scouring docs and hopefully i haven't missed something stupidly obvious, but wondering if there is a method of having polybar visibly tagging (an indicator) on workspaces that have open windows.  I'm using BSPWM so have various workspaces across monitors.  In i3 world it's generally not an issue as polybar only shows active workspaces (those with windows).

Thanks

**Comment by patrick96** [comment]
I think that's what `label-occupied` and `label-empty` are for.
