### ISSUE TITLE
[Feature] Add ramp-headphones format to pulseaudio module

### ISSUE THREAD

**Issue by iK4tsu** [polybar/polybar#2115]
I used to use the `alsa` module, and having a `ramp-headphones` format is great! Sometimes I start listening to music with headphones and then I take them out, without turning the music off. Having that little extra icon helps me remind I have the music on, and not be bombarded when I take the headphones out.

Since the `alsa` sound module already has this format, I think it would make sense for the `pulseaudio` format to have it as well.

**Comment by patrick96** [comment]
Hi,

This feature was already proposed in #1071. There was some work done there but I think we got stuck at some point.

Closing in favor of #1071
