### ISSUE TITLE
Workspace icons disappearing when getting a notification

### ISSUE THREAD

**Issue by rupansh** [polybar/polybar#2119]
## Describe the issue
If I am in workspace y and I get a notification in workspace x, the icon of workspace x disappears from polybar. The same happens if firefox is open in workspace x and I click a link in workspace y 

**Expected behavior:**
workspace x icon shouldn't disappear

**Actual behavior:**
workspace x icon disappears

**Was it working before?**
No

## To Reproduce
config: https://del.dog/crilyfostu.txt
Open firefox in workspace x
switch to workspace y and click on any web link
OR
Open any app that you expect to get a notification in
switch to workspace y and wait for a notification

## Polybar Log
Nothing relevant

## Screenshots
![image](https://user-images.githubusercontent.com/3929608/83375559-dd61b980-a3ec-11ea-80ad-415cabf39e69.png)
(Firefox in workspace 1)

## Environment:
* WM: i3
* Distro: Arch Linux 
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
You bar text color is almost the same as the background color. The workspace with the urgent tag is still getting displayed, it's just displayed as black on a black background.

This doesn't happen for the other workspaces because you have explicitly set the foreground color for them to white.

**Comment by rupansh** [comment]
@patrick96 thanks!
