### ISSUE TITLE
Wrong brightness value with amdgpu_bl1

### ISSUE THREAD

**Issue by Syzygianinfern0** [polybar/polybar#2124]
## Describe the issue
Wrong brightness value (absurdly ~4000%) with the `amdgpu_bl1`

**Expected behavior:**
Correct brighness to be reported

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/brightness]
type = internal/backlight
card = amdgpu_bl1
```

Possibly related to #1870 and #1900

**Comment by patrick96** [comment]
What version of polybar are you using?

**Comment by Syzygianinfern0** [comment]
3.4.2

**Comment by Syzygianinfern0** [comment]
#2122 Fixes it. Built from source. Works now :tada: :partying_face:
