### ISSUE TITLE
[Improvement] Polybar CPU, memory and temperature module margin, padding and space need a small improvement

### ISSUE THREAD

**Issue by gusbemacbe** [polybar/polybar#2127]
## Describe the issue

Firstly, the Polybar's [Formatting the tokens](https://github.com/polybar/polybar/wiki/Formatting#tokens) does not solve the problem of CPU, memory and temperature modules padding and space. In reference to @enigmatic-system's https://github.com/adi1090x/polybar-themes/pull/33, the modules keep expanding and collapsing many times and _creates an annoying movement_, when it _bounces between single and double digit numbers_. 

I tried @enigmatic-system's code, but it did not solve he problem. I also tested with @vladdoster's code, in reference to https://github.com/polybar/polybar/issues/2049, but it did not solve either. I tried with the answer from [Zero padding](https://www.reddit.com/r/Polybar/comments/7hng6j/zero_padding/). I manipulated many codes in the modules in other config files, but nothing solved the problem. 

**Expected behaviour:**

The text should be centred and **fixed**, with a **padding** and a **margin**, so the modules would not bounce when it reaches one or two digits. 

**Actual behaviour:**

Without `tokens:2%%` (without space):

![screenshot example 1](https://user-images.githubusercontent.com/2257024/83978710-b3723080-a8df-11ea-8d2f-e2b584a4bf51.gif)

With ` %tokens:2%%` (with space):

![screenshot example 2](https://user-images.githubusercontent.com/2257024/84107376-d42baa80-a9f3-11ea-9126-0d60656d5f29.gif)

## To Reproduce

Alternative 1, based on @enigmatic-system's code:

```dosini
[module/cpu]
type = internal/cpu

interval = 0.5

format = <label>
format-background = ${color.mf}
format-foreground = ${color.fg}
format-padding = 2

label = " %percentage:2%%"
```

Alternative 2, based on @vladdoster's code:

```dosini
[module/cpu]
type = internal/cpu

interval = 0.5

format = <label>
format-background = ${color.mf}
format-foreground = ${color.fg}
format-padding = 2

label = %{A1:$TERMINAL -e htop >/dev/null 2>&1 &:}%percentage%%%{A}
```

I am using the fonts [Bahnschrift (a Microsoft font)](https://docs.microsoft.com/en-us/typography/font-list/bahnschrift) for the Polybar's text and Material Icons for the Polybar's icons. The fonts, bar modules and measures configurations:

```dosini
font-0 = "Bahnschrift:size=12;2"
font-1 = "icomoon\-feather:size=12;2"
font-2 = "xos4 Iosevka:size=12;2"
font-3 = "Weather Icons:size=10;2"
font-4 = "FontAwesome5Free:style=Solid:size=10;2"
font-5 = "FontAwesome5Free:style=Regular:size=10;2"
font-6 = "FontAwesome5Brands:style=Regular:size=10;2"
font-7 = "MaterialIcons:size=10:2"

modules-left = menu_i menu workspaces
modules-center =  app_title_i app_title
modules-right = updates_i updates keyboard_i keyboard separator separator memory_i memory cpu_i cpu separator separator alsa_i pulseaudio checknetwork_i checknetwork separator separator separator date_i openweathermap date sysmenu_i sysmenu

[bar/main]
fixed-center = true
overline-size = 2
border-size = 4
padding = 1
module-margin-left = 0
module-margin-right = 0
spacing = 0
dim-value = 1.0

tray-position = none
tray-detached = false
tray-maxsize = 16
tray-padding = 0
tray-scale = 1.0

[settings]
format-spacing =
format-padding =
format-margin =
format-offset =
```

## Screenshots

Check **Actual behaviour**. 

## Environment:
* WM: i3
* Distro: Endeavour OS Linux (Arch Linux-based)
* Output of `polybar -vvv`:

```shell
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context

I call @patrick96, for hearing his feedback, as he reviewed https://github.com/polybar/polybar/pull/1963.

**Comment by vladdoster** [comment]
I don't use polybar anymore, but what I ended up doing in my dwm-blocks setup is just formatting with leading 0s to as much so it wouldn't bounce. 

https://github.com/vladdoster/dotfiles/blob/master/.local/bin/statusbar/network_traffic

**Comment by gusbemacbe** [comment]
@vladdoster 

Maybe are you referring to https://github.com/vladdoster/dotfiles/blob/master/.local/bin/statusbar/cpu instead? Or are you suggesting the network traffic template for CPU template?

**Comment by vladdoster** [comment]
> @vladdoster
> 
> Maybe are you referring to https://github.com/vladdoster/dotfiles/blob/master/.local/bin/statusbar/cpu instead? Or are you suggesting the network traffic template for CPU template?

No, network traffic was correct. I pad it with 4 zeros so it wont bounce.

**Comment by gusbemacbe** [comment]
@vladdoster 

I applied `label = "%percentage:03%%"`, but it keeps bouncing:

![Peek 2020-06-10 01-20](https://user-images.githubusercontent.com/2257024/84226616-a0668880-aab8-11ea-8949-bc5a5dcd3b0c.gif)

**Comment by vladdoster** [comment]
> @vladdoster
> 
> I applied `label = "%percentage:03%%"`, but it keeps bouncing:
> 
> ![Peek 2020-06-10 01-20](https://user-images.githubusercontent.com/2257024/84226616-a0668880-aab8-11ea-8949-bc5a5dcd3b0c.gif)

That is weird.... I really am lost then.

**Comment by gusbemacbe** [comment]
Let @patrick96 see. He must know.

**Comment by patrick96** [comment]
> I am using the fonts Bahnschrift (a Microsoft font) for the Polybar's text and Material Icons for the Polybar's icons. The fonts, bar modules and measures configurations:

This is the problem. See how the module "bounces" even when it changes between different two-digit numbers? The font you are using is not monospaced that means different characters use a different amount of space. And polybar just draws the characters, so if you replace one character that takes a small amount of space (for example `1`) and replace it with another (for example `0`), all the other text shifts around as well.

If you want to get consistency, you have to use a monospaced font, where all characters take the use amount of space.

**Comment by gusbemacbe** [comment]
@patrick96 

I reassigned the individual font to a module, but the text does not appear.

```dosmini
[bar/main]
font-8 = "VictorMono Nerd Font:style=SemiBold,Regular:size=12;2"

[module/cpu]
type = internal/cpu
label = %{A1:$TERMINAL -e htop >/dev/null 2>&1 &:}%percentage%%%{A}
label-font = 8
```

![image](https://user-images.githubusercontent.com/2257024/84243616-d74c9680-aad8-11ea-89f4-742d92fe1cac.png)

**Comment by gusbemacbe** [comment]
To go well with PF DIN Mono, I switched from Bahnschrift to PF DIN Text:

![image](https://user-images.githubusercontent.com/2257024/84245831-087a9600-aadc-11ea-991d-edce5f1db6fa.png)

Problem solved

**Comment by Samarth2005** [comment]
Yeah, there is should be no problem if you just use monospaced fonts.
