### ISSUE TITLE
Displaying volume greater than 100%

### ISSUE THREAD

**Issue by ndench** [polybar/polybar#2128]
## Describe the issue
From the [pulseaudio wiki page](https://github.com/polybar/polybar/wiki/Module:-pulseaudio) it appears that the `use-ui-max` option allows you to display volumes above 100%. However, regardless of what I set this to, 100% is the highest value displayed, even when the volume is greater than that.

I can get the real volume by using `pamixer --get-volue` or using the pulseaudio gui.

**Expected behavior:**

The correct volume percentage is displayed, even over 100%

**Actual behavior:**

Volume percentage is displayed correctly below 100%. Once the volume increases beyond this, 100% is displayed regardless of the percentage. Until it drops bellow 100% at which point the correct volume is displayed again.

**Was it working before?**

No

## To Reproduce
```dosini
[module/volume-bar]
type = internal/pulseaudio
bar-volume-font = 2
bar-volume-width = 20
format-volume = <label-volume><bar-volume>
label-volume = "  "
label-muted = "   mute"
use-ui-max = false
label-volume-foreground = #B6C2E7
format-muted-foreground = #E76BB4
bar-volume-foreground-0 = #92A3F7
bar-volume-foreground-1 = #92A3F7
bar-volume-foreground-2 = #6BB3E7
bar-volume-foreground-3 = #6BB3E7
bar-volume-foreground-4 = #6BB3E7
bar-volume-foreground-5 = #6BE7D8
bar-volume-foreground-6 = #6BE7D8
bar-volume-gradient = true
bar-volume-indicator = |
bar-volume-fill = •
bar-volume-empty = ·
bar-volume-empty-foreground = #666666
```

## Environment:
* WM: i3
* Distro: Arch
* Output of `polybar -vvv`:
```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by patrick96** [comment]
This setting only controls how high you can set your volume via the pulseaudio module. Polybar will still show the real percentage in the `%percentage%` token, even if it's higher than 100% or 150%.
In the config you posted, you are using a progress bar, but those can only go up to 100%. They can't really get fuller than full.
