### ISSUE TITLE
Not able to display muted emoji when ALSA muted

### ISSUE THREAD

**Issue by fifn2** [polybar/polybar#2130]
## Describe the issue
I'm not able to get my alsa module to display 🔇 when it's muted. Here's what I have:

```
[module/alsa]
type = internal/alsa

format-volume = <ramp-volume>
format-muted = <label-muted>

label-muted = 🔇

enable-scroll = false

# Volume emojis
ramp-volume-0 = 🔈🔈
ramp-volume-1 = 🔈
ramp-volume-2 = 🔉
ramp-volume-3 = 🔊
```

**Expected behavior:**

*A clear and concise description of what you expected to happen.*

I expect the muted emoji, and only the muted emoji, to be displayed when ALSA is muted.

**Actual behavior:**

*What actually happens*

The double low volume emoji is being displayed.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?

No, no, and no.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```
[bar/bar]
monitor = HDMI1

modules-left = alsa

font-0 = DejaVuSansMono:size=12;2
# Fixes a problem where the emojis are absolutely enormous.
font-1 = "Noto Color Emoji:pixelsize=16:style=Regular:scale=10;2"

[module/alsa]
type = internal/alsa

format-volume = <ramp-volume>
format-muted = <label-muted>

label-muted = 🔇

enable-scroll = false

# Volume emojis
ramp-volume-0 = 🔈🔈
ramp-volume-1 = 🔈
ramp-volume-2 = 🔉
ramp-volume-3 = 🔊
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: bspwm
* Distro: Voild Linux
* Output of `polybar -vvv`:

```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/lib/ccache/bin/g++
Compiler flags: -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -Wno-error=deprecated-declarations -D_LINUX_IF_ETHER_H -g -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-z,relro -Wl,-z,now -Wl,--as-needed 
```

## Additional context
*Add any other context that you think is necessary about the problem here.*
You need to mute alsa to see the bug.

**Comment by patrick96** [comment]
I can't reproduce this.

How are you muting the sound? Are you muting the `Master` mixer of the default soundcard in alsa? Because by default the alsa module just shows the volume of the Master mixer.

**Comment by fifn2** [comment]
I am muting the Master mixer of the default soundcard. Is the module showing something else?

**Comment by patrick96** [comment]
The module should show the master mixer of the default sound card.

How exactly are you muting?

**Comment by fifn2** [comment]
I'm muting by using `alsamixer` to turn the master volume down all the way.

**Comment by patrick96** [comment]
That's not muting, that's turning the volume down. Mute is a separate state. I think in alsamixer you need to press <kbd>M</kbd> to mute a mixer

**Comment by fifn2** [comment]
Oh, okay. Thanks so much.
