### ISSUE TITLE
`custom/ipc` off by one bug

### ISSUE THREAD

**Issue by R0flcopt3r** [polybar/polybar#2131]
## Describe the issue

**Expected behavior:**

When initializing the nr 1 hook, it should initiallize `hook-1` When signaling `1` it should call `hook-1`.

The documentation mentions that `initial` is set to `0` by default. However there are no `hook--1` and the default value will therefore never do anything. 

**Actual behavior:**

To initialize `hook-0` you type `initial = 1`.
To signal `hook-0` you message `1`.

## To Reproduce
```dosini
[bar/all]
monitor = 
width = 100%
height = 20
offset-y = 0
radius = 0
fixed-center = true
line-size = 1
border-size = 0
padding-left = 2
padding-right = 2
module-margin-left = 1
module-margin-right = 1
modules-right = demo
cursor-click = pointer
cursor-scroll = ns-resize
bottom=true
tray-position = right
dpi-x = 0
dpi-y = 0
enable-ipc = true

[module/demo]
type = custom/ipc
hook-0 = echo foobar
hook-1 = date +%s
hook-2 = whoami
initial = 1
click-left = polybar-msg -p %pid% hook demo 1
click-right = polybar-msg -p %pid% hook demo 2
double-click-left = polybar-msg -p %pid% hook demo 3
```

## Environment:
* WM: bspwm
* Distro: Fedora 32
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -Wextra -Wpedantic -O2 -g -DNDEBUG
Linker flags: -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
```

**Comment by patrick96** [comment]
That's not a bug. The indexes you use to trigger the hooks are 1-based (as described on the [wiki](https://github.com/polybar/polybar/wiki/Module:-ipc)). That means `polybar msg hook ipc demo 1` executes the first hook (`hook-1`).

An initial value of 0 is a special value, meaning that no hook is executed when the module starts.

**Comment by R0flcopt3r** [comment]
Then that should be made clearer in the documentation.

**Comment by patrick96** [comment]
I added a note about an initial value of 0. Was it also not clear that the hook index is 1-based?
