### ISSUE TITLE
Wired network return %essid% and nothing else

### ISSUE THREAD

**Issue by Oselium** [polybar/polybar#2132]
System: Manjaro bspwm
Polybar doesn't seems to recognize the network or sees it as down (?)
Connection is wired, it's working but the command
`iw dev eno1 info` returns: _command failed: No such device (-19)_
I searched for more infos but I can't find an exaustive answer (most of the issues seems to be from wireless)
The wired has an alt _enp33s0_ that returns DISCONNECTED

**Comment by patrick96** [comment]
Wired connections don't have an ESSID, and the `%essid%` token is only available for wireless network interfaces. Try the `%local_ip%` or `%ifname%` tokens.

The [wiki](https://github.com/polybar/polybar/wiki/Module:-network#additional-formatting) has a list of tokens that are available for the different network types.

If that still doesn't work, please edit your post the with the [bug report template](https://github.com/polybar/polybar/issues/new?template=bug_report.md) as there is a lot of information missing for us to properly diagnose the issue.

**Comment by Oselium** [comment]
Hi, I was dumb enough to not search enough the wiki and/or related infos. The problem was not related to Polybar but something else (even %local_ip% or %downspeed% didn't worked).
