### ISSUE TITLE
Reload module using RTMIN

### ISSUE THREAD

**Issue by sampaio23** [polybar/polybar#2133]
Hi!

## Is your feature request related to a problem? Please describe.
I'd like to print the output of a file to polybar, and now I have `interval=1` set in a `custom/script` type module. But this file only changes when I run another script. So my polybar updates without the need for it, and when I run the script and really need to see this change, it takes a moment. I would be great if I could reload only this module using, for example, a `pkill -RTMIN*`.

## Why does polybar need this feature?
In the performance aspect, it saves resources, because I don't need to update it every second.
In the aesthetic aspect, when I execute the script, it could immediately change. It would open many new possibilities for the users.

## Describe the solution you'd like
There could be a config option, for example, called `signal`, which corresponds to the signal polybar has to receive to update the module.

## Describe alternatives you've considered
None.

## Additional context
None.

Thank you!

**Comment by patrick96** [comment]
This will be implemented as part of #786, but it won't be using signals but rather [IPC](https://github.com/polybar/polybar/wiki/Inter-process-messaging) with either an action for the script module or a command to reload arbitrary modules.

Closing in favor of #786
