### ISSUE TITLE
filesystem: reading free storage incorrectly

### ISSUE THREAD

**Issue by shervinsahba** [polybar/polybar#2134]
## Describe the issue
The filesystem module is incorrectly reading free storage. The value for /home in particular is very far from the value provided by `gparted`.

**Expected behavior:**

I expect the filesystem module to accurately estimate the free memory on mount points. I expected estimates somewhat near those provided by `gparted`, for instance, which gives:
```
/ 14.81 GB
/home 18.14 GB
```

**Actual behavior:**
The filesystem module reports I have:
```
/ 11.54 GB
/home 30.71 MB
```

The estimate for /home in particular is concerning. Why is it so far off?

**Was it working before?**

No, I'm new to polybar. 

## To Reproduce

I'm calling the filesystem module with the following config:
```
[module/filesystem]
type = internal/fs

; Mountpoints to display
mount-0 = /
mount-1 = /home
;;mount-2 = /var

; Seconds to sleep between updates
; Default: 30
interval = 10

; Display fixed precision values
; Default: false
fixed-values = true

; Spacing between entries
; Default: 2
spacing = 0

; Available tags:
;   <label-mounted> (default)
;   <bar-free>
;   <bar-used>
;   <ramp-capacity>
format-mounted = <label-mounted>
format-mounted-prefix = 
format-mounted-background = ${color.mb}
format-mounted-padding = ${layout.module-padding}

; Available tags:
;   <label-unmounted> (default)
format-unmounted = <label-unmounted>
format-unmounted-prefix = 
format-unmounted-background = ${color.mb}
format-unmounted-padding = ${layout.module-padding}

; Available tokens:
;   %mountpoint%
;   %type%
;   %fsname%
;   %percentage_free%
;   %percentage_used%
;   %total%
;   %free%
;   %used%
; Default: %mountpoint% %percentage_free%%
label-mounted = " %mountpoint% %free%"

; Available tokens:
;   %mountpoint%
; Default: %mountpoint% is not mounted
label-unmounted = %mountpoint%: not mounted
```

## Polybar Log
I have some errors, but they don't seem related:
```
error: module/mpd: Connection refused
error: Disabling module "network" (reason: Invalid network interface "wlp3s0")
error: module/brightness: Could not get data (err: XCB_NAME (15))
error: Disabling module "brightness" (reason: Not supported for "DP-2")
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused
error: module/mpd: Connection refused

```

## Environment:
* WM: i3
* Distro: Manjaro-5.4
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by patrick96** [comment]
gparted gives you the raw number of bytes free on the drive, polybar doesn't.

We use the `statvfs` (`man 2 statvfs`) function to gather file system statistics and we display the number of free bytes for an unprivileged user (`f_bavail`). This explains the disparity on the root file system, but not for `/home`.

I am not really sure why the home partition reports such a huge difference. Is your home partition encrypted somehow?

Can you also please post the output of the `df` command, it should produce similar values as polybar.
And finally, if you can, please compile and run the following program. It prints the raw data polybar uses in the filesystem module.

```c
#include <stdio.h>
#include <sys/statvfs.h>

int main(int argc, char* argv[]) {
    struct statvfs vfs;
    statvfs("/home", &vfs);
    printf(
        "f_bsize (block size): %lu\n"
        "f_frsize (fragment size): %lu\n"
        "f_blocks (size of fs in f_frsize units): %lu\n"
        "f_bfree (free blocks): %lu\n"
        "f_bavail free blocks for unprivileged users): %lu\n"
        "f_files (inodes): %lu\n"
        "f_ffree (free inodes): %lu\n"
        "f_favail (free inodes for unprivileged users): %lu\n"
        "f_fsid (file system ID): %lu\n"
        "f_flag (mount flags): %lu\n"
        "f_namemax (maximum filename length): %lu\n",
        vfs.f_bsize, vfs.f_frsize, vfs.f_blocks, vfs.f_bfree, vfs.f_bavail,
        vfs.f_files, vfs.f_ffree, vfs.f_favail, vfs.f_fsid, vfs.f_flag,
        vfs.f_namemax);

    return 0;
}
```
Save it as `main.c` and compile and run it with `gcc main.c -o main && ./main`

**Comment by shervinsahba** [comment]
Thanks Patrick for elucidating the `statvfs` function... I always wondered how storage was calculated in different ways. I did a bit of maintenance, so the storage values changed to those below, but `/home` is still off by a lot. I added outputs of `df` and `main.c` at the end, but I may have found some culprits.

### updated values
```
filesystem module / 11.25 GB   /home 20.82 GB
thunar            / 11.3  GB   /home 20.8  GB
df                / 12    GB   /home 21    GB

sudo gparted      / 14.52 GB   /home 38.92 GB
```
So it looks like the filesystem module is working just as well as everything else. Discrepency? About **18 G**.

## output of df and main.c
`df` output:
```
df: /run/user/1000/doc: Operation not permitted
Filesystem      Size  Used Avail Use% Mounted on
dev             7.7G     0  7.7G   0% /dev
run             7.7G  2.0M  7.7G   1% /run
/dev/nvme0n1p4   64G   49G   12G  82% /
tmpfs           7.7G  249M  7.5G   4% /dev/shm
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
tmpfs           7.7G   20M  7.7G   1% /tmp
/dev/nvme0n1p5  375G  336G   21G  95% /home
/dev/nvme0n1p1  256M   15M  242M   6% /boot/efi
tmpfs           1.6G   16K  1.6G   1% /run/user/1000
pCloud.fs       2.0T  277G  1.8T  14% /home/shervin/pCloudDrive
/dev/sdc1       117G   77G   35G  70% /media/minisd
/dev/sdb1       3.1T  702G  2.2T  25% /mnt/element_data
/dev/sdb3        98G   74G   20G  79% /mnt/element_backup_root
```

`./main` output:
```
f_bsize (block size): 4096
f_frsize (fragment size): 4096
f_blocks (size of fs in f_frsize units): 98050805
f_bfree (free blocks): 10203741
f_bavail free blocks for unprivileged users): 5457059
f_files (inodes): 24944640
f_ffree (free inodes): 22755701
f_favail (free inodes for unprivileged users): 22755701
f_fsid (file system ID): 4140332798657084050
f_flag (mount flags): 1024
f_namemax (maximum filename length): 255
```


### Info about `/home` and some culprits...
I may have found the issue. First, my `/home` directory isn't encrypted. I do have a virtual drive (pCloud), but each of its directories are massive compared to the discrepancy here. Anyway, running `du -h -max-depth=1 /home` comes up with the following. After querying as `root` I added in the corresponding values in `[[brackets]]`.
```
4.0K	/home/partimag
[[4.0K] du: cannot read directory '/home/lost+found': Permission denied
16K	/home/lost+found
4.0K	/home/sonarr
[[3.8G]] du: cannot read directory '/home/shervin/.cache/pacaur/mullvad-vpn/pkg': Permission denied
[[1.7G]] du: cannot read directory '/home/shervin/.cache/pacaur/mullvad-vpn-cli/pkg': Permission denied
[[2.1G]] du: cannot read directory '/home/shervin/.cache/pacaur/julia-git/pkg': Permission denied
607G	/home/shervin
[[5.2G]] du: cannot read directory '/home/carpenter': Permission denied
4.0K	/home/carpenter
607G	/home
```
The values in brackets total to **12.8 G**. This closes a good part of the gap on the discrepancy.  Do you think this was the issue, even though it's still a good 5G off?

Strange that I can't read my own package caches for those programs! Side observation... that 607G value above accounts for my virtual drive. Interestingly, `root` cannot read the virtual drive and reports only the disk value, which is far smaller.

**Comment by patrick96** [comment]
According to [this](https://stackoverflow.com/a/965701/5363071) SO answer, the default amount of storage reserved for root is 5%, which is 18.75GiB for your 375GiB drive. This is consistent with the ~18GiB discrepancy you are seeing, so the difference between `f_bavail` and `f_bfree` is the only reason you get different values in gparted.
