### ISSUE TITLE
Metric prefix symbol for kilo is *lowercase* k (not uppercase K)

### ISSUE THREAD

**Issue by jaimet** [polybar/polybar#2135]
## Describe the issue
*A clear and concise description of what the bug is.*
Just a typo in the network module output (it shows K rather than k)

**Expected behavior:**
0 kB/s (note the lowercase k)

*A clear and concise description of what you expected to happen.*
0 kB/s (note the lowercase k)

**Actual behavior:**
0 KB/s (note the uppercase k)

*What actually happens*
0 KB/s (note the uppercase k)

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?
I don't know.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
Any usage of the network module

*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM:
* Distro:
* Output of `polybar -vvv`:

## Additional context
*Add any other context that you think is necessary about the problem here.*

I think the problem is in https://github.com/polybar/polybar/blob/master/src/adapters/net.cpp#L233

**Comment by patrick96** [comment]
I don't think I have ever seen kilobyte written kB and not KB. Also, I'd rather have the network module consistently use uppercase prefixes instead of having `kB`, `MB`, `GB` and being technically correct.
