### ISSUE TITLE
battery: Add option to have an indicator when battery is below a certain percentage

### ISSUE THREAD

**Issue by CodingCellist** [polybar/polybar#2136]
## Is your feature request related to a problem? Please describe.
I frequently miss the fact that my laptop battery is almost out of charge, occasionally resulting in it shutting down 'unexpectedly'. It would be nice if the battery module supported an indicator, along the lines of the `Caps Lock` indicator in the `xkeyboard` module which would be enabled at a user-specified battery percentage.

## Why does polybar need this feature?
Most laptop users which use the `battery` module probably do so to keep an eye on the charge when it is unplugged. While occasionally glancing at the battery percentage is a habit one can develop, it is possible to forget to do so, especially if you are focused on a task. Having a visual change/indication of low battery would help alert users to the fact that their battery needs charging, potentially avoiding data/work loss from sudden power-off due to a depleted battery.

## Describe the solution you'd like
A visual indicator, e.g. a background colour change, when the battery percentage is below a certain threshold. This could have the following configs:
- `indicate-low-at` - specify the percentage at and below which the indicator would be shown
- `indicator-icon` - specify the icon that should be shown when the indicator is on
- `indicator-background` - specify the background colour
- `indicator-foreground` - specify the foreground colour
- `format-indicator-on` and `format-indicator-off` - applied before(?) the other format specifiers

Optionally, if possible, there could also be support for a flashing indicator (similar to the animated (dis)charging ramp):
- `indicator-flashing` - `true` or `false`
- `indicator-flashing-frequency` - flashing frequency in milliseconds

## Describe alternatives you've considered
Having a warning symbol (or similar) in the `ramp-capacity-0` value. However, this often does not provide enough of a visual change to be noticeable in the peripheral vision, leading to the low capacity going unnoticed.

**Comment by patrick96** [comment]
Warning formats were already requested in #570. This gives you basically the same capabilities as what you requested here. And together with #1752 you could also implement a blinking light.
