### ISSUE TITLE
Polybar skipping lines echoed by custom script

### ISSUE THREAD

**Issue by tam-carre** [polybar/polybar#2137]
## Describe the issue
Polybar is ignoring lines produced by `echo` in a continuous custom script (as confirmed by running it in an interactive shell). The script watches new lines being appended to a file. The module is configured with `tail = true`, and `interval = 0` just to make sure.

**Expected behavior:**
Every line produced should be displayed on the bar until a new line is produced.

**Actual behavior:**
Lines are skipped in a way that I don't understand.

**Was it working before?**
No

## To Reproduce
Config:
```ini
[module/myscript]
type = custom/script
exec = /path/to/script.sh
format = <label>
label-padding = 1
tail = true
interval = 0
```

Script:
```sh
file="$HOME/.config/polybar/test"
touch "$file"
tail -n 1 -f "$file" |
	while read -r line; do
		echo "$line"
		sleep 1
		echo "%{A1:some_stuff}         %{A}" # it seems that things work as expected without this line, but I am using it to wipe the last line from the bar
	done
```

Then in a terminal:
```sh
echo "first line
second line
third line
fourth line" >> $HOME/.config/polybar/test
```

## Polybar Log
(No output)

## Screenshots
Demonstration: https://u.teknik.io/aTJZ3.mp4
In this video I first show the output of the script run in an interactive shell, then how it behaves in Polybar, twice, to different results.

## Environment:
* WM: Openbox
* Distro: Ubuntu
* Output of `polybar -vvv`:
```c
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:```

**Comment by patrick96** [comment]
I can't reproduce this at all, the script works fine for me and always displays all four lines in polybar.  How regularly does this happen for you?

Can you try to add a line like `echo "$line" >> /tmp/dump` into the while loop and see if all the lines end up in the dump file.

**Comment by alnj** [comment]
I noticed there were some typos in my example, I fixed them.

Pretty much every time. I tried doing what you said, and had pretty strange results.

```sh
#!/bin/sh
file="$HOME/.config/polybar/test"
touch "$file"
tail -n 1 -f "$file" |
	while read -r line; do
		echo "$line"
		echo "$line" >> $HOME/dump
		sleep 1
		echo "%{A1:some_stuff}         %{A}" # it seems that things work as expected without this line, but I am using it to wipe the last line from the bar
	done
```

This skipped lines in Polybar but the lines made their way to the dump file safely. After various further experiments I found out that this fixed the problem entirely for me:
```sh
#!/bin/sh
file="$HOME/.config/polybar/test"
touch "$file"
tail -n 1 -f "$file" |
	while read -r line; do
		sleep 0.02
		echo "$line"
		sleep 1
		echo "%{A1:some_stuff}         %{A}" # it seems that things work as expected without this line, but I am using it to wipe the last line from the bar
	done
```

Any command other than sleep that takes time to run works... I tried with stuff like `echo "$line" >> $HOME/dump` and it fixed it *most* of the time so I'm assuming it was too fast the times it failed. (The lines made it to the dump even when Polybar skipped them)  Very strange.

This could matter here, my shell is dash.

**Comment by patrick96** [comment]
If you do something like

```bash
sleep 1
echo "$line"
sleep 1
echo "%{A1:some_stuff}         %{A}"
```
inside the loop, does it work then?

The only way I can think of where polybar would swallow the output, is when the lines are echoed very fast after each other. This obviously can't be the case with the sleep after `echo "$line"`, but the line you use to clear the output is immediately followed by the next line.

I actually explicitly tested this on dash because I know `sh` is dash on ubuntu, and I still couldn't reproduce it.

**Comment by petmi627** [comment]
Hi, sorry for the inconvenience, I found a solution here #793
