### ISSUE TITLE
Run polybar on a disconnected monitor?

### ISSUE THREAD

**Issue by DimaGashko** [polybar/polybar#2138]
## Describe the issue
*A clear and concise description of what the bug is.*
I use 1 or 2 monitors (internal laptop's monitor and external hdmi monitor). I means, the hdmi one is often disconnected.

I have to bars:

```ini
[bar/base]
monitor-strict = false # looks as a solution of my problem but has no effect

[bar/primary]
inherit = bar/base
monitor = eDP1

[bar/secondary]
inherit = bar/base
monitor = HDMI1
```

So, when I restart i3 while the html monitor is connected everything is ok, but if I connect the monitor after i3 is started there's still  only 1 bar (on eDP1, but no bar on HDMI1). So, I've to press `$mod+Shift+r` to restart i3 and polybar (or just restart polybars).

**Expected behavior:**

Each time I connect HDMI1 monitor I see bar/secondary

*A clear and concise description of what you expected to happen.*

I expect to see an polybar instance on HDMI1 monitor whenever I connect it

**Actual behavior:**

There's just no bars on HDMI1 output, if I connect the monitor when the bar has been already launched

## Environment:
* WM: i3
* Distro: ubuntu
* Output of `polybar -vvv`:

```bash
$ polybar -vvv
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm -xcursor

Build type: Release
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:  
```
* Output of `xrandr` when both monitors are connected:

```bash
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1920x1080     60.03*+  59.93    48.00  
   . . .
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 530mm x 300mm
   1920x1080     60.00*+  50.00    59.94  
  . . .
   720x400       70.08  
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

* Output of `xrandr` when HDMI1 monitors is disconnected:

```bash
$ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1920x1080     60.03*+  59.93    48.00  
  . . .  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)

```
In the wiki there's this:
```ini
; Require the monitor to be in connected state
; XRandR sometimes reports my monitor as being disconnected (when in use)
monitor-strict = false
```
And it looks like that I need (excluded 'when in use' part).
But that option just does nothing for me (probably it does something, but I don't see it)

Of course I can fix the problem by myself by relaunching polybars on monitor connecting but I would like to have an option in polybar's config to do that

**Comment by kronn** [comment]
I use `autorandr` to detect changes in my monitor-setup. `autorandr` stores configurations like "laptop" or "work", where the resolutions and such are applied once a new or different monitor is detected. It also has the ability to run "postchange"-scripts, which I use to restart polybar and have it then displayed on the right monitors.

In my (of course narrow-minded) opinion it is not the task of the status-bar to manage available monitors and wait for changes to maybe reload itself. Therefore: https://github.com/phillipberndt/autorandr, available as systempackage in a repository near you.

**Comment by DimaGashko** [comment]
@kronn sounds great, thanks, I'll see at that.
p.s. one of solutions I saw is in an option to make polybar a bit "stupid" and just don't check if any monitor is connected - just run everything I set up in the config file. So, in this case there's nothing that isn't the task of the status-bar (but it's most likely that with autorandr I could  do even better then I wanted)
