### ISSUE TITLE
change custom/script module formatting on click?

### ISSUE THREAD

**Issue by LunarLambda** [polybar/polybar#2144]
I have written a custom/script module, which displays some text, and, when clicked, copies some text to the clipboard

I would like to have some visual feedback when this happens, like temporarily showing the module with different colors

Is there any non-hackish way to achieve this? I know I could have the copy command create a flag file, and have the regular exec script check for it, and emit %{F} tags if it's present, then remove the flag, however this would have varying amounts of delay depending on the configured interval.

Is there a different way to write custom modules that would allow this?

**Comment by patrick96** [comment]
That's really the only way to do it if you have a script with an interval. Alternatively, you could have a long running script together with `tail = true` and have the click command send a signal to the script.

Also Ref #786 which will make what you are doing easier
