### ISSUE TITLE
internal/mpd: show track progress through underline

### ISSUE THREAD

**Issue by seamus-45** [polybar/polybar#2146]
Greetings!
First of all, thank you for this great project!

I miss one feature, when I was on [luastatus](https://github.com/shdown/luastatus) + [lemonbar](https://github.com/LemonBoy/bar) I wrote small [lua widget](https://github.com/seamus-45/dotfiles/blob/ac46b2124c2043675e4e11a2c358148a4213a655/.config/bspwm/widgets/mpd.lua#L98) for mpd control, which among other things was able to show track progress through underline colors.

e.g:
![image](https://user-images.githubusercontent.com/2586286/87673198-960d6d80-c78d-11ea-8888-990cab9a7a6a.png)

Is it possible to implement? Maybe add one extra parameter to module mpd, something `format-online-elapsed-underline` ?

**Comment by patrick96** [comment]
This isn't really possible in polybar. The mpd module would have to parse the entire formatting string it produced to insert the underline tags at the right position. It can't just split the outputs string as in the script you linked because it could cut into another formatting tag.
