### ISSUE TITLE
libjsoncpp.so.22 not found

### ISSUE THREAD

**Issue by majormeng1989** [polybar/polybar#2147]
after upgrade to archlinux5.7.9,the JSONCPP package upgraded too. it now provide libjsoncpp.so.24—64. but not support libjsoncpp.so.22. when I start polybar ,the error is“cant open the shared files,libjsoncpp.so.22 cant be found.”
now my polybar can't execute.

**Comment by MartialGeek** [comment]
Same thing for me on archlinux: `polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory`

**Comment by MTBorg** [comment]
Recompiling polybar solved it for me. 
See https://wiki.archlinux.org/index.php/Polybar#Cannot_open_shared_object_file_libjsoncpp.so for more information.

**Comment by patrick96** [comment]
https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp

**Comment by julienmiclo** [comment]
easy trick it's to do ln -s /usr/lib/libjsoncpp.so.{n} /usr/lib/libjsoncpp.so.22
where n it's your installed version

**Comment by patrick96** [comment]
> easy trick it's to do ln -s /usr/lib/libjsoncpp.so.{n} /usr/lib/libjsoncpp.so.22

Don't do that. The reason why the SONAME of the library changed is because the newer version is not compatible with the older version. So if you force polybar to use a newer version when it expects the old one can potentially have major side effects.
