### ISSUE TITLE
occupied desktops are not detected by xworkspaces module.

### ISSUE THREAD

**Issue by everett1992** [polybar/polybar#2148]
## Describe the issue

**Expected behavior:**
occupied desktops should be displayed using label-occupied configurations.

**Actual behavior:**
occupied desktops are displayed using label-empty configurations.

**Was it working before?**
I am a new polybar user, I don't know if it was working before.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/main]
foreground = #FFF
background = #000

modules-center = ewmh

[module/ewmh]
type = internal/xworkspaces

label-active = " #%name% "
label-occupied = " :%name% "
label-empty = " .%name% "
label-urgent = " !%name % "

```
Using herbstluftwm 0.8.3. My tags are named `z, x, c, v, b, n, m`. 

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: No fonts specified, using fallback font "fixed"
```

## Environment:
* WM: harbstluftwm 0.8.3
* Distro: Ubuntu
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl -i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker Flags:
```

## Additional context

```
$ xprop -root _NET_DESKTOP_VIEWPORT
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0
$ xprop -root _NET_DESKTOP_NAMES
_NET_DESKTOP_NAMES(UTF8_STRING) = "z", "x", "c", "v", "b", "n", "m"
$ xprop - root _NET_CLIENT_LIST
_NET_CLIENT_LIST(WINDOW) = window id # 0x1000003, 0x4400002, 0x2c00002, 0x5600002, 0x6200002
$ xprop -id 0x1000003 _NET_WM_DESKTOP
_NET_WM_DESKTOP(CARDINAL) = 0
$ xprop -id 0x4400002 _NET_WM_DESKTOP
_NET_WM_DESKTOP(CARDINAL) = 1
$ herbstclient tag_status
	#z	:x	.c	.v	.b	.n	.m
```
As you can see from _NET_WM_DESKTOP 0 and 1 have clients. hc client understands that z is active and x is occupied.

polybar displays `x` as empty.

```
	#z	.x	.c	.v	.b	.n	.m
```

The bar updates when I change desktops, when I focus `x` it becomes active and `z` is incorrectly marked empty.

**Comment by patrick96** [comment]
Occupied desktop support for the xworkspaces module is not released yet. It will come in version 3.5.0.
