### ISSUE TITLE
Unable to run polybar: "Error: No monitors found"

### ISSUE THREAD

**Issue by Linkandzelda** [polybar/polybar#2150]
I have compiled polybar for Arch Linux ARM aarch64. I am running XServer XSDL with Arch in a chroot.

xrandr outputs the following:
```
~ xrandr   
Screen 0: minimum 160 x 160, current 1440 x 720, maximum 1920 x 1200
default connected (normal left inverted right x axis y axis)
   1440x720       0.00  
   1920x1200      0.00  
   1920x1080      0.00  
   1600x1200      0.00  
   1400x1050      0.00  
   1280x1024      0.00  
   1280x960       0.00  
   1280x800       0.00  
   1280x720       0.00  
   1152x864       0.00  
   1024x768       0.00  
   832x624        0.00  
   800x600        0.00  
   800x480        0.00  
   720x400        0.00  
   640x480        0.00  
   640x400        0.00  
   320x240        0.00  
   320x200        0.00  
   160x160        0.00
```

Monitor specific config for polybar:
```
monitor =
monitor-fallback =
monitor-strict = false
```

Running polybar outputs the following:
```
~ polybar main                                 
error: No monitors found
```

Running `polybar -m` gives an empty output.
Also tried with config `monitor = default` with the same result.

**Comment by hegelocampus** [comment]
Little sanity check: It seems to me that this may be an issue with polybar being unable to connect to the user's X server. Have you tried running `$ xhost +local:` to give that permission?

**Comment by Linkandzelda** [comment]
I just tried this. Was able to run the command, but it did not change the behaviour of polybar.

**Comment by erhan-** [comment]
@Linkandzelda have you found a solution yet ? I also want to use polybar and bspwm with XSDL instead of DWM.

**Comment by Linkandzelda** [comment]
@erhan- No I have not, and eventually just switched to using Xvnc because it seems to not present this kind of issue.

**Comment by erhan-** [comment]
> @erhan- No I have not, and eventually just switched to using Xvnc because it seems to not present this kind of issue.

I would also use alternatively DWM but I have polybar etc on my desktop now as well.

**Comment by patrick96** [comment]
Polybar has gotten a bit better at detecting monitors in version 3.6. Does anyone still experience this on XSDL?
