### ISSUE TITLE
Nerd Font crop on i3 module only on focused mode

### ISSUE THREAD

**Issue by ltadeu6** [polybar/polybar#2152]
## Describe the issue
This don't appear to be the same as issue #991 because the cut only happens on the label-focused and not on label-unfocused and maybe is related to 

**Expected behavior:**

An consistent result on label focused and unfocused

**Actual behavior:**

Unfocused icons show just fine but on focused mode it doesn't happens

![image](https://user-images.githubusercontent.com/52164335/88491372-b94bd000-cf78-11ea-8d2c-82038851c254.png)
![image](https://user-images.githubusercontent.com/52164335/88491392-c5379200-cf78-11ea-9ded-5f075efd7ae1.png)

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?

## To Reproduce

```dosini

[global/wm]

margin-bottom = 0
margin-top = 0

[bar/main]

monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true
width = 100%
height = 26
offset-x = 0
offset-y = 0
background = ${color.bg}
foreground = ${color.fg}
radius-top = 0.0
radius-bottom = 0.0
padding = 3
module-margin-left = 3
module-margin-right = 3

font-0 = "Noto Sans:size=9:weight:bold;2"
font-1 = "Iosevka Nerd Font:size=12;2"

modules-left = i3

dim-value = 1.0
locale = pt_BR.utf8
tray-position = none
tray-detached = false
tray-maxsize = 16
tray-transparent = false
tray-background = ${root.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0

enable-ipc = true

;; Application Settings

[settings]

throttle-output = 5
throttle-output-for = 10
throttle-input-for = 30
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = out
compositing-border = out
pseudo-transparency = false

[color]

;; Active Colors
bg = #141A1B
fg = #EAEAEA
fg-alt = #9C9C9C

white = #FFFFFF
black = #000000

red = #e53935

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = false
wrapping-scroll = false

label-mode-padding = 8
label-mode-foreground = #000
label-mode-background = ${color.bg}
label-focused-background = #F8F8F2
label-focused-foreground = ${color.bg}
label-focused-underline = ${color.red}
label-focused = %name%
label-focused-padding = 8
label-unfocused = %name%
label-unfocused-padding = 8
label-visible = %name%
label-urgent = %name%
label-urgent-padding = 8



```
then on terminal enter
```
i3-msg 'workspace 阮; exec /usr/bin/firefox'
```

**Comment by d33n** [comment]
I have the same issue with a nerd font icon. For me the issue disappears when I set the label-focused-padding to 0.

**Comment by patrick96** [comment]
I think this is another instance of #991, a bug in nerd fonts.

The reason why it only appears when the workspace is focused is because we have to explicitly draw the background for the focused workspaces (the other workspace just inherit the bar background) and because nerd fonts for some reason doesn't correctly report how many pixels its characters take up, we draw over parts of the icon.
