### ISSUE TITLE
Error while trying to compile polybar

### ISSUE THREAD

**Issue by adeleke5140** [polybar/polybar#2153]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*

I cloned the git repo, opened the terminal in the local directory, and ran the cmake .. command

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*

This is the error I got:
Trying to enable ccache
-- Using compiler cache /usr/bin/ccache
-- No build type specified; using Release
-- Using supported compiler GNU-7.5.0
-- Checking for module 'alsa'
--   No package 'alsa' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  cmake/common/utils.cmake:85 (pkg_check_modules)
  cmake/03-libs.cmake:10 (querylib)
  CMakeLists.txt:53 (include)

-- Configuring incomplete, errors occurred!
See also "/home/kehinde/.config/polybar/polybar/build/CMakeFiles/CMakeOutput.log".
See also "/home/kehinde/.config/polybar/polybar/build/CMakeFiles/CMakeError.log".

```

```

## Environment:
* Distro (with Version):
ubuntu 18.04

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by scrouthtv** [comment]
```
-- No package 'alsa' found
...
A required package was not found
```
I think you need alsa first.

**Comment by adeleke5140** [comment]
I thought so as well. I've got polybar installed but now, I can't activate it. I use  Regolith as my DE.
Is there a way for me to like, "turn it on"(I'm a noob to tiling managers)

**Comment by scrouthtv** [comment]
What happens if you run `polybar` from the command line? Do you get any output?

**Comment by patrick96** [comment]
You "turn on" polybar, by running the polybar executable.

First you create your config at `~/.config/polybar/config` and then you start polybar by running `polybar BARNAME` where `BARNAME` is the name of the bar section in your config `[bar/BARNAME]`.
