### ISSUE TITLE
Polybar broke on arch due update in libjsoncpp

### ISSUE THREAD

**Issue by ask6155** [polybar/polybar#2154]
## Describe the issue
Polybar was working untill I did a system update and libjsoncpp got updated with broke polybar's dependency.
Now I get this error:
`polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory`
**Expected behavior:**
I should work with the new version

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
No it broke now.

## To Reproduce
- Install Arch linux.
- Install polybar.
- Run polybar.

## Environment:
* WM: BSPWM
* Distro: Archlinux
* Output of `polybar -vvv`: - 

## Additional context
The version for the library I have on the system now is `libjsoncpp.so.24`

**Comment by scrouthtv** [comment]
```
cd /usr/lib/
sudo ln libjsoncpp.so.22 libjsoncpp.so.24
```

This is because the lib version is hard linked in polybar for some reason.

**Comment by scrouthtv** [comment]
The Arch version of `libjsoncpp` provides a link without the version number as well:
```
 ~ pacman -Ql jsoncpp | grep libjsoncpp | xsel -pb
jsoncpp /usr/lib/libjsoncpp.a
jsoncpp /usr/lib/libjsoncpp.so
jsoncpp /usr/lib/libjsoncpp.so.24
 ~ file /usr/lib/libjsoncpp.so
/usr/lib/libjsoncpp.so: symbolic link to libjsoncpp.so.24
```

I don't know about other distros, but using this version (whose path stays the same over libjsoncpp updates) could be a fix?

**Comment by scrouthtv** [comment]
It looks like Ubuntu has the version independant library as well:
https://packages.ubuntu.com/focal/amd64/libjsoncpp-dev/filelist
as well as: https://packages.debian.org/buster/amd64/libjsoncpp-dev/filelist

I think this is a problem on the AUR package's side

**Comment by scrouthtv** [comment]
The other way of fixing this @ask6155 on the user's side is mentioned on the AUR website:
![image](https://user-images.githubusercontent.com/23227405/88697420-d44b4b00-d104-11ea-99e7-3ff903a6ee43.png)

**Comment by TheRealVira** [comment]
Same here - you should be able to fix it by compiling polybar yourself (as described on this githubs' wiki page):

https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp

**Comment by scrouthtv** [comment]
You don't even have to compile polybar yourself. Just rebuild and reinstall it via your AUR package manager

**Comment by TheRealVira** [comment]
> You don't even have to compile polybar yourself.

> Just rebuild [...]

yes.

**Comment by patrick96** [comment]
> This is because the lib version is hard linked in polybar for some reason.

This is standard behavior of the linker. Different library versions are not necessarily compatible. That's why you shouldn't fix this with a symlink.
