### ISSUE TITLE
polybar: error while loading shared libraries

### ISSUE THREAD

**Issue by b4skyx** [polybar/polybar#2155]
Unable to launch polybar since the last system update and jsoncpp seems to be the root cause.

Prior to update, I was able to launch polybar without any issues but after moving from ``jsoncpp-1.9.2`` -> ``jsoncpp-1.9.3`` it seems to not launch and giving an error

```
polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory
```
When rolling back to jsoncpp-1.9.2 the issue seems to go away.

## Environment:
* WM: bspwm
* Distro: Arch
* Output of `polybar -vvv`: polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory
* Polybar Version: 3.4.0.r113.ga625e2b7-1

**Comment by patrick96** [comment]
https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp

You have to recompile polybar.
