### ISSUE TITLE
Resolve variables in, for example, exec commands

### ISSUE THREAD

**Issue by tobeypeters** [polybar/polybar#2158]
I'm trying to make my system as "generic" and easy to config as possible.  So, I've put my color theme inside my .Xresources, converted my i3 config and now my polybar configuration.  One problem in my configuration is that I have a python script, which I'm passing "polybar" colors into as parameters.  Since, I can't use the color variables I already declared above, I have to hard-code the colors.  I mean, there's got to be other real-world examples, were variable resolving could come in handy.  Anyhow, my example:

**Currently have:**
```
[color]
bg = ${xrdb:color0:#ffffff}
fg = ${xrdb:color1:#000000}
primary_color = ${xrdb:color2:#000000}
comp_color = ${xrdb:color3:#000000}
comp_color2 = ${xrdb:color4:#000000}
dot = ${xrdb:color5:#000000}

exec = python3 -u ~/.config/polybar/scripts/window_info.py --application_colors "#ff9147" "#ffffff" --title_colors "#e69e6e" "#ffffff"

```
**Desired syntax:**
```
[color]
bg = ${xrdb:color0:#ffffff}
fg = ${xrdb:color1:#000000}
primary_color = ${xrdb:color2:#000000}
comp_color = ${xrdb:color3:#000000}
comp_color2 = ${xrdb:color4:#000000}
dot = ${xrdb:color5:#000000}

exec = python3 -u ~/.config/polybar/scripts/window_info.py --application_colors 
${color.comp_color}" "${color.fg}" --title_colors "${color.comp_color2}" "${color.fg}"
```

**Comment by tobeypeters** [comment]
I really want this functionality and I don't know c++.  If I could have the code changes necessary to make a private build, I'd be very happy with that.

**Comment by frebib** [comment]
As a workaround, you could ready the xrdb from your python script. It would achieve the same effect with a lot less work. Whilst I do agree that having polybar able to substitute variables into the `exec` command, I think it's probably a bit of a stretch for this use-case. That being said, I'd argue that polybar is intended to be used as a bar, not a configuration manager. You ideally shouldn't put it in the critical path between your config and your application. Moving the xrdb reading out of this path is probably the better solution here

**Comment by tobeypeters** [comment]
Well, i can come up a million million of different cases where variable substitution would be beneficial.  Things where people are repeating things over and over, that are slightly different.  Too be honest, my example is a good one.  I shouldn't have to manually read colors in the colors from the xrdb, when Polybar has already read them in.  I'm writing these scripts, for Polybar and they are not meant to be able to stand-alone.  I understand, what you were getting at & I definitely appreciate the feedback.  Nothing I said, was really directed at you.

**Comment by patrick96** [comment]
We will track this in #954
