### ISSUE TITLE
Add -exec option for menu-labels

### ISSUE THREAD

**Issue by Sporqist** [polybar/polybar#2161]
## Is your feature request related to a problem? Please describe.
So I was making a little shutdown menu that i can control either by mouse or by keys. The way I'm doing that is using polybar's 'menu' and i3's 'mode'. They communicate via IPC with each other.

2 Examples from my configs:
polybar: `menu-0-0-exec = i3-msg mode default; i3exit lock`
i3:          `bindsym $mod+0 mode powermenu; exec polybar-msg action menu-open-0`

The Problem is that polybar can communicate it's actions inside the menu via menu-x-n-exec but it can't communicate opening and closing the initial layer of a menu.

## Why does polybar need this feature?!
More consistency for the menu module + more interactive menus

## Describe the solution you'd like
`label-open = "blablah"`
`label-open-exec = _some program_` <-- I thought of something like this

## Alternative
Cut out the 'label' stuff from 'menu' and let `menu-0` be the default closed state

**Comment by patrick96** [comment]
I don't really know what you want to achieve. Do you want to execute a different command when you press on `label-open`? Why?

**Comment by Sporqist** [comment]
I want to notify i3 that i just opened the first layer of a menu `layer-open`
Opening the first layer of a menu doesn't give you the option to execute programs tho. This is only possible for `menu-n` with `menu-n-exec`

My proposal is to treat the initial `label-open` & `label-close` of a menu the same as `menu-n` by also giving them `-exec` options.

**Comment by patrick96** [comment]
I see. This is already possible, just not as straightforward. You can use [formatting tags](https://github.com/polybar/polybar/wiki/Formatting#action-a) to define your own click actions:

```dosini
label-open = %{A1:i3-msg mode powermenu; polybar-msg action menu-open-0:}Apps%{A}
```
and similarly for `label-close`.

**Comment by Sporqist** [comment]
Nice! I must have missed that when i was reading the wiki.

There is something odd on my end tho. Executing `i3-msg` works just fine but `polybar-msg`'s messages don't get executed by polybar.
It's also kinda weird that `label-open` loses it's own `open` action when adding action formatting tags.

**Comment by patrick96** [comment]
Oh that's because polybar ignores inputs (like clicks) when they happen to quickly after another input. You can fix this by setting `throttle-input-for = 0` in your [`[settings]` section](https://github.com/polybar/polybar/wiki/Configuration#application-settings). In the next version this will be permantently fixed.

>  It's also kinda weird that label-open loses it's own open action when adding action formatting tags.

That's because the original open action also uses action tags and action tags override each other.
