### ISSUE TITLE
`xprop` classes for bars and borders

### ISSUE THREAD

**Issue by bvalyou** [polybar/polybar#2168]
## Is your feature request related to a problem? Please describe.
I have my bar rendering with a small gap around it to allow the background to be visible, with a compositor (picom) configured to create transparent windows with a mild blur. The problem I ran into is that the blur applies to the border spacing, not just the visible content. I spent a few hours trying to make these two pieces work together, by trying various compositing-border options to attempt to exclude the border from the blur, and attempting to change how the border is created by trying all the likely sounding options (e.g. offsets). I landed on just excluding polybar from the compositor blur as a 'good enough' solution for now, but had the idea that having `xprop` attributes on different elements within polybar might make this and similar types of controls easier.

## Why does polybar need this feature?
Being able to set attributes on borders, bars, etc would provide users some powerful ways to customize the compositing behavior of polybar.

## Describe the solution you'd like
We extend the config options for bars (possibly other elements as well) with a class specifier (with predefined defaults?) e.g.
```
[bar/foo]
class = polybar-foo

border-size = 10
border-class = polybar-foo-border
```

## Describe alternatives you've considered
Described above

## Additional context
I'm not an expert in this topic by any means - I'm not even certain that you can differentiate attributes with this granularity. If this is feasible, I think it could be valuable.

**Comment by patrick96** [comment]
Unfortunately that's not how it works. The properties shown by `xprop` are defined per X window and polybar only has two of those: the bar itself and the tray.

So I don't think there is a way to use different compton settings for the border and the bar background.

If you want to just have a gap between the bar and the edge of the screen, you can use `offset-x` and `offset-y` in the [bar section](https://github.com/polybar/polybar/wiki/Configuration#bar-settings) to move it away from the edge (On some WMs this requires `override-redirect = true`).

**Comment by bvalyou** [comment]
`offset-x` and `offset-y` with `override-redirect = true` (with i3-gaps) did the trick! Thank you for the suggestion!
