### ISSUE TITLE
3.4.3 release tarball missing git submodules

### ISSUE THREAD

**Issue by tguruswamy** [polybar/polybar#2169]
Released archive https://github.com/polybar/polybar/archive/3.4.3.tar.gz has empty lib/xpp and lib/i3ipcpp subdirectories. Compiling from this tarball therefore fails.

> tar tf ./3.4.3.tar.gz | grep lib
polybar-3.4.3/cmake/03-libs.cmake
polybar-3.4.3/lib/
polybar-3.4.3/lib/CMakeLists.txt
polybar-3.4.3/lib/concurrentqueue/
polybar-3.4.3/lib/concurrentqueue/include/
polybar-3.4.3/lib/concurrentqueue/include/moodycamel/
polybar-3.4.3/lib/concurrentqueue/include/moodycamel/blockingconcurrentqueue.h
polybar-3.4.3/lib/concurrentqueue/include/moodycamel/concurrentqueue.h
polybar-3.4.3/lib/i3ipcpp/
polybar-3.4.3/lib/xpp/

**Comment by patrick96** [comment]
That's not the right tarball. Github creates both a zip file and a tarball for every release, however these don't include the submodules.

We upload a complete tarball for each release, for 3.4.3 it is called [polybar-3.4.3.tar](https://github.com/polybar/polybar/releases/download/3.4.3/polybar-3.4.3.tar)
