### ISSUE TITLE
Emoji in Polybar is breaking the font for the text

### ISSUE THREAD

**Issue by mushi-nova** [polybar/polybar#2171]
Recently I found out about `Noto Color Emoji` so I applied it and added the font using `font-4 = "Noto Color Emoji:pixelsize=16:style=Regular:antialias=true:scale=10;2"`. The emoji is showing perfectly but the problem is with the text as it is getting broken with all the spaces in between.
![17-41-37 - 24  ⁄  08  ⁄ 2020](https://user-images.githubusercontent.com/62972573/91046311-d0dcae00-e635-11ea-810b-d0ccc1349c63.png)

My default font is `font-0 = "FontAwesome:style=Regular:antialias=true:size=12;3"`. 

In the quest to solve this issue I rebooted my `i3wm` system and did `fc-cache -fv`. But none of that solves the issue. It would be great if you could suggest to me as to what is going wrong here.

**Comment by patrick96** [comment]
Fixed in #2802
