### ISSUE TITLE
Additional content type: underline/overline bar

### ISSUE THREAD

**Issue by K4rakara** [polybar/polybar#2172]
## Is your feature request related to a problem? Please describe.
Not really, its just something that would be really nice to have, especially for more minimal themes.

## Why does polybar need this feature?
While both `bar` and `ramp` exist, I'm confident some users (myself included) would really enjoy a lower-profile way of displaying a percent value: the underline/overline. `bar` and `ramp` are nice: they get the point across, but they take up a lot more space than is necessary to convey the information. By putting something like a bar in the underline or overline, you save a good deal of space.

## Describe the solution you'd like

This solution might conflict with `format-NAME-underline`/`format-NAME-overline`, but it probably would make sense to just throw a warning and use this one in case both are defined.
```ini
underline-NAME-filled = 50  ; The percent of the underline to fill.
underline-NAME-centered = false ; A boolean. If true, the line would be drawn outwards from the center.
underline-NAME-foreground = #ffffff ; The color to use for the filled part of the line.
underline-NAME-background = #000000 ; The color to use for the empty part of the line.

; overline would have the exact same config, just with "overline" for a prefix instead of "underline".
```

## Describe alternatives you've considered

If you don't want to conflict with `format-NAME-underline`/`format-NAME-overline`, then you could do something like this:
```ini
format-NAME-underline-filled = 50 ; The percent of the underline to fill.
format-NAME-underline-centered = false ; A boolean. If true, the line would be drawn outwards from the center.
format-NAME-underline = #ffffff ; The color to use for the filled part of the line.
format-NAME-underline-empty = #000000 ; The color to use for the empty part of the line.

; overline would have the exact same config, just with "overline" instead of "underline".
```

## Additional context
Heres some examples of how it could be used:
![image](https://user-images.githubusercontent.com/40474474/91666711-07e70f80-eacd-11ea-8751-e10aa9427c80.png)
![image](https://user-images.githubusercontent.com/40474474/91666559-cc981100-eacb-11ea-997f-a65984167046.png)

**Comment by patrick96** [comment]
While this does look very nice, this is not something that could feasibly be done in polybar.
