### ISSUE TITLE
Environment variables not working with include-file

### ISSUE THREAD

**Issue by Kratacoa** [polybar/polybar#2174]
## Describe the issue
`include-file` doesn't work with environment variables

**Expected behavior:**
As of [3.1.0](https://github.com/polybar/polybar/commit/bf16a4d415ea7d8845f578544de0c71e56ad314e) this feature has been implemented, specifically in #724 PR and [this commit by jaagr](https://github.com/polybar/polybar/commit/d3b0670f30eb497d10c1190f73fd700fbcb91500)

**Actual behavior:**
It doesn't understand paths such as `$XDG_CONFIG_HOME/polybar/colors/default`, giving me *default root pixmap* bla bla error

**Was it working before?**
I've tried this feature only in the current release.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[colors]
include-file = $XDG_CONFIG_HOME/polybar/colors/default

```

For reference, my current config is [here](https://github.com/Kratacoa/dotfiles/blob/44f902bc25e2e652e3bec9db0d432e54e253723f/polybar/.config/polybar/config)  

## Environment:
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/lib/ccache/bin/g++
Compiler flags: -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -Wno-error=deprecated-declarations -D_LINUX_IF_ETHER_H -g -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-z,relro -Wl,-z,now -Wl,--as-needed 
```

**Comment by patrick96** [comment]
Why do you know that the environment expansion isn't working?

It is working fine for me and if it wasn't working you should get an `Invalid include file` error.

**Comment by Kratacoa** [comment]
> Why do you know that the environment expansion isn't working?

It doesn't source the module, and therefore the bar is loaded as pitch black.  

By the way, tilde expansion is working, I shouldn't have included jaagr's commit. It's the environment variable that is failing.

**Comment by patrick96** [comment]
> It doesn't source the module, and therefore the bar is loaded as pitch black.

It doesn't source which module?

The "default root pixmap ..." error generally has a different cause. Can you post the entire polybar output?

**Comment by Kratacoa** [comment]
> It doesn't source which module?

`[colors]`; I meant to say section, not module, sorry.

> The "default root pixmap ..." error generally has a different cause. Can you post the entire polybar output?

```
  polybar|error: Disabling module "alsa" (reason: Cannot find simple element)
  polybar|error: Disabling module "xkeyboard" (reason: <gb> is not a valid format tag for "format")
  polybar|error: Disabling module "eth_usb" (reason: Invalid network interface "enp0s20u1")
  polybar|warn:  background_manager: Failed to get root pixmap, default to black (is there a wallpaper?)
  polybar|warn:  background_manager: Failed to get root pixmap, default to black (is there a wallpaper?)
  polybar|warn:  background_manager: Failed to get root pixmap, default to black (is there a wallpaper?)
  polybar|warn:  background_manager: Failed to get root pixmap, default to black (is there a wallpaper?)
  polybar|warn:  Dropping unmatched character  (U+e028)
  polybar|warn:  Dropping unmatched character  (U+e026)
  polybar|warn:  Dropping unmatched character  (U+e21a)
  polybar|warn:  Dropping unmatched character  (U+e238)
  polybar|warn:  Dropping unmatched character  (U+e0cb)
  polybar|warn:  Dropping unmatched character  (U+e016)
  polybar|warn:  Dropping unmatched character  (U+e10c)
  polybar|warn:  Dropping unmatched character  (U+e028)
  polybar|warn:  Dropping unmatched character  (U+e026)
  polybar|warn:  Dropping unmatched character  (U+e21a)
  polybar|warn:  Dropping unmatched character  (U+e238)
  polybar|warn:  Dropping unmatched character  (U+e0cb)
  polybar|warn:  Dropping unmatched character  (U+e016)
  polybar|warn:  Dropping unmatched character  (U+e10c)
  polybar|warn:  Dropping unmatched character  (U+e028)
  polybar|warn:  Dropping unmatched character  (U+e026)
  polybar|warn:  Dropping unmatched character  (U+e21a)
  polybar|warn:  Dropping unmatched character  (U+e237)
  polybar|warn:  Dropping unmatched character  (U+e0cb)
  polybar|warn:  Dropping unmatched character  (U+e016)
  polybar|warn:  Dropping unmatched character  (U+e10c)
  polybar|warn:  Dropping unmatched character  (U+e028)
  polybar|warn:  Dropping unmatched character  (U+e026)
  polybar|warn:  Dropping unmatched character  (U+e21a)
```
It keeps on going on with the dropping characters.

**Comment by Kratacoa** [comment]
EDIT: Uhm, it works properly now. What? I'm pretty sure it wasn't a mistype, as I have tested it more than 10 times. No clue.
Anyway, I'm closing this for now.

**Comment by patrick96** [comment]
I'm pretty sure this wasn't an issue with `include-file`. You would have gotten a different error if it couldn't include the file and at the least you would have gotten an error once you tried to reference the colors.

**Comment by Kratacoa** [comment]
> I'm pretty sure this wasn't an issue with `include-file`. You would have gotten a different error if it couldn't include the file and at the least you would have gotten an error once you tried to reference the colors.

Ok now I can confirm it wasn't. I figured out the issue behind it, it was due to how I configured my shell, fish, not loading the environment variables before the scripts get executed.  
(Basically I had autologin into X as the first condition in my config and I set all the variables later)
