### ISSUE TITLE
Polybar does not rise from i3

### ISSUE THREAD

**Issue by 1m-N00b** [polybar/polybar#2176]
## Describe the issue
Applications and scripts other than polybar will stand up, but only polybar won't stand up for some reason
But the script itself is written correctly, and when you run `./.config/polybar/launch.sh`. the polybar is displayed correctly
- **launch.sh**
```
#!/bin/bash

# restart i3
if [[ $1 = "restart" ]]; then
        i3-msg restart
        sleep 1
fi

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar
polybar bar1 &
```

- **i3 config**(If you want to see the whole thing, just let me know.)
```
# Auto Start App
exec --no-startup-id ~/tools/i3Autostart.sh
exec --no-startup-id fcitx
exec --no-startup-id slack
exec --no-startup-id discord
exec --no-startup-id telegram-desktop
exec --no-startup-id keepassxc

# Polybar
exec_always --no-startup-id $HOME/.config/polybar/launch.sh
```

**Was it working before?**
>No
* Did you also experience this bug in an earlier version of polybar?
>No
* If no, what was the last version where this worked correctly?
>Maybe before polybar 3.4.3

## Polybar Log(When `polybar -r bar1`)
```
warn: No monitor specified, using "HDMI2"
warn: internal/volume is deprecated, use internal/alsa instead
error: tray: Failed to put tray above 0x3200002 in the stack (XCB_MATCH (8))
error: Invalid _XEMBED_INFO for window 0x0c00153
```

## Environment:
* WM:i3-gaps version 4.18.2
* Distro:Arch 5.8.5-arch1-1
* Output of `polybar -vvv`:polybar 3.4.3
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
What do you mean by "polybar won't stand up"? Is the bar hidden behind other windows?

Can you post a screenshot of the problem.

**Comment by 1m-N00b** [comment]
thank you for fast your reply

Originally, after logging in with lightdm, polybar automatically stands up, but it doesn't stand up for some reason.
but another app(telegram and slack and dicord and something ) stand up
So I checked launch.sh and config, but it was described correctly.

**Comment by patrick96** [comment]
You mean polybar doesn't start when logging in?

You should try to redirect the output of the launch script somewhere to see whether it gives you any error messages. For example like this:

```bash
exec_always --no-startup-id $HOME/.config/polybar/launch.sh > /tmp/polybar.log 2>&1
```

You should also try to remove the `while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done` line in your launch script, we've had problems with this before as well.

**Comment by 1m-N00b** [comment]
yep thats right

I rewrote it to `exec_always --no-startup-id $HOME/.config/polybar/launch.sh > /tmp/polybar.log 2>&1` and looked at it and it didn't work. /tmp/polybar.log looks like this. Of course,  `while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done` commented out, too.

```
 polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory
```

**Comment by patrick96** [comment]
https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp

**Comment by patrick96** [comment]
Hold on. You said when you run polybar in the terminal, it works? Is it possible that you have multiple polybar executable in your system and when you run it in the terminal you get the correct one but when you run it in i3, you get the wrong one?

In any case, this seems to be an issue with your system. Can you try running `which polybar` from the terminal and also put that line at the beginning of the `launch.sh` and again post the output of the log file.

**Comment by 1m-N00b** [comment]
That's what I meant. launch.sh itself works, so it's not that existing bug in polybar.

When I did `./.config/polybar/launch.sh > /tmp/polybar.log 2>&1` , 
I got the following output  
```
 polybar|warn:  No monitor specified, using "HDMI2"                                                                                                                                                                                      
 polybar|warn:  internal/volume is deprecated, use internal/alsa instead
 polybar|error: Invalid _XEMBED_INFO for window 0x0c04af6
```

**Comment by patrick96** [comment]
I am suspecting that you have two versions of polybar on your system. i3 picks up the older, broken, version and when you run it in the terminal you get the correct version.

Please run `which polybar` both from your terminal and as part of the i3 startup and post both results.

**Comment by 1m-N00b** [comment]
I'm sorry, but I don't know what the following means
Does this mean after logging in with lightdm and executing `launch.sh` after i3 is started?(I put it up as a result of that interpretation. Please let me know again if I'm wrong.)
> as part of the i3 startup and post both results.

When I did `which polybar` in terminal , I'm getting  `/bin/polybar` in the output.

**Comment by patrick96** [comment]
No, I meant doing something like `exec --no-startup-id which polybar > /tmp/polybar2.log`. This will tell us which `polybar` executable is used if you launch polybar through i3

**Comment by 1m-N00b** [comment]
i see 
I rewrote it from `exec_always --no-startup-id $HOME/.config/polybar/launch.sh > /tmp/polybar.log 2>&1` to `exec --no-startup-id which polybar > /tmp/polybar2.log` and rebooted and looked at /etc/polybar2.log, and this is what I got

```
 /usr/local/bin/polybar
```

**Comment by patrick96** [comment]
Alright, so the problem is that you have installed polybar twice on your system. Once in `/usr/bin/polybar` and once in `/usr/local/bin/polybar`.

Deleting `/usr/local/bin/polybar` should fix your issue.

**Comment by 1m-N00b** [comment]
Thank you for your patience.
Keep up the good work!
