### ISSUE TITLE
Closing current window by clicking on the xwindow module

### ISSUE THREAD

**Issue by maxigaz** [polybar/polybar#2180]
## Is your feature request related to a problem? Please describe.
I use i3 without window borders to save on-screen space, which means there are no clickable buttons for closing, maximizing etc.. In most cases, I don’t miss these buttons, but sometimes, when I use a mouse driven-application, it may show a window that has no other way of closing it with the mouse.

## Why does polybar need this feature?
If the xwindow module had the feature of closing the window currently in focus by clicking on the module, I wouldn’t need to reach for the keyboard just for closing the window without borders.

## Describe the solution you'd like
The user clicks on the xwindow module and then the window whose title it displayed closes. This could be made optional by a setting such as

```
close-on-click = true
```

## Describe alternatives you've considered
I could write a bash script for doing what the module already does *and* what I’m proposing, although using that might be more resource hungry, especially if I wanted it to query the window title every few milliseconds.

Also, in the past I’ve tried mapping one of my extra mouse buttons to a script that would close the current window, but it didn’t always work for some reason.

**Comment by patrick96** [comment]
I don't think this feature is necessary. You can already use [action tags](https://github.com/polybar/polybar/wiki/Formatting#action-a) with a command (or script) that kills the current window to create a clickable area in your xwindow module.

**Comment by maxigaz** [comment]
Thank you for the advice! I could do it by modifying the polybar config as follows (I’m including this in case anyone else happens to be looking for the same solution):

```
[module/xwindow]
label = %{A1:xdotool getwindowfocus windowkill:}%title:0:30:...%%{A}
```

**Comment by MiguelRodrii** [comment]
> Thank you for the advice! I could do it by modifying the polybar config as follows (I’m including this in case anyone else happens to be looking for the same solution):
> 
> ```
> [module/xwindow]
> label = %{A1:xdotool getwindowfocus windowkill:}%title:0:30:...%%{A}
> ```

Hello I've followed your advice but I'm experiencing the bar freezing after I press the text. Have you or anybody else that is reading this experienced something similar and if that is the case how do I solve it. 
Thank for reading.

**Comment by maxigaz** [comment]
@MiguelRodrii I've never experienced anything like that, at least not because of this.

In any case, here's what I've been using for almost a year. I've customised it further for my personal needs.

```conf
[module/xwindow]
; Label with mouse actions (A1: left click; A2: middle click; A3: right click)
label = %{A1:i3-msg floating toggle:}%{A2:xdotool getwindowfocus windowkill:}%{A3:i3-msg move scratchpad:}%title:0:30:...%%{A}%{A}%{A}
```

**Comment by patrick96** [comment]
@MiguelRodrii Are you using an old version of polybar? Before 3.5.0 polybar could freeze while a click command was running.

**Comment by MiguelRodrii** [comment]
> @MiguelRodrii Are you using an old version of polybar? Before 3.5.0 polybar could freeze while a click command was running.

Well after a while trying to figure out what was the cause it seems like xfwm somehow doesn't works well with what I'm trying to do. I'm currently trying to move my workflow to openbox where everything works fine. 
I would also like to report the bug to the xfwm team but I don't know how to elaborate the report because it's so specific.
Thanks for your response btw haha ^^.
