### ISSUE TITLE
Polybar crashes and hangs bspwm

### ISSUE THREAD

**Issue by subnut** [polybar/polybar#2181]
## Describe the issue
*A clear and concise description of what the bug is.*
Polybar crashes and dumps core, also causing `bspwm` to hang.
Happens randomly, but generally it happens every 1-3 days, depends on usage (heavy usage => crash comes sooner)

One thing I have noticed is that only the bspwm modules hang. The rest of the bar keeps working.
Also, the common thing between every crash is that there is some `bspwm`-`polybar` interaction involved. Like workspace-switching (may or may not be by clicking/scrolling polybar), connecting/disconnecting monitors, etc.

**Expected behavior:**
Nothing hangs/crashes

**Was it working before?**
No. Always kept crashing.
* Did you also experience this bug in an earlier version of polybar? YES

## To Reproduce
*A minimal but complete config with which the problem occurs:*
Just use the `example` bar provided with polybar itself.

*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
Keep using extensively your desktop/laptop/whatever WITHOUT restarting or shutting down. Sleep is allowed.

## Polybar Log
Currently I don't have logs, but will start collecting them, and post a comment below with the logs when the next crash happens.

 <strike>In the meantime, check out this [coredump](https://github.com/subnut/coredumps/blob/master/core.picom.1000.d6f5a39061f740ecb81ab01f488269ce.1650996.1599833624000000.zst)</strike>

EDIT: Sorry, I uploaded the wrong coredump :sweat:
Will report back with correct coredump soon

## Environment:
* WM: bspwm
* Distro: Arch
* Output of `polybar -vvv`:
```
polybar 3.4.0-113-ga625e2b7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by parmort** [comment]
It looks like the core file is from picom (according to the name)... did you upload the right core dump? Do you have any logs available?

**Comment by subnut** [comment]
> did you upload the right core dump?

Sorry, my mistake. I uploaded the wrong coredump.
As I have not used my linux PC for a while, I don't have any coredumps
available right now. I will reopen this issue when I obtain a coredump, OK? :sweat_smile: 

> Do you have any logs available?

Umm... no. Actually I don't know how to tell polybar to make logs, 
nor do I know where they are stored ..

@parmort Would you please tell me how to
generate logs? And where they are stored?
Thank you!
<br>
Closing this issue as of now.

**Comment by patrick96** [comment]
Polybar doesn't produce log files, all its log messages are printed to stderr. So you can redirect polybars stderr to a file yourself.

This looks extremely tough to debug, so a coredump would be greatly appreciated
