### ISSUE TITLE
set label for custom/script that are not running

### ISSUE THREAD

**Issue by jeffinshadow** [polybar/polybar#2187]
let's assume I have this custom module

```
[module/custommodule]
type = custom/script
exec = sh custommodule.sh
exec-if = anycondition
label = %output%"
interval = 1
```

I would like an option that lets me define a label for when this script is not running, like the _label-empty_ option of the title module does when there is no window open.

Would it be possible to add this option?
(theoretically an _exec-else_ option would work too)

**Comment by jeffinshadow** [comment]
> let's assume I have this custom module
> 
> ```
> [module/custommodule]
> type = custom/script
> exec = sh custommodule.sh
> exec-if = anycondition
> label = %output%"
> interval = 1
> ```
> 
> I would like an option that lets me define a label for when this script is not running, like the _label-empty_ option of the title module does when there is no window open.
> 
> Would it be possible to add this option?
> (theoretically an _exec-else_ option would work too)

**Comment by shivanshu-semwal** [comment]
Just use the `echo` command or any other script that prints that label.
