### ISSUE TITLE
Reloaded polybar appears above fullscreen windows.

### ISSUE THREAD

**Issue by adigitoleo** [polybar/polybar#2188]
## Describe the issue

**Expected behavior:**
Polybar can be reloaded on the fly to test/configure modules, and fullscreen still works.

**Actual behavior:**
After reloading polybar, it is no longer hidden for fullscreen windows (bspwm).

**Was it working before?**
Unknown

## To Reproduce

1. Load polybar with bspwm, using a minimal config, e.g.:

```dosini
[bar/statusbar]
modules-left = bspwm

[module/bspwm]
type = internal/bspwm
label-focused = %index%
label-occupied = %index%
label-urgent = %index%!
label-empty = %index%
```

2. Open any window
3. Enter fullscreen (monocle) view - confirm that polybar is hidden
4. Exit fullscreen view (back to tiling)
5. Reload polybar: `pkill -USR1 polybar`
6. Repeat 3 - the bar is drawn over the fullscreen window

## Polybar Log
N/A

## Environment:
* WM: bspwm (with picom for compositing)
* Distro: Arch
* Output of `polybar -vvv` (+i3 because I still have i3 installed):

```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by adigitoleo** [comment]
FWIW this also happens when reloading `bspwmrc`

**Comment by patrick96** [comment]
Does this also happen with proper fullscreen mode (e.g. youtube fullscreen video)?

Can you try setting `wm-restack = bspwm` in the bar section?

I think when restarting, the bar is placed at the top of the window stack and thus is over other windows in monocle mode.

**Comment by adigitoleo** [comment]
> Can you try setting `wm-restack = bspwm` in the bar section?

Ah, that did it! I saw the parameter in the wiki but got the impression that it only applied to i3. And yes, this also solves fullscreen video, reloading `bspwmrc` etc.

Thanks, I'll close this.
