### ISSUE TITLE
polybar compilation error

### ISSUE THREAD

**Issue by ianmajkut** [polybar/polybar#2193]
I tried to install polybar using yay. This problems appears with the packages 'polybar'. And i tried to use the 'polybar-git' but i didn't work.
I am using Arch Linux and i am new and I would appreciate it if someone could help me
## Build Process
I typed yay -S polybar. I choosed the polybar option. Then I put enter, when the option packages to clean appeared, and then enter, when differences appeared to show. Then it started to download but finally it couldn't because it says that there was an error in build ().

## Build Log
```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (XCB_XCB)
  does not match the name of the calling package (XCB).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
...
- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Configuring done
-- Generating done
...
IsADirectoryError: [Errno 21] Is a directory: '/etc/localtime'
make[2]: *** [doc/CMakeFiles/doc_html.dir/build.make:77: doc/CMakeFiles/doc_html] Error 1
make[1]: *** [CMakeFiles/Makefile2:514: doc/CMakeFiles/doc_html.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
==> ERROR: Se produjo un fallo en build().
    Cancelando...
error compilando: polybar
```

## Environment:
* Distro (with Version): Arch Linux x86_64

**Comment by parmort** [comment]
Is your system up-to-date?

**Comment by ianmajkut** [comment]
yes, i wrote yay -Syu --devel and update everything, and then i tried again yay -S polybar but the problem is still there

**Comment by patrick96** [comment]
> IsADirectoryError: [Errno 21] Is a directory: '/etc/localtime'

You did not set your system up correctly. `/etc/localtime` is supposed to be a symlink to a zoneinfo file. In your case it is a directory. See the [arch installation guide](https://wiki.archlinux.org/index.php/Installation_guide#Time_zone).

**Comment by ianmajkut** [comment]
I did everything in the documentation and I keep getting the same error

**Comment by parmort** [comment]
What is the output of `ls -la /etc/localtime`?

**Comment by ianmajkut** [comment]
it shows a lot of  cities of the country where i live and:
Buenos_Aires -> /usr/share/zoneinfo/America/Argentina/Buenos_Aires

**Comment by parmort** [comment]
It should just show a symlink called `localtime` linking to one of those cities. Run, if your city is, for instance, Buenos Aires, `ln -sf /usr/share/zoneinfo/America/Argentina/Buenos_Aires /etc/localtime`. Make sure to delete the current symlink first. These commands probably have to be run as superuser.

To find the correct file to symlink to, explore the directories inside of `/usr/share/zoneinfo`.
