### ISSUE TITLE
Faint line persists across the bar

### ISSUE THREAD

**Issue by TechieAndroid** [polybar/polybar#2194]
## Describe the issue
*I'm experiencing a faint (but noticeable) line that persists across the bar wherever there are modules. I find it distracting and it messes with my ocd.*

**Expected behavior:**

*I expect no artifacts on the bar.*

**Actual behavior:**

*There is a consistent line that spans across the bar's elements even if they are supposed to be 100% transparent.*

**Was it working before?**
*I have always experienced it.

## To Reproduce
*My bar: https://github.com/TechieAndroid/arch-dotfiles/blob/master/laptop/config/polybar/config.ini*

## Polybar Log
`error: Disabling module "network" (reason: Invalid network interface "enp4s0f3u1")`
This error is normal for me since I have a external NIC for my laptop.

## Screenshots
![polybar-line](https://user-images.githubusercontent.com/17918163/95147272-defa1000-0745-11eb-9ed1-1dc09cf62dd9.png)
![polybar-line-2x](https://user-images.githubusercontent.com/17918163/95147277-e3262d80-0745-11eb-8db3-2067b665071c.png)

## Environment:
* WM: i3-gaps w/ Picom
* Distro: Arch x64
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /sbin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
*N/A*

**Comment by j0n4t** [comment]
Have you tried using another compositor, like xcompmgr? I tried to reproduce using your config and no line appears (using arch, openbox and xcompmgr). 
![image](https://user-images.githubusercontent.com/4040817/108608964-4f2dc900-73a9-11eb-8a1a-8f750be09556.png)

OBS.: I had tried using picom before, but it made some annoying shadows before (got too lazy to figure out how to properly config it).

**Comment by patrick96** [comment]
I think I figured out why this happens. It's the bar being slightly taller than the diagonal characters you use as separators. Try doubling the bar height and you'll see that that "faint" line gets really big:
![x](https://user-images.githubusercontent.com/2452038/124241421-08509c80-db1c-11eb-924a-55d6e718f1fd.png)

Those separation characters that you use have purple as their background color and a transparent text color, this means everything that isn't occupied by the symbol will be purple. This is desirable for the space to the side but everythin above and below is also affected. Seems the only solution is to tweak the font size until it occupies the entire bar height.
I'd suggest using `content-font` in the modules for the separators to use a dedicated font definition just for the separators.
