### ISSUE TITLE
PROBLEMS WHILE BUILDING.......UBUNTU 20.04 LTS

### ISSUE THREAD

**Issue by shivam3690** [polybar/polybar#2198]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*
Using the same exact commands as mentioned in the repo,i went to build folder and wrote cmake ..
Then i found such an error
 

**If you build polybar directly from this repository:**

YES,did exactly as mentioned.

* Output of `git describe --tags`:

**If you use some other way (like the AUR):**

*List exactly where you are building from and which version you are building.*

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```cmake ..
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- No build type specified; using Release
-- Using supported compiler GNU-7.3.0
--  Build:
--    Version: 3.4.0-118-g31096de
--    Type: Release
--    CXX: /home/shivam/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/shivam/anaconda3/include -Wall -Wextra -Wpedantic -O3 -DNDEBUG
--    LD: /usr/bin/ld -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/shivam/anaconda3/lib -Wl,-rpath-link,/home/shivam/anaconda3/lib -L/home/shivam/anaconda3/lib 
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.2.2)
-- [X]   curl (7.71.1)
-- [X]   i3
-- [X]   mpd (2.18)
-- [X]   network (libnl) (3.4.0)
-- [X]   pulseaudio (13.99.1)
-- [X]   xkeyboard (1.14)
--  X extensions:
-- [X]   xcb-randr (1.14)
-- [X]   xcb-randr (monitor support) (1.14)
-- [X]   xcb-composite (1.14)
-- [X]   xcb-xkb (1.14)
-- [X]   xcb-xrm (1.0)
-- [X]   xcb-cursor (0.1.1)
--  Log options:
-- [X]   Trace logging
-- XCB[XCB]: Found component XCB
-- Could NOT find XCB_ICCCM (missing: XCB_ICCCM_LIBRARY) 
-- Could NOT find XCB_EWMH (missing: XCB_EWMH_LIBRARY) 
-- Could NOT find XCB_UTIL (missing: XCB_UTIL_LIBRARY) 
-- Could NOT find XCB_IMAGE (missing: XCB_IMAGE_LIBRARY) 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find XCB (missing: XCB_ICCCM_FOUND XCB_EWMH_FOUND XCB_UTIL_FOUND
  XCB_IMAGE_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  lib/xpp/cmake/FindXCB.cmake:249 (find_package_handle_standard_args)
  lib/xpp/CMakeLists.txt:28 (find_package)


-- Configuring incomplete, errors occurred!


```

## Environment:
* Distro (with Version):
UBUNTU 20.04 LTS

## Additional context
*Add any other context that you think is necessary about the problem here.*

Tried this also but with same results:cmake -DSPHINX_BUILD=sphinx-build ..
cmake -DCMAKE_CXX_COMPILER="clang++"

**Comment by patrick96** [comment]
Did you install all the dependencies listed [here](https://github.com/polybar/polybar/wiki/Compiling#dependencies-1)? Because it looks like you are missing `libxcb-ewmh-dev`, `libxcb-icccm4-dev`, and `libxcb-util0-dev `

**Comment by shivam3690** [comment]
apt install build-essential git cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python3-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev



I had executed the commands as was given on repo .

**Comment by shivam3690** [comment]
![Screenshot from 2020-10-08 15-30-30](https://user-images.githubusercontent.com/53882992/95444362-5795e200-097b-11eb-82da-73606695e56f.png)

**Comment by patrick96** [comment]
Hmm. I think anaconda is still interfering with the compilation. I would guess it is because you disabled conda *after* running `cmake ..` for the first time. This is because when you run cmake for the first time it will already configure some stuff and that could still break the build even if you fix your setup afterwards. I would suggest doing a clean build.

What you need to do is:

1. delete the `build` directory
1. Disable conda and remove any conda-related paths from both the `PATH` and `PKG_CONFIG_PATH` environment variables
1. Create the `build` directory, go into it and run `cmake ..`

Make sure to do all of this in the same terminal window because changes to `PATH` and `PKG_CONFIG_PATH` are only temporary.

**Comment by shivam3690** [comment]
Yeah,it worked as you said,THANKS for the kind help.
