### ISSUE TITLE
Offset not working as intended

### ISSUE THREAD

**Issue by cpiber** [polybar/polybar#2202]
## Describe the issue
Offsets don't offset on multimonitor. I can use a negative value or `>= width` to push it to the next monitor but the bar doesn't actually get offset.

**Expected behavior:**

Offset from screen border.

**Actual behavior:**

Sticks to screen border.

**Was it working before?**

First time using polybar.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/test]
width = 100
height = 30
offset-x = 18

modules-center = date

[module/date]
type=internal/date
time = %H:%M
label = %time%
```

## Polybar Log
Nothing

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3
* Distro: Ubuntu 20.04
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/c++
Compiler flags: -g -O2 -fdebug-prefix-map=/build/polybar-IKpyNi/polybar-3.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-Bsymbolic-functions -Wl,-z,relro
```

**Comment by patrick96** [comment]
i3 doesn't seem to respect offsets defined by polybar. You need to set `override-redirect = true` to force i3 to not reposition polybar, then the offset will work (but i3 will no longer reserve space for the bar at the screen edge).

**Comment by cpiber** [comment]
Thank you. Could you also please point me how to then have i3 reserve some space? The margins don't seem to do anything

**Comment by patrick96** [comment]
https://github.com/polybar/polybar/wiki/Known-Issues#override-redirect-in-i3

**Comment by cpiber** [comment]
Thank you so much.
I currently use transparent borders, would it be possible to introduce "pseudo-margins" that work like that to allow one to have a border as well?

**Comment by patrick96** [comment]
I don't think we should introduce pseudo-margins just for i3. There are already workarounds for that issue, I would suggest you use i3-gaps where you can easily reserve space for polybar.
