### ISSUE TITLE
i3 & tray missing/black (respectively) if polybar starts before i3

### ISSUE THREAD

**Issue by OJFord** [polybar/polybar#2203]
I launch polybar via a user service:
```ini
# polybar@.service
[Unit]
Description=Polybar %I
After=default.target

[Service]
Environment=DISPLAY=:0
ExecStart=/usr/bin/polybar -r %i
Restart=always

[Install]
WantedBy=default.target
```

Every time I restart/login, polybar will not show the i3 module, and the system tray is a black rectangle, no visible icons.

Obviously I can't see it before i3 starts, but I assume this is because i3 is unavailable when it starts up, and it doesn't retry. I fix it by restarting polybar - `systemctl --user restart polybar@one`.

Logs:
```
polybar|error: Disabling module "i3" (reason: Could not find socket: <empty>)
polybar|error: Failed to reconfigure tray client, removing... (XCB_WINDOW (3))
```

**Comment by patrick96** [comment]
Polybar generally needs a window manager to work properly, not just the modules but also things like `wm-restack`. You shouldn't start it before your WM.

**Comment by OJFord** [comment]
OK, thanks. In case it's of help to anybody else in the future - I was already using a systemd service to check if X was ready (`Before=default.target`); I solved this by simply adding `&& i3 --get-socketpath` to that check.
