### ISSUE TITLE
Generic/Xmonad-specific window restacker

### ISSUE THREAD

**Issue by tjbrn** [polybar/polybar#2205]
I'm using xmonad as my wm.
In some use cases, starting polybar after xmonad put polybar above windows, even with the correct configuration on both programs (without xmonad ``avoidStruts`` hook).
In xmobar, the ``option lowerOnStart = True`` is used to fix this.

Solution: Add `lowerOnStart` options support to polybar, which, if set `true`, will start polybar on the bottom of window stack.

ArchLinux
polybar 3.4.3
Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

**Comment by patrick96** [comment]
Polybar has the `wm-restack` option to do this. However, it only supports bspwm and i3.

I think an xmonad specific restacker or a generic one that just lowers polybar to the bottom of the stack would be a good solution here.

If anyone wants to tackle this, the place to add this new restacker is the `bar::restack_window` function in `bar.cpp`

**Comment by mjkalyan** [comment]
In the mean time one could create a hacky solution using a tool like `xdo` to lower polybar after you start it:

```sh
xdo lower $(xwininfo -name <polybar instance name> | cut -sd '"' -f2)
```

Find the name of each polybar instance by running `xwininfo` with no args and clicking on it (in my case they are called `polybar-xmonad_HDMI-0` etc.)
Do this for each of your polybar instances.
