### ISSUE TITLE
Polybar not visible afther setting wm-restack = i3.

### ISSUE THREAD

**Issue by ErikEBZ** [polybar/polybar#2208]
## Describe the issue
*I want to make polybar hide when i'm in fullscreen *

**Expected behavior:**

*Polybar being visible and hiding when i enter in fullscreen (I'm using i3)*

**Actual behavior:**
So i set wm-restack = override-redirect = truei3 and the bar just shows black.
*What actually happens*
Here is what happens:
![Captura de pantalla de 2020-10-13 12-48-01](https://user-images.githubusercontent.com/36607582/95896747-60f3c580-0d52-11eb-91e1-b163082c1448.png)

**Was it working before?**
Yes, when i had only override-redirect = true and ;wm-restack = i3
* Did you also experience this bug in an earlier version of polybar?
I'm a new user of polybar.
* If no, what was the last version where this worked correctly?
Polybar 3.4.3-2 (AUR)
## To Reproduce
*A minimal but complete config with which the problem occurs:*
```
[bar/example]
 ;monitor = ${env:MONITOR:HDMI-1}
 width = 100%
 height = 20
 ;offset-x = 1%
 ;offset-y = 1%
 ;radius = 6.0
 fixed-center = false
 background = ${colors.background}
 foreground = ${colors.foreground}
 line-size = 3
 line-color = #f00
 border-size = 0
 border-color = #00000000
 padding-left = 0
 padding-right = 2
 module-margin-left = 1
 module-margin-right = 2
 font-0 = fixed:pixelsize=11;1
 font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
 font-2 = siji:pixelsize=11;1
 tray-position = right
 tray-padding = 2
 ;tray-background = #0063ff
;wm-restack = bspwm
 wm-restack = i3
 override-redirect = true
 scroll-up = i3wm-wsnext
 scroll-down = i3wm-wsprev

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
$ polybar example
notice: Parsing config file: /home/erikebz/.config/polybar/config
notice: Loaded font "fixed:pixelsize=11" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
notice: Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
notice: Loaded font "siji:pixelsize=11" (name=Siji, offset=1, file=/usr/share/fonts/misc/siji.bdf)

```
## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3
* Distro: Arch Linux
* Output of `polybar -vvv`:
polybar 3.4.0-120-g3895ace1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
## Additional context
*Well, i don't know if it as problem with my config file, so if its needed i can upload, hope you can help me fix this, thanks :)*

**Comment by patrick96** [comment]
That's not exactly what `wm-restack` does. It moves polybar down the window stack so that it is below *all* other windows (also non-fullscreen ones).
I also doubt that you want polybar to draw over your windows when not in fullscreen mode.

Please read [this](https://github.com/polybar/polybar/wiki/Known-Issues#override-redirect-in-i3) for how get space at the edge of the screen for your polybar. Alternatively you probably can also do `override-redirect = false` to get i3 to reserve space *and* for polybar to not appear above fullscreen windows.

**Comment by ErikEBZ** [comment]
Thanks, it really worked, this is how:
 I put this on my i3 config file:
bar {
         position top
         mode hide
         workspace_buttons no
}

And in polybar config:
wm-restack = i3
override-redirect = false

I write this in hope maybe it can help others, thanks :)
