### ISSUE TITLE
Module x-y position(s) for passing to scripts

### ISSUE THREAD

**Issue by OJFord** [polybar/polybar#2210]
## Is your feature request related to a problem? Please describe.
I have some pop-ups on click, and want them to appear just beneath the module that's been clicked.

The problem is that I have to manually determine the (typical) location, and hard-code that for each one. Then, it may move based on the dynamic size of other modules, and the pop-up is then incorrectly located.

## Why does polybar need this feature?
Help interactive modules with menus or extra information.

## Describe the solution you'd like
For me it'd be enough to have a single `self.x`/`self.y` attribute that refer to a corner of the module determined by whether the module is left/right, and in a bar that is top/bottom (so if the module is top-left on-screen, the  lower-left coordinate would be given).

```ini
[module/foo]
exec = sh -c 'popup -x ${self.x} -y $((${self.y} + 10))'
```

## Describe alternatives you've considered
A more generic solution would be to have say `self.upper_left.x`, `self.lower_left.y`, etc. and maybe easier to implement that (always provide everything) than do the work to determine which is most useful in polybar as above.

It'd also be nice if arithmetic could be done, so the above would instead be:
```ini
exec = popup -x ${self.x} -y ${self.y + 10}
```
(offset y further to have a gap between it and the bar) rather than invoking the shell just in order to do the addition.

**Comment by patrick96** [comment]
While this would be nice, there really is no way to do this in polybar. The point when we know the position of elements (when rendering) is way waaay after any kind of variable resolution is done. Also when rendering we don't even know anymore where modules start.

I think the better solution here is to use the x,y positions of your mouse to display the popup.

**Comment by OJFord** [comment]
I was hoping for a keyboard shortcut to open in the same place, so mouse wouldn't work, but I do understand, thanks for considering.
