### ISSUE TITLE
error in build process

### ISSUE THREAD

**Issue by jorget08** [polybar/polybar#2216]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*

mkdir build
cd build
cmake
make -j$(nproc)

**If you use some other way**
List exactly where you are building from and which version you are building.
Polybar 3.4.0 (tar) from the releases page

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*

mkdir build
cd build
cmake 
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- The CXX compiler identification is GNU 10.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could not detect version with git, falling back to built-in version information.
-- No build type specified; using Release
-- Using supported compiler GNU-10.2.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.16.0
-- Checking for module 'alsa'
--   Found alsa, version 1.2.3.2
-- Checking for module 'libcurl'
--   Found libcurl, version 7.72.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.19
-- Checking for module 'libnl-genl-3.0'
--   Found libnl-genl-3.0, version 3.4.0
-- Checking for module 'libpulse'
--   Found libpulse, version 13.0
-- Checking for module 'xcb-composite'
--   Found xcb-composite, version 1.14
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.14
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.14
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.14
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.0
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.1
--  Build:
--    Version: 3.4.0
--    Type: Release
--    CXX: /usr/bin/c++  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
--    LD: /usr/bin/ld  
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.2.3.2)
-- [X]   curl (7.72.0)
-- [X]   i3
-- [X]   mpd (2.19)
-- [X]   network (libnl) (3.4.0)
-- [X]   pulseaudio (13.0)
-- [X]   xkeyboard (1.14)
--  X extensions:
-- [X]   xcb-randr (1.14)
-- [X]   xcb-randr (monitor support) (1.14)
-- [X]   xcb-composite (1.14)
-- [X]   xcb-xkb (1.14)
-- [X]   xcb-xrm (1.0)
-- [X]   xcb-cursor (0.1.1)
--  Log options:
-- [X]   Trace logging
-- The C compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.14
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.18", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/x86_64-linux-gnu/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/x86_64-linux-gnu/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Searching for xcbgen with python2
-- Searching for xcbgen with python2.7
-- Searching for xcbgen with python3
-- Found xcbgen in /usr/lib/python3/dist-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- XCB[COMPOSITE]: Found component COMPOSITE
-- Found XCB_COMPOSITE: /usr/lib/x86_64-linux-gnu/libxcb-composite.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-composite.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-composite.so;/usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- xpp: including xcb proto composite.xml
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp>=1.7.7'
--   Requested 'jsoncpp >= 1.7.7' but version of jsoncpp is 1.7.4
You may find new versions of jsoncpp at https://github.com/open-source-parsers/jsoncpp
-- Could not find jsoncpp>=1.7.7 -- building static lib...
-- JsonCpp Version: 1.7.7
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.18", minimum required is "2.6") 
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/polybar/build

make -j$(nproc)
make[1]: se entra en el directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
[  1%] Generating ../../../lib/xpp/include/xpp/proto/randr.hpp
Scanning dependencies of target jsoncpp_lib_static
Scanning dependencies of target doc_man
[  2%] Generating ../../../lib/xpp/include/xpp/proto/xkb.hpp
Scanning dependencies of target polybar-msg
[  3%] Generating ../../../lib/xpp/include/xpp/proto/composite.hpp
Scanning dependencies of target doc_html
make[2]: se sale del directorio '/opt/polybar/build'
[  4%] Generating ../../../lib/xpp/include/xpp/proto/x.hpp
make[2]: se sale del directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
make[2]: se sale del directorio '/opt/polybar/build'
make[2]: se sale del directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
[  4%] sphinx-build html: see doc/builder-html.log
[  5%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
[  6%] sphinx-build man: see doc/builder-man.log
[  7%] Building CXX object bin/CMakeFiles/polybar-msg.dir/ipc.cpp.o
[  8%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/env.cpp.o
list: size, ['red', 'green', 'blue']
[  9%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o
list: size, ['red', 'green', 'blue']
[ 10%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/string.cpp.o
[ 11%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o
[ 12%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_writer.cpp.o
WARNING: html_static_path entry '/opt/polybar/doc/_static' does not exist
WARNING: html_static_path entry '/opt/polybar/doc/_static' does not exist
make[2]: se sale del directorio '/opt/polybar/build'
[ 12%] Built target doc_man
make[2]: se sale del directorio '/opt/polybar/build'
[ 12%] Built target doc_html
make[2]: se entra en el directorio '/opt/polybar/build'
Scanning dependencies of target doc
make[2]: se sale del directorio '/opt/polybar/build'
[ 12%] Built target doc
[ 13%] Linking CXX executable polybar-msg
make[2]: se sale del directorio '/opt/polybar/build'
[ 13%] Built target polybar-msg
[ 14%] Linking CXX static library libjsoncpp.a
make[2]: se sale del directorio '/opt/polybar/build'
[ 14%] Built target jsoncpp_lib_static
make[2]: se entra en el directorio '/opt/polybar/build'
Scanning dependencies of target i3ipc++
make[2]: se sale del directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
[ 15%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc-util.cpp.o
[ 16%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
Scanning dependencies of target xpp
make[2]: se sale del directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
[ 17%] Linking CXX static library libxpp.a
make[2]: se sale del directorio '/opt/polybar/build'
[ 17%] Built target xpp
[ 18%] Linking CXX static library libi3ipc++.a
make[2]: se sale del directorio '/opt/polybar/build'
[ 18%] Built target i3ipc++
make[2]: se entra en el directorio '/opt/polybar/build'
Scanning dependencies of target poly
make[2]: se sale del directorio '/opt/polybar/build'
make[2]: se entra en el directorio '/opt/polybar/build'
[ 20%] Building CXX object bin/CMakeFiles/poly.dir/adapters/alsa/mixer.cpp.o
[ 20%] Building CXX object bin/CMakeFiles/poly.dir/adapters/net.cpp.o
[ 21%] Building CXX object bin/CMakeFiles/poly.dir/adapters/alsa/control.cpp.o
[ 22%] Building CXX object bin/CMakeFiles/poly.dir/adapters/mpd.cpp.o
[ 24%] Building CXX object bin/CMakeFiles/poly.dir/cairo/utils.cpp.o
[ 24%] Building CXX object bin/CMakeFiles/poly.dir/adapters/pulseaudio.cpp.o
[ 26%] Building CXX object bin/CMakeFiles/poly.dir/components/bar.cpp.o
[ 26%] Building CXX object bin/CMakeFiles/poly.dir/adapters/net_nl.cpp.o
In file included from /opt/polybar/include/adapters/alsa/generic.hpp:47,
                 from /opt/polybar/src/adapters/alsa/mixer.cpp:3:
/opt/polybar/include/errors.hpp:12:12: error: ‘runtime_error’ has not been declared in ‘std’
   12 | using std::runtime_error;
      |            ^~~~~~~~~~~~~
/opt/polybar/include/errors.hpp:14:48: error: expected class-name before ‘{’ token
   14 | class application_error : public runtime_error {
      |                                                ^
/opt/polybar/include/errors.hpp: In constructor ‘polybar::application_error::application_error(const string&, int)’:
/opt/polybar/include/errors.hpp:16:69: error: class ‘polybar::application_error’ does not have any field named ‘runtime_error’
   16 |   explicit application_error(const string& message, int code = 0) : runtime_error(message), code(code) {}
      |                                                                     ^~~~~~~~~~~~~
In file included from /opt/polybar/include/adapters/pulseaudio.hpp:8,
                 from /opt/polybar/src/adapters/pulseaudio.cpp:1:
/opt/polybar/include/errors.hpp:12:12: error: ‘runtime_error’ has not been declared in ‘std’
   12 | using std::runtime_error;
      |            ^~~~~~~~~~~~~
/opt/polybar/include/errors.hpp:14:48: error: expected class-name before ‘{’ token
   14 | class application_error : public runtime_error {
      |                                                ^
/opt/polybar/include/errors.hpp: In constructor ‘polybar::application_error::application_error(const string&, int)’:
/opt/polybar/include/errors.hpp:16:69: error: class ‘polybar::application_error’ does not have any field named ‘runtime_error’
   16 |   explicit application_error(const string& message, int code = 0) : runtime_error(message), code(code) {}
      |                                                                     ^~~~~~~~~~~~~
In file included from /opt/polybar/include/adapters/mpd.hpp:9,
                 from /opt/polybar/src/adapters/mpd.cpp:6:
/opt/polybar/include/errors.hpp:12:12: error: ‘runtime_error’ has not been declared in ‘std’
   12 | using std::runtime_error;
      |            ^~~~~~~~~~~~~
/opt/polybar/include/errors.hpp:14:48: error: expected class-name before ‘{’ token
   14 | class application_error : public runtime_error {
      |                                                ^
/opt/polybar/include/errors.hpp: In constructor ‘polybar::application_error::application_error(const string&, int)’:
/opt/polybar/include/errors.hpp:16:69: error: class ‘polybar::application_error’ does not have any field named ‘runtime_error’
   16 |   explicit application_error(const string& message, int code = 0) : runtime_error(message), code(code) {}
      |                                                                     ^~~~~~~~~~~~~
make[2]: *** [bin/CMakeFiles/poly.dir/build.make:76: bin/CMakeFiles/poly.dir/adapters/alsa/mixer.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
In file included from /opt/polybar/include/adapters/net.hpp:11,
                 from /opt/polybar/src/adapters/net_nl.cpp:1:
/opt/polybar/include/errors.hpp:12:12: error: ‘runtime_error’ has not been declared in ‘std’
   12 | using std::runtime_error;
      |            ^~~~~~~~~~~~~
/opt/polybar/include/errors.hpp:14:48: error: expected class-name before ‘{’ token
   14 | class application_error : public runtime_error {
      |                                                ^
/opt/polybar/include/errors.hpp: In constructor ‘polybar::application_error::application_error(const string&, int)’:
/opt/polybar/include/errors.hpp:16:69: error: class ‘polybar::application_error’ does not have any field named ‘runtime_error’
   16 |   explicit application_error(const string& message, int code = 0) : runtime_error(message), code(code) {}
      |                                                                     ^~~~~~~~~~~~~
In file included from /opt/polybar/include/adapters/net.hpp:11,
                 from /opt/polybar/src/adapters/net.cpp:1:
/opt/polybar/include/errors.hpp:12:12: error: ‘runtime_error’ has not been declared in ‘std’
   12 | using std::runtime_error;
      |            ^~~~~~~~~~~~~
/opt/polybar/include/errors.hpp:14:48: error: expected class-name before ‘{’ token
   14 | class application_error : public runtime_error {
      |                                                ^
/opt/polybar/include/errors.hpp: In constructor ‘polybar::application_error::application_error(const string&, int)’:
/opt/polybar/include/errors.hpp:16:69: error: class ‘polybar::application_error’ does not have any field named ‘runtime_error’
   16 |   explicit application_error(const string& message, int code = 0) : runtime_error(message), code(code) {}
      |                                                                     ^~~~~~~~~~~~~
make[2]: *** [bin/CMakeFiles/poly.dir/build.make:128: bin/CMakeFiles/poly.dir/adapters/pulseaudio.cpp.o] Error 1
make[2]: *** [bin/CMakeFiles/poly.dir/build.make:115: bin/CMakeFiles/poly.dir/adapters/net_nl.cpp.o] Error 1
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::play()’:
/opt/polybar/src/adapters/mpd.cpp:249:45: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  249 |       m_log.err("mpdconnection.play: %s", e.what());
      |                                             ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::pause(bool)’:
/opt/polybar/src/adapters/mpd.cpp:260:46: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  260 |       m_log.err("mpdconnection.pause: %s", e.what());
      |                                              ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::toggle()’:
/opt/polybar/src/adapters/mpd.cpp:270:47: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  270 |       m_log.err("mpdconnection.toggle: %s", e.what());
      |                                               ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::stop()’:
/opt/polybar/src/adapters/mpd.cpp:280:45: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  280 |       m_log.err("mpdconnection.stop: %s", e.what());
      |                                             ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::prev()’:
/opt/polybar/src/adapters/mpd.cpp:290:45: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  290 |       m_log.err("mpdconnection.prev: %s", e.what());
      |                                             ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::next()’:
/opt/polybar/src/adapters/mpd.cpp:300:45: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  300 |       m_log.err("mpdconnection.next: %s", e.what());
      |                                             ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::seek(int, int)’:
/opt/polybar/src/adapters/mpd.cpp:310:45: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  310 |       m_log.err("mpdconnection.seek: %s", e.what());
      |                                             ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::set_repeat(bool)’:
/opt/polybar/src/adapters/mpd.cpp:321:51: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  321 |       m_log.err("mpdconnection.set_repeat: %s", e.what());
      |                                                   ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::set_random(bool)’:
/opt/polybar/src/adapters/mpd.cpp:332:51: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  332 |       m_log.err("mpdconnection.set_random: %s", e.what());
      |                                                   ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::set_single(bool)’:
/opt/polybar/src/adapters/mpd.cpp:343:51: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  343 |       m_log.err("mpdconnection.set_single: %s", e.what());
      |                                                   ^~~~
/opt/polybar/src/adapters/mpd.cpp: In member function ‘void polybar::mpd::mpdconnection::set_consume(bool)’:
/opt/polybar/src/adapters/mpd.cpp:354:52: error: ‘const class polybar::mpd::mpd_exception’ has no member named ‘what’
  354 |       m_log.err("mpdconnection.set_consume: %s", e.what());
      |                                                    ^~~~
make[2]: *** [bin/CMakeFiles/poly.dir/build.make:89: bin/CMakeFiles/poly.dir/adapters/mpd.cpp.o] Error 1
make[2]: *** [bin/CMakeFiles/poly.dir/build.make:102: bin/CMakeFiles/poly.dir/adapters/net.cpp.o] Error 1
        
make[2]: se sale del directorio '/opt/polybar/build'
make[1]: *** [CMakeFiles/Makefile2:891: bin/CMakeFiles/poly.dir/all] Error 2
make[1]: se sale del directorio '/opt/polybar/build'
make: *** [Makefile:130: all] Error 2

## Environment:
Parrot Security 4.10

**Comment by patrick96** [comment]
Polybar 3.4.0 no longer builds in gcc 10, please use the latest polybar version [3.4.3](https://github.com/polybar/polybar/releases/tag/3.4.3)
