### ISSUE TITLE
tray problem with QQ music running in deepin-wine5

### ISSUE THREAD

**Issue by akane-sora** [polybar/polybar#2222]
Hi, I noticed a problem about the tray.
Here is the way to reproduced:
Make the tray show in RIGHT,
lunch deepin-win5-qqmusic, which can be installed with https://aur.archlinux.org/packages/deepin.com.qq.qqmusic/
close the qq music, the tray show some white space, seems like there should be the icon of music, but it just the background color with nothing, also if the mouse moving to there, it also disappeared.
I have found moving the tray to left can solve the problem.

I want to know how dose the polybar implemented the tray system? Is it completely in polybar src without any 3rd part software needed?

I guessed the tray it-self is working fine, since in left it do can work with QQ music, just when it in right, things goes weird.

**Comment by akane-sora** [comment]
close since I found an alternative for wine-QQ-music

**Comment by shenweijiekdel** [comment]
my deepin-wine-wechat has same proplem
