### ISSUE TITLE
launching Steam through the menu module

### ISSUE THREAD

**Issue by sorin255** [polybar/polybar#2228]
## Describe the issue
I'm having various issues launching Steam through polybar's menu module. I've tried a few things, all with similar results.

**Expected behavior:**
I just expect Steam to be able to start with no issues.

**Actual behavior:**
There are three different things that I have attempted, with different lines in module/app-menu in polybar config:
`menu-4-2-exec = steam`

`menu-4-2-exec = steam-runtime`

`menu-4-2-exec = "~/steam-launch.sh -d" &`
this is an attempted workaround I thought I would try. Just a short bash script that looks like this:
```
#! /usr/bin/env bash

killall -p steam

steam
```
in all three cases polybar freezes until Steam is closed. App Menu doesn't toggle closed on its own nor when I click the toggle, workspaces module doesn't update with the created "Games" workspace (I can switch to it via alt+tab). Even trying to kill and relaunch polybar, the old polybar remains at the top of my screen until Steam is closed.

Once Steam is closed, I have to click on polybar to make it work again.

I want to add that with the exception of the third case, Steam doesn't launch at all if I have an ampersand appended to the end as per the suggested module format in the wiki

**Was it working before?**
I didn't install Steam until after I had i3 + polybar set up and configured.

## To Reproduce
In case it matters, under my i3 config I have:
```
# alt+tab to switch workspaces
bindsym Mod1+Tab workspace next
bindsym Mod1+Shift+Tab worskpace prev

# assign steam to games
assign [class="(?i)steam"] Games
```

basic polybar config:
```
[bar/bar1]
modules-left = menu-apps i3

[module/i3]
type = internal/i3

enable-click = true

enable-scroll = false

ws-icon-0 = Games
ws-icon-default = ♟

[module/menu-apps]
type=custom/menu
expand-right = true

format = <label-toggle><menu>

label-open = apps
label-close = x
label-separator = |

menu-0-0 = Games
menu-0-0-exec = menu-open-1
menu-1-0 = Steam
menu-1-0-exec = steam
```

## Polybar Log
This is literally the only output from Polybar when run in terminal, from start to shutdown. Nothing about Steam in it:
```
warn: No monitor specified, using "DP-0"
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
warn: Termination signal received, shutting down...
warn: module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)

```
Checking /tmp/polybar1.log isn't much different, just some additional dialogue relating to module/i3 after shutdown

## Environment:
* WM: i3wm
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 

```

**Comment by patrick96** [comment]
Can you try the following:

```dosini
menu-4-2-exec = steam >/dev/null 2>&1 &
```

I think you may be suffering from the same issue as #916

**Comment by sorin255** [comment]
Adding the command you suggested seemed to help, no longer getting the problem.

**Comment by sorin255** [comment]
Adding the command you suggested helped, am no longer having issues launching Steam through polybar.
