### ISSUE TITLE
Click format doesn't work in Awesome WM

### ISSUE THREAD

**Issue by RossComputerGuy** [polybar/polybar#2229]
## Describe the issue
When using the `%{A}` format tag, it won't work under Xephyr (an Xserver).

**Expected behavior:**
The click format tag should run the command that its set to

**Actual behavior:**
Nothing happens, no log output

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?: yes
* If no, what was the last version where this worked correctly?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/top]
monitor=
monitor-fallback=
monitor-strict=false
monitor-exact=false
fixed-center=true
width=100%
height=35px
background=#24283b
foreground=#a9b1d6
modules-left=menu
font-0=DejaVuSansMono Nerd Font Mono:size=10

[module/menu]
type=internal/xwindow
label = %{A1:jgmenu:}%title%%{A}
label-empty=ExpidusOS

; vim:ft=dosini:
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: No monitor specified, using "default"
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: AwesomeWM
* Distro: Void Linux/ExpidusOS
* Output of `polybar -vvv`: 
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/lib/ccache/bin/g++
Compiler flags: -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -Wno-error=deprecated-declarations -g -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
```

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by RossComputerGuy** [comment]
Further research of this issue leads to it being an issue between Polybar and Awesome WM

**Comment by patrick96** [comment]
Why do you believe this is something specific to awesomewm?

I think you are experiencing a known bug: https://github.com/polybar/polybar/wiki/Known-Issues#click-commands-are-not-executed

The problem there was that any click command that produces output to stderr or stdout will die as soon as it produces output. This is already fixed and will appear in 3.5.0, but the latest release still has this issue.

If that is indeed the issue, the solution would be the following:

```dosini
label = %{A1:jgmenu >/dev/null 2>&1:}%title%%{A}
```

Please confirm whether this works for you.

**Comment by RossComputerGuy** [comment]
Because I also found out that "click-right" and scrolling on the pulseaudio module doesn't work in Awesome but works in i3.

-------- Original Message --------

**Comment by patrick96** [comment]
Hmm, so `click-right` isn't available for the pulseaudio module in version 3.4.3, but scrolling certainly is (though it doesn't execute a shell command).

Do any other mouse interactions work in awesome? If not, I am guessing something is blocking polybar from receiving mouse events.

**Comment by RossComputerGuy** [comment]
Yes but not on Polybar. I can only focus the window.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by patrick96** [comment]
Is there anything blocking polybar (maybe an invisible window on top of polybar)?

You could try running `xprop` and then clicking on your bar, it should print information about the window you have clicked.

**Comment by RossComputerGuy** [comment]
Only windows are root and polybar. Only running X11 programs for it is: polybar, picom, and AwesomeWM.

**Comment by RossComputerGuy** [comment]
```
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
awful.client.property.single_instance_id(UTF8_STRING) =
_NET_WM_PID(CARDINAL) = 10758
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
WM_CLASS(STRING) = "polybar", "Polybar"
WM_NAME(STRING) = "ExpidusOS"
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 25, 0, 0, 0, 0, 0, 0, 639, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 25, 0
```
These are the properties.

**Comment by patrick96** [comment]
Alright, I was able to reproduce this. It seems once you click on polybar for the first time, awesomeWM selects it and stops delivering click events to it (I don't know why).

The solution is to set `override-redirect = true` in your bar section to tell AwesomeWM to not manage the polybar window.

**Comment by RossComputerGuy** [comment]
Interesting, maybe it will be good to add AwesomeWM not sending events to the known issues page on the wiki.

**Comment by patrick96** [comment]
[Done](https://github.com/polybar/polybar/wiki/Known-Issues#mouse-interactions-not-working-in-awesomewm)
