### ISSUE TITLE
Firma de python

### ISSUE THREAD

**Issue by ErickMorales3434** [polybar/polybar#2230]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*

El archivo /var/cache/pacman/pkg/python-pytz-2020.1-2-any.pkg.tar.zst está dañado (paquete no válido o dañado (firma PGP)).

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:

**If you use some other way (like the AUR):**

*List exactly where you are building from and which version you are building.*

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```

```

## Environment:
* Distro (with Version):

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment]
Your python package is corrupted, this has nothing to do with polybar.

https://wiki.archlinux.org/index.php/Pacman#Troubleshooting

**Comment by ErickMorales3434** [comment]
Tanks
