### ISSUE TITLE
Polybar overall problem with fonts 

### ISSUE THREAD

**Issue by Beheavyon** [polybar/polybar#2233]
Hello.
The issue is form begining i never got it to render ttf fonts properly. Bitmaps fonts are wroking, but they aren't scalable.
I tried:
* diffrent fonts (roboto, ubuntu, many more..)
* clean reinstall 
* turning antialiasing off and no 

I use terminator as terminal emulator with same Hack 10 font. I also have dual monitor setup if that changes anything 2x 1920x1080 but polybar is working same badly on both.

![polybar](https://user-images.githubusercontent.com/34106820/97804566-0b278480-1c51-11eb-971c-910a261da458.png)

* WM: BSPWM
* Distro: Arch Linux 
* Output of `polybar -vvv`: 
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by patrick96** [comment]
This does look a lot like an anti-aliasing issue. Please show us how you defined the fonts in the polybar config, as well as how you turned anti-aliasing on/off.

**Comment by Beheavyon** [comment]
`font-0 = "Hack:style=Regular:pixelsize=10:antialias=false3;2"`

This is how i turned antyaliasing off. It strange other apps dont have any problems. Yesterday i did a clean install and still same effect no change. With antialias on the font is very blury.

**Comment by Beheavyon** [comment]
```
dpi-x=96
dpi-y=96
```
ok i think i fixed it adding thins to [bar/mybar] section
