### ISSUE TITLE
Tray doesn't use icon color from gtk theme

### ISSUE THREAD

**Issue by IkorJefocur** [polybar/polybar#2235]
## Describe the issue

I using dark background on polybar, and dark gtk-3 theme that sets all symbolic icons color to white. Also i using icon theme with light symbolic icons by default, but as fallback (if needed icon not found) it using "hicolor" icon theme with default dark icons. On polybar tray i see all that icons in they default color. 

**Expected behavior:**

I expected that polybar will take into account gtk theme and change icons color according to it. For example gnome and cinnamon are doing that for they own status bars. Really it's not so important to polybar get color from gtk-3 theme (but it will be perfect variant), i just need a way to change icon color.

**Actual behavior:**

Polybar just don't changing color for symbolic icons in tray. So icons that my main theme includes are white, other icons are black.

## To Reproduce

It happens even with default polybar config. No matter what background or foreground color i set or what is my current gtk-3 theme.

## Polybar Log

I removed all custom scripts and leaved only basic modules, and got this log on start:
```
polybar|warn:  pulseaudio: using default sink alsa_output.pci-0000_00_05.0.iec958-stereo
polybar|error: tray: Failed to put tray above 0x1000001 in the stack (XCB_MATCH (8))
```
Second error appears only when i (re)start i3 with polybar.

## Screenshots
![изображение](https://user-images.githubusercontent.com/48279182/97882666-ec022300-1d34-11eb-99ac-cc5ecf037688.png)

## Environment:
* WM: I3
* Distro: Linux mint 20
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/c++
Compiler flags: -g -O2 -fdebug-prefix-map=/build/polybar-udaYph/polybar-3.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now
```

**Comment by patrick96** [comment]
Polybar isn't really responsible for rendering the individual tray icons, this is done by the application that provides the tray icon.

So I would guess this isn't specific to polybar. Does this also happen for other applications that have a system tray (i3bar, stalonetray, tint2)?

Also, does this happen when you start polybar from the terminal instead of during i3 startup?

**Comment by IkorJefocur** [comment]
> Polybar isn't really responsible for rendering the individual tray icons, this is done by the application that provides the tray icon.

Of course polybar don't have to choose icon for application, that what icon theme and application itself does. But i think that it can change icon color.

> Does this also happen for other applications that have a system tray (i3bar, stalonetray, tint2)?

For example, in i3bar i can set [statusline color](https://i3wm.org/docs/userguide.html#_colors):
```
bar {
	status_command i3status
	colors {
		statusline "#aaaaaa"
	}
}
```
And this will affect tray icons color:
![изображение](https://user-images.githubusercontent.com/48279182/97964046-2d441280-1dc9-11eb-9c77-4237472fbcbc.png)

I forgot to mention that only "hicolor" icon theme supports changing color for symbolic icons, when my main icon theme ("korla") doesn't. And the only icon in screenshot from "hicolor" is "mintupdate" (third). As you can see, it's color same as "statusline" in i3 config. So i expected that polybar have similar color setting as i3bar, or will inherit that color from gtk like cinnamon or gnome bars does.

> Also, does this happen when you start polybar from the terminal instead of during i3 startup?

No matter how i launch polybar. Only difference between launch with i3 or singly, that's string in log what i considered it important:
```
polybar|error: tray: Failed to put tray above 0x1000001 in the stack (XCB_MATCH (8))
```

**Comment by patrick96** [comment]
I just looked through the code and where i3bar is using the `statusline` color, we basically do the same thing but with the `tray-background` color.

Can you try changing the `tray-background` color to see whether this affect the icon color?
This will also change the actual background of the tray, but if it works I think we should introduce `tray-foreground` for this.

Just for me for future reference: `_NET_SYSTEM_TRAY_COLORS` is a non-standard atom and seems to be exclusive to gtk: https://bugzilla.gnome.org/show_bug.cgi?id=679591

**Comment by IkorJefocur** [comment]
I wrote this in bar config:
```
tray-background = #333333
```
But icon color didn't changed. It's still black:
![изображение](https://user-images.githubusercontent.com/48279182/97983154-e6184a80-1de5-11eb-9af9-c1942560b899.png)

**Comment by OmarAmell** [comment]
@IkorJefocur could you solve the problem?

**Comment by IkorJefocur** [comment]
@OmarAmell , No. I just reported problem.

**Comment by mid-kid** [comment]
Same issue, can't get icons to become white no matter how hard I try.

**Comment by jfly** [comment]
> I just looked through the code and where i3bar is using the statusline color, we basically do the same thing but with the tray-background color.

@patrick96, I read through the i3bar code, and you're right, but i3bar colors the tray background with a *different* color (the [`background` settings, not `statusline`](https://github.com/i3/i3/blob/43e805a00d1835db4fc0730ce5003956824b350d/i3bar/src/config.c#L234)). That's really important: i3bar ends up using a different color for the background vs the foreground, whereas polybar uses the same color, which ends up making the icon impossible to see. (Also, i3bar bit shifts the color values differently, it ends up [maxing the colors out at 0xffff](https://github.com/i3/i3/blob/43e805a00d1835db4fc0730ce5003956824b350d/i3bar/src/xcb.c#L1503-L1505), whereas polybar maxes out at 0xff.

> This will also change the actual background of the tray, but if it works I think we should introduce tray-foreground for this.

This does work and affects the icon colors, but is hard to tell because it also changes the background color, so the icons are still invisible. I've introduced the `tray-foreground` setting you mentioned over here: https://github.com/polybar/polybar/pull/2552/

**Comment by mid-kid** [comment]
@jfly Just built and tested this, and it seems to work perfectly for fcitx and xfce4-power-manager, but, for some reason, it doesn't work for wpa_gui. Granted, that's a very weird Qt app in the way it handles its icon, but I wonder if this was tested for symbolic icons under Qt applications.

**Comment by patrick96** [comment]
We use `_NET_SYSTEM_TRAY_COLORS` to set the tray foreground. This is a gtk3-specific atom and likely won't work with/affect any other applications.

I don't think there is even a way in the system tray standard to set an icon's foreground color.

**Comment by mid-kid** [comment]
Honestly wish I could disable symbolic icons as a whole, but apps seem keen on using them...

**Comment by jfly** [comment]
@patrick96: I'm very new to all this. I don't understand what the difference is/should be between the "tray foreground" and an "icon's foreground". In my mind, they're the same thing. With my change, polybar draws a background of a particular color, and then uses this `_NET_SYSTEM_TRAY_COLORS` hint to tell gtk applicantions to draw their icons using a particular color.

@mid-kid eep! I didn't even think about Qt applications, but I'm not surprised this has no effect on them. Perhaps Qt provides its own way of hinting to applications that they should draw symbolic icons in a particular color?

**Comment by patrick96** [comment]
> In my mind, they're the same thing.

They should be. The tray doesn't really have a "foreground", it doesn't have any text. Most icons are multicolored as well so they also don't really have a foreground. Maybe just using the term "foreground" makes things a bit confusing. Once the update comes out, we should also probably clarify this in the documentation that `tray-foreground` really only is a hint to gtk applications (I'm assuming to figure out whether to show the light or dark version of an icon).

I don't know of any Qt specific ways to hint at the tray icon color, but I also couldn't really find anything about symbolic icons.

@mid-kid Is it possible that your Qt theme is a light theme where the icons are darker?

**Comment by mid-kid** [comment]
To quote the specifics of my Qt setup, I'm using QT_QPA_PLATFORMTHEME=qt5ct, which is configured to use the kvantum style, with the Adwaita icon theme. The app I'm using specifically is wpa_gui, I'm not really aware of any other Qt apps using symbolic icons... The icon is being set by [QIcon::fromTheme()](https://w1.fi/cgit/hostap/tree/wpa_supplicant/wpa_gui-qt4/wpagui.cpp#n1518).

**Comment by jfly** [comment]
> Once the update comes out, we should also probably clarify this in the documentation that tray-foreground really only is a hint to gtk applications

Sounds good! I'll follow up after the next release to make sure that happens.

> (I'm assuming to figure out whether to show the light or dark version of an icon).

It's actually quite a bit fancier than that! Gtk is able to recolor symbolic images according to some [hard-to-find-documented rules](https://askubuntu.com/a/154846).

**Comment by jfly** [comment]
My reminder to check in on the documentation just fired. Looks like a new version of polybar hasn't been released yet, though? @patrick96, any idea when that'll happen?

**Comment by patrick96** [comment]
No, not yet sorry. I'm really busy atm and there are some things that I need/want to do for 3.6

**Comment by jfly** [comment]
@patrick96, looks like you (or somebody else) already updated the docs? https://github.com/polybar/polybar/wiki/Configuration seems to have a pretty good explanation about the `tray-foreground` setting.

**Comment by patrick96** [comment]
Yes, that was me. Thanks for the review :)
