### ISSUE TITLE
bspwm: Desktops whose names contain colon are parsed incorrectly, with warnings issued

### ISSUE THREAD

**Issue by RuijieYu** [polybar/polybar#2242]
## Describe the issue

All my desktops are currently named as such: `1:Term`, `2:Browse` and so on. They are not parsed / displayed correctly.

**Actual behavior:**

Lots of warnings of the following are issued:
```text
polybar|warn:  module/bspwm: Undefined T => 'erm'
polybar|warn:  module/bspwm: Undefined tag => 'B'
...
```
And the full names of the desktops are not displayed; only the numbers 1, 2, ... are shown.

When run with an alternative format `1[Term]`, `2[Browse]`, no similar warnings are issued and the entire string is shown on the bar.

**Expected behavior:**

The entire name of each desktop is shown on the bar, and no warnings should be issued against it. 

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?

(First time user, no past experience with polybar)

## To Reproduce

```dosini
;polybar minimal config
[bar/small]
modules-left = bspwm
[module/bspwm]
type = internal/bspwm
label-empty =
label-focused = %name%
label-occupied = %name%
label-urgent = %name%
label-separator = " "
label-separator-padding = 1
```

```bash
#!/usr/bin/env bash
# bspwm config
bspc monitor -d '1[a]' '2[b]' '3[c]' '4[d]' '5[e]' '11[j]' # this format is working fine with polybar
#bspc monitor -d '1:a' '2:b' '3:c' '4:d' '5:e' '11:j' # this format does not work fine with polybar
```

**Steps to Reproduce**

* In bspwm, run polybar
    * make sure it is functional (has expected behavior)
    * and make sure no "undefined xxx" warning is issued
* Run the following command (to rename desktops without relaunching bspwm)
    * `bspc monitor '1:a' '2:b' '3:c' '4:d' '5:e' '11:j'`
    * observe that only indices are displayed (1, 2, 3, 4, 5, 11)
    * and that warnings are issued

## Polybar Log

(Empty stdout; the following is stderr)

```
polybar|warn:  No fonts specified, using fallback font "fixed"
polybar|warn:  module/bspwm: Undefined tag => 'a'
polybar|warn:  module/bspwm: Undefined tag => 'a'
polybar|warn:  module/bspwm: Undefined tag => 'b'
polybar|warn:  module/bspwm: Undefined tag => 'a'
polybar|warn:  module/bspwm: Undefined tag => 'b'
polybar|warn:  module/bspwm: Undefined tag => 'c'
polybar|warn:  module/bspwm: Undefined tag => 'a'
polybar|warn:  module/bspwm: Undefined tag => 'b'
polybar|warn:  module/bspwm: Undefined tag => 'c'
polybar|warn:  module/bspwm: Undefined tag => 'd'
polybar|warn:  module/bspwm: Undefined tag => 'a'
polybar|warn:  module/bspwm: Undefined tag => 'b'
polybar|warn:  module/bspwm: Undefined tag => 'c'
polybar|warn:  module/bspwm: Undefined tag => 'd'
polybar|warn:  module/bspwm: Undefined tag => 'e'
polybar|warn:  module/bspwm: Undefined tag => 'a'
polybar|warn:  module/bspwm: Undefined tag => 'b'
polybar|warn:  module/bspwm: Undefined tag => 'c'
polybar|warn:  module/bspwm: Undefined tag => 'd'
polybar|warn:  module/bspwm: Undefined tag => 'e'
polybar|warn:  module/bspwm: Undefined tag => 'j'
```

## Environment:
* WM: bspwm
* Distro: Arch Linux (kernel 5.9)
* Output of `polybar -vvv`:
```text
polybar 3.4.3
Features: +alsa +curl +i3 +mpd +network(libn1) +pulseaudio +xkeyboard
X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor
Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86_64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -W1,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
There is unfortunately not really much that we can do about that. The way polybar gets workspace information for bspwm is from a string that looks like this:

```
WMdefault:FI:fII:fIII:fIV:fV:fVI:fVII:fVIII:fIX:fX:LT
```

Here my workspaces are named with roman numerals. This uses colons to separate the different fields of the message with the first character of each field defining what the field does. For example everything starting with `f` describes an unfocused desktop.
With your example, this string looks like this:

```
WMdefault:F1:a:f2:b:f3:c:f4:d:f5:e:f11:j:LT
```

Now it is impossible to tell whether `f5:e` represents a workspace named `5:e` or whether the workspace is named `5` and `e` is just the start of a new field. Because of this, it's impossible for polybar to support colons in bspwm workspace names.
