### ISSUE TITLE
error: cairo_scaled_font_create(): file not found

### ISSUE THREAD

**Issue by Ultracoolguy** [polybar/polybar#2244]
I wish I could say more about this error. This is after a clean install of Artix.

The output of polybar -l trace top: https://dpaste.org/WQAN

**Comment by patrick96** [comment]
Does the file `/usr/share/fonts/TTF/Inconsolata-Regular.ttf` exist on your system? Also what is the output of `fc-match "/usr/share/fonts/TTF/Inconsolata-Regular.ttf"`?

**Comment by Ultracoolguy** [comment]
@patrick96:
>Does the file `/usr/share/fonts/TTF/Inconsolata-Regular.ttf` exist on your system? 

Yes

>Also what is the output of `fc-match "/usr/share/fonts/TTF/Inconsolata-Regular.ttf"`?

Weirdly:

```
NimbusSans-Regular.otf: "Nimbus Sans" "Regular"
```

**Comment by patrick96** [comment]
Oh sorry, I copied the wrong thing. I wanted to know the output of `fc-match "Inconsolata:size=10"`

Please also run polybar prefixed with `FC_DEBUG=1` (`FC_DEBUG=1 polybar ...`) and post the output of that.

**Comment by Ultracoolguy** [comment]
>Oh sorry, I copied the wrong thing. I wanted to know the output of `fc-match "Inconsolata:size=10"`

```
Inconsolata-Regular.ttf: "Inconsolata" "Regular"
```



> Please also run polybar prefixed with `FC_DEBUG=1` (`FC_DEBUG=1 polybar ...`) and post the output of that.

https://dpaste.org/SnKA

**Comment by patrick96** [comment]
Hmm, this is quite strange. Does the file `/home/me/.local/share/fonts/weathericons-regular-webfont.ttf` exist?

**Comment by patrick96** [comment]
Please also post your config, I just noticed that the issue isn't inconsolata but probably your second font.

**Comment by Ultracoolguy** [comment]
> Hmm, this is quite strange. Does the file `/home/me/.local/share/fonts/weathericons-regular-webfont.ttf` exist?

Yes, but actually no. There's a broken symbolic link due to some reasons I can't explain. I guess that's the issue, lemme check.

**Comment by Ultracoolguy** [comment]
Yes it works now! Sorry for the trouble!

**Comment by patrick96** [comment]
No worries. It's weird that it can match the font to the file, but then cairo fails when loading the file. Maybe some cache issue.
