### ISSUE TITLE
Problem with polybar in i3 (Double polybar)

### ISSUE THREAD

**Issue by Nevers0ft666** [polybar/polybar#2250]
I'm having an issue with my polybar, for some reason is showing two bars at the same time.

Here are the logs:
warn: No monitor specified, using "HDMI-0"
warn: No monitor specified, using "HDMI-0"
:: Launching secondary bars on HDMI-0...
error: Disabling module "volume" (reason: Cannot find simple element)
warn: X resource "color1" not found, using defined fallback value "#a54242"
error: Disabling module "wifi" (reason: Environment var ${IF_WIFI} does not exist (no fallback set))
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color3" not found, using defined fallback value "#de935f"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color3" not found, using defined fallback value "#de935f"
warn: X resource "color3" not found, using defined fallback value "#de935f"
warn: X resource "color3" not found, using defined fallback value "#de935f"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
error: Disabling module "battery" (reason: No suitable way to get current charge state)
error: tray: Failed to put tray above 0x4200002 in the stack (XCB_MATCH (8))
error: Disabling module "volume" (reason: Cannot find simple element)
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color3" not found, using defined fallback value "#de935f"
warn: X resource "color3" not found, using defined fallback value "#de935f"
warn: X resource "color3" not found, using defined fallback value "#de935f"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
warn: X resource "color1" not found, using defined fallback value "#a54242"
error: Disabling module "battery" (reason: No suitable way to get current charge state)

By the way, i will leave an image of the issue (For some reason github is no letting my upload pictures lol.)
https://imgur.com/a/kw4p4In

**Comment by patrick96** [comment]
The issue tracker is meant for bug reports and feature requests. Please don't ask support questions here, read our [Support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) for a list of resources where you can ask questions. We are more than happy to help you there.
