### ISSUE TITLE
Multiple Ramp Capacities

### ISSUE THREAD

**Issue by vinicius507** [polybar/polybar#2254]
## Is your feature request related to a problem? Please describe.
I'm using only icons in my polybar config. I'd like to be able to use different ramp-capacities when charging instead of animation-charging. In a way that it could show the current battery status without animation.

## Why does polybar need this feature?
I think it would be helpful for those with minimal configs who dislike animations in the bar.

## Describe the solution you'd like
I'd like to be able to set `ramp-capacity` and `ramp-capacity-charging`. So I could use one set of icons for charging and another for discharging.

## Describe alternatives you've considered
I've considered using a custom script module to set it, but I think it would be great to have this option by default.

**Comment by patrick96** [comment]
This will be possible, once we implement #1752

**Comment by vinicius507** [comment]
Awesome!
