### ISSUE TITLE
Missing parameter (type) for include directory modules

### ISSUE THREAD

**Issue by weilbith** [polybar/polybar#2258]
## Checklist

* [x] I have read the appropriate section in the [contributing  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
I before used the AUR `polybar-git` package to get the `include-directory` feature. Everything worked. Now I saw the release and switched to the "plain" `polybar` package which is on version `3.4.3`.
No I get for each module that gets defined in a file sourced via the `include-directory` configuration an error that states `error: Disabling module "network" (reason: Missing parameter "module/network.type")`. It is always the same, just the name of the module changes. The modules definitely have a `type` specified. If I temporally move the module declaration into the main config file, this module works again.

**Expected behavior:**
Modules from included directories just work.

**Actual behavior:**
All modules fail due to a ostensible missing type parameter.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)? **no**
* If no, what was the last version where this worked correctly? unfortunately I don't know in exact. It was the `polybar-git` AUR package.

## To Reproduce

```dosini
[global/wm]
include-directory = ~/.config/polybar/modules

[bar/top]
modules-left = network
```

`~/.config/polybar/modules/network.ini`:
```dosini
[module/network]
inherit = layout
type = internal/network
interface = wlp4s0

label-connected = %essid%
label-connected-maxlen = 25
label-connected-ellipsis = true
format-connected = 直  <label-connected>
format-disconnected = 睊
```

## Polybar Log

```
warn: No monitor specified, using "HDMI-2"
error: Disabling module "network" (reason: Missing parameter "module/network.type")
error: No modules created

```

## Environment:
* WM: i3wm
* Distro: ArchLinux
* Output of `polybar -vvv`: 

```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
`include-directory` has not been released yet. The release PR #2253 has not been merged yet.

I plan to publish the 3.5.0 release tomorrow.

**Comment by weilbith** [comment]
Oh I'm sorry. I think I mixed the release with the notes you have prepared in the PR. Sorry for wasting your time. Looking forward to update soon.
