### ISSUE TITLE
Regression on module battery

### ISSUE THREAD

**Issue by AlecsFerra** [polybar/polybar#2262]
## Checklist

* [X] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
The battery module doesn't work in the new git release 

**Expected behavior:**
Polybar should show the battery module

**Actual behavior:**
Polybar gives an error an disables the module (probably only on low battery levels)

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)? yes, in the non git package is still working

## To Reproduce

```dosini

[module/battery-test]
type = internal/battery
battery = ${config.battery-bat}
adapter = ${config.battery-adp}

[bar/debug]
modules-left = battery-test
```

## Polybar Log

```
❯ polybar debug
notice: Parsing config file: /home/alecs/.config/polybar/config
error: Disabling module "battery-test" (reason: format-low)
error: No modules created
```

## Environment:
* WM: XMonad
* Distro: ArchLinux
* Output of `polybar -vvv`:

```
polybar 3.5.0-8-gd6ce8c9a

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/sbin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by fiskhest** [comment]
I added `format-low = ${color.RED}` to my config and it's working again. Looking at documentation for the [battery module](https://github.com/polybar/polybar/wiki/Module:-battery) and the latest change to the [source file](https://github.com/polybar/polybar/blob/39c73a82347d3a269f9d554a3d66fe2ea3d3acff/src/modules/battery.cpp), it seems as if someone might've forgotten to document this change in the new release?

**Comment by patrick96** [comment]
@AlecsFerra thanks for the report. Can you test if #2263 fixes this?

@fiskhest This change is not part of the new release, the new warn formats introduced in #2199 are not yet released, I didn't have time yet to add the functionality to the wiki.
