### ISSUE TITLE
XWorkspaces module not show corretly

### ISSUE THREAD

**Issue by og900aero** [polybar/polybar#2268]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
I use xworkspaces module (same as bspwm) and show lable correctly when boot computer, but I open anything, and change the workspaces, then the workspaces label move ot of place, slides out of place (maybe change automtically padding or similar) with polybar 3.5.0.

**Was it working before?**
Working 3.4.3, and uninstall 3.5.0, and install 3.4.3 then working again correctly.

## Polybar Log
Nothing error show

## Screenshots
Left top of screen show xworkspaces

## Environment:
* WM: Bspwm
* Distro: Arch Linux (pure)
![screenshot](https://user-images.githubusercontent.com/49487376/101135604-53e5ab00-360c-11eb-8548-9dbd96d408eb.jpg)

* Output of `polybar -vvv`:

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

**Comment by og900aero** [comment]
Letter spacing wrong

**Comment by patrick96** [comment]
Can you post your config for the xworkspaces module. I don't really see what is going wrong here.

**Comment by og900aero** [comment]
Hello,

My global settings:

[global/wm]
margin-top = 0
margin-bottom = 0

[settings]
screenchange-reload = false
pseudo-transparency = false

And the ewmh settings:

[module/ewmh]
type = internal/xworkspaces

enable-click = true
enable-scroll = false
format-padding = 0

format = <label-state>

label-active = %name%
label-active-foreground = ${colors.background}
label-active-background = #c93648
label-active-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 2

Patrick Ziegler <notifications@github.com> ezt írta (időpont: 2020. dec.
4., P, 23:22):

**Comment by patrick96** [comment]
I think I see the issue. The xworkspaces module now properly supports `label-occupied` for non-empty non-active workspaces. Since you didn't define `label-occupied`, it uses the default value, which is `%icon% %name%` and since `%icon%` is empty, you have an extra space there.

**Comment by og900aero** [comment]
I inserted the following setting:

label-occupied = %name%

but the problem not solved. See the attachment. 1 workspace contains 2
programs, 2 workspace contains 1 program, 3-4-5 doesnt contains programs.

Patrick Ziegler <notifications@github.com> ezt írta (időpont: 2020. dec.
5., Szo, 14:13):

**Comment by og900aero** [comment]
Sorry! You were right. The correct one is as follows:

label-occupied = %name%
label-occupied-padding = 2

Problem is solved. Thank u so much! :)

Viktor

Viktor <og900aero@gmail.com> ezt írta (időpont: 2020. dec. 5., Szo, 16:33):
