### ISSUE TITLE
Better packaging practices

### ISSUE THREAD

**Issue by vaygr** [polybar/polybar#2276]
## Is your feature request related to a problem? Please describe.

Not really a problem, but a couple of nice-to-have things which I think make sense:

1. Full tarball gzipped and/or xzipped version. For saving space purposes? GitHub offers zip & gzip for tags by default at `https://github.com/polybar/polybar/archive/<version>.*`, but the full tarball, which is at `https://github.com/polybar/polybar/releases/download/<version>/polybar-<version>.tar` is plain tar, which can be compressed quite efficiently.

2. Source directory this tarball unpacks into should be `polybar-<version>` instead of plain `polybar`. This is good for clarity, but also from practical standpoint could be important for source-based distros, which unpack sources to e.g. `/usr/src`. The thing is, when package sources of another version get unpacked to `/usr/src/package` and the build fails for some reason, without additional safety checks (which I'm sure all distros have) the new version would unpack in the same dir, overwriting some files and resulting into a mixed source directory (GitHub does that for tags by default as well).

**Comment by patrick96** [comment]
Version 3.5.0 now has a `.tar.gz` release archive as well. All future releases will only have a `.tar.gz` release archive.
