### ISSUE TITLE
Detect alsa mixer source change

### ISSUE THREAD

**Issue by benchislett** [polybar/polybar#2281]
## Is your feature request related to a problem? Please describe.

I automatically start up polybar in my xconfig. It detects the default alsa mixer as master as it should, and displays the audio settings.
When I then connect my bluetooth headphones, polybar is stuck in a limbo where the alsa commands it sends are being received, but it is displaying the data for the wrong audio setting. It would be nice to have some listener for when the alsa audio source changes, or even just some way for me to reload it without having to make a trivial change to my config just to get it to reload

## Why does polybar need this feature?

It would be a huge plus to all alsa users if polybar could automatically detect a change in source and update accordingly.

## Additional context

I'm a bit of a noob. I don't know much about alsa or polybar; this may already exist, may be easy to do, or may be quite hard. In any case, please let me know

**Comment by Morantxu** [comment]
Same issue here

**Comment by TheBabu** [comment]
I actually had the same problem, and I already had this issue resolved.

This was my issue:
https://github.com/polybar/polybar/issues/693

But these are some updated ones:
https://github.com/polybar/polybar/issues/1086

https://github.com/polybar/polybar/issues/1167

**Comment by TheBabu** [comment]
I still used the old solution as previously stated, here is a snippet of what I have:

```
[module/pavolume]
type = custom/script
tail = true
interval = 2
label = %output%
exec = ~/.bin/polybar-pavolume --listen 2>/dev/null 
click-left = ~/.bin/polybar-pavolume --togmute
scroll-up = amixer set Master 5%+
scroll-down = amixer set Master 5%-

```

**Comment by benchislett** [comment]
Swapped out `internal/alsa` for `internal/pulseaudio` and it works like a charm. Checked the docs and there is in fact a warning there to use pulseaudio if you can.

Closing this issue, thanks for the help.
