### ISSUE TITLE
filesystem reports wrong partition information

### ISSUE THREAD

**Issue by DasHammett** [polybar/polybar#2283]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
[module/filesystem] reports information on the wrong mountpoint when using multiple mount points. In my case duplicates the /home entry

**Expected behavior:**
Correct information on each mountpoint

**Actual behavior:**
Information displayed is not matching the mountpoint

**Was it working before?**
Yes
I first noticed the issue when updating python from 3.7 to 3.8. Could have happened before that tough.

## To Reproduce

```
[module/filesystem]
type = internal/fs
interval = 25
format-prefix = " "
mount-0 = /
mount-1 = /home

label-mounted =  %mountpoint%%{F-}: %free%/%total% (%percentage_used%%)
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

```

## Polybar Log

```
/sys/class/thermal/thermal_zone*:
notice: Parsing config file: /home/hammett/.config/polybar/config
warn: No monitor specified, using "DP-4.8"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
notice: Loaded font "FontAwesome:pixelsize=10" (name=FontAwesome, offset=0, file=/home/hammett/.fonts/fontawesome-webfont.ttf)
notice: Loaded font "Monoid:pixelsize=9" (name=Monoid, offset=1, file=/home/hammett/.fonts/Monoid-Regular.ttf)
error: tray: Failed to put tray above 0x2e00002 in the stack (XCB_MATCH (8))

```

## Screenshots

![image](https://user-images.githubusercontent.com/13760961/101903902-4bb1e080-3bb5-11eb-82ec-b3acae4cd61b.png)

## Environment:
* WM: i3-gaps-4.19
* Distro: Gentoo
* Output of `polybar -vvv`:

```
polybar 3.5.0-12-gdf485f0-dev

Features: +alsa -curl +i3 +mpd +network(libnl) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Gentoo
Compiler: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=znver2 -O2 -pipe -fomit-frame-pointer -fgraphite-identity -floop-nest-optimize -Wall -Wextra -Wpedantic
Linker flags: -Wl,-O1 -Wl,--as-needed

```

## Additional context
Information on the mountpoints
```
[hammett][/home/hammett]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G   18G  9.7G  65% /
/dev/sda2       430G  263G  145G  65% /home
```

**Comment by patrick96** [comment]
Thanks for reporting, I think this was introduced in #2199 when we added warn states.

@DRKblade do you have time to look at this? I think the problem is that we replace the tokens in the `update` method and each label is reused for all mountpoints, so they always show the tokens from the last mountpoint.
