### ISSUE TITLE
Bspwm module show "Desktop" instead workspaces numbers

### ISSUE THREAD

**Issue by Skabit** [polybar/polybar#2287]
## Describe the bug
I'm trying a new multi screen configuration. Now I'm using laptop OFF and hdmi ON. When reload bspwm, the module of polybar don't show the workspaces numbers, instead only appears a word **Desktop**.

**Expected behavior:**
Then reload bspwm and toggle screen, Polybar should show the workspaces numbers (1, 2, 3...)

## Environment:
* WM: bspwm
* Distro: Debian 10
* Output of `polybar -vvv`:

```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/c++
Compiler flags: -g -O2 -fdebug-prefix-map=/build/polybar-U7yomB/polybar-3.4.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-z,relro -Wl,-z,now 

```

## Additional context

I use a [mons](https://github.com/Ventto/mons) script for toogle screens.

**Output of `bspc subscribe`**
```
WMLVDS1:O1:o2:o3:f4:f5:f6:f7:f8:f9:f10:LT:TT:G:mHDMI1:FDesktop:LT
```

**A snip of my config:**
```
[bar/main]
monitor = ${env:MONITOR:} 
bottom = false
width = 100%
height = 27
fixed-center = true 
offset-x = 0
offset-y = 0
```

**My module configuration:**
```
[module/bspwm]

type = internal/bspwm
format = <label-state>

pin-workspaces = true  
inline-mode = false
enable-scroll = false
label-empty =  

label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.white}
label-focused-padding = 3

label-occupied-underline = ${colors.background-alt}
label-occupied-padding = 3

label-urgent-underline = ${colors.red}
label-urgent-padding = 2
```

**Comment by patrick96** [comment]
> WMLVDS1:O1:o2:o3:f4:f5:f6:f7:f8:f9:f10:LT:TT:G:mHDMI1:FDesktop:LT

bpsmw still places all its workspaces on the `LVDS1` monitor. The `HDMI1` monitor only has a single workspace named `Desktop` and that is what polybar correctly displays. And because of `pin-workspaces = true`, the module doesn't show the workspaces of the other monitor.

**Comment by Skabit** [comment]
@patrick96  thanks for the hints. But... How to reload polybar for show update workspaces?

I've changed `pin-workspaces` to `false`, then reload bspwm (Super + Alt + r) and workspaces still looks inexact.

**Comment by patrick96** [comment]
The main problem is that you only have a single workspace named "Desktop" on your HDMI output.

Setting `pin-workspaces = false` and restarting polybar (not bspwm) should display all workspaces (including the one named "Desktop"). Does this not work for you? What does it display?

**Comment by Skabit** [comment]
I'm trying to understand polybar and bspwm. Let me explain my configuration. I want use only the external monitor when I plug it. So for to achieve that I installed `mons`, with mons I can turn on/off monitors.  But I thought that is possible load the same laptop polybar on HDMI, with the same desktops, in other words work with the same desktops on Laptop and HDMI monitor when I turn off laptop monitor. So I would work with 1, 2, 3, 4.... laptop desktops on HDMI monitor.

But looking other dotfiles that seem it no possible. Most users config a group of desktops with a particular screen, like this:
```
bspc monitor LVDS1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 0
```
With that configuration on `.config/bspwm/bspwmrc` I can avoid that `Desktop` appears, because I've configured desktops for HDMI.

As now I have setting a number of desktops for each monitor I setting `pin-workspaces = true` because if I keep `pin-workspaces = false` bspwm module shows on polybar a double set of desktops: the desktops of laptop and desktops and HDMI, and as I work with only HDMI monitor that behavior looks weird.

But another situation happens when I connect the HDMI monitor before turn on laptop. In this situation I use a little script with `xrandr` that turn off laptop monitor. In this case polybar show HDMI desktops (6, 7, 8....), that has sense, but the desktops on polybar don't point a bspwm desktops, because when I try move with `super + 7` nothing happens, the desktop works with `super + 2` but on screen appears `7`, the same situation with another desktops: 

On polybar I see:

`6, 7, 8, 9, 0`

But for access to a specific desktop:
```
Super +  1 ---->  desktop 6
Super +  2 ---->  desktop 7 
Super +  3 ---->  desktop 8 
Super +  4 ---->  desktop 9 
Super +  5 ---->  desktop 0 
```
Maybe helps the output of `bspc subscribe` when I only have hdmi monitor turn on:

`WMHDMI1:o6:O7:f8:f9:f0:LT:TT:G`

**Comment by patrick96** [comment]
I don't use bspwm, so I don't really know exactly how bspwm handles these things. But I think a solution would be to map all workspaces to the external monitor when you turn off the laptop monitor:

```
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 0
```

**Comment by Skabit** [comment]
Thanks for all @patrick96. The problem is a bad configuration on bspwm. I could find a [configuration](https://gist.github.com/danielcbaldwin/3b146824f12355e5bac7e4102ab483c7) that helps me!

Good vibes!

**Comment by abdelmoneim-elshafei** [comment]
;in bspwmc file
bspc monitor eDP-1 -d "your workspaces"
bspc monitor HDMI-1-0  -d 

;in polybar config
;in bspwm module
pin-workspaces = false
