### ISSUE TITLE
EWMH is not present on initial boot or after making changes to the polybar config file

### ISSUE THREAD

**Issue by samurailostinjapan** [polybar/polybar#2288]
Arcolinux 20.11.9 (ArchLinux Distro)
WM: https://github.com/leahneukirchen/cwm

Trying to setup CWM to use polybar, during initial boot up, no ewmh window appears. After logging off and back on again the ewmh windows appears correctly and will work fine. If you make a change to the config file then the ewmh window will disappear again until logging off and back on again. 

Any ideas why the ewmh window is not appearing correctly?
Is this even a polybar issue vs cwm issue?

polybar -vvv output
![ArcoLinux_2020-12-11_15-12-19](https://user-images.githubusercontent.com/10843832/101975788-94839b00-3c82-11eb-9e01-fce14fc647ab.png)

Polybar on bootup
![2020-12-11_15-10](https://user-images.githubusercontent.com/10843832/101975802-a9602e80-3c82-11eb-9997-86cac09bd3f0.png)

Polybar after logging in the second time
![2020-12-12_14-19](https://user-images.githubusercontent.com/10843832/101976084-1f659500-3c85-11eb-828b-4e615d35242d.png)

Config and launch.sh script can be found here
https://github.com/arcolinux/arcolinux-polybar/tree/master/etc/skel/.config/polybar

Please let me know if you need anything else.

Thanks,

**Comment by patrick96** [comment]
If the module crashes for some reason, polybar will print this to `stderr`. What kind of errors does polybar print?

When you start polybar during startup, it is possible that polybar starts before the window manager, this can be a problem because polybar thinks the window manager isn't EWMH-compliant and thus the xworkspaces module does not start.

**Comment by arcolinuxz** [comment]
![polybar](https://user-images.githubusercontent.com/36679406/102697084-3b43da80-4233-11eb-9757-b90966090fa0.png)

**Comment by arcolinuxz** [comment]
Can we use these variables somehow to tell polybar what desktop it is, before we launch it?

**Comment by patrick96** [comment]
The only solution is to start polybar after the WM has completely launched. `_NET_CURRENT_DESKTOP` (and all other EWMH hits required by the xworkspaces module) are set by the WM, I don't think there is a way for you to manually set them.

**Comment by patrick96** [comment]
This has changed in version 3.6, now the xworkspaces module can actually launch even if no EWMH information is available yet. As soon as it becomes available, the module starts working.
