### ISSUE TITLE
duplicate script process

### ISSUE THREAD

**Issue by jekanev** [polybar/polybar#2289]
## Describe the bug

duplicate process when click script module.
**Expected behavior:**

no process duplicate in process monitor or pgrep.

**Actual behavior:**

when click script module every click add empty process in top or htop.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
no
* If no, what was the last version where this worked correctly?
3.4.3
## To Reproduce
make module
[module/cputemp]
type = custom/script
exec = ~/.config/polybar/cpu
tail = true
interval = 30
click-left = notify-send "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)"
click-right = ~/.config/polybar/testclick.sh
then click 10 times left mouse or right.
execute command pgrep testclick.sh | wc -l 
or in case left click pgrep notify-send | wc -l
it show 10 or more depend how many time u click module

## Polybar Log

```
polybar|notice:  Parsing config file: /home/spikespi/.config/polybar/config
polybar|warn:  No monitor specified, using "DVI-D-0"
polybar|notice:  pulseaudio: using default sink alsa_output.pci-0000_00_14.2.analog-stereo
polybar|notice:  Loaded font "Ubuntu Mono:pixelsize=10:style=bold" (name=Ubuntu Mono, offset=0, file=/usr/share/fonts/ubuntu/UbuntuMono-B.ttf)
polybar|notice:  Loaded font "FontAwesome:fontformat=truetype:size=9:antialias=true" (name=FontAwesome, offset=1, file=/usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.ttf)
polybar|notice:  Loaded font "SauceCodePro Nerd Font Mono" (name=SauceCodePro Nerd Font Mono, offset=0, file=/usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete Mono.ttf)
polybar|notice:  Loaded font "siji:pixelsize=9" (name=Siji, offset=1, file=/usr/share/fonts/misc/siji.bdf)
polybar|notice:  Loaded font "Dejavu Sans:pixelsize=9" (name=DejaVu Sans, offset=2, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
polybar|notice:  Loaded font "Noto Sans Symbols2:pixelsize=9" (name=Noto Sans Symbols2, offset=2, file=/usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf)
polybar|notice:  Loaded font "HAN NOM A:pixelsize=9" (name=HAN NOM A, offset=2, file=/usr/share/fonts/TTF/HAN NOM A.ttf)
polybar|error: tray: Failed to put tray above 0x1c00002 in the stack (XCB_MATCH (8))
```

## Screenshots

![2020-12-12_1020x175](https://user-images.githubusercontent.com/40966572/101979445-33ea6300-3c6e-11eb-8f15-0025e039a975.png)
## Environment:
* WM:i3wm
* Distro:Arch Linux x86_64
* Output of `polybar -vvv`:

```
polybar 3.5.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

```

**Comment by patrick96** [comment]
I just fixed this yesterday in #2285 

Will be release in 3.5.1
