### ISSUE TITLE
xkeyboard module adds spaces between the indicators (capslock, etc), even if the indicator is empty, and after layout when all indicators are empty.

### ISSUE THREAD

**Issue by Filip62** [polybar/polybar#2292]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

There is an additional space/margin after the xkeyboard module even though in the config i explicitly set the margin to 0, seems like the xkeyboard module adds spaces between the indicators (capslock, etc), even if the indicator is empty.

**Expected behavior:**

No margins added by the xkeyboard module unless it should because of an active indicator.

**Actual behavior:**

The xkeyboard module adds a space/margin after the layout indicator if if CapsLock is not active.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
Do not know.
* If no, what was the last version where this worked correctly?
Do not know.

## To Reproduce

```dosini
[bar/bspwm2]
monitor = DVI-I-0
width = 100%
height = 27
;offset-x = 1%
;offset-y = 1%
; radius = 6.0
fixed-center = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin-left = 2
module-margin-right = 2

; font-0 = JetBrainsMono Nerd Font:pixelsize=10;1
font-0 = FreeSans:antialias:pixelsize=11;1
font-1 = Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid:pixelsize=10;1

modules-left = bspwm
modules-center = xwindow
modules-right = pulseaudio-control memory cpu temperature xkeyboard date powermenu2

wm-restack = bspwm

;override-redirect = true

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

cursor-click = pointer
cursor-scroll = ns-resize

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = "%{T2} "
format-prefix-foreground = ${colors.foreground}
format-prefix-underline = ${colors.secondary}
format-margin = 0

label-layout = %layout%
label-layout-underline = ${colors.secondary}
```

## Polybar Log

```
notice: Parsing config file: /home/filip/.config/polybar/config
notice: Loaded font "FreeSans:antialias:pixelsize=11" (name=FreeSans, offset=1, file=/usr/share/fonts/gnu-free/FreeSans.otf)
notice: Loaded font "Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid:pixelsize=10" (name=Font Awesome 5 Free, offset=1, file=/usr/share/fonts/TTF/fa-solid-900.ttf)
```

## Screenshots

![polybar](https://user-images.githubusercontent.com/58399088/101985578-3f975300-3c89-11eb-8cee-45890eac218f.png)

## Environment:
* WM: bspwm
* Distro: Arch Linux
* Output of `polybar -vvv`:

```
polybar 3.5.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
Thanks for opening an issue :)

The problem is that in `xkeyboard_module::build` (`xkeyboard.cpp`), we always add spaces, even if one or more indicator labels are actually empty.

If anyone wants to tackle this, I think this doesn't require much knowledge about the polybar codebase.

**Comment by Filip62** [comment]
@patrick96 I will try then as soon as possible.
