### ISSUE TITLE
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)

### ISSUE THREAD

**Issue by gaos59** [polybar/polybar#2293]
## Checklist

* [X ] I have followed every step on the [compiling wiki page](https://github.com/polybar/polybar/wiki/Compiling) and
  installed all necessary dependencies.
* [X ] My problem is not described on the [known issues page](https://github.com/polybar/polybar/wiki/Known-Issues)
* [X ] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X ] I was able to reproduce this build issue in a clean build

## Build Process

**How did you build polybar?**

* [X ] From a release archive (Which version?)
* [ ] By cloning this repository (What is the output of `git describe --tags`?)
* [ ] Some other way (How?)

## Build Log
#make -j$(nproc)
[  0%] sphinx-build html: see doc/builder-html.log
[  1%] sphinx-build man: see doc/builder-man.log
[  1%] Built target doc_html
[  2%] Generating generated-sources/include/xpp/proto/x.hpp
[  2%] Built target doc_man
[  5%] Built target i3ipc++
Traceback (most recent call last):
  File "/opt/polybar/lib/xpp/generators/cpp_client.py", line 3096, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3/dist-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3/dist-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3/dist-packages/xcbgen/xtypes.py", line 5, in <module>
    from xcbgen.align import Alignment, AlignmentLog
  File "/usr/lib/python3/dist-packages/xcbgen/align.py", line 5, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:93: lib/xpp/generated-sources/include/xpp/proto/x.hpp] Error 1
make[2]: *** Se borra el archivo 'lib/xpp/generated-sources/include/xpp/proto/x.hpp'
make[1]: *** [CMakeFiles/Makefile2:540: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
[ 10%] Built target polybar-msg
make: *** [Makefile:149: all] Error 2

```

```

## Environment:
* debian : 4.10

## Additional context
I'm alredy install al dependencies

**Comment by Ousdeferro** [comment]
Exactly the same problame here!

**Comment by patrick96** [comment]
You need to update your `python3-xcbgen` package. The previous version (1.14-2) is not compatible with python 3.9, but the current version (1.14.1-1) is compatible.

**Comment by Ousdeferro** [comment]
Still not working, I execute `sudo apt-get install pyhton3-xcbgen`, but it installs the lastest version which is 1.14-2, or that's what the output log says.
Now when I execute `make -j$(nproc)`, same error appears.

**Comment by patrick96** [comment]
1.14-2 isn't the latest version, 1.14.1-1 is: https://packages.debian.org/search?keywords=python3-xcbgen&searchon=names&suite=all&section=all

You probably need to update your repos.

**Comment by Ousdeferro** [comment]
Okey, I don know what can happen, everything is update. But it stills installs version 1.14-2. I'm using parrot, may this affect??

**Comment by patrick96** [comment]
If parrot really only has python3-xcbgen version 1.14-2, but updated python to python 3.9, then this is a distro issue because their python3-xcbgen package is not compatible with their python version.

**Comment by Ousdeferro** [comment]
It means that i vave no chances of installin polybar on parrot os?

**Comment by patrick96** [comment]
I mean there are ways (though none of them are the recommended way to do things because they might break your system in the future):

* Install polybar from the debian repos
* Downgrade python to 3.8 (this will probably break all other python packages)
* Download the .deb file for 1.14.1-1 from a debian mirror and install that

The good thing is that python3-xcbgen is only needed to compile but not to run polybar, so if you do either the second or third option you can revert it once you have built polybar. The first option is probably the best way to do it.

**Comment by gaos59** [comment]
I change the name of fractions.py in directory  /usr/lib/python3.9 to fractions .pyc and copy fractions.py of directory /usr/lib/python3.8 to /usr/lib/python3.9 and run the conmands make -j$(nproc) and sudo make instal. After that i just delete fractions.py of directory /usr/lib/python3.9 and rename fractions.pyc to fractions.py of the same directory. 

Thank you for your help.

**Comment by brojasl90** [comment]
Thank you so much @gaos59, this works for me in ParrotOS.

**Comment by toornet** [comment]
> I change the name of fractions.py in directory /usr/lib/python3.9 to fractions .pyc and copy fractions.py of directory /usr/lib/python3.8 to /usr/lib/python3.9 and run the conmands make -j$(nproc) and sudo make instal. After that i just delete fractions.py of directory /usr/lib/python3.9 and rename fractions.pyc to fractions.py of the same directory.
> 
> Thank you for your help.

Work!, Thanks!.

```
cp /usr/lib/python3.9/fractions.py /usr/lib/python3.9/fractions.py.backup
cp /usr/lib/python3.8/fractions.py /usr/lib/python3.9/fractions.py
cp /usr/lib/python3.9/fractions.py.backup /usr/lib/python3.9/fractions.py
```

**Comment by patrick96** [comment]
Are you all having this issue on parrot os or also in a different distro?

**Comment by darko-skc** [comment]
> Are you all having this issue on parrot os or also in a different distro?
i had the same problem with parrot

**Comment by patrick96** [comment]
I have already reported this to the parrot people, but I don't think it has been fixed yet.

**Comment by kzhou003** [comment]
Saw same issue. The cause is gcd is not supported by fractions anymore. 

`sudo vim /usr/lib/python3/dist-packages/xcbgen/align.py`

And update 

`from fractions import gcd `

to 

`from math import gcd `

Works for me.
