### ISSUE TITLE
i3 scrolling to change workspace broken in latest version

### ISSUE THREAD

**Issue by RealStickman** [polybar/polybar#2299]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

When scrolling anywhere on the bar the workspace does not change. One exception is scrolling on the i3 module, which does work and change the workspace.

**Expected behavior:**

Scrolling anywhere on the bar where there is no other scroll action should change workspaces in i3.

**Actual behavior:**

I stay on the same workspace.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
No
* If no, what was the last version where this worked correctly?
Version 3.5.0

## To Reproduce

```dosini
[bar/mainbar-i3]

monitor = ${env:MONITOR}
monitor-strict = false
width = 100%
height = 20

modules-left = i3

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev

[module/i3]
type = internal/i3

; Create click handler used to focus workspace
; Default: true
enable-click = true

; Create scroll handlers used to cycle workspaces
; Default: true
enable-scroll = true

; Wrap around when reaching the first/last workspace
; Default: true
wrapping-scroll = true

; Set the scroll cycle direction
; Default: true
reverse-scroll = false
```

## Polybar Log

```
marc@arco-pc ~> polybar -c ~/.config/polybar/testconf.ini mainbar-i3 &
notice: Parsing config file: /home/marc/.config/polybar/testconf.ini
error: Invalid value for "bar/mainbar-i3.monitor", using default value (reason: Environment var ${MONITOR} does not exist (no fallback set))
warn: No monitor specified, using "HDMI-A-1"
warn: No fonts specified, using fallback font "fixed"
notice: Loaded font "fixed" (name=Fira Sans, offset=0, file=/usr/share/fonts/TTF/FiraSans-Regular.ttf)
```

## Environment:
* WM: i3-gaps
* Distro: ArcoLinux (Arch-based)
* Output of `polybar -vvv`:

```
polybar 3.5.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by patrick96** [comment]
Fixed in #2296
