### ISSUE TITLE
Custom script freezes after a random delay

### ISSUE THREAD

**Issue by soywod** [polybar/polybar#2305]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
I'm using a tool named [Comodoro](https://github.com/soywod/comodoro) that writes a timer in a socket, so that different clients can listen and fetch it in real time. The tool provides a blocking `watch` command that connects to the socket and prints the timer to stdout. If the timer is not started yet, it prints a loader (a static string) and tries again 5 secs later.

I set up a custom script (with `tail = true` and `exec = comodoro watch`) and it works well. But after a random delay (let's say 10/15 min), the module doesn't update anymore. I noticed that it happens only when the timer is off (when the command `watch` prints the loader).

I tried to launch the `watch` command from the terminal for all the night and it doesn't stop nor freeze, so I guess it comes from Polybar.

## To Reproduce

1. Install the tool (https://github.com/soywod/comodoro#installation)
2. Set up the Polybar custom script:
```dosini
[module/comodoro]
type = custom/script
exec = comodoro watch 
label = %output%
tail = true
click-left = if [ -e /tmp/comodoro.pid ]; then comodoro stop; else comodoro start; fi
click-right = if [ -e /tmp/comodoro.pid ]; then comodoro stop; else comodoro start; fi
```
3. Check that the module displays well the output by running the command `comodoro start`
4. Shutdown the timer `comodoro stop`
5. Wait 1h
6. Start again the timer `comodoro start` and see that the module does not update anymore
## Polybar Log

Logs doesn't give anything relevant.

## Environment:

* WM: `i3 version 4.18.2`
* Distro: `Linux workstation 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux`
* Output of `polybar -vvv`:

```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
I don't quite understand how the issue manifests itself.

> I noticed that it happens only when the timer is off (when the command watch prints the loader).

Since the loader always prints the same string, how do you know that the module stopped updating?
Do you turn on the timer and the module doesn't update then after being off?

In that case, have you verified the timer is actually running?

**Comment by soywod** [comment]
Sorry, it's hard to fully explain. I try my best !

> Since the loader always prints the same string, how do you know that the module stopped updating?

I know it freezes when the timer starts finally and the module still shows the loader instead.

> In that case, have you verified the timer is actually running?

Yes the timer runs well and never freezes, because I can spawn an other `comodoro watch` in the terminal and I receive output (loader or timer). As I mentioned, I also tried to let run a `watch` command over night in my terminal and I receive well the loader continuously (it does not freeze).

**Comment by soywod** [comment]
In fact it was a problem with the tool itself. I was able to debug and fix, now it works perfectly. I don't get why it failed with Polybar but worked from a terminal over night. Sorry for the misdiagnosed issue!

**Comment by patrick96** [comment]
What was the problem in your tool? Programs launched through polybar can behave differently. The main reason often are different environment variables, but also the programs are not attached to a terminal when run in polybar.

>  Sorry for the misdiagnosed issue!

Don't worry about it :)

> PS: I'm using Polybar for a year and a half now and I love it! It's a very nice project. Keep going!

That's nice to hear :smiley:

**Comment by soywod** [comment]
> What was the problem in your tool?

I think some connections were not properly closed. Plus it seems that polybar starts again the command if it fails, which lead to the freeze. But I still don't get why I didn't reproduce from the terminal. Anyway, all is fixed, all is fine :)

**Comment by patrick96** [comment]
Hmm, that is weird. Maybe it's because you started the timer from polybar. Before 3.5.0 click commands were very buggy and if you started long running processes through them you may get a problem at some point (for example once it produces output).
