### ISSUE TITLE
Building with docs without Git results in build failure

### ISSUE THREAD

**Issue by ajakk** [polybar/polybar#2309]
## Checklist

* [x] I have followed every step on the [compiling wiki page](https://github.com/polybar/polybar/wiki/Compiling) and
  installed all necessary dependencies.
* [x] My problem is not described on the [known issues page](https://github.com/polybar/polybar/wiki/Known-Issues)
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I was able to reproduce this build issue in a clean build

## Build Process

**How did you build polybar?**

* [x] From a release archive (Which version?)
* [ ] By cloning this repository (What is the output of `git describe --tags`?)
* [ ] Some other way (How?)

Version 3.5.2.

Built through Gentoo's package manager, but in general this issue should be reproduced with -DBUILD_DOC=yes.

## Build Log

[build.log](https://github.com/polybar/polybar/files/5705896/build.log)

## Environment:
* Distro (with Version): Gentoo

## Additional context

No Git installed, unecessary dependency aside from this issue.

**Comment by patrick96** [comment]
Fixed in #2311. I will release 3.5.3 in a week or so.
