### ISSUE TITLE
Plasma System Tray not working on Polybar

### ISSUE THREAD

**Issue by Matsuuu** [polybar/polybar#2313]
## Checklist

* [X] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

I have tried to enable System tray (wifi icon, open applications like Slack etc.) on Polybar with the default configuration
e.g.
```
tray-position = center
tray-scale = 1.0
tray-maxsize = 16
```

But the tray doesn't show if the chosen DE is Plasma.

I've tried disabling the system tray following the notes in [this discussion](https://www.reddit.com/r/kde/comments/byfmry/disable_system_tray/), but to no avail.

If I start log in with i3, the tray is visible, but not if I try with Plasma, even if the panel is removed.

**Expected behavior:**

Tray should be visible in polybar

**Actual behavior:**

Tray isn't visible

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
* If no, what was the last version where this worked correctly?

## To Reproduce

- Install KDE Plasma
- Install Polybar
- Set tray in polybar
- Remove panel
- Log out
- Log in

```dosini
[bar/main]
bottom=true

width = 20%
height = 35
offset-x = 65%
offset-y = 0.5%
override-redirect = true
radius = 8
fixed-center = false

tray-position = center
tray-padding = 2
tray-background = ${colors.primary}
tray-scale = 1.0
tray-maxsize = 16

enable-ipc = true

[settings]
screenchange-reload = true
pseudo-transparency = true

[global/wm]
margin-top = 5
margin-bottom = 5

wm-restack = i3
override-redirect = true

; vim:ft=dosini
```

## Polybar Log

```

```

## Environment:
* WM:  i3 / KWin (tried both)
* Distro: Ubuntu 20.04.1 LTS
* Output of `polybar -vvv`:

```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/c++
Compiler flags: -g -O2 -fdebug-prefix-map=/build/polybar-IKpyNi/polybar-3.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic
Linker flags: -Wl,-Bsymbolic-functions -Wl,-z,relro
```

**Comment by patrick96** [comment]
Does polybar really not produce any output?

**Comment by Matsuuu** [comment]
https://i.imgur.com/82tVyad.mp4 

Here's a video. The only output I get is due to using KDE. In i3 even that is omitted.

I've tried it with and without having the kde/plasma panel / system tray

**Comment by patrick96** [comment]
Hmm, since your plasma panel already displays a tray, it makes sense that polybar doesn't display it. But normally polybar would print a warning that it can't display the tray and in your case it doesn't.

I think the reason this happens is because the applications on your system don't actually provide a tray icon for polybar when running in KDE. This is likely because KDE is running a watcher for StatusNotifierItems (a more modern tray specification) and all the applications just provide tray icons for that specification and not for the old XEMBED spec that polybar uses.

If that is indeed the case, I see two ways of solving this. Either find a way to disable this watcher that is running in KDE, this likely isn't the panel itself but a separate service. There is also [snixembed](https://git.sr.ht/~steef/snixembed) which "converts" these StatusNotifierItems to XEMBED icons that polybar can actually display.

**Comment by Matsuuu** [comment]
Hmm yeah I suppose that would be the reason. I would really love to be able to use KDE with the Polybar system tray.

I've tried to look around on what system processes could be responsible of the tray but haven't caught the culprit just yet

**Comment by patrick96** [comment]
I think the name of the executable is `statusnotifierwatcher`: https://github.com/KDE/plasma-workspace/tree/master/statusnotifierwatcher

I'm closing this, #2010 is the main issue regarding these new StatusNotifierItems

**Comment by XxRiKxX** [comment]
```❯ xprop -id 0x2000005
_NET_SYSTEM_TRAY_VISUAL(VISUALID): visual id # 0x7b
ATOM(ATOM) = ATOM```
this is the what I got form this error ```warn: Systray selection already managed (window=0x2000005)```
I tried putting ```snixembed --fork``` in the launch scripts before starting polybar, but nothing happened.
How can I kill this service by its window id?
