### ISSUE TITLE
Problem setting up polybar.

### ISSUE THREAD

**Issue by honestly-nuts** [polybar/polybar#2319]
so This problem made me give up polybar twice.So a little context, I first installed polybar on ubuntu using apt. Then I faced the problem. The problem was when I put the launch script in my i3 config file it did nothing. I tried to fix it twice by searching it on the internet but I found no help. But this time I took things on my own and I copied all the code in launch.sh and debugged them. I first got an error with numbers like \[1\] 3489 (not the real number). Then I saw that ```polybar example (originally mybar) >>/tmp/polybar1.log 2>&1 & disown``` was printing all error messages into a log file so I removed the code after ```example``` and then I saw it was printing something like ``` error: can't find /home/username/.config/polybar/config``` and I saw that there was a file named config.gz (to be honest I this time followed a tutorial first which told me to copy the config.gz file from a path but I checked That there was no ```config``` file before hand) in there but when I renamed it, all text became binary, so I copied all the code in config.gz to config (using vim) and it worked and it still works. Anyway, I'm not making this to flex or something (do people even flex for doing these kind of things). I'm doing this to help people with setting up polybar. I also think this is an big issue that needs to be addressed in the official polybar repo.

**Comment by patrick96** [comment]
Please don't double post.

https://www.reddit.com/r/Polybar/comments/kgvbms/problems_setting_up_polybar/
