### ISSUE TITLE
powermenu requires root privilege to use openrc-poweroff

### ISSUE THREAD

**Issue by TechieAndroid** [polybar/polybar#2334]
I don't know how to go about addressing this problem since I don't want to run polybar as root and I don't think there's a way to add it to a group with openrc rights either.

**Comment by patrick96** [comment]
There is a way to get passwordless sudo for certain executables by editing your sudoers file (`visudo`), with that you could have `sudo openrc-poweroff` in polybar. On my system these shutdown commands also required root, but with polkit I think you can also run them as a normal user. How to do this exactly is probably better asked in an openrc space.

In general, if you want to run something in polybar you have to be able to run it as your normal user without having to enter a password (or any other user interaction). This means either running it with passwordless sudo or somehow giving your user permission to just run it.
