### ISSUE TITLE
Network module - show numbers after decimal point

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [polybar/polybar#2335]
I use polybar network module to monitor my network activity (ethernet). I have 30MBit/s internet connection and polybar shows the speed in MB/s (or KB/s) which may bother me, but not the greatest issue. The actual issue for me is that above 1000 KB/s it just rounds up to closest number in MB, which isn't very informative.

The solution would be simple: just  make it the same as in RAM module. It shows numbers after decimal point just fine.

Here's a screenshot of how it looks like when I'm downlaoding something:
![](https://i.imgur.com/bJmPjZK.png)

**Comment by patrick96** [comment]
This has already been implemented in #2054 (but not yet released)
