### ISSUE TITLE
I'm getting this error: warn: No monitor specified, using "eDp-1-1

### ISSUE THREAD

**Issue by BardicSocialReform** [polybar/polybar#2349]
## Checklist

* [ ] I have followed every step on the [compiling wiki page](https://github.com/polybar/polybar/wiki/Compiling) and
  installed all necessary dependencies.
* [ ] My problem is not described on the [known issues page](https://github.com/polybar/polybar/wiki/Known-Issues)
* [ ] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [ ] I was able to reproduce this build issue in a clean build

## Build Process

**How did you build polybar?**

* [ ] From a release archive (Which version?)
* [ ] By cloning this repository (What is the output of `git describe --tags`?)
* [ ] Some other way (How?)

## Build Log

```

```

## Environment:
* Distro (with Version):

**Comment by BardicSocialReform** [comment]
I missed typed and pressed enter to soon my apologies for missing data. MY CODE SAYS DIS:
notice: Parsing config file: /home/dogudr/.config/polybar/config
warn: No monitor specified, using "eDP-1-1"
notice: Loaded font "DroidSansMono:style=Regular:pixelsize=11" (name=DejaVu Sans, offset=2, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
notice: Loaded font "Font Awesome:style=Regular:antialias=true:pixelsize=12" (name=FontAwesome, offset=2, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
notice: Loaded font "siji:style=Regular:pixelsize=24" (name=DejaVu Sans, offset=2, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
notice: Loaded font "Font Awesome:style=Regular:pixelsize=12" (name=FontAwesome, offset=2, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
notice: Loaded font "Font Awesome:style=Solid:pixelsize=12" (name=FontAwesome, offset=2, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
notice: Loaded font "Font Awesome:style=Regular:antialias=true:pixelsize=12" (name=FontAwesome, offset=2, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
notice: Termination signal received, shutting down...

**Comment by BardicSocialReform** [comment]
from issue #1337 they used `weight = 100%` and it fixed it, but I tried that and nothing happened. My coding knowledge is pretty minimal, so I've mostly been teaching myself so you might have to be patient with me but I'll work at trying to get you what you need to help me with what I need. also if I don't respond after 10:30 am, Eastern please don't close out the issue request, I'll likely be asleep and will be responding after 5 or 6 p.m. Eastern

THank you!

**Comment by patrick96** [comment]
What exactly is the problem?

The warning `No monitor specified, using "eDP-1-1"` itself is harmless. It appears if you have no monitor specified in your config and there is no primary monitor. It will then just pick first monitor (if possible the first connected monitor).

If there is indeed an underlying issue, please edit your post using [this template](https://github.com/polybar/polybar/issues/new?assignees=&labels=&template=bug_report.md). There is a lot of information missing that we need to diagnose the issue.
Please comment once you edited your post.

**Comment by BardicSocialReform** [comment]
Well my Polybar isn't loading but parts of itself and that's the only error, it's on a laptop, but I'm not sure that makes a difference. There's probably some other call, I just wanted to see if there was something there.

**Comment by patrick96** [comment]
If you want us to help you, you really need to fill out the issue template I linked to in my previous comment because we need a lot more information to be able to help you. Maybe also go through our [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config)

**Comment by BardicSocialReform** [comment]
I figured it out, it took a minute thank you. For future reference to others who see this (especially if their new to WMs and polybar) make sure all of your drivers match, so check to see what specifically is being called and what isn't.
