### ISSUE TITLE
module border radius 

### ISSUE THREAD

**Issue by siduck76** [polybar/polybar#2355]
![image](https://user-images.githubusercontent.com/59060246/104831743-9d831000-58b1-11eb-9e37-528c5923da8d.png) polybar module can have border radius ( rounded corners ) .

**Comment by patrick96** [comment]
No.

But you can get a similar experience with the half circle [powerline symbols](https://github.com/ryanoasis/powerline-extra-symbols).

The GitHub issue tracker is not meant for questions, please use one of the places listed [here](https://github.com/polybar/polybar/blob/master/SUPPORT.md) next time.
