### ISSUE TITLE
Ubuntu 18.04: sphinx from system packages not sufficient for building polybar

### ISSUE THREAD

**Issue by cschwarzmeier** [polybar/polybar#2356]
Building polybar requires `sphinx.domains.changeset`, which is not available in [sphinx 1.6.7](https://packages.ubuntu.com/bionic/all/python3-sphinx/filelist). Sphinx 1.6.7 is installed when using either `apt install python3-sphinx` or `pip install -U sphinx` on Ubuntu 18.04.

As these commands are suggested in the corresponding entry in your [wiki](https://github.com/polybar/polybar/wiki/Compiling), you should mentioned this problem there. Ideally, you could also add a brief guideline for installing a more recent version of sphinx (e. g. by using anaconda).

**Comment by patrick96** [comment]
Thanks for reporting. Can you try out the fix in #2358? It now only enables certain features if sphinx supports them.

**Comment by cschwarzmeier** [comment]
Thanks, #2358 fixes the issue.

**Comment by patrick96** [comment]
Thanks for checking. I'm going to reopen the issue until it's merged.

**Comment by voqv** [comment]
Had the same issue and this helped.
