### ISSUE TITLE
module "scroll-down" handler is being called multiple times

### ISSUE THREAD

**Issue by muhmud** [polybar/polybar#2357]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
I have a module that specifies a handler for `scroll-down`. This used to only fire once when the mouse wheel was scrolled. However, now it fires multiple times.

**Expected behavior:**
The `scroll-down` handler should only be called once, like before. If the new behaviour is required, it should be configurable, with the default being the old behaviour.

**Actual behavior:**
My `scroll-down` script is called a bunch of times.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
No, I didn't

* If no, what was the last version where this worked correctly?
I'm pretty sure it was working before `3.5.2`. I have tried `3.5.4`, but it's still not as it used to be.

## To Reproduce

```dosini
[bar/top]
modules-left = test

[module/test]
type = custom/script
interval = 1800
label = %output%
exec = ~/.config/polybar/scripts/test.sh
scroll-down = ~/.config/polybar/scripts/test.sh
```

`~/.config/polybar/scripts/test.sh`:
```bash
#!/bin/sh

echo "CALLED" >> /tmp/test.log

echo "XXX";
```

Scroll on the `XXX` with the mouse wheel.

## Polybar Log

```
notice: Parsing config file: /home/muhmud/.config/polybar/config
warn: No monitor specified, using "DisplayPort-2"
warn: No fonts specified, using fallback font "fixed"
notice: Loaded font "fixed" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
```

## Environment:
* WM: i3
* Distro: Manjaro
* Output of `polybar -vvv`:

```
polybar 3.5.4

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

```

**Comment by patrick96** [comment]
I'm unable to reproduce this on both `master` and `3.5.4` and I don't see any changes in behavior when I try it in `3.5.1` or `3.4.3`.

Can you run the config you posted with info logging (`-l info`), scroll on it once and post the output of that as well as the contents of the `test.log` file.

**Comment by muhmud** [comment]
Thanks for looking at this. As requested, here's the logging output:

```
notice: Parsing config file: /home/muhmud/.config/polybar/config
warn: No monitor specified, using "DisplayPort-2"
* Loaded monitor DisplayPort-2 (3840x2160+0+0)
* Bar geometry: 3840x24+0+0; Borders: 0,0,0,0
* Starting application
* Starting module/test
* Entering event loop (thread-id=1)
* module/test: Invoking shell command: "~/.config/polybar/scripts/test.sh"
* Eventqueue worker (thread-id=2)
* Configured DPI = 96x96
warn: No fonts specified, using fallback font "fixed"
notice: Loaded font "fixed" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Bar window: 0x0e00001
* Disabling tray manager (reason: missing `tray-position`)
* module/test: Rebuilding cache
* Redrawing bar window
* Forwarding command to shell... (input: ~/.config/polybar/scripts/test.sh)
* Executing shell command: ~/.config/polybar/scripts/test.sh
* Redrawing bar window
* Forwarding command to shell... (input: ~/.config/polybar/scripts/test.sh)
* Executing shell command: ~/.config/polybar/scripts/test.sh
* Redrawing bar window
* Forwarding command to shell... (input: ~/.config/polybar/scripts/test.sh)
* Executing shell command: ~/.config/polybar/scripts/test.sh
* Redrawing bar window
* Forwarding command to shell... (input: ~/.config/polybar/scripts/test.sh)
* Executing shell command: ~/.config/polybar/scripts/test.sh
* Redrawing bar window
* Forwarding command to shell... (input: ~/.config/polybar/scripts/test.sh)
* Executing shell command: ~/.config/polybar/scripts/test.sh
* Redrawing bar window
notice: Termination signal received, shutting down...
* module/test: Stopping
* Deconstruction of module/test took 0 ms.
* Waiting for spawned processes to end
* Reached end of application...
```

Here's the `test.log` file:
```
CALLED
CALLED
CALLED
CALLED
CALLED
CALLED
```

It seems like it's calling the script for every segment that the mouse scroll wheel moves.

**Comment by patrick96** [comment]
Does your scroll wheel have individual scroll steps or is it more like a smooth scroll?

Because it looks like polybar is actually receiving multiple scroll events. To confirm that, can you run the same thing again with trace logging, this should tell us exactly what kind of input event the polybar window receives.

**Comment by muhmud** [comment]
It's individual scroll steps rather than smooth scroll.

I'll try with the trace logging; it's bizarre that this used to work fine.

**Comment by muhmud** [comment]
This is output from trace logging:

```
* module/test: Rebuilding cache
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=33x24+0+0, falloff=0)
- bar: Received expose event
- bar: Received button press: 5 at pos(26, 2)
- Found matching input area
- controller: Processing inputdata: ~/.config/polybar/scripts/test.sh
* Forwarding command to shell... (input: ~/.config/polybar/scripts/test.sh)
* Executing shell command: ~/.config/polybar/scripts/test.sh
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=33x24+0+0, falloff=0)
- bar: Received button press: 5 at pos(26, 2)
- Found matching input area
- controller: Processing inputdata: ~/.config/polybar/scripts/test.sh
* Forwarding command to shell... (input: ~/.config/polybar/scripts/test.sh)
* Executing shell command: ~/.config/polybar/scripts/test.sh
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=33x24+0+0, falloff=0)
- bar: Received button press: 5 at pos(26, 2)
- Found matching input area
- controller: Processing inputdata: ~/.config/polybar/scripts/test.sh
* Forwarding command to shell... (input: ~/.config/polybar/scripts/test.sh)
* Executing shell command: ~/.config/polybar/scripts/test.sh
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=33x24+0+0, falloff=0)
```
I needed a fix so I used `flock` in front of my script and that's working for me.

**Comment by patrick96** [comment]
Hmm, so polybar is receiving multiple "button presses" (this includes scrolling). My guess is that for some reason your mouse produces multiple scroll events on a single scroll.

To confirm, can you run `xev -event mouse | grep -A 3 "^Button"`, and do a single scroll on the window that pops up. This should produce a single `ButtonPress` and `ButtonRelease` event for button 5 (scroll down) or button 4 (scroll up). Does this produce more than that for you?

Before 3.5, polybar swallowed mouse event commands if they were close together, but that was removed because it interfered with other internal events. This would explain why this is only happening now and not before.

> I needed a fix so I used flock in front of my script and that's working for me.

I didn't know about `flock`, but that looks really cool.

**Comment by muhmud** [comment]
Yep, you're right, I see multiple events coming through when I scroll the mouse wheel.

Thanks for looking into this & clearing up the mystery as to why this used to work!
