### ISSUE TITLE
Battery module threshold status

### ISSUE THREAD

**Issue by qtaped** [polybar/polybar#2363]
## Is your feature request related to a problem? Please describe.

If the battery is in the threshold range and my Thinkpad plugged to the AC, the battery is not currently charging and will never be full (normal behaviour) but the battery module considering the status as charging and so displaying the format-charging (wich is anoying since I configured polybar to show an animation).

## Additional context

Enable threshold with tlp.

_tlp-stat output_
```
/sys/class/power_supply/BAT0/status                         = Unknown (threshold may prevent charging)
/sys/class/power_supply/BAT0/charge_start_threshold         =     80 [%]
/sys/class/power_supply/BAT0/charge_stop_threshold          =    100 [%]

```

## Why does polybar need this feature?

Because a lot of users using tlp on their laptop.

## Describe the solution you'd like

Having a format-threshold option.

## Describe alternatives you've considered

Using full-at option and %percentage_raw%, but the problem is reverse, if the battery is currently charging above the minimum threshold the battery module displaying format-full instead of format-charging

**Comment by patrick96** [comment]
I didn't even know that this was something built-in on linux.

If anyone wants to work on this, PRs are welcome :)

I have found the following documentation for this:

* https://linrunner.de/tlp/settings/battery.html
* https://github.com/torvalds/linux/commit/2801b9683f740012863f7f0b1f0bc770c417fe72

One thing I noticed is that (on my machine) the contents of the `charge_start_threshold` file are different than the ones reported by `tlp-stat`.

**Comment by qtaped** [comment]
> One thing I noticed is that (on my machine) the contents of the `charge_start_threshold` file are different than the ones reported by `tlp-stat`.

Oh my bad, I didnt realize that some features (like threshold) are only supported for _Thinkpads_.

Btw I dont get how the polybar battery module works (I know Linux well but I am not a developer) but it seems that it doesnt get the status from _/sys/class/power_supply/BAT0/status_ maybe it only checks if AC is plugged in and the battery is not full?

**Comment by patrick96** [comment]
> Oh my bad, I didnt realize that some features (like threshold) are only supported for Thinkpads.

I also have a thinkpad. It's possible that this is just because I don't actually use the feature.

> Btw I dont get how the polybar battery module works (I know Linux well but I am not a developer) but it seems that it doesnt get the status from /sys/class/power_supply/BAT0/status maybe it only checks if AC is plugged in and the battery is not full?

This happens in `src/modules/battery.cpp` between lines 34 and 65.

It first tries to use `<ADAPTER>/online` and only then tries `<BATTERY>/status`.

**Comment by qtaped** [comment]
> > Oh my bad, I didnt realize that some features (like threshold) are only supported for Thinkpads.
> 
> I also have a thinkpad. It's possible that this is just because I don't actually use the feature.
> 
> > Btw I dont get how the polybar battery module works (I know Linux well but I am not a developer) but it seems that it doesnt get the status from /sys/class/power_supply/BAT0/status maybe it only checks if AC is plugged in and the battery is not full?
> 
> This happens in `src/modules/battery.cpp` between lines 34 and 65.
> 
> It first tries to use `<ADAPTER>/online` and only then tries `<BATTERY>/status`.

Ok thanks. So I guess there is a reason why, like some laptops doesnt have a battery/status?

I thought about a simple solution like have an option to bypass the adapter-check but if I understand, between lines 232/238, the charging state is the "default" state, so we'll have to add another state (knowing that when in threshold, the battery status return "Unknown"). Something like:

`const auto label = [this] {
      switch (m_state) {
        case battery_module::state::FULL: return m_label_full;
        case battery_module::state::DISCHARGING: return m_label_discharging;
        case battery_module::state::LOW: return m_label_low;
        case battery_module::state::CHARGING: return m_label_charging;
        default: return m_label_unknown;
      }`

**Comment by patrick96** [comment]
> Ok thanks. So I guess there is a reason why, like some laptops doesnt have a battery/status?

This was this way even before I got involved with polybar. My guess is that jaagr just tried to cover all his bases.

> I thought about a simple solution like have an option to bypass the adapter-check

It probably makes sense to check `status` before `online` because the `status` file has more information.

> but if I understand, between lines 232/238, the charging state is the "default" state, so we'll have to add another state (knowing that when in threshold, the battery status return "Unknown"). Something like:

This really depends on how we can differentiate the threshold state from other states. But if possible, I think we should add a separate `THRESHOLD` state. Just a value of `Unknown` may not only be used with threshold (could also appear in dual battery setups when one of the batteries is neither charging nor discharging).

**Comment by qtaped** [comment]
(11 months later...)
I just try your solution, aka check battery status before ac online and it works fine now.

I think this is better even for user with 2 batteries, since polybar display status for one battery, if ac is plugged that didnt mean this one is charging. And laptops with multiple adapter ports (multiple USB-C or USB-C + magsafe for the last Macbook Pro for example) should benefit too. I guess.

(I dont know if I'm doing it the right way but I clone the repository, made and commit my change if it can help. First time I am pushing on github.)

**Comment by Hanaasagi** [comment]
Hello, any new progress here? I have the same problem  https://github.com/polybar/polybar/issues/2563.

**Comment by qtaped** [comment]
> Hello, any new progress here? I have the same problem #2563.

Waiting for approval, the workaround suggested by @patrick96 is working fine.

**Comment by patrick96** [comment]
> (I dont know if I'm doing it the right way but I cloned the repository, made and committed my change if it can help. First time I am pushing on github.)

They way you did it is exactly how you create a PR on GitHub. Reviewing now.
