### ISSUE TITLE
module bspwm warning message for T@

### ISSUE THREAD

**Issue by EdwarddrawdE** [polybar/polybar#2371]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

When running polybar on bspwm window manager and having a terminal open, at times the message " warn: polybar module/bspwm undefined T => '@' " will be displayed.

**Expected behavior:**

No warning message due to not having a crash or problem with either bspwm or polybar itself.

**Actual behavior:**

The terminal will spam the warning message. I was informed that T@ indicates the node I currently have selected doesn't have a client in it, such as having 2 windows open and I select the parent node. I'm unsure if this is strictly the bspwm behavior leading to the polybar output of the bspwm module.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
* If no, what was the last version where this worked correctly?

## To Reproduce

```
killall -q polybar
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# Launch bar1 and bar2
polybar -c ~/.config/polybar/config.ini main &
```

This is a quote from someone on what the output is, but also possible to explain how to reproduce it:

"T@ indicates the node you currently have selected doesn't have a client in it
like when you have 2 windows open and you select the parent node"
## Polybar Log

```
warn: polybar module/bspwm undefined T  => '@' 
warn: polybar module/bspwm undefined T  => '@' 
warn: polybar module/bspwm undefined T  => '@' 

```

## Screenshots

https://i.imgur.com/51tSqmz.png
## Environment:
* WM: bspwm
* Distro: gentoo
* Output of `polybar -vvv`:

```
polybar 3.4.3

Features: +alsa -curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Gentoo
Compiler: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -O2 -pipe -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-O1 -Wl,--as-needed 
```

## Additional context

While I don't have a clear way to explicitly trigger the warning message because I am a novice user, it does happen over time. It will just take an open terminal that has unrelated usage and output the message. I'm not sure how to open/close the parent windows or re-create the scenario but a more capable bspwm user might be able to read the information and know exactly how to trigger the result. Any help will be appreciated!

**Comment by patrick96** [comment]
Thanks for the detailed report.

> "T@ indicates the node you currently have selected doesn't have a client in it
like when you have 2 windows open and you select the parent node"

Since this isn't really a special state, I think the bspwm should ignore it, but not produce a warning. I think this basically involves just adding an extra case in the switch statement that produces this warning.

**Comment by LowzG** [comment]
Gave this a try as my first contribution to the project
