### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by ahmadshaik1106** [polybar/polybar#2372]
I searched through internet about keyboard shortcuts to navigate in polybar. I didn't found one

Navigation through keyboard is faster, rather than using a mouse to click on polybar icons.

It is better to have a shortcut(key binding) 
Just ctrl + alt + tab on Debian/Ubuntu to navigate through desktop applications,dock,top bar.

As I said, I can't find a keybinding/shortcut to navigate in polybar. Please let me know if it already exists.

Thanks in advance!

**Comment by patrick96** [comment]
I'm not really sure what you're use-case is. Polybar's main purpose is to display information with mouse interactions as a convenience. In most cases, the polybar window is not focusable, so literally selecting elements on the bar with your keyboard is not possible.

Every module that is controllable via mouse click can also be controlled through a command (which could be bound to a key). The full list of supported actions is described [here](https://polybar.readthedocs.io/en/stable/user/actions.html).

If you want to use polybar to quickly select and execute certain commands, I think you would be better served with something like rofi or dmenu.

**Comment by ahmadshaik1106** [comment]
I mean, the use-cases are adjusting backlight and volume controls without a mouse.

Anyhow, I I'll stick with mouse :)

**Comment by patrick96** [comment]
Why not create keybindings that do that?
