### ISSUE TITLE
Extra front padding for the xworkspaces and bspwm modules

### ISSUE THREAD

**Issue by j-james** [polybar/polybar#2373]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

Invisible padding around the bspwm / xworkspaces module pushes it off from the rest of the modules.

**Expected behavior:**

There shouldn't be front padding, and it should behave like other modules.

**Actual behavior:**

The internal module padding occurs as follows: " I II III". The front padding of this module bumps into the defined separator of the bar " | " and makes it look off. These are the only modules where this appears to happen (although, i3 is probably also affected).

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
  * Don't know.
* If no, what was the last version where this worked correctly?

## To Reproduce

```dosini
[bar]
separator = " | "
modules-left = text bspwm mod
[module/bspwm]
type = internal/bspwm
label-focused-foreground = #888
label-empty = ""
```

## Screenshots
Expected behavior:
![2021-02-12-121835](https://user-images.githubusercontent.com/35242550/107818497-8d354800-6d2c-11eb-9a8e-2ac051bcf9d9.png)

Actual behavior (bspwm)
![2021-02-12-121759](https://user-images.githubusercontent.com/35242550/107818494-8c9cb180-6d2c-11eb-9fe8-8391fa9e820c.png)

Actual behavior (xworkspaces)
![2021-02-12-121740](https://user-images.githubusercontent.com/35242550/107818491-8c041b00-6d2c-11eb-808c-1ea71c4b0f2f.png)

## Environment:
* WM: bspwm
* Distro: EndeavourOS
* Output of `polybar -vvv`:
```
polybar 3.5.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by patrick96** [comment]
Not a bug, I think. The default value for all the workspace labels is `%icon%  %name%`, since there aren't any icons defined, the `%icon%` token will be empty, thus the separating space appears on the left of the label making it look like extra padding.

It's a bit unfortunate that this is the default, but we can't really change that now because people that use the `%icon%` token might be relying on it.

**Comment by j-james** [comment]
That's too bad, but I figured out a workaround anyway:

```ini
[module/bspwm]
type = internal/bspwm
label-empty = ""
label-occupied = "%name% "
label-focused = "%name% "
label-monocle = " monacle"
label-tiled = " tiled"
label-fullscreen = " fullscreen"
label-floating = " floating"
label-pseudotiled = " pseudotiled"
format = <label-state>| <label-mode>
```
