### ISSUE TITLE
Add toggle to always show urgent workspaces in i3 module

### ISSUE THREAD

**Issue by zappolowski** [polybar/polybar#2374]
I'm running a multi-monitor setup using i3 and configured polybar to just display the workspaces of the current monitor (`pin-workspaces = true`). When a window gets the urgent hint (e.g. a messenger receiving a message) the workspace is highlighted, but only on the bar of the monitor where it happened.

It might be beneficial to add a toggle to allow to show urgent workspaces on the current bar even when the workspace itself is not on the current monitor (this just makes sense, if `pin-workspaces = true` is set).

I've implemented this already [here](https://github.com/polybar/polybar/compare/master...zappolowski:feature%2Fi3-always-show-urgent-windows). If accepted I'd open a PR.

**Comment by patrick96** [comment]
I think that's a good idea, go ahead and open a PR :smiley: 

I think `show-urgent` is a more concise name for the option.
