### ISSUE TITLE
Missing text in system tray

### ISSUE THREAD

**Issue by alourie** [polybar/polybar#2377]
I'm using a golang library to create a systray entry (https://github.com/getlantern/systray); it uses libappindicator to place the icons/text.

It works fine when using Gnome and Libappindicator shell extension, but it doesn't place the text in the tray area while using polybar (or, actually, trayer and stalonetray as well). The example code:

```
func main() {
	systray.Run(onReady, onExit)
}

func onReady() {
	systray.SetIcon(icon.Data)
	systray.SetTitle("Awesome App")
}

func onExit() {
	// clean up here
}
```

The code will place the icon in the tray but not the text ("Awesome App"). Any advice would be appreciated.

**Comment by patrick96** [comment]
Polybar (and stalonetray and I believe trayer as well) doesn't support appindicators. libappindicator uses a different protocol than polybar for the tray. See #2010

**Comment by alourie** [comment]
@patrick96 fair enough....what protocol should I be using to have the text/icon properly appear in the polybar's tray?

Thanks!

**Comment by patrick96** [comment]
I'm pretty sure we are using the freedesktop [systemtray spec](https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-latest.html). But if you're designing specifically for polybar, I'd recommend using the script module to display text (unless you also want to render images).

**Comment by alourie** [comment]
Thanks, @patrick96!
