### ISSUE TITLE
%output:x:y% sub-string ignores non-zero starting index

### ISSUE THREAD

**Issue by SayantanRC** [polybar/polybar#2383]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
If a `label` is set as sub-string of `%output%`, the beginning index do not work if non-zero.
For example:
```
[module/my_module]
type = custom/script
exec = "echo abcdefgh"
label = %output:2:4% %output:0:2%
```

**Expected behavior:**
In the above example, expected output is: `cd ab`

**Actual behavior:**
In the above example, actual output is `abcd ab`
Clearly, in the section `%output:2:4%` the beginning index `2` is being considered as `0`.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)? - Don't know

## To Reproduce
Try the module above :)

## Polybar Log
Nothing of much significance.
```
~ >>> polybar bottom                                                            
notice: Parsing config file: /home/src/.config/polybar/config
notice: Loaded font "icomoon:style=Regular" (name=icomoon, offset=0, file=/usr/share/fonts/TTF/polybar-icons.ttf)
notice: Loaded font "Material Design Icons:style=Regular:pixelsize=15" (name=Material Design Icons, offset=5, file=/usr/share/fonts/TTF/material-design-icons-extended.ttf)
notice: Loaded font "Sans:style=Regular:Bold=11" (name=Nimbus Sans, offset=4, file=/usr/share/fonts/gsfonts/NimbusSans-Regular.otf)


```

## Environment:
* WM: i3wm
* Distro: manjaro
* Output of `polybar -vvv`:

```
~ >>> polybar bottom                                                            
notice: Parsing config file: /home/src/.config/polybar/config
notice: Loaded font "icomoon:style=Regular" (name=icomoon, offset=0, file=/usr/share/fonts/TTF/polybar-icons.ttf)
notice: Loaded font "Material Design Icons:style=Regular:pixelsize=15" (name=Material Design Icons, offset=5, file=/usr/share/fonts/TTF/material-design-icons-extended.ttf)
notice: Loaded font "Sans:style=Regular:Bold=11" (name=Nimbus Sans, offset=4, file=/usr/share/fonts/gsfonts/NimbusSans-Regular.otf)


```

## Additional context
I think its a coding error in polybar and can be easily resolved.

**Comment by patrick96** [comment]
`%token:x:y%` does not output a substring. It's for minlen, maxlen: https://github.com/polybar/polybar/wiki/Formatting#tokens

So `%output:2:4%` will pad the contents of the token until it is two characters long and cut off anything beyond 4 characters.

**Comment by SayantanRC** [comment]
oh.. I think I have to make 2 different scripts for 2 modules then...

**Comment by patrick96** [comment]
I mean there are tools like `cut` that you can use to output a substring that you could pipe your command into.
