### ISSUE TITLE
Issue with dual battery setup

### ISSUE THREAD

**Issue by YeahBTW** [polybar/polybar#2389]
## Is your feature request related to a problem? Please describe.
I use a thinkpad with 2 batteries. When my internal battery dies in my bar it shows "%percentage%%". This is really annoying and it takes up a lot of space.

## Why does polybar need this feature?
Polybar needs this feature so if you have 2 batteries in your laptop and ones dies it does not look weird.

## Describe the solution you'd like
I think if polybar is not receiving any data it should not show anything, as in it should not display the module.

## Describe alternatives you've considered
It would also be nice if there was a way to click to collapse the module so it does not take up as much space.

## Additional context
![Screenshot_2021-02-23_09-46-36](https://user-images.githubusercontent.com/77241134/108860445-334e4100-75bc-11eb-83d2-684d5218b6f5.png)
It is the "%percentage%%" because after running the command `sudo tlp-stat -b` it showed that my internal battery was dead.

**Comment by patrick96** [comment]
This looks more like a bug report than a feature request. What version of polybar are you using?

At what percentage does this happen? When the battery is completely dead or when it drops to 10% or below?

Might be a duplicate of #2379

**Comment by YeahBTW** [comment]
I am on version 3.5.4
It happens when the battery is below 10% (I think this is when it starts) as can be seen by the output of tlp-stat -b

+++ Battery Features: Charge Thresholds and Recalibrate
natacpi    = active (data, thresholds)
tpacpi-bat = active (recalibrate)
tp-smapi   = inactive (ThinkPad not supported)

+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/class/power_supply/BAT0/manufacturer                   = LGC
/sys/class/power_supply/BAT0/model_name                     = 01AV489
/sys/class/power_supply/BAT0/cycle_count                    =     19
/sys/class/power_supply/BAT0/energy_full_design             =  23940 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  22050 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =   1050 [mWh]
/sys/class/power_supply/BAT0/power_now                      =      0 [mW]
/sys/class/power_supply/BAT0/status                         = Unknown

/sys/class/power_supply/BAT0/charge_start_threshold         =     75 [%]
/sys/class/power_supply/BAT0/charge_stop_threshold          =     85 [%]
tpacpi-bat.BAT0.forceDischarge                              =      0

Charge                                                      =    4.8 [%]
Capacity                                                    =   92.1 [%]

as you can see my internal battery is at 4.8% but in polybar it shows %percentage% for how much charge it has.

**Comment by YeahBTW** [comment]
I think this is a duplicate of https://github.com/polybar/polybar/issues/2379 so I am closing this issue
