### ISSUE TITLE
Border with radius creates colored boxes on corners

### ISSUE THREAD

**Issue by iandwelker** [polybar/polybar#2406]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

Recently, PR #2359 was merged, which added curved corners. I tried this out, and saw that, although the borders were curved as they should be, small rectangles were also appearing on the corners of my bar.

**Expected behavior:**

No colored boxes should appear on the inner corners of the bar. See picture for what should be happening:
![polybar_fixed](https://user-images.githubusercontent.com/61218022/112866238-cf191400-9076-11eb-87a4-4d9bea3afcbe.png)

**Actual behavior:**

Colored boxes are appearing on the inner corners of the bar. See picture for what is happening:
![polybar_broken](https://user-images.githubusercontent.com/61218022/112866300-e0622080-9076-11eb-830e-32a9258d61e4.png)

**Was it working before?**
No, since this feature hadn't yet been implemented in polybar.

* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?

No, since the feature hadn't been implemented before.

## To Reproduce

```dosini
[bar/main]

width = 60%
height = 52

offset-x = 20%
offset-y = 0.5%

background = #70182232

radius-top = 16.0
radius-bottom = 16.0

border-bottom-size = 2
border-top-size = 2
border-left-size = 2
border-right-size = 2
border-color = #4088aaff

font-0 = "SF Pro:size=15;2"
modules-right = test

[module/test]
type = custom/text
content = "test"
```

Running the above config with `polybar main -c config.ini &` should reproduce the problem.

## Polybar Log

```
notice: Parsing config file: ./test_config.ini
notice: Loaded font "SF Pro:size=15" (name=SF Pro, offset=2, file=/usr/share/fonts/TTF/SF-Pro.ttf)
```

## Screenshots

See screenshots above

## Environment:
* WM: bspwm
* Distro: Arch Linux
* Output of `polybar -vvv`:

```
polybar 3.5.5-113-gd3797ace

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -Wsuggest-override -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context

I have forked the repo and have a pull request ready to go that should fix this issue. If you can reproduce this and think the problem should be fixed, just let me know and I'll file it for review. The screenshot under `Expected Behavior` is from polybar running on my fork.

Also, I don't know if it's relevant  (since the bar is partially transparent), but I use `picom` for compositing.

**Comment by patrick96** [comment]
I can reproduce this.

Looks like it happens only if the bar background is transparent. Weird that we never caught this.

Yes, please open a PR with your fix. Thanks :smiley:

**Comment by iandwelker** [comment]
Just opened #2407; thanks for the quick response :)
