### ISSUE TITLE
wm-restack = i3 not working correctly

### ISSUE THREAD

**Issue by legendofa** [polybar/polybar#2411]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
`wm-restack = i3` does not prevent the bar from showing in fullscreen.
If i set `override-redirect = false` the problem is fixed, but the window size of non-fullscreen windows is smaller with my i3-gaps configuration. I would like to keep `override-redirect = true`.

**Expected behavior:**
Bar is hidden while viewing fullscreen content.

**Was it working before?**
Not to my knowledge, but i read that wm-restack should prevent the bar to be shown in fullscreen mode.

## To Reproduce

```dosini
[bar/example]
override-redirect = true
wm-restack = i3
width = 100%
height = 35
radius = 0.0
fixed-center = true

modules-center = date 

[module/date]
type = internal/date
interval = 0.5

time = %H:%M:%S | %d. %m. %Y
time-alt = %H:%M:%S | %m. %d. %Y

label = %date% %time%
```

## Polybar Log

```
warn: No monitor specified, using "DP-4"
warn: No fonts specified, using fallback font "fixed"
warn: Ignoring unsupported wm-restack option 'i3'
```

## Environment:
* WM: i3
* Distro: nixos
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa -curl -i3 -mpd +network(libnl) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gcc-wrapper-9.3.0/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:
```

**Comment by patrick96** [comment]
> `warn: Ignoring unsupported wm-restack option 'i3'`

Your polybar was not built with i3 support, so the i3 restack option is not available.

To get i3 support, you need to compile polybar while having all [optional dependencies](https://github.com/polybar/polybar/wiki/Compiling#optional-dependencies) for i3 installed (i3 and jsoncpp). And i3 support must not be explicitly disabled.

**Comment by legendofa** [comment]
Thanks for the info, i will try that out.
