### ISSUE TITLE
xkeyboard extend icon str-match to variant

### ISSUE THREAD

**Issue by birdspider** [polybar/polybar#2414]
Given that `%variant%` is implemented now in `internal/xkeyboard` - it would be nice to be able to configure  `layout-icon-N`, not only on layout-str but also on variant-str.

### Usecase: 

```
setxkbmap -rules evdev -model evdev -layout us,us -variant altgr-intl,colemak_dh
```

2 x `us` layout - how would one configure the icon?

https://github.com/polybar/polybar/wiki/Module:-xkeyboard mentions that icons for `layouts` are "found" by str-search, how about extending to `variant` search: (see last line)

### Configuration idea:

```
; layout-icon-[0-9]+ = layout;icon
; Assign each layout an icon that will be available as %icon% token for the
; <label-layout> tag. The part before ';' will try to match %layout% value.
layout-icon-default = some-icon
layout-icon-0 = ch;C
layout-icon-1 = us;U
layout-icon-2 = us;colemak;U2      <------ new 
```

**Comment by polkacode** [comment]
I support this idea.
I use two different us layouts too and so far I could also not figure out, how to define icons for them. And sorry, displaying %variant% occupies just too much space for this little information.

**Comment by parmort** [comment]
I like the idea, but I'm not sure how feasible it is. It might be easier to create a `variant-icon` tag?

**Comment by patrick96** [comment]
I think matching both the layout and variant at once should be possible, the matching logic may just get a bit more complicated. Matching them together also gives more flexibility and maybe it could be extended to allow for variant-only matching by specifying an empty layout (e.g. `layout-icon-* = ;colemak;...`).

The matching logic would need to prefer an exact layout & variant match to just a layout or just a variant match. Also, an empty variant in `layout-icon-*` should probably only match keyboard configurations without a variant set and is different from no variant being specified in the match string.

I'll mark this as "help wanted". If anyone wants to take a crack at this, let me know.

**Comment by dvermd** [comment]
I'd like to work on this one.
The `layout-icon-*` configuration may be updated to be:
```
; layout-icon-[0-9]+ = layout;icon
; layout-icon-[0-9]+ = layout;variant;icon
; Assign each layout an icon that will be available as %icon% token for the
; <label-layout> tag. 
; In the first configuration form, the `layout` will try to match %layout% value without using any variant
; In the second configuration form, 
;     the `layout` will try to match %layout% value and the `variant` will try to match %variant%.
;     the `variant` can be empty to match against a %layout% with an empty %variant%
;     the `variant` can be the wildcard '_' to match a %layout% and any variant. 
;         This is equivalent to the first configuration form
;     the `layout` can be the wildcard '_' to match any %layout% with a specific %variant%
; These are incorrect configuration
;     '_;_;icon': use layout-icon-default instead
;    ';variant;icon':  there can't be a %variant% without a %layout%
```

The layout, variant are matched against defined icons in that order:
1. perfect match on layout and perfect match on variant (ex: us;Colemak;<icon>)
2. perfect match on layout and case insensitive search on variant (ex: us;coLEmAk;<icon>)
3. perfect match on layout and the any variant '_' (ex: us;<icon> or us;_;<icon>)
4. perfect match on layout and no variant (ex: us;;<icon>)
5. no layout for icon and perfect match on variant (ex: _;Colemak;<icon>)
6. no layout for icon and case insensitive search on variant (ex: _;coLEmAk;<icon>)
7. no match at all => default icon if defined

**Comment by patrick96** [comment]
Just to confirm, is `layout;icon` equivalent to `layout;_;icon`?

Number 4 in the matching order shouldn't exist, if `us;;` is a match, that is equivalent to number 1, a case-sensitive layout + variant match.

Otherwise the matching order seems reasonable and should be backwards compatible :+1: 

If two matchings are equivalent, the first one should be used. This is also what happens right now if you for example have:

```
layout-icon-0 = us;iconA
layout-icon-1 = us;iconB
```

`iconA` is used. As an alternative, we could print a warning or error if we detect equivalent matchings.

For the `_;_;` matching. I don't think there should be multiple ways to define a default icon. Either we should deprecate `layout-icon-default` and only support `_;_;` or completely disallow wildcards for both entries (and just ignore them).

---

One thing I am wondering, and this may be out of scope for your PR because it will likely require quite a few changes, is whether a different syntax for mappings may not be more appropriate:

```
layout-icon[us] = iconA
layout-icon[us][Colemak] = iconB
```

It would certainly look a lot nicer. I am also not a big fan of using numbered lists when the numbering itself is irrelevant.

Maybe we could takle this after we merge the feature (but before it makes it into a release) and adapt the config parser to support these kinds of things later. The matching logic should be independent of how the matching definitions are represented in the config anyway.

**Comment by dvermd** [comment]
> Just to confirm, is `layout;icon` equivalent to `layout;_;icon`?

Indeed, they're equivalent

> Number 4 in the matching order shouldn't exist, if `us;;` is a match, that is equivalent to number 1, a case-sensitive layout + variant match.

You're right, the number 4 is included in the number 1.

> If two matchings are equivalent, the first one should be used. This is also what happens right now if you for example have:
> 
> ```
> layout-icon-0 = us;iconA
> layout-icon-1 = us;iconB
> ```
> 
> `iconA` is used. As an alternative, we could print a warning or error if we detect equivalent matchings.

Understood, the first match with the same number is the winner.

> For the `_;_;` matching. I don't think there should be multiple ways to define a default icon. Either we should deprecate `layout-icon-default` and only support `_;_;` or completely disallow wildcards for both entries (and just ignore them).

I think I prefer the `layout-icon-default` syntax that is more explicit.
For now, if it's defined alongside `_;_;icon`, I'll log a warning and ignore it.

> One thing I am wondering, and this may be out of scope for your PR because it will likely require quite a few changes, is whether a different syntax for mappings may not be more appropriate:
> 
> ```
> layout-icon[us] = iconA
> layout-icon[us][Colemak] = iconB
> ```
> 
> It would certainly look a lot nicer. I am also not a big fan of using numbered lists when the numbering itself is irrelevant.

That map-like syntax is really more explicit and would surely make the configuration more readable.
You're right it deserves it's own issue for tracking.
 
> Maybe we could takle this after we merge the feature (but before it makes it into a release) and adapt the config parser to support these kinds of things later. The matching logic should be independent of how the matching definitions are represented in the config anyway.

This change looks like a breaking change in the configuration (at least of xkeyboard) except if we accept both syntaxes in the same configuration file then some priorities must be defined between syntaxes

**Comment by patrick96** [comment]
> This change looks like a breaking change in the configuration (at least of xkeyboard) except if we accept both syntaxes in the same configuration file then some priorities must be defined between syntaxes

Yeah, we would have to accept both and print a deprecation warning for the old syntax.
