### ISSUE TITLE
module/script: precise output shall be \n terminated in wiki

### ISSUE THREAD

**Issue by ramacassis** [polybar/polybar#2415]
Hello,
As I was playing with a simple module/script, I was not able to get a polybar display from a script output like:
`printf "%s %02d" "<my_string>" 2`

Or simpler,
`echo -n <sth>`

Not a C++ specialist but I believe it comes from the readline() function used in script.cpp (which need an explicit newline character to parse output)

Should this precision be put in the wiki section ? (that the script output shall be \n terminated)
Is it better if I make the request directly by editing the wiki section ?

Thanks, and congrats for this amazing project !

**Comment by patrick96** [comment]
Yes, please clarify this directly on script module wiki page. Thanks :)

This never really occured to me that someone would not terminate their output with a newline.
