### ISSUE TITLE
Compatibility issue due to Sphinx  v4.0.0

### ISSUE THREAD

**Issue by florianperrenet** [polybar/polybar#2424]
## Checklist

* [X] I have followed every step on the [compiling wiki page](https://github.com/polybar/polybar/wiki/Compiling) and
  installed all necessary dependencies.
* [X] My problem is not described on the [known issues page](https://github.com/polybar/polybar/wiki/Known-Issues)
* [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X] I was able to reproduce this build issue in a clean build

## Build Process

**How did you build polybar?**

* [X] By cloning this repository (What is the output of `git describe --tags`?)
* 3.5.5 (also tested olders versions)

```bash
./build.sh
```

## Build Log

```
CMake Error at doc/cmake_install.cmake:50 (file):
  file INSTALL cannot find
  "/home/florian/programs/polybar/build/doc/man/polybar.1": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:51 (include)


make: *** [Makefile:83: install] Error 1
** Failed to install executables...
```

## Additional context

Due to the new Sphinx 4.0.0 release `/home/florian/programs/polybar/build/doc/man/polybar.1` doesn't exist, instead `/home/florian/programs/polybar/build/doc/man/1/polybar.1` is generated. And therefore INSTALL cannot find it.

Downgrading Sphinx to 3.5.4 solved the issue.

**Comment by patrick96** [comment]
Thanks for letting us know. I have a fix in #2425
