### ISSUE TITLE
Font display problem

### ISSUE THREAD

**Issue by nemo231987** [polybar/polybar#2432]
I managed to install polybar on my raspberry, only one problem I currently have ... I cannot activate the fonts (I have installed the awesome ones) if I insert any image this is not displayed on the bar, on the onfig file I have inserted these lines: ont -3 = Font Awesome 5 Free: pixelsize = 12; 2
font-4 = Font Awesome 5 Free Solid: pixelsize = 12; 2
font-5 = Font Awesome 5 Brands: pixelsize = 12; 2 ideas?

**Comment by patrick96** [comment]
The issue tracker is meant for bug reports and feature requests. Please don't ask support questions here, read our [Support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) for a list of resources where you can ask questions. We are more than happy to help you there.

In your case, you should also read our font debugging guide: https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues
