### ISSUE TITLE
Font Polybar

### ISSUE THREAD

**Issue by nemo231987** [polybar/polybar#2434]
Hi,
I followed the guide to install the fonts and inserted the lines:  

font-3 = Font Awesome 5 Free:pixelsize=12;2
font-4 = Font Awesome 5 Free Solid:pixelsize=12;2
font-5 = Font Awesome 5 Brands:pixelsize=12;2

in the config file but I can't see the icons on the bar in any way ... do you have any ideas?

**Comment by patrick96** [comment]
The issue tracker is meant for bug reports and feature requests. Please don't ask support questions here, read our [Support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) for a list of resources where you can ask questions. We are more than happy to help you there.
