### ISSUE TITLE
xworkspaces crashes polybar segfault

### ISSUE THREAD

**Issue by paulhersch** [polybar/polybar#2440]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

Polybar crashes with segfault when i start it with the xworkspaces module under leftwm, without it everything is running perfectly fine

**Expected behavior:**

I can run Polybar with the xworkspace module to see my workspaces

**Actual behavior:**

Polybar doesn't start/instantly crashes

**Was it working before?**
it was working when i used the module for the first time for some reason, but now it doesn't any more
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
no because i used the i3 module because i used i3 instead of LeftWM
* If no, what was the last version where this worked correctly?

## To Reproduce

This is the module that makes polybar crash
```
[module/ewmh]
type = internal/xworkspaces

label-active = 
label-active-foreground = ${colors.foreground}
label-active-background = ${colors.accent}
label-active-underline = ${colors.foreground}

label-occupied = 

label-urgent = 
label-urgent-foreground = ${colors.background}
label-urgent-background = ${colors.foreground}
label-urgent-underline  = ${colors.foreground}

label-empty = 
label-empty-foreground = ${colors.unfocused}


```

## Polybar Log

```

```
Theres is nothing else besides a segfault message

## Environment:
* WM: LeftWM
* Distro: Manjaro
* Output of `polybar -vvv`:

```
~ > polybar -vvv
polybar 3.5.5

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context

I installed Polybar via the AUR
when i was using polybar with the module it worked on this one session but stopped working in a new Xsession (didn't update anything)
also I am using picom-joanburg, although this might not be problematic really

**Comment by patrick96** [comment]
I can't reproduce this issue. Could you please share your entire config and also post the entire polybar output (polybar always outputs at least one line telling you which config it loaded), maybe also run it with `-l trace`.

Also, try to update your polybar, there was an update a few days ago.

**Comment by paulhersch** [comment]
Installed the newest -git version, issue is solved
