### ISSUE TITLE
[feature request] New format : Progress Circle/Arc

### ISSUE THREAD

**Issue by TheTrveAnthony** [polybar/polybar#2441]
Hi,

## Is your feature request related to a problem? Please describe.
Not really, but here is I actually want to do:
I want to display CPU and memory usage with progress arcs, and as you already know it, this formatting feature is not avaiable in polybar, I tried another solution to mimic that (I'll discuss it in the appropriate section) but it didn't work.

## Why does polybar need this feature?
Because progress arcs look great on a status bar (in my opinion), and it's polybar's main goal to help people making sick looking status bars right ?

## Describe the solution you'd like
This would actually be an alternative to status bar. As I said I want to use this for cpu and ram, but it could be used for battery, volume, brightness and filesystems modules as well. Basically, the user would have to define the arc like this: (exemple with memory module)

```
[module/memory]
type = internal/memory
format = <arc-used>

arc-used-radius = 10
arc-used-thickness = 5
arc-used-foreground = #000000
arc-used-background = #ffffff
arc-used-start-angle = 270  ; default 0
arc-used-border = 1
arc-used-border-color = #123456
arc-used-text = %mb_used%  ; if the user wants text inside the arc
```

## Describe alternatives you've considered
I did try to create a font with arc glyphs for each values, but the tools I found couldn't convert the svg files I made properly, because they contain shape description instead of paths, and I couldn't find something to convert shapes into paths as well, so in the end having this feature directly in polybar is my last hope.

## Additional context
That would look like this (screenshot from my plasma desktop)
![circles](https://user-images.githubusercontent.com/40374762/120084249-eef8a280-c0ce-11eb-9207-278e3adcddd8.png)

Thank you for reading and hopefully, considering this request.
Have a nice evening

**Comment by patrick96** [comment]
Sorry for the delay.

This is a very neat idea and I agree it would look amazing.

However, this is outside of the scope for polybar for now. Polybar is purely text-based (with exception for a very hacky tray) and so trying to put anything else on the bar is not feasible, simply for the reason that polybar was not designed for it.

There were already attempts to put images into the bar and even that was already extremely difficult and in the end went nowhere.

For now, we will not consider adding non-text element into the bar. This can of course change in the future, if polybar is at a point where it could facilitate such a thing.
