### ISSUE TITLE
Stop bars from shutting down themselves when a monitor switch input signal between two machines

### ISSUE THREAD

**Issue by alo0oz** [polybar/polybar#2444]
## Is your feature request related to a problem? Please describe.
I’m using the same monitor for two different machines at the same time. When I switch from one machine to my other machine and come back to first machine using the monitors input signal switching, my polybar closes itself showing the below output---
````polybar|notice:  randr_screen_change_notify (1920x1080)... reloading
polybar|notice:  Termination signal received, shutting down...
polybar|notice:  randr_screen_change_notify (1920x1080)... reloading
polybar|notice:  Termination signal received, shutting down...
polybar|notice:  Parsing config file: /home/arafat/.config/polybar/config
polybar|notice:  Parsing config file: /home/arafat/.config/polybar/config
polybar|error: No monitors found
polybar|error: No monitors found
````
Please give us a option to persistently run polybar. This is a big inconvenience to re-run polybar each time I switch between two machines.

## Why does polybar need this feature?
This feature will help people like me who need to use the same monitor for different machines at the same time. 

## Describe the solution you'd like
either a option when running the bars to make the bar persistent regardless of a monitor disconnection signal or run polybar persistently all the time.

**Comment by patrick96** [comment]
The bar is persistent by default. You probably have the `screenchange-reload` setting in your config set to true which causes a reload everytime the screen configuration changes and in your case the monitor has disappeared so the bar doesn't start anymore.
