### ISSUE TITLE
Font charwidth has no effect

### ISSUE THREAD

**Issue by qsmodo** [polybar/polybar#2445]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
If I set

    font-0 = Terminus-10

the Terminus font is loaded as expected (I've double checked it in `fc-match`). However, I find its characters are too spread apart from each other, so I tried the [`charwidth` specifier](https://keithp.com/~keithp/render/Xft.tutorial):

    font-0 = Terminus-10:charwidth=7

**Expected behavior:**
The characters of the font should be slightly squeezed together.

**Actual behavior:**
No effect, the font is loaded as just before.

**Was it working before?**
I don't know because I did not use Polybar before.

## To Reproduce

```dosini
[bar/issue]
font-0 = Terminus-10:charwidth=10
modules-right = text
[module/text]
type = custom/text
content = label
```

## Polybar Log

For `charwidth=10`:

```
notice: Parsing config file: /home/user/.config/polybar/config
notice: Loaded font "Terminus-10:charwidth=10" (name=Terminus, offset=0, file=/usr/share/fonts/opentype/terminus/terminus-normal.otb)
```

For `charwidth=7`:
```
notice: Parsing config file: /home/user/.config/polybar/config
notice: Loaded font "Terminus-10:charwidth=7" (name=Terminus, offset=0, file=/usr/share/fonts/opentype/terminus/terminus-normal.otb)
```

## Environment:
* WM: Spectrwm
* Distro: Debian
* Output of `polybar -vvv`:

```
polybar 3.5.5

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Debian package, build flags removed from output for reproducibility
You can refer to the build logs at:
https://buildd.debian.org/status/package.php?p=polybar
```

## Additional context

The exact same setting does work in the built-in bar of my window manager (Spectrwm). Please note that changing the format to `Terminus:size=10:charwidth=7` also has no effect, and that I tried various `charwidth` values.

**Comment by patrick96** [comment]
Our text rendering isn't the best because we do it at a very low level, so unless cairo (what we use for font rendering) directly honors this property or the property causes a different font file to be loaded, it probably won't work in polybar.

At some point we will want to start using a more powerful font rendering library that does the heavy lifting for us (see https://github.com/polybar/polybar/issues/2369).

I'm going to mark this as "won't fix" because any time spent on implementing this would be better spent on exploring a different font rendering library.

**Comment by qsmodo** [comment]
Thanks. If someone stumbles on this issue, I've found that Dzen works fine.
