### ISSUE TITLE
Noto Color Emoji fonts are found but no emoji gets printed

### ISSUE THREAD

**Issue by Chiyo-no-sake** [polybar/polybar#2448]
## Checklist

* [ x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x ] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x ] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [ x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
In my terminal everything is working, i'm able to see all emoji's, but within polybar, emoji's are not printed.

JetBrainsMono is working, Noto Color Emoji is not working even if in the logs of polybar I can see that it does find successfully the font, hence, no unmatched character gets printed to the logs.
I even tried with EmojiOne font, and without the truetype parameter.
I've already tried removing the scale, setting the pixelsize, enabling anti-aliasing and so on.

fc-match successfully find the fonts too.

**Expected behavior:**
I can see colored emoji in polybar such as 🔉.

**Actual behavior:**
Polybar doesn't print the emoji, however, it seems to "make space" where the emoji should stand.

## To Reproduce

These are my configurations for setting the font in polybar:
```
font-0 = "JetBrainsMono NF:pixelsize=12;1"
font-1 = "Noto Color Emoji:fontformat=truetype:scale=10:antialias=false;"
```

How I use the fonts:
```
ramp-volume-0 = 🔈
ramp-volume-1 = 🔉

ramp-volume-font = 2
```
How I also tried it:
```
ramp-volume-0 = %{T2}🔈%{T-}
...
```

## Polybar Log
This is the log of polybar with ```-l info```. The unmatched character you see here is not the only being rendered, but is the only one missing and i don't know why.
```
notice: Parsing config file: .config/polybar/material/config.ini
* Created ipc channel at: /tmp/polybar_mqueue.1241989
warn: No monitor specified, using "DP-0"
* Loaded monitor DP-0 (1920x1080+0+0)
* Bar geometry: 1920x25+0+0; Borders: 3,3,3,3
* Starting application
* Starting module/bspwm
* Starting module/title
* Starting module/network
* module/bspwm: Parsing socket data: MDP-0:o1:O2:f3:f4:f5:f6:f7:f8:f9:f10:LT:TT:G
* Starting module/cpu
* Starting module/backlight
* Starting module/battery
* Starting module/date
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=9)
* Configured DPI = 90x90
notice: Loaded font "JetBrainsMono NF:pixelsize=12" (name=JetBrainsMono NF, offset=1, file=/home/kalu/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete Mono Windows Compatible.ttf)
notice: Loaded font "NotoColorEmoji:fontformat=truetype:scale=10:antialias=false" (name=Noto Color Emoji, offset=0, file=/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf)
* Bar window: 0x0400003
* Successfully restacked bar window
* Activating tray manager
* Tray window: 0x0400007
* module/bspwm: Rebuilding cache
* module/title: Rebuilding cache
* module/network: Rebuilding cache
* module/cpu: Rebuilding cache
* module/backlight: Rebuilding cache
* module/battery: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character ️ (U+fe0f) in '⬇️'
* module/network: Rebuilding cache
* Notifying pending tray clients
* Processing docking request from 'pasystray' (0x4400020)
* Processing docking request from 'Bluetooth Enabled' (0x1400218)
* Processing docking request from 'Discord' (0x18004a0)
* Processing docking request from 'mailspring' (0x0c00017)
* Redrawing bar window
warn: Dropping unmatched character ️ (U+fe0f) in '⬇️'
* Redrawing bar window
* Processing docking request from 'Network' (0x4600036)
warn: Dropping unmatched character ️ (U+fe0f) in '⬇️'
```

## Environment:
* WM: bspwm
* Distro: ubuntu 20.04
* Output of `polybar -vvv`:

```
polybar 3.5.6

Features: +alsa +curl -i3 -mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm -xcursor

Build type: Release
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:
```

## Additional context
This is my font.conf (to ensure that nothing is wrong here):
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <dir>~/.fonts</dir>
 <match target="font">
  <edit mode="assign" name="hinting">
   <bool>false</bool>
  </edit>
 </match>
 <match target="font">
  <edit mode="assign" name="hintstyle">
   <const>hintnone</const>
  </edit>
 </match>
 <match target="font">
  <edit mode="assign" name="antialias">
   <bool>true</bool>
  </edit>
 </match>
<alias>
    <family>serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
```

**Comment by patrick96** [comment]
Could you please post your entire config? I don't see any mention of any kind of volume module in your log, what's the name of the module these characters are in?

**Comment by KatonKalu** [comment]
> Could you please post your entire config? I don't see any mention of any kind of volume module in your log, what's the name of the module these characters are in?

Yes, that's becouse i used that emoji as an example, however, I got plenty of modules with plenty of emojis. 
As an example, here is the config of the date module:
```
[module/date]
type = internal/date
interval = 1.0
time = "%H:%M"
time-alt = "%a, %d %b %Y"
format = <label>
format-underline = ${color.primary}
label = %{T2}🕓%{T1} %time%
```

**Comment by patrick96** [comment]
I can't reproduce this, even with this config, the emojis display just fine.

You don't seem to be doing anything wrong with the fonts (otherwise you'd get unmatched character warnings).

Could you maybe go through our config debugging guide [here](https://github.com/polybar/polybar/wiki/Debugging-your-Config) and see if you can narrow this down to a minimal config that still has the issue?

**Comment by KatonKalu** [comment]
> I can't reproduce this, even with this config, the emojis display just fine.
> 
> You don't seem to be doing anything wrong with the fonts (otherwise you'd get unmatched character warnings).
> 
> Could you maybe go through our config debugging guide [here](https://github.com/polybar/polybar/wiki/Debugging-your-Config) and see if you can narrow this down to a minimal config that still has the issue?

This is the smallest config i'm able to write:
```
include-file = modules.ini

[global/wm]
margin-bottom = 0
margin-top = 0

[bar/main]
width = 100%
font-0 = "JetBrainsMono NF:pixelsize=12;1"
font-1 = "NotoColorEmoji:fontformat=truetype:scale=10:antialias=false;"
modules-center = title 
```

modules.ini:
```
[module/title]
type = internal/xwindow
format = <label>%{T2}🔥🔥🔥🔥%{T-}<label>
label = " %title%"
label-empty = Kalu@Ubuntu
```

And the problem is still there:
![Screenshot_20210617_201122](https://user-images.githubusercontent.com/20605899/122451248-36749f00-cfa8-11eb-87c4-9d48fcab2779.png)

**Comment by patrick96** [comment]
That is very weird. Can you run polybar additionally with the `-s` flag, this will print the bar contents to the terminal instead of to the bar. Do the emojis show up there?

**Comment by KatonKalu** [comment]
> That is very weird. Can you run polybar additionally with the `-s` flag, this will print the bar contents to the terminal instead of to the bar. Do the emojis show up there?

Yes I can see all the emojis there.

**Comment by patrick96** [comment]
Hmm, so definitely a rendering issue, but normally there should be a warning when polybar can't render something.

So this must mean that it is actually rendering it, but just with size 0 probably for some reason.

I am still struggling to reproduce this myself, so debugging this could prove difficult.
Can you do the following for me?

Run the bars `main1`, `main2`, `main3`, and `main4` from this config:

```dosini
[bar/main]
modules-left = text 

[bar/main1]
inherit = bar/main
font-0 = "NotoColorEmoji:scale=10"

[bar/main2]
inherit = bar/main
font-0 = "JetBrainsMono NF"

[bar/main3]
inherit = bar/main
font-0 = "JetBrainsMono NF"
font-1 = "NotoColorEmoji:scale=10"

[bar/main4]
inherit = bar/main
font-0 = "NotoColorEmoji:scale=1"

[module/text]
type = custom/text
content = 🔥😀😃😄😁😆😅
```

And report for which the emojis are displayed and for which they are not.

**Comment by KatonKalu** [comment]
The same as before, none of them works.
With main and main2 polybar prints the unmatched characters, but with the other bars i have no log, and emojis are not rendered. Fonts are loaded correctly in all the bars.

**Comment by patrick96** [comment]
Was finally able to reproduce this. The culprit is `hintstyle` in your fonts.conf. Setting it to `hintnone` doesn't display any emojis while setting it to one of `hintslight`, `hintmedium`, or `hintfull` displays them.

Someone also reported this as a bug on the noto emoji repo: https://github.com/googlefonts/noto-emoji/issues/353
