### ISSUE TITLE
Weird green line next to download speed

### ISSUE THREAD

**Issue by 92naMoN** [polybar/polybar#2452]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [ ] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

There is a vertical green line next to download speed. 

**Expected behavior:**

I expected to be just download speed without the vertical green line.

**Actual behavior:**

It has vertical green line next to the downloadspeed

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)? don't know
* If no, what was the last version where this worked correctly?

## To Reproduce

```dosini

```

## Polybar Log

```
I would post log file but there is no errors or warnings so i am even more confused. 
```

## Screenshots

![greenline](https://user-images.githubusercontent.com/79383086/122633575-9cad0f00-d0d9-11eb-97cc-90bf77b65996.png)
![ps](https://user-images.githubusercontent.com/79383086/122633581-a0409600-d0d9-11eb-9ee6-34bdcefb13ba.png)

## Environment:
* WM: bspwm
* Distro: Archl Linux 5.12.9
* Output of `polybar -vvv`: 

```
polybar 3.5.6

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
Please post your config

**Comment by 92naMoN** [comment]
https://pastebin.com/BhWgJMJ0

**Comment by patrick96** [comment]
The default background value for your formats (as defined in the `[settings]` section) is green, so in any part of the module where you don't explicitly change the background color of the format, you will get the green background.

Here this happens because the default padding for the format is 1 which adds 1 space of padding to the format and that space has a green background.

In the future, if you are not sure this is a bug in polybar, please ask on reddit, gitter or IRC first. The issue tracker is primarily meant for bugs.
