### ISSUE TITLE
Make IPC module accept arbitrary text over the socket

### ISSUE THREAD

**Issue by vincentbernat** [polybar/polybar#2455]
Currently, to extend polybar, we can either use the script module or the IPC module. The script module allows to do anything, but you have to spawn a new process. With the `tail` directive, it's possible to avoid spawning processes at a regular interval. But, a distinct process is still needed (and it eats some memory). With the IPC module, you can trigger an update from another process, but this will run a script to make the update (and it eats CPU and battery).

Something between the two could be useful: extend the IPC module to allow sending arbitrary text to be displayed instead of just a hook number.

I am willing to implement this, but as there is already some issues around the IPC module, I would like to gather some feedback and agreement around such a feature.

See #1127 and #1670 which are somewhat related.

**Comment by patrick96** [comment]
I think there has been demand for this in the past as well and I think this would fit in polybar.

I do have some thoughts:

* Polybar already has a one-way FIFO it uses for IPC, we should also use it for this feature. In fact, we could (and probably should) just create a module action where the data is the text sent to the module.
* I'm not sure if we should extend the IPC module, it's probably better to have a new module dedicated for this. Unless you have an argument why this would integrate well with the IPC module.
