### ISSUE TITLE
Do not add spaces when a format is empty

### ISSUE THREAD

**Issue by vincentbernat** [polybar/polybar#2458]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
Using the following configuration:

```dosini
[module/disk]
type = internal/fs
mount-0 = /
mount-1 = /home
mount-2 = /var
mount-3 = /tmp
mount-4 = /boot
mount-5 = /var/lib/systems
warn-percentage = 80
fixed-values = true
interval = 15
format-unmounted =
format-mounted =
format-warn = <label-warn>
format-warn-foreground = #ff0000
label-warn = %mountpoint%: %percentage_used%%
```

If only `/` and `/home` are over 80%, I get additional spaces due to spacing behind added between each format.

**Expected behavior:**
No spaces should be added between empty formats.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/631446/125169581-2b79ec80-e1ab-11eb-926a-aa1075dbb0bc.png)

I have tried to play around the code, but the workflow is a bit mysterious to me. Is the actual way the builder work documented?

## Environment:
* WM: i3
* Distro: Debian
* Output of `polybar -vvv`:

```
 18:19 ❱ polybar -vvv
polybar 3.5.6-122-gdcd33057fda1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/lib/ccache/c++
Compiler flags:  -Wall -Wextra -Wpedantic -Wsuggest-override -O3 -DNDEBUG
Linker flags:
```

**Comment by patrick96** [comment]
Thanks for the report, I have a fix in #2459
