### ISSUE TITLE
Click right for alsa

### ISSUE THREAD

**Issue by lioaslan** [polybar/polybar#2462]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
I try to map `click-right` of `internal/alsa` with `pavucontrol` ([PAVC](https://archlinux.org/packages/extra/x86_64/pavucontrol/))  but there isn't anything that appeared. 
```
click-right = puvacontrol &
```
Of course, I'm sure that I can access PAVC from the terminal.

## Polybar Log
Nothing, I try replacing command `echo "abc" ` but it still didn't show anything.

## Environment:
* WM: bspwm
* Distro: Arch
* Output of `polybar -vvv`:

```
polybar 3.5.6

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
The alsa module does not have the `click-right` key, as a workaround you can use [action tags](https://github.com/polybar/polybar/wiki/Formatting#action-a) to define your own clickable areas.
Also, since you seem to be using pulseaudio, the [pulseaudio module](https://github.com/polybar/polybar/wiki/Module:-pulseaudio) may better suit you. It is more stable and it has `click-right`.

**Comment by lioaslan** [comment]
It's amazing. When I use alsa, I can't control volume with this module while using bluetooth headphones.  Now it works completely
