### ISSUE TITLE
Socket should be in /run/user/XXXX/polybar

### ISSUE THREAD

**Issue by vincentbernat** [polybar/polybar#2465]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
Polybar creates its IPC socket in `/tmp`. This presents two problems:
* This is vulnerable to a symlink attack
* Many files may be present, forcing `polybar-msg` to process a long list of files

**Expected behavior:**
Polybar should create its socket in `/run/user/XXXX/polybar/`.

**Actual behavior:**
It creates it in `/tmp`.

I am willing to provide a patch if you agree with me.

**Comment by patrick96** [comment]
I think that's a good idea. Thanks for proposing this :)

I do have some questions/concerns though:

* Are there distros that do not have a `/run/` filesystem (e.g. systems without systemd)?
* We can't just stop using the fifos in `/tmp` because it would break backwards compatibility. Most people probably exclusively use `polybar-msg`, so this wouldn't be a concern, but unfortunately the location of fifo is kind of part of our API.
As a transition, we could deprecate the use of the file in `/tmp` and create a symlink to `/run/....` for the time being. I don't really know how we would notify the user that their current way of sending IPC is deprecated though. We should probably not directly make the fifo path part of the API and expose something like i3's `i3 --get-socketpath` but with an additional PID argument.

**Comment by vincentbernat** [comment]
All distributes have `/run` (or `/var/run` if we want to support older alternatives). However, some may not have `/run/user/XXXX`. `/run` is only writable by root. Therefore, if they don't have it, it would be a problem. In fact, the location is not a standard. What's a standard is that `$XDG_RUNTIME_DIR` should be available for this purpose and writable by the user. This is part of [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> There is a single base directory relative to which user-specific runtime files and other file objects should be placed. This directory is defined by the environment variable $XDG_RUNTIME_DIR. 

I didn't think about users not using `polybar-msg` (myself included). This seems quite a hassle. I was expecting something super easy. If we never are able to deprecate the old location, this seems pointless to do the change. Also, do we have users without `$XDG_RUNTIME_DIR`? I think this is pretty common. i3 is using that for example and fallback to `/tmp`. The change is from 2011 without a transition, but this is a bit different since people are unlikely to use the socket directly from a script.

**Comment by patrick96** [comment]
> I didn't think about users not using polybar-msg (myself included). This seems quite a hassle.

Yes, it's a bit unfortunate.

> I was expecting something super easy. If we never are able to deprecate the old location, this seems pointless to do the change

It's not that we can never remove it, but just not in a regular release. In the next major release (4.0) we'll be able to remove all deprecations.

> Also, do we have users without $XDG_RUNTIME_DIR? I think this is pretty common. i3 is using that for example and fallback to /tmp. The change is from 2011 without a transition, but this is a bit different since people are unlikely to use the socket directly from a script.

I have no idea how widespread `XDG_RUNTIME_DIR` is. It seems systemd systems set it, I don't know about other init systems. But we should have a fallback anyway. Either to `/tmp` or maybe somewhere in the user directory like `~/.cache/polybar` which would make only the current user have access to it.

I don't know what the situation for i3 was, but they probably had `i3 --get-socketpath` back then as well.

**Comment by vincentbernat** [comment]
>> I was expecting something super easy. If we never are able to
>> deprecate the old location, this seems pointless to do the change
>
> It's not that we can never remove it, but just not in a regular
> release. In the next major release (4.0) we'll be able to remove all
> deprecations.

Oh, that's fine then!

>> Also, do we have users without $XDG_RUNTIME_DIR? I think this is
>> pretty common. i3 is using that for example and fallback to /tmp.
>> The change is from 2011 without a transition, but this is a bit
>> different since people are unlikely to use the socket directly from
>> a script.
>
> I have no idea how widespread `XDG_RUNTIME_DIR` is. It seems systemd
> systems set it, I don't know about other init systems.

`XDG_RUNTIME_DIR` is indeed set by `pam_systemd.so`. Using a Devuan Live
CD (XFCE desktop without systemd), it's also here, so at least, it's not
exclusive to systemd.

> But we should have a fallback anyway. Either to `/tmp` or maybe
> somewhere in the user directory like `~/.cache/polybar` which would
> make only the current user have access to it.

An alternative would be to use a `/tmp/polybar-XXXX` directory (like
i3). This prevents symlink attacks as well. But your proposition seems
better and I don't see any argument against it.

**Comment by patrick96** [comment]
> `XDG_RUNTIME_DIR` is indeed set by `pam_systemd.so`. Using a Devuan Live
CD (XFCE desktop without systemd), it's also here, so at least, it's not
exclusive to systemd.

That's good to know.

> An alternative would be to use a `/tmp/polybar-XXXX` directory (like
i3). This prevents symlink attacks as well. But your proposition seems
better and I don't see any argument against it.

I'm fine with either.

**Comment by rehashedsalt** [comment]
[FD spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) says that `~/.cache` (or more specifically `$XDG_CACHE_HOME`) should only contain "user-specific non-essential (cached) data", so stuffing a FIFO there seems like a poor choice.

Obeying `$XDG_RUNTIME_DIR` and using `/tmp/polybar-XXXX` as a fallback seems like the best choice IMO.

**Comment by patrick96** [comment]
Hmm, in that case we shouldn't use `~/.cache`. Creating a directory in `/tmp` is the way to go then. However, we can't use `mktemp` with a pattern because we won't know where the file was created afterwards, so the directory would probably need to be something like `/tmp/polybar-<PID>/`

**Comment by patrick96** [comment]
@vincentbernat Have you already done any work on this? Because we might need to swtich over to using UNIX domain sockets for our IPC channel (see #2504). If you haven't started on this yet, I will do this and do the switch to sockets and the change of the file location in one step.

I will also deprecate both the manual syntax for ipc messages and sending IPC messages directly to the pipe without using `polybar-msg`.

**Comment by vincentbernat** [comment]
I did nothing. :)
