### ISSUE TITLE
[module/memory] Display MiB instead of GiB when GiB value is less than 1GiB

### ISSUE THREAD

**Issue by malta895** [polybar/polybar#2472]
## Is your feature request related to a problem? Please describe.
I find more intuitive if the memory/swap values are displayed in MiB instead of GiB when the value is less than 1 GiB, for better precision. 
For example, display `512 MiB` instead of `0.50 GiB`.

Coming from `i3-status`, which does this by default, I find this more appropiate

## Why does polybar need this feature?
I think that when values are lower than 1GiB is better to see their MiB value: we have an higher precision and the same number of digits. 

## Describe the solution you'd like
In addition to the already existing label tokens:
```
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
```
add something like: 
```
;   %mb_gb_used%
;   %mb_gb_free%
;   %mb_gb_total%
```
that show the memory value as described earlier.

I'd like the same options available also for swap.

**Comment by patrick96** [comment]
Hmm good idea :+1: 

But, I'd opt for different names:

```
;   %used%
;   %free%
;   %total%
;   %swap_total%
;   %swap_free%
;   %swap_used%
```

These would work similarly to `%upspeed%` and `%downspeed%` in the network module.
