### ISSUE TITLE
Polybar gives error when reloading from terminal

### ISSUE THREAD

**Issue by Kjvthomas** [polybar/polybar#2476]
## Checklist

* [X ] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [X ] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [X ] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X ] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

When loading into Xmonad, Polybar will not load. When I force it to load via commandline with prompt:
"polybar --reload mainbar-xmonad -c ~/.config/polybar/config &"

I get this error message:
"error: Invalid value for "bar/mainbar-xmonad.monitor", using default value (reason: Environment var ${MONITOR} does not exist (no fallback set))

**Expected behavior:**

I have my fallback set in my config file

[bar/mainbar-xmonad]
monitor = ${env:MONITOR}
;monitor-fallback = LVDS1
monitor-strict = false
override-redirect = false
width = 100%
height = 30
;offset-x = 1%
;offset-y = 1%
radius = 0.0
fixed-center = true
bottom = false
separator = |

**Actual behavior:**

It will load with an error, so I have a bandaid and i added the command to my auto start for now and is working:
"polybar --reload mainbar-xmonad -c ~/.config/polybar/config &"

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
* N/A
* 
* If no, what was the last version where this worked correctly?

## To Reproduce

```dosini

```

## Polybar Log

```
notice: Parsing config file: /home/sav3d/.config/polybar/config
~ ✦ Sun, Aug 08, 2021 | 01:04am ️  ┌───────────────────>
 │
error: Invalid value for "bar/mainbar-xmonad.monitor", using default value (reason: Environment var ${MONITOR} does not exist (no fallback set))
notice: Loaded font "Noto Sans:size=10" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "FontAwesome:size=13" (name=FontAwesome, offset=0, file=/usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.ttf)
notice: Loaded font "Noto Sans:size=10" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "Noto Sans Mono:size=10" (name=Noto Sans Mono, offset=0, file=/usr/share/fonts/noto/NotoSansMono-Regular.ttf)
notice: Loaded font "FontAwesome5Brands:size=13" (name=Font Awesome 5 Brands, offset=0, file=/usr/share/fonts/TTF/fa-brands-400.ttf)

```

## Environment:
* WM: xmonad
* Distro: arcolinux
* 
* Output of `polybar -vvv`:

```
└─> polybar -vvv
polybar 3.5.6

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by patrick96** [comment]
> ` ;monitor-fallback = LVDS1`

The semicolon at the beginning means that the line is commented out, so there is no fallback set in your config. Also the fallback mentioned in the error message is the fallback for the environment variable: `${env:MONITOR}`. A fallback would look like this: `${env:MONITOR:LVDS1}`

The error message is not causing polybar not to start (it just tells you it is using the default value).

I'm not exactly sure what the problem is. Under what circumstances is polybar not running? Because you say the command works when adding it to your auto-start.

**Comment by Kjvthomas** [comment]
> > ` ;monitor-fallback = LVDS1`
> 
> The semicolon at the beginning means that the line is commented out, so there is no fallback set in your config. Also the fallback mentioned in the error message is the fallback for the environment variable: `${env:MONITOR}`. A fallback would look like this: `${env:MONITOR:LVDS1}`
> 
> The error message is not causing polybar not to start (it just tells you it is using the default value).
> 
> I'm not exactly sure what the problem is. Under what circumstances is polybar not running? Because you say the command works when adding it to your auto-start.

In my xmonad config it says:
(sleep 2; run $HOME/.config/polybar/launch.sh) &
(polybar --reload mainbar-xmonad -c ~/.config/polybar/config &) &

Now I added that bottom line, because polybar wasn't starting.

****Trying Your Fix****
Now when using """polybar --reload mainbar-xmonad -c ~/.config/polybar/config &"""

 There are no errors. However it still wont launch with just """
(sleep 2; run $HOME/.config/polybar/launch.sh) &"""

 from the xmonad config, so im using the """polybar --reload mainbar-xmonad -c ~/.config/polybar/config &""" to launch it

So no more errors! Will close! Thanks for your help
