### ISSUE TITLE
BSPWM module: ignore hidden windows

### ISSUE THREAD

**Issue by maybeetree** [polybar/polybar#2478]
## Is your feature request related to a problem? Please describe.

I use polybar with BSPWM. I have keybinds to "minimise" and "uniminimise" windows. Minimising works by simply setting the `hidden` flag the currently focused window using the `bspc` command. Unminimising uses `bspc query` to find all hidden windows and then pipes them through dmenu. It then removes the 'hidden' flag from the chosen window, brings it to the current desktop, and focuses it.

The issue itself lies in the BSPWM module of polybar. It has the ability to show occupied and unoccupied desktops in different colors. The problem is that when determining whether a desktop is occupied or not, it takes into account hidden windows. So, a desktop will show up as occupied, even if it only contains hidden windows. This is rather inconvenient, since I have to keep a mental note of which workspaces are *actually* occupied, and which ones just happen to have hidden windows associated with them. 

So, my feature request is to add an option to the BSPWM module to ignore hidden windows when determining whether a desktop is occupied. In other words, there should be an option to treat desktops that only contain hidden windows as empty.

## Why does polybar need this feature?

I am sure that at least a few other people make use of the `hidden` flag in BSPWM, so it would be nice to have an option to make the 'bspwm' module show desktops that only contain hidden windows as empty. Moreover, even though hidden windows are technically associated with a desktop, I don't think many people actually keep this fact in mind. It's counterintuitive to think "well, this desktop is empty, but it's not actually empty, because there's a hidden window on it"

## Describe the solution you'd like

A configuration option called `ignore-hidden` (or something like that) for the bspwm module, that, if set to true, does not treat windows with the `hidden` flag set as belonging to a desktop, thus desktops occupied only by hidden windows will be shows as empty.

## Describe alternatives you've considered

My current workaround is to modify my "Minimise window" keybind to also move the window to the last desktop on the monitor, so that way only one desktop gets shows as occupied due to the hidden windows.

**Comment by patrick96** [comment]
This won't be possible in the bspwm module. The bspwm module takes the workspaces information directly from bspwm itself (basically by running `bspc subscribe -c 1 report`).

Bspwm reports that those workspaces are occupied and so polybar displays it that way. Polybar doesn't know which windows are in which workspace.
