### ISSUE TITLE
Pinned taskbar app icons does not disappear after being removed from taskbar.

### ISSUE THREAD

**Issue by StefanPopovic2005** [polybar/polybar#2483]
## Checklist
* [x ] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x ] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x ] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x ] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
Pinned apps icon cannot be removed from polybar when removed from taskbar.

**Expected behavior:**
I expected that when I remove pinned app from taskbar that icon will disappear from polybar.

**Actual behavior:**
Application Icon is still there, even multiplied by two, if you pin the same app to the taskbar and remove it again, it just duplicates existing polybar icon.

**Was it working before?**
I never used polybar before so I dont know if it works fine in other versions

## Screenshots
![image](https://user-images.githubusercontent.com/45667971/131196545-b6288388-08ac-4a12-875e-3d5f83e12023.png)

## Environment:
Windows 10

```

```

**Comment by StefanPopovic2005** [comment]
Ok, it seams like every app that was pinned to taskbar, and it has specified icon on polybar theme does not disappear from polybar taskbar

**Comment by patrick96** [comment]
This repository is for the linux program `polybar` and not the rainmeter skin
