### ISSUE TITLE
Xworkspaces enable-click does not work - Qtile

### ISSUE THREAD

**Issue by addy419** [polybar/polybar#2489]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
enable-click from xworkspaces module does not allow me to switch groups (workspaces) in Qtile.

**Expected behavior:**
I should be able to go to a particular workspace on click.

**Actual behavior:**
no response. no error. nothing

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)? don't know
* If no, what was the last version where this worked correctly?

## To Reproduce

```dosini

[bar/main]
background=${colors.background}
bottom=true
font-0=Iosevka Nerd Font:pixelsize=12;3
font-1=Font Awesome 5 Free Regular:pixelsize=12;2
font-2=Font Awesome 5 Free Solid:pixelsize=12;2
font-3=Font Awesome 5 Brands:pixelsize=12;2
foreground=${colors.foreground}
height=32px
modules-left=i3 bspwm ewmh
modules-right=date
monitor=${env:MONITOR:}
override-redirect=false
radius=0
tray-padding=2
tray-position=right
width=100%

[colors]
background=${xrdb:background}
empty=#44475a
foreground=${xrdb:foreground}
urgent=${xrdb:color1}

[module/ewmh]
enable-click=true
enable-scroll=false
label-active=
label-active-font=3
label-active-padding=1
label-empty=
label-empty-font=2
label-empty-foreground=${colors.empty}
label-empty-padding=1
label-occupied=
label-occupied-font=2
label-occupied-padding=1
label-urgent=
label-urgent-font=2
label-urgent-foreground=${colors.urgent}
label-urgent-padding=1
pin-workspaces=false
type=internal/xworkspaces
```

## Polybar Log
Nothing, just normal start

```
notice: Parsing config file: /home/aditya/.config/polybar/config
error: Disabling module "i3" (reason: Missing section "module/i3")
error: Disabling module "bspwm" (reason: Missing section "module/bspwm")
notice: Loaded font "Iosevka Nerd Font:pixelsize=12" (name=Iosevka, offset=3, file=/nix/store/jcx6ygq5bmhy1lmnd0zqakd4fcy6rl9c-home-manager-path/share/fonts/truetype/NerdFonts/Iosevka Nerd Font Complete.ttf)
notice: Loaded font "Font Awesome 5 Free Regular:pixelsize=12" (name=Font Awesome 5 Free, offset=2, file=/nix/store/jcx6ygq5bmhy1lmnd0zqakd4fcy6rl9c-home-manager-path/share/fonts/opentype/Font Awesome 5 Free-Regular-400.otf)
notice: Loaded font "Font Awesome 5 Free Solid:pixelsize=12" (name=Font Awesome 5 Free, offset=2, file=/nix/store/jcx6ygq5bmhy1lmnd0zqakd4fcy6rl9c-home-manager-path/share/fonts/opentype/Font Awesome 5 Free-Solid-900.otf)
notice: Loaded font "Font Awesome 5 Brands:pixelsize=12" (name=Font Awesome 5 Brands, offset=2, file=/nix/store/jcx6ygq5bmhy1lmnd0zqakd4fcy6rl9c-home-manager-path/share/fonts/opentype/Font Awesome 5 Brands-Regular-400.otf)
```

## Environment:
* WM: Qtile 0.16.0
* Distro: NixOS 21.05
* Output of `polybar -vvv`:

```
polybar 3.5.5

Features: +alsa -curl -i3 -mpd +network(libnl) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gcc-wrapper-10.3.0/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:  
```

## Additional context
I have tried this with override-redirect=true and false both. It does not work with either. I though this was a click issue but right/left clicking on kdeconnect-indicator in systray works perfectly

**Comment by patrick96** [comment]
Interesting, maybe qtile doesn't respond to our workspace requests the same way other WMs to. Could you run polybar with trace logging (add `-l trace` to the `polybar` command) and post the log of that when you try clicking on workspaces.

Maybe also try setting `enable-scroll = true` and try scrolling on the module.

**Comment by addy419** [comment]
Looks like the input is being given properly.

```
- bar: Received button press: 1 at pos(46, 15)
- Found matching input area
- controller: Processing inputdata: #ewmh.focus.1
* Forwarding action to modules (module: 'ewmh', action: 'focus', data: '1')
* module/ewmh: Requesting change to desktop #1
* Delivered action to 1 module
```
```
- bar: Received button press: 5 at pos(86, 16)
- Found matching input area
- controller: Processing inputdata: #ewmh.prev
* Forwarding action to modules (module: 'ewmh', action: 'prev', data: '')
* module/ewmh: Requesting change to desktop #4294967295
* Delivered action to 1 module
- bar: Received button press: 5 at pos(86, 16)
- Found matching input area
- controller: Processing inputdata: #ewmh.prev
* Forwarding action to modules (module: 'ewmh', action: 'prev', data: '')
* module/ewmh: Requesting change to desktop #4294967295
* Delivered action to 1 module
- bar: Received button press: 5 at pos(86, 16)
- Found matching input area
- controller: Processing inputdata: #ewmh.prev
* Forwarding action to modules (module: 'ewmh', action: 'prev', data: '')
* module/ewmh: Requesting change to desktop #4294967295
* Delivered action to 1 module
- bar: Received button press: 5 at pos(86, 16)
- Found matching input area
- controller: Processing inputdata: #ewmh.prev
* Forwarding action to modules (module: 'ewmh', action: 'prev', data: '')
* module/ewmh: Requesting change to desktop #4294967295
* Delivered action to 1 module
```

**Comment by patrick96** [comment]
So the click commands seem to work fine, but there is a problem with scrolling. I'll have to investigate this a bit. I think qtile does not set its desktop properties in a way that we expect.

Could you try changing the desktop using the `wmctrl` tool (e.g. `wmctrl -s 1`) and see if that works?

**Comment by addy419** [comment]
@patrick96 Yes, that works

**Comment by patrick96** [comment]
I'm unable to reproduce this with both polybar 3.5.5 and the most recent commit. Both scrolling and clicking work fine. Though trying to go to the previous workspace when in the first one doesn't work which I have to investigate.

I only have qtile 0.18 and 0.16 doesn't run on my machine, so maybe this is something that doesn't occur in an updated qtile.

Could you maybe share your qtile config, maybe something in there messes with things.

Are you able to update qtile to 0.18?

**Comment by patrick96** [comment]
The scrolling thing is a general issue in the module, not just with qtile, I'm going to open a new issue for that.

**Comment by addy419** [comment]
@patrick96 can you point out at what point I should start polybar in qtile config? I am able to run 0.18 but it jumps back to lightdm if I tried to trigger a lazy.restart. So for now, if the polybar runs too early, ewmh will not find _NET_DESKTOP (something) and will disable ewmh. If I start it after qtile completely loads, the bar does not show up without a restart (which will jump back to login). Hence, I'm not able to test this on 0.18.0

**Comment by patrick96** [comment]
Hmm...

I just started it by hand after qtile was running, but I had to set `override-redirect = true` to get it to appear.

**Comment by addy419** [comment]
@patrick96 Yes, it works with 0.18.0.  Thank you for helping me :)

**Comment by patrick96** [comment]
Good to know :)
