### ISSUE TITLE
Option to set min-length of xwindow

### ISSUE THREAD

**Issue by the-anonymous-raven** [polybar/polybar#2490]
The title says it all. It would be great if we can define min-length of xwindow title.

**Comment by patrick96** [comment]
That's already possible. Every label has the `minlen` property: https://github.com/polybar/polybar/wiki/Formatting#label

Tokens also have a way to set the minimum length: https://github.com/polybar/polybar/wiki/Formatting#tokens

So there is two ways to achieve this.
