### ISSUE TITLE
Polybar Works Laggy

### ISSUE THREAD

**Issue by Huso112** [polybar/polybar#2495]
## Checklist
* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug
Polybar works laggy.

**Expected behavior:**
Runs smoothly.

**Actual behavior:**
Polybar work laggy when i use keybindings on bspwm and startimg-closing programs.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
No it was working good.

* If no, what was the last version where this worked correctly?
The latest version

## To Reproduce

It happend today. So everything is same
https://raw.githubusercontent.com/Huso112/my-dotfiles/main/config

## Polybar Log
```
notice: Parsing config file: .config/polybar/config
warn: No monitor specified, using "eDP-1-1"
notice: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
notice: Loaded font "Mononoki Nerd Font:pixelsize=12" (name=mononoki Nerd Font, offset=3, file=/home/hoovy/.fonts/mononoki-Regular Nerd Font Complete.ttf)
notice: Termination signal received, shutting down...
notice: Parsing config file: .config/polybar/config
warn: No monitor specified, using "eDP-1-1"
notice: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
notice: Loaded font "Mononoki Nerd Font:pixelsize=12" (name=mononoki Nerd Font, offset=3, file=/home/hoovy/.fonts/mononoki-Regular Nerd Font Complete.ttf)
notice: Termination signal received, shutting down...
notice: Parsing config file: .config/polybar/config
warn: No monitor specified, using "eDP-1-1"
notice: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
notice: Loaded font "Mononoki Nerd Font:pixelsize=12" (name=mononoki Nerd Font, offset=3, file=/home/hoovy/.fonts/mononoki-Regular Nerd Font Complete.ttf)
notice: Termination signal received, shutting down...
notice: Parsing config file: .config/polybar/config
warn: No monitor specified, using "eDP-1-1"
notice: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
notice: Loaded font "Mononoki Nerd Font:pixelsize=12" (name=mononoki Nerd Font, offset=3, file=/home/hoovy/.fonts/mononoki-Regular Nerd Font Complete.ttf)
notice: Termination signal received, shutting down...
```

## Screenshots
https://drive.google.com/file/d/1qgmTLjd0pW4XBGACAcTxjLTlbFMbfOFQ/view?usp=sharing

## Environment:
* WM: BSPWM
* Distro: Arch Linux
* Output of `polybar -vvv`:

```
polybar 3.5.6

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
I downloaded from yay

**Comment by patrick96** [comment]
I'm assuming the lag you are referring to is where the bspwm module has quite a big delay when updating its workspace list after you switched workspaces with a keybinding.

In the video it seems like your bar is restarting a lot and at around 26seconds, there seems to be multiple bars running on top of each other. Are you restarting the bars or does this happen automatically? 

It looks like the delay only appears when you use keybindings for switching workspaces, but not when you directly click on the module. Is this *always* the case or is there sometimes no delay, even when using keybindings?
Could you try changing workspaces by using `bspc` from the commandline: `bspc desktop -f ^N` where you replace `N` with the number of the workspace.

>  Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
    No it was working good.
    If no, what was the last version where this worked correctly?
    The latest version

You are currently using the latest version. Did you update from an older version where this was not an issue? If so from which version?

**Comment by Huso112** [comment]
>In the video it seems like your bar is restarting a lot and at around 26seconds, there seems to be multiple bars running on top of each other. Are you restarting the bars or does this happen automatically?

I typed `polybar bspbar` on my bspwm config and I use just one bar.

> You are currently using the latest version. Did you update from an older version where this was not an issue? If so from which version?

I did an aur update 3 or 5 days ago but i can’t remember did i update or when did I updated it. 

I tried recompile it but didn’t work.

> It looks like the delay only appears when you use keybindings for switching workspaces

It happens when I open a program or close a program

The interesting thing is it started today. Yesterday it hasn’t got a problem. 

So I think that’s not revenant to update or version.

Maybe it caused by drivers or special modules (the `custom/script` ones )

**Comment by patrick96** [comment]
> I typed polybar bspbar on my bspwm config and I use just one bar.

If you have just that in your bspwm config, I think it will start a new polybar instance everytime without closing the old one. So it's possible that you have a lot of polybars running on top of each other.
When polybar has a big delay, can you run `pgrep polybar` and see how many lines it outputs? That's how many bars are running.

> I did an aur update 3 or 5 days ago but i can’t remember did i update or when did I updated it.

The last polybar release was 4 months ago, it's unlikely you actually updated polybar.

> It happens when I open a program or close a program

So after you open a program, the bspwm module updates slowly? For how long? Just forever or does it normalize at some point?

> Maybe it caused by drivers or special modules (the custom/script ones )

Maybe. Try disabling all the modules except the bspwm one and see if polybar is still laggy.

**Comment by Huso112** [comment]
Ok i solved the problem.

Wrong things are:
Bad picom.conf
wal comman on fish.config

**Comment by rbilk** [comment]
Hi what exactly was wrong with the picom config? Seem to be having a similar issue. thanks
