### ISSUE TITLE
VPN module not shown

### ISSUE THREAD

**Issue by andersostling56** [polybar/polybar#2496]
## Checklist

* [X] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

Module for VPN status now shown at start of Polybar. The module defintion is shown here below

[module/vpn-network]
type = internal/network
interface = tun0
interval = 1.0
ping-interval = 10

format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = VPN Up
label-connected-foreground = #aaff77
label-disconnected = VPN down
label-disconnected-foreground = #66

**Expected behavior:**

Module should be active and visible in disabled state upon start of Polybar

**Actual behavior:**

error message Disabling module "vpn-network" (reason: basic_string::_M_construct null not valid)

Module is disabled upon start of Polybar if the TUN0 adapter is absent. If I instead activate TUN0 in the lanuch.sh script, it works as expected.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
* If no, what was the last version where this worked correctly?

## To Reproduce

```dosini

```

## Polybar Log

```

```

## Environment:
* WM: i3-gaps
* Distro: UBUNTU 21.04
* Output of `polybar -vvv`:
anders@ws-ubuntu:~/.config/polybar$ polybar -vvv
polybar 3.5.6-128-g5f346224-dev

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/g++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

```

**Comment by patrick96** [comment]
I was able to reproduce this.

The bug here is the error message which is caused by an exception somewhere. Normally the `reason` part of the error message would be `Invalid network interface "tun0"`.

The fact that the module doesn't work if the interface doesn't exist, is normal polybar behavior, see #1164 for the feature request about this.

**Comment by patrick96** [comment]
This seems to be a regression caused by #2025
