### ISSUE TITLE
Battery request: ramp-capacity-charging/discharging

### ISSUE THREAD

**Issue by vaskark** [polybar/polybar#2503]
## Is your feature request related to a problem? Please describe.
No.

## Why does polybar need this feature?
It would just be nice since the Nerd Font project has 2 sets of battery icons in the mdi section, one for charging (lightning bolt) and one for discharging.

## Describe the solution you'd like
New properties:
ramp-capacity-CHARGING-0 = ...
etc.
ramp-capacity-DISCHARGING-0 = ...
etc.

## Describe alternatives you've considered
I tried using animation-capacity for one state. Works okay.

## Additional context
N/A

Thanks.

**Comment by patrick96** [comment]
This will automatically be possible once we have #1752
