### ISSUE TITLE
Doc changerequest: Fedora 33+ offers PolyBar in it's repo

### ISSUE THREAD

**Issue by Cyborgscode** [polybar/polybar#2513]
Since Fedora 30 Polybar is available in Fedora stable repos:

https://koji.fedoraproject.org/koji/packageinfo?packageID=30438

Please change your docs section about installing polybar and add:

Fedora: install with "sudo dnf -y install polybar"

**Comment by patrick96** [comment]
It's already there: https://github.com/polybar/polybar#installation

**Comment by Cyborgscode** [comment]
This page is meant:

https://polybar.github.io/

**Comment by patrick96** [comment]
Ah, I see. Added it to the webpage.
