### ISSUE TITLE
How to handle relative includes?

### ISSUE THREAD

**Issue by metov** [polybar/polybar#2523]
polybar's config format supports including files and directories. However, the path is expected to be an absolute path.

In practice this is not true: I have found that if I put in a local path, polybar will try to access it relative to the current working directory. Normally, programs with similar configuration methods (eg. gitconfig) will interpret the relative path in relation to the file itself, not where the program has been launched from.

1. Is the intent to support inclusion with relative paths, or to support absolute paths only? The wiki [section on inclusion](https://github.com/polybar/polybar/wiki/Configuration#file-inclusion) is written as if only absolute paths are supported.
2. If the intent is to support only absolute paths, what is the reasoning behind this? Relative paths are very useful in organizing configs - for example I version my polybar config in a dotfiles repo which is shared across many different computers. The polybar configs don't necessarily end up under the same path on every computer (due to trivial differences like username or `XDG_HOME`). Thus I am forced to add workarounds and add complexity to my dotfiles.
3. If the intent is to support relative paths, can the wiki section be revised to make this clear, and also explain the relative include behavior? Moreover, in that case is it fair to say that the normal behavior should be to interpret the include paths relative to the config itself, not the working directory?

Sorry if I'm missing anything obvious, but having searched through the issues I couldn't really find anything relevant, and I can't imagine I'm the only one who has this problem.

**Comment by metov** [comment]
Also, I'll share here some workarounds that I've come up with:

* Create a directory in some stable absolute path (eg. `/polybar-config/`) and either symlink this to your real config or bind mount it there. Write your include paths based on this path, eg. `include-file = /polybar-config/my-config.ini` and the file itself is at `~/.config/polybar/my-config.ini`.
* In your launch script, `cd `~/.config/polybar/` (or wherever you have the configs) before launching polybar. If you are only executing the script with `./launch.sh` as opposed to sourcing it with `source launch.sh` this will change the working directory inside the script only.
* Use a template system and put a placeholder in the path, then render the template as needed. Version the template, not the rendered config. For example `include-file = {{ base_path_to_config }}/my-config.ini` if you want to use Jinja or `include-file = $BASEPATH/my-config.ini` if you want to use `envsubst`.

These are all more or less hacky, so if you find a better method let's note it here for future readers.

**Comment by patrick96** [comment]
The current state of this is that we support absolute paths (anything else is coincidental).

But we don't explicitly disallow relative paths and that's why you get the behavior you experienced.

I think polybar should start officially supporting relative paths, in particular paths relative to the file that specified them (and not the current working directory).

There have been some efforts in #1523 but progress there stalled, mainly because we did also try to support tilde expansion and environemt variable references all at once.

Let's track this in this issue and start small by just supporting paths relative to the config file.
