### ISSUE TITLE
[Bug]: Only one systemtray visiable at a time

### ISSUE THREAD

**Issue by famfo** [polybar/polybar#2546]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

`polybar -c=config.ini 1 & polybar-c=config.ini 2`

### Minimal config

```dosini
[bar/1]
modules-left=xwindow
tray-position = right

[bar/2]
modules-right=xwindow
tray-position = left

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
```

### Polybar log

```text
[1] 87644
notice: Parsing config file: config.ini
notice: Parsing config file: config.ini
* Loaded monitor DVI-I-0 (1920x1080+1280+0)
* Bar geometry: 1920x24+1280+0; Borders: 0,0,0,0
* Starting application
* Starting module/xwindow
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=3)
* Configured DPI = 96x96
warn: No fonts specified, using fallback font "fixed"
* Loaded monitor DVI-I-0 (1920x1080+1280+0)
* Bar geometry: 1920x24+1280+0; Borders: 0,0,0,0
* Starting application
* Starting module/xwindow
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=2)
* Configured DPI = 96x96
warn: No fonts specified, using fallback font "fixed"
notice: Loaded font "fixed" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
notice: Loaded font "fixed" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Bar window: 0x0c00001
* Bar window: 0x0e00001
* Activating tray manager
* Tray window: 0x0c00005
* module/xwindow: Rebuilding cache
* Redrawing bar window
* Activating tray manager
* Tray window: 0x0e00005
error: tray: Failed to put tray above 0x0e00001 in the stack (XCB_MATCH (8))
warn: Systray selection already managed (window=0x0c00005)
* Deactivating tray manager
* module/xwindow: Rebuilding cache
* Redrawing bar window
* Redrawing bar window
* Notifying pending tray clients
* Processing docking request from 'schildichat-desktop' (0x4e00094)
* Processing docking request from 'flameshot' (0x2e0014c)
* Redrawing bar window
* Redrawing bar window
* Redraw tray container (id=0x0c00005)
* Redraw tray container (id=0x0c00005)
* Redraw tray container (id=0x0c00005)
* Redraw tray container (id=0x0c00005)
* Processing docking request from 'Steam' (0x34000aa)
* Redrawing bar window
* Redraw tray container (id=0x0c00005)
* Redraw tray container (id=0x0c00005)
```

### Expected behavior

I get a systemtray in both bars

### Actual behavior

I get a systemtray in only one of the bars

### Window Manager and Version

i3 version 4.20 (2021-10-19)

### Linux Distribution

Arch Linux

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/clang++
Compiler flags: -fuse-ld=lld -O3 -flto -march=native -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -Wno-error=parentheses-equality -Wno-zero-length-array -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

### Additional Context / Screenshots

I wanted to put a systemtray on my secondary monitor as well, but I only get it on my primary monitor.
![image](https://user-images.githubusercontent.com/44938471/139510027-ebb2bd96-03d3-4b25-ba8e-d06864dc1761.png)

**Comment by patrick96** [comment]
This is not a bug. The [System Tray Protocol Specification](https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-latest.html) only allows for a single tray to run. That's why one of the bars gives you the warning `Systray selection already managed`.

There is no way around that. Each tray icon is its own window created by its application (for example steam), so there is no way to put that window into multiple trays
