### ISSUE TITLE
Unable to remove bottom padding/margin/underlines on my bar

### ISSUE THREAD

**Issue by starcraft66** [polybar/polybar#2550]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Launch Polybar
2. Observe that there is wasted space at the bottom of the bar making the modules not centered

### Minimal config

```dosini
[bar/main]
background=#263238
border-color=#37474F
border-size=2
dpi=144
enable-ipc=true
font-0=Noto Sans:size=10
font-1=Font Awesome 5 Free Regular:pixelsize=10
font-2=Font Awesome 5 Free Solid:pixelsize=10
font-3=Font Awesome 5 Brands:pixelsize=10
foreground=#82AAFF
height=42
line-size=0
modules-center=time
modules-left=i3
modules-right=cpu memory pulseaudio wlan eth battery
monitor=${env:MONITOR}
offset-x=14
offset-y=5
override-redirect=true
padding=3
scroll-down=#i3.next
scroll-up=#i3.prev
tray-detached=false
tray-maxsize=24
tray-position=right
width=100%:-28
wm-restack=i3
[global/wm]
margin-bottom=0
margin-top=0
```

### Expected behavior

I expect that the spacing at the top and bottom of my modules be the same so that they can be centered.

### Actual behavior

My bar looks like this even with margin-bottom set to 0. I would expect that the spacing at the top and bottom of the text to be the same.
<img width="154" alt="image" src="https://user-images.githubusercontent.com/1858154/141079126-5eb36ee0-0d13-4e7a-bcdd-00972dbe880a.png">

### Window Manager and Version

i3-gaps 4.19.1

### Linux Distribution

NixOS unstable

### Polybar version

```text
polybar 3.5.7

Features: +alsa -curl +i3 -mpd +network(libnl) -pulseaudio +xkeyboard
```

**Comment by patrick96** [comment]
This is not technically extra margin or padding. The size between the top and bottom border is only controlled by the `height` setting, nothing else.

The problem here is that the font is not aligned at the center by default. You need to specify a vertical offset

**Comment by starcraft66** [comment]
Thanks fixed my problem thanks. Sorry for opening an issue but I searched for all sorts of terms and couldn't find out what was wrong, I didn't think to search for a font vertical offset. Even when on the font docs page you linked, there isn't any information about the offset other than mentioning it exists, the docs aren't super great on that front.
