### ISSUE TITLE
[Bug]: dual monitor setup: workspaces module not showing

### ISSUE THREAD

**Issue by DeinMathelehrer** [polybar/polybar#2555]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

0. start polybar with the minimal config to see how it should look like

1. Setup a dual monitor setup like this:
![Screenshot_2021-11-27-09-09-41_3000x1920](https://user-images.githubusercontent.com/58335765/143720877-4c381526-d4ff-4603-ac68-844553d04535.png)

2. move the 1. monitor to the half height of the 2. one like this:
![Screenshot_2021-11-27-09-11-37_3000x1920](https://user-images.githubusercontent.com/58335765/143720919-4b44230a-f58a-4acd-833b-5e6abe2c30ca.png)
 
3. start polybar again with the config I provided

### Minimal config

```dosini
;; Global WM Settings
[global/wm]
margin-bottom = 0
margin-top = 0

;; modules
[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = true
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-default = 
format = <label-state>
label-monitor = %name%
label-active = %icon%
label-active-foreground = ${color.pink}
label-occupied = %icon%
label-occupied-foreground = ${color.cyan}
label-urgent = %icon%
label-urgent-foreground = ${color.red}
label-empty = %icon%
label-empty-foreground = ${color.foreground}
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1

;; just color settings
[color]
pink = #EC407A
cyan = #4DD0E1
red = #EC7875
foreground = #C4C7C5

;; Bar Settings
[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false

width = 100%
height = 34

font-0 = "Iosevka Nerd Font:size=10;4"
font-1 = "Iosevka Nerd Font:size=10;3"
font-2 = "feather:size=12;3"

modules-left = workspaces
```

### Polybar log

```text
polybar --config=./config.ini main

notice: Parsing config file: ./config.ini
notice: Loaded font "Iosevka Nerd Font:size=10" (name=Iosevka, offset=4, file=/usr/share/fonts/archcraft/nerd-fonts/Iosevka Nerd Font Complete.ttf)
notice: Loaded font "Iosevka Nerd Font:size=10" (name=Iosevka, offset=3, file=/usr/share/fonts/archcraft/nerd-fonts/Iosevka Nerd Font Complete.ttf)
notice: Loaded font "feather:size=12" (name=feather, offset=3, file=/usr/share/fonts/archcraft/icon-fonts/Icomoon-Feather.ttf)
```

### Expected behavior

Polybar should show 5 icons standing for 5 virtual desktops/workspaces

### Actual behavior

The module/these 5 icons doesn't show up

### Window Manager and Version

openbox 3.6.1-8

### Linux Distribution

Archcraft (rolling release)

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

### Additional Context / Screenshots

This is my first issue I filed here and I'm not a very pro so pls expect me to ask questions if I don't understand something particular 
And also don't hate me for the minimal config, I grepped it out of an existing configuration which partly worked

Additional info: 
I tried multiple (preinstalled) configs and they all worked except the workspaces module didn't show up
Imma attach a neofetch maybe it'll help you finding the issue
![Screenshot_2021-11-27-09-23-16_3000x1920](https://user-images.githubusercontent.com/58335765/143721239-1e7061f1-27f5-4e32-a7e2-6d80104877c3.png)

**Comment by DeinMathelehrer** [comment]
sorry I forgot to give the issue a title :P

**Comment by patrick96** [comment]
Thanks for the detailed report. So before you setup the multi-monitor system, polybar displays the workspaces just fine?

Could you post the output of the `xprop -root` command in that dual-monitor setup. Polybar basically uses that information in the xworkspaces module.

And finally, instead of using `%icon%` in your xworkspaces module, try using `%name%` and see it that works. If it does, this is merely an issue with fonts.

**Comment by DeinMathelehrer** [comment]
Thx for the answer :D

Yes it worked fine on dual monitor when the left monitor was in the upper left corner but when it's positioned in the middle height it's not working

As you said I tried to replace %icon% with %name% but that results in the same as before

Just to confirm my changed code:
`;; minimal config to show a bug

;; Global WM Settings
[global/wm]
margin-bottom = 0
margin-top = 0

;; modules
[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = true
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-default = 
format = <label-state>
label-monitor = %name%
label-active = %name%
label-active-foreground = ${color.pink}
label-occupied = %name%
label-occupied-foreground = ${color.cyan}
label-urgent = %name%
label-urgent-foreground = ${color.red}
label-empty = %name%
label-empty-foreground = ${color.foreground}
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1

;; just color settings please ignore
[color]
pink = #EC407A
cyan = #4DD0E1
red = #EC7875
foreground = #C4C7C5

;; Bar Settings
[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false

width = 100%
height = 34

font-0 = "Iosevka Nerd Font:size=10;4"
font-1 = "Iosevka Nerd Font:size=10;3"
font-2 = "feather:size=12;3"

modules-left = workspaces`


And as you wanted here the xprop -root output

`_NET_ACTIVE_WINDOW(WINDOW): window id # 0x3000002
XKLAVIER_ALLOW_SECONDARY(INTEGER) = 0
AT_SPI_BUS(STRING) = "unix:path=/tmp/dbus-wFAJP52E0S,guid=21ff11caebd28f232c906b1e61a4e074"
GDK_VISUALS(INTEGER) = 43, 130
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x600004
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x600004
_NET_CLIENT_LIST(WINDOW): window id # 0x1600003, 0x1a00001, 0x2600003, 0x3c00008, 0x2400002, 0x540002c, 0x2a00039, 0x3000002
_NET_SHOWING_DESKTOP(CARDINAL) = 0
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2", "3", "4", "5", ""
_NET_WORKAREA(CARDINAL) = 0, 466, 3000, 1454, 0, 466, 3000, 1454, 0, 466, 3000, 1454, 0, 466, 3000, 1454, 0, 466, 3000, 1454
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 5
_NET_DESKTOP_GEOMETRY(CARDINAL) = 3000, 1920
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x2600003, 0x3c00008, 0x2400002, 0x2a00039, 0x540002c, 0x3000002, 0x1600003, 0x1a00001
_OB_THEME(UTF8_STRING) = "Juno-palenight"
_OB_VERSION(UTF8_STRING) = "3.6.1"
_NET_SUPPORTED(ATOM) = _NET_SUPPORTING_WM_CHECK, _NET_WM_FULL_PLACEMENT, _NET_CURRENT_DESKTOP, _NET_NUMBER_OF_DESKTOPS, _NET_DESKTOP_GEOMETRY, _NET_DESKTOP_VIEWPORT, _NET_ACTIVE_WINDOW, _NET_WORKAREA, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_DESKTOP_NAMES, _NET_CLOSE_WINDOW, _NET_DESKTOP_LAYOUT, _NET_SHOWING_DESKTOP, _NET_WM_NAME, _NET_WM_VISIBLE_NAME, _NET_WM_ICON_NAME, _NET_WM_VISIBLE_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_STRUT, _NET_WM_STRUT_PARTIAL, _NET_WM_ICON, _NET_WM_ICON_GEOMETRY, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ALLOWED_ACTIONS, _NET_WM_WINDOW_OPACITY, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_STATE, _NET_WM_STATE_MODAL, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SHADED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_MOVERESIZE_WINDOW, _NET_WM_MOVERESIZE, _NET_WM_USER_TIME, _NET_FRAME_EXTENTS, _NET_REQUEST_FRAME_EXTENTS, _NET_RESTACK_WINDOW, _NET_STARTUP_ID, _NET_WM_SYNC_REQUEST, _NET_WM_SYNC_REQUEST_COUNTER, _NET_WM_PID, _NET_WM_PING, _KDE_WM_CHANGE_STATE, _KDE_NET_WM_FRAME_STRUT, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _OB_WM_ACTION_UNDECORATE, _OB_WM_STATE_UNDECORATED, _OPENBOX_PID, _OB_THEME, _OB_CONFIG_FILE, _OB_CONTROL, _OB_VERSION, _OB_APP_ROLE, _OB_APP_TITLE, _OB_APP_NAME, _OB_APP_CLASS, _OB_APP_GROUP_NAME, _OB_APP_GROUP_CLASS, _OB_APP_TYPE
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x2000e3
_OPENBOX_PID(CARDINAL) = 872
RESOURCE_MANAGER(STRING) = "*background:\t#2E3440\n*color0:\t#3B4252\n*color1:\t#BF616A\n*color10:\t#A3BE8C\n*color11:\t#EBCB8B\n*color12:\t#81A1C1\n*color13:\t#B48EAD\n*color14:\t#8FBCBB\n*color15:\t#ECEFF4\n*color2:\t#A3BE8C\n*color3:\t#EBCB8B\n*color4:\t#81A1C1\n*color5:\t#B48EAD\n*color6:\t#88C0D0\n*color7:\t#E5E9F0\n*color8:\t#4C566A\n*color9:\t#BF616A\n*cursorColor:\t#D8DEE9\n*foreground:\t#D8DEE9\nURxvt*depth:\t24\nURxvt*externalBorder:\t0\nURxvt*internalBorder:\t16\nURxvt*iso14755:\tfalse\nURxvt*letterSpace:\t1\nURxvt*saveline:\t15000\nURxvt*scrollBar:\tfalse\nURxvt*scrollBar_right:\tfalse\nURxvt*termName:\trxvt-256color\nURxvt*urgentOnBell:\ttrue\nURxvt.boldFont:\txft:Terminus:bold:size=8\nURxvt.boldItalicfont:\txft:Terminus:boldItalic:size=8\nURxvt.font:\txft:Terminus:regular:size=8\nURxvt.geometry:\t85x25\nURxvt.italicFont:\txft:Terminus:italic:size=8\nURxvt.keysym.Control-Down:\t\\033[1;5B\nURxvt.keysym.Control-Left:\t\\033[1;5D\nURxvt.keysym.Control-Right:\t\\033[1;5C\nURxvt.keysym.Control-Up:\t\\033[1;5A\nURxvt.keysym.Shift-Down:\tcommand:\\033]721;1\\007\nURxvt.keysym.Shift-Up:\tcommand:\\033]720;1\\007\nURxvt.lineSpace:\t1\nXft.autohint:\t0\nXft.lcdfilter:\tlcddefault\nXft.antialias:\t1\nXft.hinting:\t1\nXft.hintstyle:\thintslight\nXft.rgba:\tnone\nXcursor.theme:\tVimix\nXcursor.size:\t0\nXcursor.theme_core:\t1\n"
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "de", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 1
Xorg_Seat(STRING) = "seat0"`

**Comment by patrick96** [comment]
> _NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

So this is the problem. This defines the top left corners of the five workspaces (each pair defines one corner). However, for you it looks like the top left corner would be at (0, 420) because the monitor is moved down.

This property is really only needed for `pin-workspaces = true`, if you set it to false, you won't have this problem.

Polybar assumes that the viewports specified this way are inside a monitor and either openbox does not correctly implement this part of the specification or it just has a different understanding of what the viewport is compared to polybar.

Another thing you could maybe try, and I don't know if this is even possible, is to reload openbox since it's possible that it just didn't properly handle the change in monitor setup.

**Comment by DeinMathelehrer** [comment]
You are a hero, it works fine after changing pin-workspaces to false. Thank you very much for your time :D
