### ISSUE TITLE
[Bug]: `format-charging` is displayed when BAT0's status is discharging

### ISSUE THREAD

**Issue by Hanaasagi** [polybar/polybar#2563]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Hi, I configured the battery module according to the documentation, but when I plug the power cable in, it keeps showing that it is charging. It is not actually charging. It looks like the polybar is not determining the battery's charging threshold.

My Laptop is Lenovo ThinkBook 14p Gen 2.

### Minimal config

```dosini
[bar/main]
modules-right = battery

[module/battery]
type = internal/battery

full-at = 99
battery = BAT0
adapter = ADP1

poll-interval = 5
time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 
label-full-foreground = ${color.green}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 

animation-charging-framerate = 750

```

### Expected behavior

Display `format-charging`

### Actual behavior

Display `format-discharging`

### Window Manager and Version

bspwm-0.9.10-1

### Linux Distribution

Linux 5.15.10-arch1-1

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

### Additional Context / Screenshots
Please see the top right corner, it's displaying `format-charging` anime.
![output](https://user-images.githubusercontent.com/9482395/147184038-69d3529f-46cc-4b87-a71a-cab779438394.gif)

**Comment by Hanaasagi** [comment]
Related code and my local file content

https://github.com/polybar/polybar/blob/f488a889bc8012e7da714be7b9543254ac65cfc4/src/modules/battery.cpp#L300-L312

https://github.com/polybar/polybar/blob/f488a889bc8012e7da714be7b9543254ac65cfc4/src/modules/battery.cpp#L38-L45

```
>> cat /sys/class/power_supply/BAT0/status
Discharging

~/Videos
>> cat /sys/class/power_supply/ADP1/online
1
```

**Comment by specaries** [comment]
Try this see if it fixed your issue



## Battery ##

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

battery = BAT0
adapter = ADP1

poll-interval = 5

label-full =   %percentage%%
label-full-padding-left = 1
label-full-padding-right = 1
label-full-foreground = #DEDDDA

label-discharging = %percentage%%
label-charging = %percentage%%
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging> 

label-charging-padding-left = 0
label-charging-padding-right = 1
label-discharging-padding-left = 0
label-discharging-padding-right = 1

ramp-capacity-0-padding = 1
ramp-capacity-1-padding = 1
ramp-capacity-2-padding = 1
ramp-capacity-3-padding = 1
ramp-capacity-4-padding = 1

animation-charging-0-padding = 1
animation-charging-1-padding = 1
animation-charging-2-padding = 1
animation-charging-3-padding = 1
animation-charging-4-padding = 1

animation-discharging-0-padding = 1
animation-discharging-1-padding = 1
animation-discharging-2-padding = 1
animation-discharging-3-padding = 1
animation-discharging-4-padding = 1

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500

**Comment by Hanaasagi** [comment]
```
format-charging =
format-discharging = 
```

The options in the above configuration are empty， nothing is shown in the status bar. I changed it myself and found that the bugs still exist.

```
format-charging = <label-charging> <animation-charging>
format-discharging = <label-discharging> <animation-discharging>
```

It looks like https://github.com/polybar/polybar/pull/2556 is solving this problem.

**Comment by Hanaasagi** [comment]
Because https://github.com/polybar/polybar/issues/2363, I close this duplicate issue.

**Comment by specaries** [comment]
i posted the the full config with the configuration that fixed your problem somehow github didn't put here check the last commit of this repo https://github.com/specaries/.configs/blob/main/polybar/config

**Comment by Hanaasagi** [comment]
Thank you for your help. but the problem still exists.

![output](https://user-images.githubusercontent.com/9482395/147673311-dadb4c70-be9e-4e0c-b6bf-1d9e1ba71106.gif)
