### ISSUE TITLE
Allow widgets to have the first letter in any word to uppercase

### ISSUE THREAD

**Issue by Hund** [polybar/polybar#2564]
The date currently looks like this for me:

```
sun 26 dec
```

It would be nice if it could be like this:

```
Sun 26 Dec
```

Why isn't this a thing already? :)

**Comment by patrick96** [comment]
This behavior is defined by your locale. For me, everything is capitalized.

Try running `locale -k LC_TIME`. This should show you what kind of names are used for your locale. This should match what is in polybar unless there is a different locale set when polybar starts or you explicitly override the locale in the polybar config.

We will not add these kinds of text transformation features to polybar in its current state.

**Comment by Hund** [comment]
Thank you! I didn't know that. I'll see what I can do about it.

```
$ LC_ALL=sv_SE.utf8 locale -k LC_TIME
abday="sön;mån;tis;ons;tor;fre;lör"
day="söndag;måndag;tisdag;onsdag;torsdag;fredag;lördag"
abmon="jan;feb;mar;apr;maj;jun;jul;aug;sep;okt;nov;dec"
mon="januari;februari;mars;april;maj;juni;juli;augusti;september;oktober;november;december"
```

(I'm only using the time and date in Polybar in Swedish)
