### ISSUE TITLE
[Bug]: [Module Xwindow] doesn't output in any terminal emulator 

### ISSUE THREAD

**Issue by specaries** [polybar/polybar#2565]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [ ] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

xwindow works with every application the only package that xwindow doesn't show the full output like the screenshot below is the terminal emulator i suspect that i removed something that xwindow rely on, i decided to debloat my system so i started removing stuff that i dont need, some help to get it working again with the terminal and thanks.

## Xwindow ##

[module/xwindow]
type = internal/xwindow
label = [%title:0:66:.%]
label-padding-left = 1
label-empty-padding-left = 1
label-empty-padding-right = 1
label-empty = [Gnu/linux]
label-padding-right = 1
label-empty-foreground = #0A0D0C
label-empty-background = #7FA094
format-foreground = #0A0D0C
label-background = #7FA094

### Expected behavior

xwindow should show the output of what i cd or alias or the ps1 in the terminal like it used to do [see the screenshots below to know what im talking about]

### Actual behavior

xwindow just show the terminal name and nothing else 

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Manjaro Linux x86_64

### Polybar version

```text
polybar 3.5.5
```

### Additional Context / Screenshots

![2021-12-20_1366x768](https://user-images.githubusercontent.com/89179372/147521310-30606f6d-5494-4594-b382-3eff75b5ad4d.png)
![2021-12-28_1366x768](https://user-images.githubusercontent.com/89179372/147521324-cdcecd32-c1d8-4dc3-82cc-d66de38e6f64.png)

**Comment by patrick96** [comment]
We already discussed this on reddit. Polybar correctly displays the window title set by the terminal emulator.

Either your terminal emulator is not properly changing the title or your shell is not providing a title.

**Comment by specaries** [comment]
but yesterday i installed manjaro i3 and i put my config and xwindow worked with urxvt and xfce terminal, i tried them both on bspwm and none of them worked which in fact i know its working cuz it was working last week, im thinking that i should reinstall my whole os just to get this working again, and sorry for any inconvenience.
