### ISSUE TITLE
Middle and right mouse button events in alsa module

### ISSUE THREAD

**Issue by FoxySeta** [polybar/polybar#2566]
## Is your feature request related to a problem? Please describe.
The `alsa` module is lacking middle and right button events.

## Why does polybar need this feature?
The other audio module, `pulseaudio`, has them all, so it's really a simple matter of consistency.

## Describe the solution you'd like
Adding the missing events to the `alsa` module.

## Describe alternatives you've considered
N/T

## Additional context
Since this is pretty much just copypaste from the `pulseaudio` module to the `alsa` one, I can open a PR myself.

**Comment by patrick96** [comment]
Sure, go ahead! I initially wanted to not do this for all modules manually and provide a universal approach as described in #1524. But it's probably going to take a while until I can get to that.
