### ISSUE TITLE
[Bug]: Label connected is not triggering for wifi network

### ISSUE THREAD

**Issue by prateekmedia** [polybar/polybar#2567]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

No steps, try adding network module and network status is not shown.

I think I am missing some packages or idk, It also happened in axyl Linux and now it is same in my current setup of Arch.

### Minimal config

```dosini
[module/network]
type = internal/network
;interface = wlp0s29f7u8
interface-type = wireless
click-left = networkmanager_dmenu
format-connected = <label-connected>
format-connected-prefix = 
format-disconnected = <label-disconnected>
format-disconnected-prefix = 
label-connected = "%{A1:networkmanager_dmenu &:} %essid%%{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:} %downspeed%%{A}"
format-connected-background = ${color.primary}
format-disconnected-background = ${color.primary}
format-connected-padding = 2
format-disconnected-padding = 2
```
```


### Polybar log

_No response_

### Expected behavior

My wifi strength and essid is shown in status bar

### Actual behavior

It shows disconnected wifi icon and my down speed is shown correctly

### Window Manager and Version

Bspwm 0.9.10

### Linux Distribution

Arch Linux

### Polybar version

```text
polybar 3.5.7-219-gf488a889

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/41370460/148060105-60398724-45aa-406a-a385-f22787bed2ae.png)

**Comment by patrick96** [comment]
> It shows disconnected wifi icon and my down speed is shown correctly

Wait. So even if it uses `label-disconnected` the downspeed dynamically changes?

Can you post the output of `ip link`? My guess is that polybar doesn't recognize the interface status.

**Comment by prateekmedia** [comment]
> Wait. So even if it uses `label-disconnected` the downspeed dynamically changes?
 
Yes, I will post the output after when I am back to my PC.

**Comment by prateekmedia** [comment]
Sorry, It seems to be fixed in My new void linux installation, I think it was the problem with arch linux somehow, Maybe some packages were not installed that's why.
