### ISSUE TITLE
Mac Address in Network Module

### ISSUE THREAD

**Issue by Camerooooon** [polybar/polybar#2568]
## Is your feature request related to a problem? Please describe.
I'm unable to easily show my mac address in the internal/network module type

## Why does polybar need this feature?
It will allow people to easily see their current mac address without the need for a custom script.

## Describe the solution you'd like
There already exist things like %ifname% and %local_ip% which show information about the current network. How about adding %mac_addr%

## Describe alternatives you've considered
Creating a custom script in order to read the output of `/sys/class/net/<interface>/address` however this solution doesn't allow me to put my mac address in my network module's text

## Additional context
In order to get the mac address of a certain interface you can read the directory `/sys/class/net/<interface>/address`

**Comment by patrick96** [comment]
Good idea!

PRs are welcome :)

This should be a straight-forward change for both C++ and polybar newcomers.

Add the mac address to the `link_status` struct in `include/adapters/net.hpp` and populate it in `network::query`

**Comment by Camerooooon** [comment]
> Good idea!
> 
> PRs are welcome :)
> 
> This should be a straight-forward change for both C++ and polybar newcomers.
> 
> Add the mac address to the `link_status` struct in `include/adapters/net.hpp` and populate it in `network::query`

I can probably do this
