### ISSUE TITLE
reverse-scroll = true for ewmh?

### ISSUE THREAD

**Issue by agoodfellow123** [polybar/polybar#2582]
## Is your feature request related to a problem? Please describe.
I like most of the polybar defaults however there is one small thing I would like to change and that's the way the mouse wheel scrolls in ewmh module. So can a true/false switch be implemented for the way of rotation?

## Why does polybar need this feature?
It's more customization and it's already available for bspwm and i3 modules. Not only that but you probably just have to add a small amount of code.

## Describe the solution you'd like
You can implement the i3 or bspwm modules `reverse-scroll = ` option to ewmh too.

**Comment by patrick96** [comment]
I was just about to accept this feature request. But I wanted to first check the code to see if this would require any non-trivial changes. And it turns out we already have this feature :smiley:.

It was implemented in #2365 and will be available in polybar 3.6.0 once it is released ;)
