### ISSUE TITLE
[Bug]: `pin-workspaces` option of i3 module is not working

### ISSUE THREAD

**Issue by TripleK2004** [polybar/polybar#2586]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Built the latest releases of i3 gaps and polybar on Debian 11
Nor the i3 and polybar packages from the official repositories are working

### Minimal config

```dosini
Default config with 
`pin-workspaces = true`
```

### Polybar log

```text
notice: Parsing config file: /home/triplek/.config/polybar/config
* Loaded monitor eDP1 (1920x1080+0+0)
* Bar geometry: 1920x35+0+0; Borders: 4,4,4,4
* Starting application
* Starting module/i3
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=3)
* Configured DPI = 96x96
notice: Loaded font "Google Sans:pixelsize=10" (name=Google Sans, offset=1, file=/usr/share/fonts/google-sans/GoogleSans-Regular.ttf)
* Bar window: 0x1200001
* Activating tray manager
* Tray window: 0x1200008
* module/i3: Rebuilding cache
* Redrawing bar window
* Notifying pending tray clients
notice: Termination signal received, shutting down...
* module/i3: Disconnecting from socket
* module/i3: Stopping
warn: module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)
* module/i3: Reconnecting socket succeeded
* Deconstruction of module/i3 took 0 ms.
* Deactivating tray manager
* Waiting for spawned processes to end
* Reached end of application...
```

### Expected behavior

All workspaces(even if empty) should be displayed as per the wiki

`; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true`

### Actual behavior

Only workspaces with windows show up

### Window Manager and Version

i3 version 4.20.1 (2021-11-03)

### Linux Distribution

Debian 11

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:
```

**Comment by patrick96** [comment]
Please show how you assign workspaces to monitors in your i3 config.

Also post your polybar config. You are not using the sample config that comes with polybar, the sample config has more modules and loads different fonts.

> All workspaces(even if empty) should be displayed as per the wiki

In i3, empty workspaces don't exist.

**Comment by TripleK2004** [comment]
> Please show how you assign workspaces to monitors in your i3 config.
> 
> Also post your polybar config. You are not using the sample config that comes with polybar, the sample config has more modules and loads different fonts.
> 
> > All workspaces(even if empty) should be displayed as per the wiki
> 
> In i3, empty workspaces don't exist.

i3 config
`set $ws1 "1"
set $ws2 "2"
set $ws3 "3"`

I have stripped down the config removing other modules , leaving only i3 module

So, pin workspaces option doesnt function as such ?
Check out [This](https://stackoverflow.com/questions/63711437/show-all-workspaces-on-i3)

**Comment by patrick96** [comment]
> So, pin workspaces option doesnt function as such ?
Check out This

No. The only thing `pin-workspaces` does is that it reduces the list of displayed workspaces to workspaces that are on the same monitor as the bar.
There is no way for polybar to display empty workspaces because those workspaces don't exist.

**Comment by TripleK2004** [comment]
> > So, pin workspaces option doesnt function as such ?
> > Check out This
> 
> No. The only thing `pin-workspaces` does is that it reduces the list of displayed workspaces to workspaces that are on the same monitor as the bar. There is no way for polybar to display empty workspaces because those workspaces don't exist.

I see. Thank you.
