### ISSUE TITLE
script module: add formatting for script failure

### ISSUE THREAD

**Issue by nathanielevan** [polybar/polybar#2588]
## Is your feature request related to a problem? Please describe.

I would love to be able to configure a script module to use different formatting and foreground/background colors if a command/script fails i.e. returns an exit code other than 0.

## Why does polybar need this feature?

Well, I figured being able to use different formatting and colors for a failed command (e.g. background turns bright red if a command specified in `exec = ` returns a non-zero exit code) would be a very welcome feature as it increases visibility, I suppose.

## Describe the solution you'd like

I'm thinking of something like so:
```
format-success-prefix =
format-success-suffix =
format-success-foreground =
format-success-background =
format-failure-prefix =
format-failure-suffix = 
format-failure-foreground =
format-failure-background =
```
So for example if the command I run in `exec = ` succeeds, then the output will be shown with the formatting specified by the `format-success-*` configurations. Likewise if the command fails, then `format-failure-*` will be used to format the output on the bar.

## Describe alternatives you've considered

As dumb as it sounds, I have tried putting `exec = tput setaf 1; echo "Hello"` in the script module. I was totally surprised to find out that it didn't work. I could not think of other alternatives, honestly, but I might not have RTFM-ed enough.

**Comment by patrick96** [comment]
> As dumb as it sounds, I have tried putting exec = tput setaf 1; echo "Hello" in the script module. I was totally surprised to find out that it didn't work. I could not think of other alternatives, honestly, but I might not have RTFM-ed enough.

Polybar doesn't use ANSI escape codes, it used [lemonbar formatting tags](https://github.com/polybar/polybar/wiki/Formatting#format-tags). So, this is already possible to do inside the `exec` command.

However, I think this is a reasonable functionality for the module to have.
I don't think `format-success` is necessary, we can just reuse the existing `format` for that. And maybe call the other one `format-fail` and also add a `label-fail`.

As always PRs are welcome. If someone's interested, comment here and I can assign this to you.

I think the two biggest caveats are:

* Making sure existing configs don't break. `format-fail` should only be used if the user actually defined it.
* Handling `tail = true` commands. These can fail, but only at the end while still producing output before exit code is clear.

**Comment by indev29** [comment]
> As always PRs are welcome. If someone's interested, comment here and I can assign this to you.

I would like to be assigned to this, please.

**Comment by patrick96** [comment]
@indev29 Thanks :smiley:
