### ISSUE TITLE
[Bug]: Triggering a script, but the results are inconsistent with triggering in the terminal

### ISSUE THREAD

**Issue by KuringMIN** [polybar/polybar#2589]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

 I use formatting "Action %{A}" to trigger a script in date module, but result is inconsistent with triggering in terminal.
Before this
1.sddm start bspwm
2.a launch script in bspwmrc to launch polybar

### Minimal config

```dosini
[module/date]
type = internal/date
interval = 5

date-alt = " %Y-%m-%d %a"

time = %H:%M
time-alt = %H:%M:%S

format = %{A3:~/.local/mbin/polybar/calendar.sh:}<label>%{A}
format-prefix = 


label = %date% %time%
################################
calendar.sh
#!/usr/bin/env bash
dunstify "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")"
```

### Polybar log

```text
polybar|notice:  Parsing config file: /home/kuring/.config/polybar/Sky&Sea/bar-light
polybar|notice:  Loaded font "FiraCode Nerd Font:size=12:antialias=true:autohint=true" (name=FiraCode Nerd Font, offset=2, file=/usr/share/fonts/OTF/Fira Code Regular Nerd Font Complete.otf)
polybar|notice:  Loaded font "LXGW WenKai:size=16:antialias=true:autohint=true" (name=霞鹜文楷, offset=4, file=/home/kuring/.local/share/fonts/LxgwWenKai/Chinese/LXGWWenKai-Regular.ttf)
polybar|notice:  Loaded font "FiraCode Nerd Font:size=20" (name=FiraCode Nerd Font, offset=4, file=/usr/share/fonts/OTF/Fira Code Regular Nerd Font Complete.otf)
polybar|notice:  Loaded font "JoyPixels:scale=5" (name=JoyPixels, offset=4, file=/usr/share/fonts/joypixels/JoyPixels.ttf)
```

### Expected behavior

trigger the `calendar.sh` in teminal.
![2022-02-02_19-03](https://user-images.githubusercontent.com/51042283/152142080-1a55fceb-8878-44a1-90dc-094571a48a63.png)

### Actual behavior

use`%{A3:~/.local/mbin/polybar/calendar.sh:}<label>%{A}` ,right click the module
![2022-02-02_19-04](https://user-images.githubusercontent.com/51042283/152142102-64212945-9a66-41b8-81fb-0218f21080b9.png)

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

archliux 5.15.18-1-lts

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

### Additional Context / Screenshots

When  i kill polybar, then restart polybar in terminal ,this bug is gone
![2022-02-02_19-30](https://user-images.githubusercontent.com/51042283/152145763-418d0bd4-f524-41c7-acdf-d9a516031a01.png)
Then i use hot key to restart bspwm (also relaunch polybar),this bug reproduce
![2022-02-02_19-35](https://user-images.githubusercontent.com/51042283/152146404-6fc1a9c0-7d66-4e2e-9f41-75798f9aaa66.png)

**Comment by patrick96** [comment]
This has nothing to do with polybar. You should get the same behavior if you run `calendar.sh` in your bspwm startup with a delay:

```
(sleep 10; /bin/bash ~/.local/mbin/polybar/calendar.sh) &
```

The problem is that `cal` doesn't produce any color output (even with `--color=always`) if it isn't started (directly or indirectly) from a terminal.

In your case, `cal` is called from `calendar.sh` which is called from polybar which is called from bspwm which is called from sddm. Nowhere on that path is a terminal involved and so `cal` runs in an environment without a terminal.
In particular, it looks for the `TERM` environment variable. If it is not set, it will not produce any color output.
