### ISSUE TITLE
[Bug]: polybar only registers one click on awesome wm

### ISSUE THREAD

**Issue by qube-03** [polybar/polybar#2591]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. log into awesomewm and have polybar load up with a script
2. click on the polybar (powermenu, clock etc.)
3. now you cant click anything in polybar again

### Minimal config

```dosini
[bar/yes]
monitor = ${env:MONITOR}
width = 100%
height = 28

modules-left = xwindow
modules-center = date
modules-right = pulseaudio memory powermenu
tray-position = right

[module/date]
type = internal/date
interval = 1
time = %H / %M
time-alt = %H/%M/%S
format-prefix = " "
format-prefix-foreground = ${colors.foreground}
format-underline = #0a6cf5
label = %date% %time%
```

### Polybar log

```text
notice: Parsing config file: /home/qube/.config/polybar/config
error: Invalid value for "bar/yes.monitor", using default value (reason: Environment var ${MONITOR} does not exist (no fallback set))
* Loaded monitor DP-2 (1920x1080+1920+0)
* Bar geometry: 1920x28+1920+0; Borders: 0,0,0,0
notice: pulseaudio: using default sink alsa_output.pci-0000_0b_00.3.analog-stereo
* Starting application
* Starting module/xwindow
* Starting module/date
* Starting module/pulseaudio
* Starting module/memory
* Starting module/powermenu
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=7)
* Configured DPI = 96x96
notice: Loaded font "Terminus:size=14" (name=Terminus, offset=1, file=/usr/share/fonts/misc/ter-u14n.otb)
notice: Loaded font "TerminessTTFNerdFont:pixelsize=13" (name=TerminessTTF Nerd Font, offset=1, file=/usr/share/fonts/TTF/Terminess (TTF) Nerd Font Complete.ttf)
* Bar window: 0x2000002
* Activating tray manager
* Tray window: 0x2000006
error: tray: Failed to put tray above 0x2000002 in the stack (XCB_MATCH (8))
warn: Systray selection already managed (window=0x0c00006)
* Deactivating tray manager
* module/xwindow: Rebuilding cache
* module/date: Rebuilding cache
* module/pulseaudio: Rebuilding cache
* module/memory: Rebuilding cache
* module/powermenu: Rebuilding cache
* Redrawing bar window
* module/xwindow: Rebuilding cache
* module/memory: Rebuilding cache
* module/memory: Rebuilding cache
* module/memory: Rebuilding cache
* module/memory: Rebuilding cache
```

### Expected behavior

click on polybar, preferrably on the clock or the powermenu and be able to click again to shut down the pc for example

### Actual behavior

click on the polybar and an action happens, but after that no inputs are registered on polybar and the xwindow module shows the name of the polybar in itself (polybar-name-display)

### Window Manager and Version

awesome v4.3

### Linux Distribution

Arch Linux with 5.16  Kernel

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

### Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/92535344/152691069-28e6025d-ccfc-4327-a8fa-fbcdfebbd526.png)

**Comment by patrick96** [comment]
See [Known-Issues](https://github.com/polybar/polybar/wiki/Known-Issues#mouse-interactions-not-working-in-awesomewm)

**Comment by qube-03** [comment]
thank you
