### ISSUE TITLE
[issue] Thunar label-urgent never change color accordingly

### ISSUE THREAD

**Issue by thyeun** [polybar/polybar#2594]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I notice that `Thunar` file manager no matter assign to which workspace, the label-urgent color will never get correctly (only Thunar, others no issue).

### Minimal config

```dosini
Polybar setting for `module/i3`

[module/i3]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = true
index-sort = true

enable-click = true
enable-scroll = true
wrapping-scroll = false
reverse-scroll = false

fuzzy-match = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;漣
format = <label-state><label-mode>
format-background = #16161E

label-mode = %mode%
label-mode-padding = 1
label-mode-background = #16161E
label-mode-foreground = ${color.yellow}

label-focused = %icon%
label-focused-foreground = ${color.yellow}
label-focused-background = #16161E

label-unfocused = %icon%
label-unfocused-foreground = ${color.foreground}
label-unfocused-background = #16161E

label-visible = %icon%
label-visible-foreground = ${color.green}
label-visible-background = #16161E

label-urgent = %icon%
label-urgent-foreground = ${color.red}
label-urgent-background = #16161E

label-focused-padding = 1
label-unfocused-padding = 1
label-visible-padding = 1
label-urgent-padding = 1

;label-separator = |
;label-separator-padding = 0
;label-separator-foreground = ${color.foreground}
;label-separator-background = #16161E
```
i3 setting for all workspace
```
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"```
```
i3 rules for workspace
```
assign [class="Alacritty"] 1
assign [class="Google-chrome|firefox|Brave"] 2
assign [class="Thunar"] 3
assign [class="Geany|Code"] 4
assign [class="vlc"] 5
assign [class="Tauon Music Box"] 6
assign [class="Gimp-2.10|Inkscape"] 7
assign [class="Teams|discord"] 8
assign [class="Lxappearance"] 9
```
```


### Polybar log

_No response_

### Expected behavior

color should change according to 
```
label-urgent-foreground = ${color.red}
label-urgent-background = #16161E
```

### Actual behavior

Color remain not change

### Window Manager and Version

i3 version 4.20.1 (2021-11-03) 

### Linux Distribution

Arch linux

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
The i3 module directly gets the workspace state directly from i3. Can you confirm that i3 actually reports the workspace that thunar is on as urgent? Posting the output of `i3-msg -t get_workspaces` would confirm this.

**Comment by thyeun** [comment]
@patrick96 yup, i already confirm it using the below command line

`i3-msg -t get_workspaces | jq '.[] | select(.urgent==true).name'  | cut -d"\"" -f2 2>/dev/null)`

**Comment by patrick96** [comment]
Please post the output of the command `i3-msg -t get_workspaces` (the whole thing, not the command that you ran, I also need to other data reported by i3 to confirm).

Also make sure that your `${color.red}` actually exists and is red.

**Comment by thyeun** [comment]
@patrick96 i already mention, others application will show red, only thunar wont

**Comment by thyeun** [comment]
@patrick96 

The output
```
[{"id":93917999799360,"num":1,"name":"1","visible":true,"focused":true,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999203296,"num":2,"name":"2","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999209648,"num":4,"name":"4","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false}]
```

**Comment by patrick96** [comment]
There are no urgent workspaces in that output. Did you take that output when there was supposed to be an urgent workspace? If so, then the issue is not on the polybar side, rather either Thunar or i3.

**Comment by thyeun** [comment]
@patrick96 i show you two output, with `Thunar` in urgent and `vlc` in urgent, so that you can compare.

Thunar in urgent
```
[{"id":93917999799360,"num":1,"name":"1","visible":true,"focused":true,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999203296,"num":2,"name":"2","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999836368,"num":3,"name":"3","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999209648,"num":4,"name":"4","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false}]
```
Vlc in urgent
```
[{"id":93917999799360,"num":1,"name":"1","visible":true,"focused":true,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999203296,"num":2,"name":"2","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999836368,"num":3,"name":"3","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999209648,"num":4,"name":"4","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":false},{"id":93917999819392,"num":5,"name":"5","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1366,"height":738},"output":"LVDS1","urgent":true}]
```
Picture below show red on vlc but not thunar
![Screenshot_2022-02-16-12-54-07_1366x768](https://user-images.githubusercontent.com/1939446/154249587-1f517501-0753-4c00-8345-357374a10b28.png)

**Comment by thyeun** [comment]
@patrick96 Forgive me, My connect here abit slow and line are not so good, that why sometime will keep on re-edit the post since press comment wont send out :(

**Comment by patrick96** [comment]
So in your two outputs, the workspace that thunar is supposed to be on (3) is not reported as urgent in i3. It seems the issue indeed lies on the side of thunar or i3.

Most likely Thunar does not set itself to urgent, or at least not in a way i3 understands.

**Comment by thyeun** [comment]
@patrick96 i dont think `i3` will do an investigation, since they not do things according to i3bot need. hahaha, any way thanks, im very sure it is either `i3` or `Thunar`, since i double check on `i3`open issue, some of the color issue (client.focused or client.urgent), they wont do things on it just let it continue occur. 

i really dont like to open an issue here or there, since things like this are hard to explain, especially it is combination on i3-thunar-polybar/eww-bar, and it is not a big deal also for some of the people out there.

I will close it for now.
