### ISSUE TITLE
`custom/script`: execute once for multiple bars

### ISSUE THREAD

**Issue by indev29** [polybar/polybar#2605]
## Is your feature request related to a problem? Please describe.
I have a multi-bar setup. Every script module runs independently on each bar which leads to resource ownership conflict for some tasks.   

For example, a script returning the number of updates available with package manager will almost always fail on one of the bars, since it locks corresponding cache for the time of execution.   
There are also some heavy or just long operations, that i would rather not do twice.

## Why does polybar need this feature?
This feature is necessary for multi-bar users. Without it some scripts are just unusable with multiple bars.

## Describe the solution you'd like
I'd like to be able to execute the script once and then reuse its output on every bar. Maybe it would make sense to do as a separate module or just an option to the current one.

## Describe alternatives you've considered
I tried starting bars with a slight delay (i.e. start first, wait 5 seconds, start second). This works, but intervals of all modules need to be considered. It also makes starting process a bit clunky.

The alternative I'm settled with right now - module scripts are running under `systemd` outputting their results to the temporary files. Polybar modules are just simple scripts that grab the output.  
This approach works perfectly, but requires a lot of work to get running, so having polybar support instead would be much more convenient.

**Comment by patrick96** [comment]
This is not possible in polybar's current architecture. Every bar is its own process, it's infeasible to have them somehow coordinate script executions across multiple processes.
