### ISSUE TITLE
`custom/script`: repeat inverval for script failure

### ISSUE THREAD

**Issue by indev29** [polybar/polybar#2606]
## Why does polybar need this feature?
Now that polybar has options for formatting in case of script failure, it makes sense to add other options for failure handling.

## Describe the solution you'd like
`interval-fail` option, which sets the repeat interval in case of the last script execution failed (exited with non-zero status). If not specified, falls back to the `interval` option.

## Describe alternatives you've considered

1. Module scripts running under `systemd` outputting their results to the temporary files. Polybar modules are just simple scripts that grab the output.
2. Module scripts running as `tail`, managing their lifetime manually.  

These approaches require a lot of work to get running, so having polybar support instead would be much more convenient.

**Comment by indev29** [comment]
I could also implement this one.

**Comment by indev29** [comment]
`interval-if` could also be added (#943).   
With `interval-fail` it becomes unclear which one (`interval` or `interval-fail`) should be used for `exec-if`.

**Comment by patrick96** [comment]
Yeah, that's a good idea :+1:

**Comment by indev29** [comment]
Closed with #2630
