### ISSUE TITLE
[Bug]: in 3.6.0 non-existing monitor in unused bar makes polybar shut down

### ISSUE THREAD

**Issue by thugcee** [polybar/polybar#2617]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

`polybar foo`

### Minimal config

```dosini
[bar/foo]
monitor = DP-0
[bar/bar]
inherit = bar/foo
monitor = HDMI-0
```

### Polybar log

```text
error: Uncaught exception, shutting down: Monitor "HDMI-0" not found or disconnected
```

### Expected behavior

I use shared configuration with different bars activated on different machines. Those different machines have different monitors attached. Polybar is started with `polybar $(hostname)`. In previous versions a configuration of unused bars was ignored. In 3.6.0 non-existing `monitor` defined in unused bar causes start failure.

### Actual behavior

Start failure with `Uncaught exception, shutting down`

### Window Manager and Version

bspwm

### Linux Distribution

Ubunto 20.04

### Polybar version

```text
polybar 3.6.0

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by patrick96** [comment]
Please post the entire polybar output of `polybar -l trace foo`

**Comment by thugcee** [comment]
> Please post the entire polybar output of `polybar -l trace foo`

I should have done it sooner. I'm so sorry for wasting your time. It was my bad. I had actually `${env:MONITOR:DP-0}` in the config and I was sure `MONITOR` env var is empty, but it wasn't. Thank you for fast response. I love polybar :)
