### ISSUE TITLE
Don't start a script on polybar startup

### ISSUE THREAD

**Issue by RewardedIvan** [polybar/polybar#2618]
## Is your feature request related to a problem? Please describe.
I have an update script that runs topgrade. That script needs root permissions so it launches a terminal and asks for my password. Every time I change some polybar settings and want to relaunch polybar, the sudo prompt opens (that gets really annoying)

## Why does polybar need this feature?
I think other people will have this issue.

## Describe the solution you'd like
Add a settings called "runonstartup" that can be false or true. You can change the name however you like.

## Describe alternatives you've considered
I didn't find any way around this.

## Additional context
Thanks for taking your time on reading this.

**Comment by patrick96** [comment]
If the script doesn't run at startup when does it run? A second later? Never?

I'm assuming you want to be able to click something on polybar and then have topgrade upgrade your system, right?

In that case I would recommend using the [menu module](https://github.com/polybar/polybar/wiki/Module:-menu) or the [ipc module](https://github.com/polybar/polybar/wiki/Module:-ipc). The commands in the menu module never run at startup and the ipc module can be configured to run nothing at startup.

**Comment by RewardedIvan** [comment]
It runs only after the interval. And repeats (due to tails)

**Comment by patrick96** [comment]
Polybar is definitely not meant to be used as your periodic task runner.

You can of course quite easily mimic such a setting yourself:

```bash
while true; do
    sleep 3600
    # Your command to run topgrade
done
```

And in the script module set `tail = true`.
