### ISSUE TITLE
`polybar-msg`and pacman hook

### ISSUE THREAD

**Issue by ngmoviedo** [polybar/polybar#2622]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Two bars are launched through a `launch.sh`script and its pids are saved to `/tmp/polybar.pids`for later use:
```bash
#!/bin/bash

# Terminate already running bar instances
killall -q polybar
rm /tmp/polybar.pids

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
polybar -r mybar &
echo "$!" >> /tmp/polybar.pids
polybar -r tray &
echo "$!" >> /tmp/polybar.pids

sleep 2

polybar-msg -p $! cmd hide


echo "Polybar launched..."

```

2. Polybar launches successfully and all modules work correctly, including `updates-arch-combined` (shown below). I am able to manually run 
```bash
polybar-msg action updates-arch-combined reset
```
and
```bash
polybar-msg -p $pid action updates-arch-combined reset
```
with the correct `$pid` specified.

3. A Pacman hook is created to automatically reset said module after an update:
```ini
[Trigger]
Operation=Install
Operation=Upgrade
Operation=Remove
Type=Package
Target=*

[Action]
Description=Change update module on Polybar
Depends=polybar
When=PostTransaction
Exec=sh -c '/home/nicolas/.config/polybar/scripts/updates_hook.sh'

```
which calls the following script:
```bash
#!/bin/bash
input="/tmp/polybar.pids"
pid=$(head -n 1 "$input")
polybar-msg -p $pid action updates-arch-combined reset

```
Can confirm that it works when manually executed.

4. Run a Pacman update:
```bash
sudo pacman -Syu
```

### Minimal config

```dosini
[bar/mybar]
monitor = ${env:MONITOR:HDMI-0}
width = 100%
height = 27
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin-left = 0
module-margin-right = 1

font-0 = "Deja Vu Sans:fontformat=book:size=11;1"
font-1 = "Jetbrains Mono Nerd Font:size=12;1"


modules-right = updates-arch-combined

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/updates-arch-combined]
type = custom/ipc
hook-0 = ~/.config/polybar/scripts/updates-arch-combined.sh
initial = 1
interval = 600
click-left = ~/.config/polybar/scripts/updates-arch-combined.sh
format-underline = ${colors.secondary}
```

### Expected behavior

The Pacman hook should run successfully. It worked on previous version of Polybar, although using
```
polybar-msg -p $pid hook updates-arch-combined 1
```
instead of
```
polybar-msg -p $pid action updates-arch-combined reset
```

### Actual behavior

Instead Pacman returns the following error:
```text
(4/5) Change update module on Polybar
polybar-msg: No channel available for pid 788
error: command failed to execute correctly
```

### Window Manager and Version

i3-gaps 4.20.1

### Linux Distribution

Arrch

### Polybar version

```text
polybar 3.6.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by patrick96** [comment]
Since version 3.6, `polybar-msg` has to run under the same user as the target bar instance. Under which user does the pacman hook run?

**Comment by ngmoviedo** [comment]
Oh. I was thinking it might be a user related problem, yes. Pacman is executed with `sudo`so I guess the hook would be running as root. Can confirm that the behavior is the same when executing directly `polybar-msg`as root.

I've been trying to find a way to execute pacman hooks as user instead of root, with no luck so far. I guess this might not be the right place to ask, though.

I've tried, for example, prepending `sudo -u $(logname)`, but I keep getting the same error.

**Comment by patrick96** [comment]
Not completely the wrong place to ask. `polybar-msg` (and polybar itself) use `$XDG_RUNTIME_DIR` to look for the IPC socket. So when you run `polybar-msg`, it needs to have this variable set correctly.

Apparently `machinectl` can help here: https://unix.stackexchange.com/questions/346841/why-does-sudo-i-not-set-xdg-runtime-dir-for-the-target-user

**Comment by ngmoviedo** [comment]
I'll look into it. Thank you very much.

**Comment by pvonmoradi** [comment]
Is it possible to run just one command via `machinectl` method? It also asks for password, I'm not even sure if it could be used in scripts.

**Comment by patrick96** [comment]
@pvonmoradi This works for me:

```
machinectl shell "patrick96@" /usr/bin/bash -c "echo hello world"
```

> It also asks for password, I'm not even sure if it could be used in scripts.

You really only need `machinectl` when you want to run `polybar-msg` as a different user. Otherwise, you can directly use `polybar-msg`. If you want to run `polybar-msg` as a different user, you have to run `machinectl` as root, in which case it shouldn't ask for a password.

**Comment by pvonmoradi** [comment]
@patrick96 Thanks.
That `@` is really needed. Also the binaries in front of bash -c should be in full path.

In `machinectl` manpages it is written:
> Note that systemd-run(1) with its --machine=
           switch may be used in place of the machinectl
           shell command, and allows non-interactive
           operation, more detailed and low-level
           configuration of the invoked unit, as well as
           access to runtime and exit code/status
           information of the invoked shell process. In
           particular, use systemd-run's --wait switch to
           propagate exit status information of the
           invoked process. Use systemd-run's --pty switch
           for acquiring an interactive shell, similar to
           machinectl shell. In general, systemd-run is
           preferable for scripting purposes. However,
           note that systemd-run might require higher
           privileges than machinectl shell.

Does it mean systemd-run is another method in this problem?

**Comment by patrick96** [comment]
> Also the binaries in front of bash -c should be in full path.

Only if there is no `PATH` set. Everything inside of the quotes after `bash -c` is resolved according to your `$PATH` variable, so absolute paths generally aren't needed.

> I wonder if it means systemd-run is another method in this problem...

Sounds like it. Best to try it.

**Comment by nikmosi** [comment]
Exec = /usr/bin/sudo -u nikmosi /bin/zsh -c "echo hook:module/updatesc-trigger1 > /tmp/polybar_mqueue* || true"
1 is hook-id in updatesc-trigger1
