### ISSUE TITLE
[Bug]: Bar won't go to the Bottom

### ISSUE THREAD

**Issue by Moncheeta** [polybar/polybar#2623]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Make two bars. One with the variable "bottom" set to "false" and one with "bottom" set to "true".
2. Start the bars.

### Minimal config

```dosini
[bar/mainbar-dwm]
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true
width = 100%
height = 20
offset-x = 0%
offset-y = 0%
padding-left = 0
padding-right = 0
module-margin-left = 0
module-margin-right = 0

[bar/bottom-bar]
monitor-strict = false
override-redirect = false
bottom = true
fixed-center = true
width = 100%
height = 20
offset-x= 0%
offset-y = 0%
padding-left = 0
padding-right = 0
module-margin-left = 0
module-margin-right = 0
```

### Polybar log

```text
ln: failed to create symbolic link '/tmp/ipc-bottom': File exists
notice: Parsing config file: /home/moncheeta/.config/polybar/config
notice: Parsing config file: /home/moncheeta/.config/polybar/config
warn: No monitor specified, using "DP-0"
error: Invalid value for "module/dwm.label-focused-background", using default value (reason: The reference ${colors.label-focused-background} does not exist (no fallback set))
error: Invalid value for "module/dwm.label-visible-background", using default value (reason: The reference ${colors.label-focused-background} does not exist (no fallback set))
warn: No monitor specified, using "DP-0"
notice: Loaded font "UbuntuMono Nerd Font:size=10" (name=UbuntuMono Nerd Font, offset=2, file=/home/moncheeta/.local/share/fonts/NerdFonts/Ubuntu Mono Nerd Font Complete.ttf)
notice: Loaded font "UbuntuMono Nerd Font:size=10" (name=UbuntuMono Nerd Font, offset=2, file=/home/moncheeta/.local/share/fonts/NerdFonts/Ubuntu Mono Nerd Font Complete.ttf)
notice: Loaded font "UbuntuMono Nerd Font:size=16" (name=UbuntuMono Nerd Font, offset=3, file=/home/moncheeta/.local/share/fonts/NerdFonts/Ubuntu Mono Nerd Font Complete.ttf)
notice: Loaded font "UbuntuMono Nerd Font:size=16" (name=UbuntuMono Nerd Font, offset=3, file=/home/moncheeta/.local/share/fonts/NerdFonts/Ubuntu Mono Nerd Font Complete.ttf)
notice: Loaded font "Font Awesome 5 Free:style=Regular:pixelsize=8" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "Font Awesome 5 Free:style=Regular:pixelsize=8" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "Font Awesome 5 Free:style=Solid:pixelsize=8" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "Font Awesome 5 Free:style=Solid:pixelsize=8" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "Font Awesome 5 Brands:pixelsize=8" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "Font Awesome 5 Brands:pixelsize=8" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
```

### Expected behavior

One bar should be at the top, and the other bar should be at the bottom.

### Actual behavior

Both bars end up at the top.

### Window Manager and Version

dwm with patches

### Linux Distribution

Manjaro

### Polybar version

```text
polybar 3.5.2-100-g0c3e139a

Features: +alsa +curl +dwm +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

### Additional Context / Screenshots

![2022-03-04_16-17](https://user-images.githubusercontent.com/72705603/156850259-f481ffd5-55ba-470b-ad12-f72bc7e55765.png)

You can also see that the kde connect icon is at the bottom.

![2022-03-04_16-27](https://user-images.githubusercontent.com/72705603/156850364-bf9058e4-8910-4423-9258-2dc7e01656bb.png)

**Comment by patrick96** [comment]
You are using a fork of polybar, next time please first ask for support there.

This issue seems to be fixed in the newest version (3.6.0).

**Comment by Moncheeta** [comment]
I tried the official version of polybar and it still happens. I was using polybar-dwm-module before to communicate with dwm. This time, I use the official polybar for the bottom bar the polybar-dwm-module for the top bar.

**Comment by patrick96** [comment]
I see. Please update your post with the following:

* The new output of `polybar -vvv`
* Which dwm patches you are using

Polybar does accurately compute and request its position at the bottom of the monitor (that's why you see the tray on the bottom), but dwm does not seem to respect that request and places it at the top.
This does not seem to happen with vanilla dwm, so most likely one of the patches is at fault here.
