### ISSUE TITLE
Fonts to get started with Polybar

### ISSUE THREAD

**Issue by pguerin3** [polybar/polybar#2629]
I know the documentation makes it clear that the polybar example doesn't work 100% off the shelf:
```
> polybar example
```
However I would like to see some icons in an example as a starting point to creating my own configuration.
After installing all the Awesome fonts in my distro (Fedora), there are still no icons showing and instead I get the warnings:
```
warn: Dropping unmatched character  (U+e202) in ' '
```
So to get started, which fonts would be recommended to install for polybar?

**Comment by patrick96** [comment]
The issue tracker is meant for bug reports and feature requests. Please don't ask support questions here, read our [Support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) for a list of resources where you can ask questions. We are more than happy to help you there.

**Comment by pguerin3** [comment]
Just found that I should install the following from Github, as it isn't available in the Fedora repo:
https://github.com/stark/siji

**Comment by pguerin3** [comment]
For Fedora, if you want all the emojis for the example bar to show then you need to install the following:

1) For the U+1f507 (muted speaker) you need the google-noto-emoji font (or similar).
The package is google-noto-emoji-color-fonts.

2) Then edit the font-1 line in the config file (~/.config/polybar/config) to this so that Polybar can recognise the font.
font-1 = NotoColorEmoji:fontformat=truetype:scale=8;0

3) Then install the following siji font for the other (non-muted-speaker) emojis in the example configuration:
https://github.com/stark/siji
Also you need to install the xset app for the siji font.

Hope this information is able to assist all the Polybar newbies - especially those that are using Fedora.

**Comment by patrick96** [comment]
Oh, you're right, there is indeed an emoji in the old sample config. That is an oversight, we tried to explicitly only use characters provided by the fonts listed in the `font-*` settings.

Another reason why the new default config doesn't use any font icons :wink:
