### ISSUE TITLE
[Bug]: Volume module does not update after connecting to different audio output

### ISSUE THREAD

**Issue by wiktor-waj** [polybar/polybar#2665]
### Checklist

- [x] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Launch bar with volume module on
2. Change volume -> Volume updates normally on polybar
3. Change audio output (connecting to bluetooth headset in my case)
4. Change volume -> Volume does not update on polybar

### Minimal config

```dosini
[bar/wpgtk]

modules-left = i3 
modules-right = volume

[module/volume]
type = internal/alsa

format-volume = %{A3:pavucontrol &:}<ramp-volume> <label-volume>%{A}
;format-volume = <ramp-volume> <label-volume>
format-volume-padding = 0
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
```

### Polybar log

```text
* Forwarding action to modules (module: 'volume', action: 'inc', data: '')
* Delivered action to 1 module
* module/xkeyboard: Rebuilding cache
* module/volume: Rebuilding cache
* Redrawing bar window
* module/volume: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'dec', data: '')
* Delivered action to 1 module
* module/volume: Rebuilding cache
* Redrawing bar window
* module/volume: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* module/openweathermap-detailed: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'inc', data: '')
* Delivered action to 1 module
* module/xkeyboard: Rebuilding cache
* module/volume: Rebuilding cache
* Redrawing bar window
* module/volume: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'dec', data: '')
* Delivered action to 1 module
* module/volume: Rebuilding cache
* Redrawing bar window
* module/battery: Polling values (inotify fallback)
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'inc', data: '')
* Delivered action to 1 module
* module/xkeyboard: Rebuilding cache
* module/volume: Rebuilding cache
* Redrawing bar window
* module/volume: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'dec', data: '')
* Delivered action to 1 module
* module/volume: Rebuilding cache
* Redrawing bar window
* module/volume: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* module/date: Rebuilding cache
* Redrawing bar window
* module/battery: Polling values (inotify fallback)
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'inc', data: '')
* Delivered action to 1 module
* module/xkeyboard: Rebuilding cache
* module/xwindow: Rebuilding cache
* module/xwindow: Rebuilding cache
* Forwarding action to modules (module: 'volume', action: 'dec', data: '')
* Delivered action to 1 module
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'inc', data: '')
* Delivered action to 1 module
* module/xkeyboard: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'dec', data: '')
* Delivered action to 1 module
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'inc', data: '')
* Delivered action to 1 module
* module/xkeyboard: Rebuilding cache
* Forwarding action to modules (module: 'volume', action: 'dec', data: '')
* Delivered action to 1 module
* Forwarding action to modules (module: 'volume', action: 'inc', data: '')
* Delivered action to 1 module
* module/xkeyboard: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'dec', data: '')
* Delivered action to 1 module
* Forwarding action to modules (module: 'volume', action: 'inc', data: '')
* Delivered action to 1 module
* module/xkeyboard: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
* Forwarding action to modules (module: 'volume', action: 'dec', data: '')
* Delivered action to 1 module
* module/date: Rebuilding cache
* Redrawing bar window
* module/battery: Polling values (inotify fallback)
* module/battery: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
```

### Expected behavior

Volume percentage will update 

### Actual behavior

Volume percentage stays the same

### Window Manager and Version

i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors

### Linux Distribution

5.16.13-arch1-1

### Polybar version

```text
polybar 3.6.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

In the Polybar log section you can see that when I change volume using volume module with scroll it clearly works and it even says it is updating it, yet it does not take any effect on the bar itself.
Only way to make the volume module update again after changing audio output is to restart the polybar which is not ideal.
I've made 1 min video to highlight the bug and how to reproduce it: https://youtu.be/3uaDHVIXbn4
![image](https://user-images.githubusercontent.com/46874349/160236434-bc3e4016-1f40-49e6-b87e-cb2f9018f2f6.png)

**Comment by patrick96** [comment]
Hi, thanks for reporting :)

Funnily enough the thing that is "misbehaving" here, is what happens when you change the volume using the scroll wheel.

The module itself does not have the functionality to automatically update when the default soundcard changes, it always uses the connection to the soundcard that was selected when the module started. The reason that scrolling actually "correctly" changes the volume is because the code executed as a result of scrolling does not reuse that connection but always creates a new connection (and if the default soundcard changes, the connection will be to a different card).
We have to do this because the code for the scroll-handler runs in a different thread and would otherwise cause concurrency issues.

For your specific case, I would suggest using the [pulseaudio module](https://github.com/polybar/polybar/wiki/Module:-pulseaudio), muting/unmuting doesn't work properly anyway when you do it through alsa. It will automatically switch audio outputs if you don't specify a sink.

The behavior in the alsa module will probably be "fixed" (it will change the volume, the module is displaying) once we either get better concurrency handling in the module or we manage to integrate it into our main loop (#2337)
