### ISSUE TITLE
[Bug]: Angle brackets escaped in text module

### ISSUE THREAD

**Issue by coloursofnoise** [polybar/polybar#2673]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Launch polybar with provided config

### Minimal config

```dosini
[bar/main]
modules-center = text

[module/text]
type = custom/text
CONTENT = some text<some more text>even more text
```

### Polybar log

```text
> polybar -c polybar-minimal-config.ini --log=trace
notice: Parsing config file: polybar-minimal-config.ini
- config_parser: Parsing polybar-minimal-config.ini
* Loaded monitor DVI-0 (1920x1080+1280+0)
* Configured DPI = 96x96
* Bar geometry: 1920x24+1280+0; Borders: 0,0,0,0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Setup user-defined modules
* Starting application
- controller: Main thread id = 1
* Starting module/text
* Entering event loop (thread-id=1)
- bar: Create renderer
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- renderer: Load fonts
warn: No fonts specified, using fallback font "fixed"
notice: Loaded font "fixed" (name=Bitstream Vera Sans, offset=0, file=/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf)
* Bar window: 0x0a00001
- bar: Reconfigure window
- bar: Set window WM_NAME
- bar: Set window _NET_WM_WINDOW_TYPE
- bar: Set window _NET_WM_STATE
- bar: Set window _NET_WM_DESKTOP
- bar: Set window _NET_WM_PID
- bar: Map window
- bar: Draw empty bar
- bar: Setup tray manager
* Disabling tray manager (reason: missing `tray-position`)
* module/text: Rebuilding cache
- bar: Force update
* Redrawing bar window
- renderer: flush(2 geom=203x24+859+0, falloff=0)
- bar: Received expose event
notice: Received signal(2): Interrupt
* Eventloop finished
notice: Termination signal received, shutting down...
- controller: Detach signal receiver
- controller: Stop modules
* module/text: Stopping
- module/text: Release sleep lock
* Deconstruction of module/text took 0 ms.
- module/text: Deconstructing
* Waiting for spawned processes to end
* Reached end of application...
```

### Expected behavior

`some text<some more text>even more text`

### Actual behavior

`some texteven more text`

### Window Manager and Version

i3-gaps 4.19.1

### Linux Distribution

Linux Mint 20.3

### Polybar version

```text
polybar 3.6.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags:  -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

Since `content` for `custom/text` modules is handled as `format-NAME` ([docs](https://github.com/polybar/polybar/wiki/Module:-text#additional-formatting),[source](https://github.com/polybar/polybar/blob/652652f9435b4013db026820af490963e345db4b/src/modules/text.cpp#L11)) all tags are escaped, but since there are no defined tags for the module, there is no way to use a tag to substitute text.

**Comment by patrick96** [comment]
See also #1331

There was an attempt to make the text module more like the other modules in #1342 but that introduced a breaking change.

We can probably achieve almost the same thing without breaking anything (by simply completely deprecating `content` and replace it with the standard `format` and `<label>`).
