### ISSUE TITLE
[Bug]: `px` is treated as spaces.

### ISSUE THREAD

**Issue by ilexite** [polybar/polybar#2678]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. `polybar -c minimal.ini minimal`
2. observe

### Minimal config

```dosini
[colors]
bg1 = #282c34
bg2 = #2f333d
fg = #979fad

[bar/minimal]
font-0 = JetBrains Mono:size=14;4

; 30 pixels - correct
height = 30px

background = ${colors.bg1}
foreground = ${colors.fg}

; 5 spaces, not pixels - incorrect
module-margin = 5px

modules-left = foo bar baz

[module/foo]
type = custom/text
content = "first label; in the correct place"
content-background = ${colors.bg2}

; 5 spaces, not pixels - incorrect
content-padding = 5px

[module/bar]
type = custom/text
content = "second label; too much offset"
content-background = ${colors.bg2}

; 5 spaces, not pixels - incorrect
content-padding = 5px

[module/baz]
type = custom/text
content = "third label; same issue"
content-background = ${colors.bg2}

; 5 spaces, not pixels - incorrect
content-padding = 5px
```

### Polybar log

```text
notice: Parsing config file: .config/polybar/minimal.ini
notice: Loaded font "JetBrains Mono:size=14" (name=JetBrains Mono, offset=4, file=/usr/share/fonts/jetbrains-mono/JetBrainsMono-Regular.ttf)
notice: Termination signal received, shutting down...
```

### Expected behavior

I expected modules to have 5px of padding and 10px in-between one another.

### Actual behavior

modules were 10 spaces away from each other and had 5 spaces of padding.

### Window Manager and Version

dwm 6.3

### Linux Distribution

Gentoo 5.15.14

### Polybar version

```text
polybar 3.5.7

Features: +alsa -curl -i3 -mpd -network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Gentoo
Compiler: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -O2 -pipe -Wall -Wextra -Wpedantic
Linker flags: -Wl,-O1 -Wl,--as-needed
```

**Comment by patrick96** [comment]
That's a version 3.6 feature, you are still using an older version
