### ISSUE TITLE
[Bug]: Polybar seems to be affecting the execution of a bash script

### ISSUE THREAD

**Issue by citosid** [polybar/polybar#2760]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Create a new custom script module
2. Add this script:
    ```bash
    #!/usr/bin/env bash

   DOMAIN="https://own.gitlab.server.org"
   HEADER_AUTH="PRIVATE-TOKEN: ${GITLAB_TOKEN}"

   _merge_count=$(curl --silent --header "${HEADER_AUTH}" "${DOMAIN}/api/v4/merge_requests?scope=assigned_to_me&state=opened" | jq -r '. | length')
   _todo_count=$(curl --silent --header "${HEADER_AUTH}" "${DOMAIN}/api/v4/todos" | jq -r '. | length')

   echo -n "  ${_todo_count}  ${_merge_count}"
   ```

### Minimal config

```dosini
[module/gitlab]
type = custom/script
exec = ~/.config/polybar/scripts/gitlab_status.bash
interval = 60

format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-padding = 1
format-underline = ${colors.background}
format-prefix = " "
format-prefix-foreground = #fc6d26
label = %output%
```

### Expected behavior

Output 7 Merge requests and 1 TODO:

![image](https://user-images.githubusercontent.com/201430/177005082-84e60a3f-5e13-46a4-896c-19bb99ddf4d7.png)

### Actual behavior

Outputs 1 and 1

![image](https://user-images.githubusercontent.com/201430/177005093-b4237c9b-a265-4cda-93f8-853b5ffe0ee5.png)

### Window Manager and Version

i3 version 4.20-non-git © 2009 Michael Stapelberg and contributors

### Linux Distribution

Linux blinkin 5.10.28 #2 SMP PREEMPT Sun Apr 11 13:25:48 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

**Comment by patrick96** [comment]
Is `GITLAB_TOKEN` set when you run polybar?

Also, you could dump the output of the curl commands to a log file and compare to see why you get different results

**Comment by citosid** [comment]
I tried that... everytime it fails the data is correct... so not really sure why it fails. I'm gonna close this since it is also hard to replicate. sometimes it fails, sometimes it does not... 

Thanks for replying @patrick96 ! And thanks for your hard work! I love this tool ;)
