### ISSUE TITLE
[Bug]: When autostarted in awesomewm, polybar is on top of fullscreen windows

### ISSUE THREAD

**Issue by beni69** [polybar/polybar#2766]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. create an autostart shell script file
```sh
#!/bin/sh
polybar main &
```
2. launch it in awesomewm
```lua
awful.spawn.with_shell("~/.config/awesome/autorun.sh")
```

### Minimal config

```dosini
[bar/main]
modules-left = xwindow
override-redirect = true
wm-restack = generic

[module/xwindow]
type = internal/xwindow
```

### Polybar log

```text
polybar|notice:  Parsing config file: /home/beni/.config/polybar/config.ini
polybar|trace: config_parser: Parsing /home/beni/.config/polybar/config.ini
polybar|info:  Loaded monitor eDP-1 (1920x1080+0+0)
polybar|info:  Configured DPI = 96x96
polybar|info:  Bar geometry: 1920x24+0+0; Borders: 0,0,0,0
polybar|trace: bar: Attach X event sink
polybar|trace: bar: Attach signal receiver
polybar|trace: controller: Setup user-defined modules
polybar|notice:  Loading module 'xwindow' of type 'internal/xwindow'
polybar|notice:  Loaded 1 modules
polybar|info:  Starting application
polybar|trace: controller: Main thread id = 1
polybar|info:  Starting module/xwindow
polybar|info:  Entering event loop (thread-id=1)
polybar|trace: bar: Create renderer
polybar|trace: renderer: Get TrueColor visual
polybar|trace: renderer: Allocate colormap
polybar|trace: renderer: Allocate output window
polybar|trace: renderer: Allocate window pixmaps
polybar|trace: renderer: Allocate graphic contexts
polybar|trace: renderer: Allocate alignment blocks
polybar|trace: renderer: Allocate cairo components
polybar|trace: renderer: Load fonts
polybar|warn:  No fonts specified, using fallback font "fixed"
polybar|notice:  Loaded font "fixed" (name=Liberation Mono, offset=0, file=/usr/share/fonts/liberation/LiberationMono-Regular.ttf)
polybar|info:  Bar window: 0x0800001
polybar|trace: bar: Reconfigure window
polybar|info:  Successfully restacked bar window
polybar|trace: bar: Set window WM_NAME
polybar|trace: bar: Set window _NET_WM_WINDOW_TYPE
polybar|trace: bar: Set window _NET_WM_STATE
polybar|trace: bar: Set window _NET_WM_DESKTOP
polybar|trace: bar: Set window _NET_WM_PID
polybar|trace: bar: Map window
polybar|trace: bar: Draw empty bar
polybar|trace: bar: Setup tray manager
polybar|info:  Disabling tray manager (reason: missing `tray-position`)
polybar|info:  module/xwindow: Rebuilding cache
polybar|trace: bar: Force update
polybar|info:  Redrawing bar window
polybar|trace: bar: Received expose event
polybar|info:  module/xwindow: Rebuilding cache
polybar|trace: bar: Ignoring update (unchanged)
polybar|info:  module/xwindow: Rebuilding cache
polybar|info:  Redrawing bar window
polybar|trace: renderer: flush(1 geom=90x24+0+0, falloff=0)
```

### Expected behavior

1. opened a terminal
2. set it to fullscreen
3. expected the bar to not be on top of the window

### Actual behavior

the bar was on top of the window

### Window Manager and Version

awesome v4.3

### Linux Distribution

Arch Linux with kernel 5.18.11-arch1-1

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

This issue only occurs if polybar is launched before I open any windows. If I put `sleep 5 && polybar [...]` in my autostart script and I open a terminal for example before the 5 seconds, it works fine. If I start polybar manually from a terminal it's also fine. If I autostart it with the `--reload` option and i write the config file and the bar restarts, that also fixes the problem temporarily.

**Comment by patrick96** [comment]
Hmm, looks like the generic restacker may not work on awesomewm.

Can you post the output of `xwininfo -root -tree` when polybar appears above a fullscreen window?

**Comment by beni69** [comment]
here it is:
```

xwininfo: Window id: 0x79d (the root window) (has no name)

  Root window id: 0x79d (the root window) (has no name)
  Parent window id: 0x0 (none)
     14 children:
     0x1600000 (has no name): ()  1x1+0+0  +0+0
     0x1400000 (has no name): ()  1x1+0+0  +0+0
     0x1200000 (has no name): ()  1x1+0+0  +0+0
     0x1000000 (has no name): ()  1x1+0+0  +0+0
     0xc00000 (has no name): ()  1x1+-1+-1  +-1+-1
     0x800004 "picom": ("picom" "picom")  1x1+0+0  +0+0
     0x40000d "Awesome drawin": ("awesome" "awesome")  100x32+0+0  +0+0
     0x400007 "Awesome no input window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0x400006 "Awesome systray window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0x400005 "awesome": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0x400004 "Awesome WM_Sn selection owner window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0xc0000a "Polybar tray window": ("tray" "Polybar")  1x32+1907+5  +1907+5
     0xc00002 "polybar-main_eDP-1": ("polybar" "Polybar")  1920x42+0+0  +0+0
     0x40005a (has no name): ()  1920x1080+0+0  +0+0
        1 child:
        0xe00002 "Alacritty": ("Alacritty" "Alacritty")  1920x1080+0+0  +0+0
```

**Comment by patrick96** [comment]
Hmm, I can't reproduce this on my end with the default `rc.lua`.

Can you share your `rc.lua`? How are you putting alacritty in fullscreen mode? Does it also happen with `override-redirect = false`?

**Comment by beni69** [comment]
I've tried the default config and it does indeed work. The default awesome bar is on top of polybar, but when I fullscreen a window none of them are visible. The problem seems to arise when I remove the code for setting up the default bar from the `rc.lua`. (I comment out lines 199-218) so maybe it could be a problem in awesome?
I put alacritty in fullscreen mode by using the default keybind `Mod + F`. But doing any other way produces the same result, for example putting a youtube video in fullscreen from a browser.
This problem does not occur with `override-redirect = false`, but then mouse clicks are broken.

**Comment by patrick96** [comment]
So for some reason, the terminal window appears at the bottom of the window stack now, even below polybar, when those lines are removed.

I'm not sure why this happens as those settings seem unrelated.

I would argue that this is something weird going on on the awesomeWM side. Polybar is behaving correctly as it is placing itself at the bottom of the window stack when it starts. It's just that awesomeWM places new windows below polybar.

**Comment by beni69** [comment]
I'll close this since the problem doesn't seem to be here. Thank you for your help!
