### ISSUE TITLE
Option to turn off struts

### ISSUE THREAD

**Issue by patrick96** [polybar/polybar#2769]
### Discussed in https://github.com/polybar/polybar/discussions/2768

<div type='discussions-op-text'>

<sup>Originally posted by **patrick96** July 16, 2022</sup>
Polybar's struts can cover entire monitors if polybar is placed on a monitor that is in the middle of the X root screen. See also previous issues with tint2: https://gitlab.gnome.org/GNOME/mutter/-/issues/452 

There was also a report for this on [reddit](https://www.reddit.com/r/Polybar/comments/vz9271/polybar_restricts_my_windows_to_only_one_monitor/)

Ideally, WMs would compensate for that and only apply the parts of the struts which do not cover entire screens. However, many don't.

On the polybar side, the only conforming solution seems to be to just turn off struts.

For this, we should give the user an option in the bar section to enable/disable struts (enabled by default).
If struts are disabled, `global/wm.margin-{top,bottom}` being set, should produce a warning, because they are ignored.

</div>

**Comment by VanillaViking** [comment]
Hi, I would like to work on this.  so, `bar::reconfigure_struts()` should be run **if** a new struts option is set to true ?
Is this the correct way to implement it?

**Comment by patrick96** [comment]
Yes, I think that would be good solution
