### ISSUE TITLE
Native styling support for custom IPC modules

### ISSUE THREAD

**Issue by patrick96** [polybar/polybar#2775]
### Discussed in https://github.com/polybar/polybar/discussions/2771

<div type='discussions-op-text'>

<sup>Originally posted by **beyond9thousand** July 21, 2022</sup>
Would love to be able to assign different colors to different hooks in a custom IPC module</div>

---

That could probably be done by supporting `format-X` for every `hook-X` and have `format-X` inherit from `format`.

PRs welcome :)

**Comment by madhavpcm** [comment]
Hey I would love to contribute, please let me know where I should start :). I assume it is the src/ipc folder, where I should add code for format-x like in other modules.

**Comment by patrick96** [comment]
@madhavpcm Awesome! I'll assign the issue to you.

The code you are looking for is in `src/modules/ipc.cpp`. The stuff in `src/ipc` should not be relevant for this, it is for polybar's IPC mechanism (not just the ipc module).

**Comment by madhavpcm** [comment]
From the users perspective, I am assuming will write they're config something like 
```
type = custom/ipc
format = <label>
format-0-background= ${color0}
format-1-background= ${color1}
format-2-background= ${color2}

hook-0 = echo foobar
hook-1 = date +%s
hook-2 = whoami
initial = 1
click-left = "#demo.hook.0"
click-right = "#demo.hook.1"
double-click-left = "#demo.hook.2"
```
 and for each hook a different color will be displayed ?

So do I need to implement a new class say
```
class hook_format private hook{
  size_t hook_no; 
  string color
}; 

``` 
or is there something I can do to the existing m_formatter

**Comment by patrick96** [comment]
Yes, I would expect the module config to look like that.

Each format can be configured completely independently (not just changing a color), but `m_formatter` already does that work for you.
What you have to do, is register a new format for each hook using `m_formatter->add(...)` and in the `get_format` function return the right format for the currently selected hook.

Have a look at the `github` module, it's a relatively simple example of a module with multiple formats (only 2 though)
