### ISSUE TITLE
[Bug]: Filesystem and Network modules don't inherit DEFAULT_FORMAT

### ISSUE THREAD

**Issue by createchange** [polybar/polybar#2777]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Hello,

I was working with polybar this evening (thanks for the neat, useful tool, by the way), and was exploring how I could integrate pywal with it.

As I put in some work, I noticed that I couldn't ovewrite the color for the file system and network modules. I checked the code, and noted that other modules inherit a `DEFAULT_FORMAT` attribute, but that the two aforementioned ones do not. Here is an example where it does exist: https://github.com/polybar/polybar/blob/master/src/modules/memory.cpp#L18-L23

The alternative seems to be to hardcode in the hex code or, if I want to do it dynamically, go the environment variable route. Ideally, I would prefer to be able to use the `format-background` / `format-foreground` , etc. paradigm that I found exists for other modules. That made it very easy to bring some consistency into my theming.

### Minimal config

```dosini
N/A
```

### Expected behavior

Able to set foreground/background or network and file system modules with same attributes that are used in other modules.

### Actual behavior

Configured attributes are ignored.

### Window Manager and Version

i3-gaps, 4.20.1 

### Linux Distribution

arch-parallels 5.18.1-1-aarch64-ARCH #1 SMP PREEMPT Wed Jun 1 19:34:45 MDT 2022 aarch64 GNU/Linux

### Polybar version

```text
~ ➜  polybar --version
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

### Additional Context / Screenshots

I very well may be misunderstanding how to do what I am trying to accomplish. If so, apologies in advance!

Here is a screenshot:
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/29058450/182065217-1027147e-e276-42ab-a78c-65db6f537a9c.png">

**Comment by patrick96** [comment]
Wouldn't classify this as a bug. `DEFAULT_FORMAT` is only meant to hardcode the default name for the config option, it does not mean that that config option holds the default values others inherit.

There are config-wide formatting settings in the `[settings]` section that *are* inherited: https://github.com/polybar/polybar/wiki/Configuration#application-settings

There is also already a feature request asking for per-module fallbacks: #2022. But there are some backward-compatibility concerns
