### ISSUE TITLE
[Bug]: Weird gap in underline between format-prefix and module when using emoji

### ISSUE THREAD

**Issue by andreykaere** [polybar/polybar#2785]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Run `polybar bar`.

### Minimal config

```dosini
[bar/bar]
width = 100%
height = 27
radius = 6.0
fixed-center = false

background = #252737
foreground = #dfdfdf

line-size = 3
line-color = #f00

border-size = 4
border-color = #00000000


wm-name = "mypolybar"

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2



enable-ipc = true

font-0 = fixed:pixelsize=10;2
font-1 = fixed:pixelsize=10;2
font-2 = NotoColorEmoji:fontformat=truetype:scale=10:antialias=false;1
override-redirect = true

modules-right = memory



[module/memory]
type = custom/script
exec = echo "foo"
label = "%output%"
interval = 30
format-prefix = "🧠 "
format-prefix-foreground = #f4abba
format-underline = #f4abba

; vim:ft=dosini
```

### Polybar log

```text
notice: Parsing config file: polybar-minimal-config
notice: Loaded font "fixed:pixelsize=10" (name=DejaVu Sans, offset=2, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
notice: Loaded font "fixed:pixelsize=10" (name=DejaVu Sans, offset=2, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
notice: Loaded font "NotoColorEmoji:fontformat=truetype:scale=10:antialias=false" (name=Noto Color Emoji, offset=1, file=/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf)
notice: Termination signal received, shutting down...
```

### Expected behavior

No gap in underline between `format-prefix` emoji and module itself.

### Actual behavior

Some modules are shown with gap in underline between module and `format-prefix` emoji.
![image](https://user-images.githubusercontent.com/32775308/184250588-57380999-4671-492e-836a-452dec925971.png)

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Ubuntu 22.04

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Debian package, build flags removed from output for reproducibility
You can refer to the build logs at:
https://buildd.debian.org/status/package.php?p=polybar
```

**Comment by parmort** [comment]
Can you include a screenshot of the behavior you're experiencing using exactly the minimal config you provided?

**Comment by andreykaere** [comment]
![image](https://user-images.githubusercontent.com/32775308/185578207-d65ff933-86eb-445b-93d4-ceeed4ba3dd0.png)

I just wanted to show you with the previous screenshot, that it's not persistent. For some modules it's the case, for some it's not.

**Comment by parmort** [comment]
My apologies, I didn't see the break in the underline in your original screenshot. Could you update your description of the issue with something to that effect? I don't have this issue using FontAwesome in my personal config­.

**Comment by andreykaere** [comment]
I am sorry, I don't really understand what you mean by "Could you update your description of the issue with something to that effect?". I mean, I don't know what's wrong with my current description of the issue.

**Comment by parmort** [comment]
I can only see a gap in the underline of the affected modules—the text rendering looks ok. I was asking if you could edit your description to mention that the gap appears in the underline.

**Comment by patrick96** [comment]
This is one of the weirder bugs that I've seen recently. I reduced the config even further and noticed a few things:

```dosini
[bar/bar]
width = 200px
font-0 = monospace
font-1 = NotoColorEmoji:scale=10

modules-left = text

[module/text]
type = custom/text
format = "🧠%{-u}   %{-u}    %{-u}  "
format-background = #fff
```

![scrot](https://user-images.githubusercontent.com/2452038/186521892-9e3bc0ed-3b4d-46f0-97de-b6f8284b6f47.png)

Just the mere existence of the emoji messes up the rendering later on. It seems the whole renderer jumps forward a few pixels.

These gaps happen whenever I put a `%{-u}` tag (any other tag works as well). Polybar renders all consecutive text at once, but when there is a tag, it first has to process the tag and then render what comes after it. So it seems whenever polybar renders a new piece of text (after every tag), the renderer for some reason introduces a small gap, but this only happens if the emoji is there at the start.

There seems to be some mismatch between how many pixels polybar thinks it rendered and how many it actually rendered. I'll have to investigate further.

**Comment by patrick96** [comment]
Alright, looks like the emoji takes about 17.5 pixels to render, while all other characters take an integer number of pixels. Because of that all future rendering blocks start at a half pixel which cairo doesn't really handle that well, causing these gaps. I think I'm able to solve this by just rounding up the number of pixels taken up by characters.

**Comment by parmort** [comment]
I did a little more investigating and I found that all of the emoji present in the original screenshot present gaps, some were "darker" than others (depending on the bg color).

![poly](https://user-images.githubusercontent.com/26724997/186536577-68ed9e4e-a712-4e8d-8bbf-efbe9d6ea5f6.png)

```ini
[bar/bar]
width = 350px
font-0 = monospace
font-1 = NotoColorEmoji:scale=10

modules-right = text1 text2 text3 text4 text5 text6
module-margin-left=1

[module/text1]
type = custom/text
format = "🧠%{-u}   "
format-background = #fff

[module/text2]
type = custom/text
format = "📅%{-u}   "
format-background = #fff

[module/text3]
type = custom/text
format = "💻%{-u}   "
format-background = #fff

[module/text4]
type = custom/text
format = "🔥%{-u}   "
format-background = #fff

[module/text5]
type = custom/text
format = "🔋%{-u}   "
format-background = #fff

[module/text6]
type = custom/text
format = "🔊%{-u}   "
format-background = #fff
```

**Comment by andreykaere** [comment]
Thanks a lot for fixing it! It was annoying me for quite some time!
