### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by QiangF** [polybar/polybar#2799]
### Steps to reproduce

1. start polybar
2. hide it with:

    xdo hide -N Polybar

3. show it with:

    xdo hide -N Polybar

4. the tray is always shown.

### Minimal config

```dosini
wm-restack =
override-redirect = true

tray-position = right
tray-detached = false
```

### Window Manager and Version

openbox

### Linux Distribution

arch

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by QiangF** [comment]
When I set override-redirect = false, then they are in sync. But mouse click doesn't work on windows key down.

I have a setup that the bar only appears on windows key down.
https://github.com/polybar/polybar/issues/1209

**Comment by patrick96** [comment]
Why not use `polybar-msg` to show/hide the bar?
