### ISSUE TITLE
[Bug]: Polybar PulseAudio empty string in label-muted doesn't render

### ISSUE THREAD

**Issue by jayp0521** [polybar/polybar#2800]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

`polybar -q main -c "$DIR"/config &`

Load pulseaudio module below with polybar. You shall see the icon and the spacing both are not there.

### Minimal config

```dosini
[module/volume]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = false

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

format-volume = <ramp-volume> <label-volume>

format-muted-prefix = 婢
format-muted-prefix-font = 2
format-muted-prefix-foreground = ${color.RED}

label-volume = %percentage%%
label-muted = ""
label-muted-foreground = #757575

ramp-volume-0 = 奄
ramp-volume-1 = 奄
ramp-volume-2 = 奄
ramp-volume-3 = 奔
ramp-volume-4 = 奔
ramp-volume-5 = 奔
ramp-volume-6 = 墳
ramp-volume-7 = 墳
ramp-volume-8 = 墳
ramp-volume-9 = 墳
ramp-volume-font = 2
ramp-volume-foreground = ${color.BLUE}

ramp-headphones-0 = 
ramp-headphones-1 = 

; Right and Middle click
click-right = pavucontrol
```

### Expected behavior

Running the polybar module, I should be able to see just the icon without any sort of spacing.

I should be able to pass in

`label-muted=""`

### Actual behavior

The image below is what I currently see with `label-muted = " "`.

![image](https://user-images.githubusercontent.com/36803168/186293308-618fcc21-0cd6-4a3c-841f-8cdb2cf6977a.png)

This is what I see without the space:
![image](https://user-images.githubusercontent.com/36803168/186294986-3e78c94a-9ffd-4158-bd0d-dee9d0b02150.png)

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Archcraft 2022.07.18

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by patrick96** [comment]
Not a bug, this is expected behavior.

If a format (`format-muted` in your case) is empty, its prefix and suffix will not be shown.
