### ISSUE TITLE
[Bug]: Shows usb0 as disconnected when it's connected

### ISSUE THREAD

**Issue by locriacyber** [polybar/polybar#2815]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

[The network module](https://github.com/polybar/polybar/wiki/Module:-network) shows the interface below as disconnected. `%netspeed%` does show network speed properly.

`usb0` is usb tethering.

```
$ ip link

9: usb0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
```

### Minimal config

```dosini
[bar/main]
width = 100%
height = 16pt
radius = 0

separator = |

font-0 = "Fira Code:style=Medium:size=10;2"
font-1 = "Noto Color Emoji:style=Regular:scale=10;2"
font-2 = "Noto Sans Symbols:style=Regular;size=11;2"
font-3 = "Noto Sans Symbols2:style=Regular;size=11;2"
font-4 = "Noto Sans Math:size=12;3"
font-5 = "Symbols Nerd Font:size=11;2"

modules-right = eth


[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %ifname% %netspeed%
label-disconnected-foreground = ${colors.disabled}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip% %netspeed%
```

### Polybar log

```text
N/A
```

### Expected behavior

The should show usb0 as connected.

### Actual behavior

The should show usb0 as disconnected.

### Window Manager and Version

N/A

### Linux Distribution

N/A

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

![screenshot](https://user-images.githubusercontent.com/74560659/189541947-1cf4b3fc-ae42-4671-8f41-92c221d7de0f.png)

**Comment by locriacyber** [comment]
I guess it thinks the interface is down because `state UNKNOWN` from `ip link`.

**Comment by patrick96** [comment]
> I guess it thinks the interface is down because state UNKNOWN from ip link.

Exactly, polybar (and your computer) don't know whether the interface is connected.
We actually have a setting to deal with this: `unknown-as-up`.

https://github.com/polybar/polybar/wiki/Module:-network
