### ISSUE TITLE
[Bug]: warn: Dropping unmatched character  (U+e745)

### ISSUE THREAD

**Issue by XDDudeGuy** [polybar/polybar#2819]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. install polybar 3.5.7
2. install UbuntuMono NF
3. set a workspace name as a symbol
4. set up a minimal config and launch.sh

### Minimal config

```dosini
[bar/base]
enable-ipc = true
font-0 = UbuntuMono:size=12:antialiasing=true;
...

[module/workspaces]
type = internal/xworkspaces
...
label-focused = %icon%
...
label-unfocused = %icon%
...
label-visible = %icon%
...
label-urgent = %icon%
```

### Polybar log

```text
notice: pulseaudio: using default sink alsa_output.pci-0000_28_00.4.analog-stereo
notice: Loaded font "UbuntuMono:size=12:antialiasing=true" (name=Ubuntu Mono, offset=0, file=/usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf)
warn: Dropping unmatched character  (U+f120) in '  '
warn: Dropping unmatched character  (U+e745) in '  '
```

### Expected behavior

My bar would display the correct symbols I set as my workspace names.

### Actual behavior

the bar drops the symbols and does not display them

### Window Manager and Version

dkwm 1.7

### Linux Distribution

Pop!_OS 22.04

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

### Additional Context / Screenshots

All "fixes" in closed issues have been attempted and been unsuccessful

**Comment by patrick96** [comment]
> notice: Loaded font "UbuntuMono:size=12:antialiasing=true" (name=Ubuntu Mono, offset=0, file=/usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf)

You're not loading Ubuntu Mono Nerd Font, you are loading the regular Ubuntu Mono (which doesn't have any of the nerd fonts characters).

Please read the [font debugging guide](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues).
