### ISSUE TITLE
[Bug]: No tray icon: nm-applet

### ISSUE THREAD

**Issue by og900aero** [polybar/polybar#2821]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Hello,

I cannot see tray icon: nm-applet, when I use Debian 11 minimal installation with Bspwm tiling windows manager. When I use same config on Arch Linux minimal installation with Bspwn, then works fine.
Sometimes show nm-applet, but most of the time it doesn't show.

Thanks for your help

### Minimal config

```dosini
; POLYBAR config file

[global/wm]
margin-top = 0
margin-bottom = 0

[settings]
screenchange-reload = false
pseudo-transparency = false

[bar/main]
wm-restack = bspwm
monitor = ${env:MONITOR:eDP1}
#monitor = ${env:MONITOR:HDMI1}
width = 100%
height = 30
fixed-center = true
line-size = 3
line-color = #f00f00
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2

font-0 = Oswald:size=12;4
font-1 = Oswald:size=12:weight=bold;4
font-2 = FontAwesome:size=12;4

modules-left = ewmh networkspeed networkspeed2 memory cpu
modules-center = date time
modules-right = xbacklight pavolume wlan eth battery

separator = "|"

tray-detached = false
tray-offset-x = 0
tray-offset-y = 0
tray-position = right
tray-padding = 0
tray-maxsize = 20
tray-scale = 1.0

cursor-click = pointer
cursor-scroll = ns-resize
```

### Polybar log

```text
polybar -l info:
* Environment var ${MONITOR} is undefined, using defined fallback value "eDP1"
* Loaded monitor eDP1 (1920x1080+0+0)
* Bar geometry: 1920x30+0+0; Borders: 0,0,0,0
* Starting application
* Starting module/ewmh
* Starting module/networkspeed
* Starting module/networkspeed2
* Starting module/memory
* Starting module/cpu
* module/memory: Invoking shell command: "free -m | awk '/^Mem/ {print $3}'"
* Starting module/date
* Starting module/time
* Starting module/xbacklight
* Starting module/pavolume
* Starting module/wlan
* module/pavolume: Invoking shell command: "~/.config/polybar/scripts/pavolume.sh --listen"
* Starting module/eth
* Starting module/battery
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=11)
* Configured DPI = 96x96
notice: Loaded font "Oswald:size=12" (name=Oswald, offset=4, file=/home/shyciii/.fonts/Oswald-Regular.ttf)
notice: Loaded font "Oswald:size=12:weight=bold" (name=Oswald, offset=4, file=/home/shyciii/.fonts/Oswald-Bold.ttf)
notice: Loaded font "FontAwesome:size=12" (name=FontAwesome, offset=4, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
* Bar window: 0x1e00002
* Successfully restacked bar window
* Activating tray manager
* Tray window: 0x1e00006
warn: Systray selection already managed (window=0x1c00006)
* Deactivating tray manager

Sometimtes have warn: Systray selection error message, somatime not.
```

### Expected behavior

When I click on wifi module, the nm-applet icon must show, but only empty space show.

### Actual behavior

When I run nm-applet, the icons doesnt show, only empty space show.

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Debian 11.5

### Polybar version

```text
polybar 3.5.5

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Debian package, build flags removed from output for reproducibility
You can refer to the build logs at:
https://buildd.debian.org/status/package.php?p=polybar
```

### Additional Context / Screenshots

![screenshot](https://user-images.githubusercontent.com/49487376/190876782-17e5b586-2f36-416f-bc47-d466f67450df.jpg)

**Comment by patrick96** [comment]
> warn: Systray selection already managed (window=0x1c00006)

This means there is another program already controlling the system tray and so polybar can't display it (there can ever be only one program displaying the tray). That's why you can't see nm-applet on the bar.

**Comment by og900aero** [comment]
I try xprop -id idnumber, but nothing show, so I dont know what other program used.

**Comment by og900aero** [comment]
Polybar is a problem. I see the warn message ith id:

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  21 (X_ListProperties)
  Resource id in failed request:  0x1400015
  Serial number of failed request:  12
  Current serial number in output stream:  12
[3]-  Done                    polybar main

This show, the polybar controlling this number

**Comment by patrick96** [comment]
Are you running multiple instances of polybar at the same time?

This would explain why it sometimes works and sometimes doesn't. The first instance of polybar will control the tray while the remaining ones will fail to get control of the tray and print that warning message.

**Comment by og900aero** [comment]
> Are you running multiple instances of polybar at the same time?
> 
> This would explain why it sometimes works and sometimes doesn't. The first instance of polybar will control the tray while the remaining ones will fail to get control of the tray and print that warning message.

No. I ran only once in bspwmrc file:
killall -q polybar;polybar main &

**Comment by og900aero** [comment]
I have a solution. I use specialized notify program (not XFCE4, KDE etc). The I run with config, now works perfect.
dunst -config ~/.config/dunst/dunstrc
