### ISSUE TITLE
[Feature]: Better fuzzy matching for icon sets (i3, bspwm)

### ISSUE THREAD

**Issue by ron0studios** [polybar/polybar#2829]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. run a polybar config with the i3 module
2. include ws-icon layout from the minimal config
3. conflict

### Minimal config

```dosini
[module/i3]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false

fuzzy-match = true

ws-icon-0 = "1;"
ws-icon-1 = "2;"
ws-icon-2 = "3;"
ws-icon-3 = "4;"
ws-icon-4 = "5;"
ws-icon-5 = "6;6"
ws-icon-6 = "7;"
ws-icon-7 = "8;"
ws-icon-8 = "9;"
ws-icon-9 = "10;💬"
ws-icon-default = 💬

format = <label-state> <label-mode>
```

### Polybar log

```text
no warnings or errors
```

### Expected behavior

the icon for workspace 10 should be 💬.

### Actual behavior

The icon for workspace 10 is the same as the first one, which is ws-icon-0

### Window Manager and Version

i3-gaps

### Linux Distribution

EndeavourOS

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/47331292/193413450-5116d7f0-d90a-499d-ab22-4925839074af.png)

This is the same bug as https://github.com/polybar/polybar/issues/2095, which appears to have already been resolved, but, as mentioned by others is still sometimes occurring. 

Thank you!

**Comment by patrick96** [comment]
Can you post the output of `i3-msg -t get_workspaces` when this happens?

Also, does this happen when you turn fuzzy matching off?

**Comment by ron0studios** [comment]
> Can you post the output of `i3-msg -t get_workspaces` when this happens?
> 
> Also, does this happen when you turn fuzzy matching off?

I get this
```
[{"id":94240379053248,"num":1,"name":"1:","visible":true,"focused":true,"rect":{"x":0,"y":0,"width":1920,"height":1060},"output":"eDP1","urgent":false},{"id":94240379066080,"num":2,"name":"2:","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1060},"output":"eDP1","urgent":false},{"id":94240379072496,"num":3,"name":"3:","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1060},"output":"eDP1","urgent":false},{"id":94240379036512,"num":4,"name":"4:","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1060},"output":"eDP1","urgent":false},{"id":94240379260288,"num":9,"name":"9:","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1060},"output":"eDP1","urgent":false},{"id":94240379078912,"num":10,"name":"10:💬","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1060},"output":"eDP1","urgent":false}]
```

which I've just reformatted as this
```
[
    { "id": 94240379053248, "num": 1, "name": "1:", "visible": true, "focused": true, "rect": { "x": 0, "y": 0, "width": 1920, "height": 1060 }, "output": "eDP1", "urgent": false },
    { "id": 94240379066080, "num": 2, "name": "2:", "visible": false, "focused": false, "rect": { "x": 0, "y": 0, "width": 1920, "height": 1060 }, "output": "eDP1", "urgent": false },
    { "id": 94240379072496, "num": 3, "name": "3:", "visible": false, "focused": false, "rect": { "x": 0, "y": 0, "width": 1920, "height": 1060 }, "output": "eDP1", "urgent": false },
    { "id": 94240379036512, "num": 4, "name": "4:", "visible": false, "focused": false, "rect": { "x": 0, "y": 0, "width": 1920, "height": 1060 }, "output": "eDP1", "urgent": false },
    { "id": 94240379260288, "num": 9, "name": "9:", "visible": false, "focused": false, "rect": { "x": 0, "y": 0, "width": 1920, "height": 1060 }, "output": "eDP1", "urgent": false },
    { "id": 94240379078912, "num": 10, "name": "10:💬", "visible": false, "focused": false, "rect": { "x": 0, "y": 0, "width": 1920, "height": 1060 }, "output": "eDP1", "urgent": false }
]
```

**Comment by patrick96** [comment]
So what happens is, `ws-icon-*` tries to match the name of the workspace. When the module tries to find the right icon for the workspace named `10:💬`, none of the mappings match exactly so it tries to find a substring match. `ws-icon-0` matches and is thus used for the workspace.

The fuzzy matching mechanism could probably be improved to select a "best" match, right now it just takes the first match.
The length of the match would probably be a good measure to determine the best match.

I'll mark this as a feature request since this is technically not a bug (fuzzy matching works as documented). PRs are welcome.

To anyone wanting to work on this, the logic for fuzzy matching is entirely limited to `src/drawtypes/iconset.cpp` and there is a small test suite at `unit_tests/drawtypes/iconset.cpp`.

**Comment by ron0studios** [comment]
I'll try and contribute to this!

**Comment by ron0studios** [comment]
Ok I just PRd my implementation! [#2831](https://github.com/polybar/polybar/pull/2831)
