### ISSUE TITLE
[Bug]: config default and discovery

### ISSUE THREAD

**Issue by jimenezj8** [polybar/polybar#2869]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Pop!_OS 22.04, GNOME 42.3.1
1. `sudo apt-get install polybar`
2. `polybar`
3. Copy `config` from GitHub repo into `${XDG_CONFIG_HOME}/.config/polybar/config.ini`
4. `polybar`

### Minimal config

```dosini
Config supposedly included with package.
```

### Polybar log

```text
No log possible
```

### Expected behavior

According to the READMEs and Wiki, I would expect `polybar` to start like [this](https://github.com/polybar/polybar/blob/master/doc/_static/default.png), using a config file packaged with the install and auto-discovered through parsing the PATH indicated by [this excerpt](https://github.com/polybar/polybar/wiki#running-the-app).

### Actual behavior

Instead, `polybar` consistently fails to find any config until specified explicitly using the `-c` flag.

### Window Manager and Version

Mutter

### Linux Distribution

Pop!_OS 22.04 LTS

### Polybar version

```text
$ polybar -vvv                                                          11:28AM
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Debian package, build flags removed from output for reproducibility
You can refer to the build logs at:
https://buildd.debian.org/status/package.php?p=polybar
```

### Additional Context / Screenshots

Seems to be two distinct issues:
1. Default config is not provided in the described locations (seemingly an issue with the build provided by the Ubuntu repo maintainers)
2. Polybar fails to find the config files even after manually placing in one of the specified locations

**Comment by patrick96** [comment]
The behavior you are expecting only applies to the latest version of polybar (3.6), the version you are using (3.5) looks for the config file at `~/.config/polybar/config` and doesn't have a default config.
