### ISSUE TITLE
[Bug]: Custom script time interval behaviour depends on the typed command ?

### ISSUE THREAD

**Issue by seVenVo1d** [polybar/polybar#2880]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

No steps required

### Minimal config

```dosini
[module/kernel]
type = custom/script
exec = uname -r | cut -d'-' -f1
tail = false
interval = 1800

format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = #fffac8
format-underline = #fffac8

format-background = ${colors.background}
format-foreground = ${colors.foreground}

;################################################################################
[module/dnf_update]
type = custom/script
exec = dnf check-update --refresh --q --downloadonly | grep -c .
tail = false
interval = 1800

format-prefix = " "
format-prefix-font = 3
format-prefix-foreground = #e6194B
format-underline = #e6194B

format-background = ${colors.background}
format-foreground = ${colors.foreground}
```

### Expected behavior

I would expect that both modules should have the same type of behaviour for the `interval` command. Since, they have the same structure. Only the commands and the fonts differ.

### Actual behavior

I am not exactly sure about how `interval` should behave but there is something strange going on that I cannot understand. The `kernel` module is always displayed in the polybar which is totally fine by me. 

However, the `dnf-upgrade` module is displayed for 30 min then it disappears and after 30 min it re-appears again. This is odd since both of the modules have the same structure and interval. 

I believe this should not happen...

### Window Manager and Version

i3 - v4.21

### Linux Distribution

Fedora 37

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/g++
```

**Comment by patrick96** [comment]
Could it be that the `dnf` command sometimes does not produce any output (or at least produces an empty line as the first line in its output)? That would explain why the module disappears.

**Comment by seVenVo1d** [comment]
It seems that if there is an update the module does not disappear (I'll test it again but it seems that way). *However*, if the update is 0, which looks like this in my setup,

![screenshot_1](https://user-images.githubusercontent.com/45866787/208417595-ccb512dc-d70e-4aa9-98ae-caf5dcf5007b.png)

the module disappears and re-appears in every interval. 

![screenshot_2](https://user-images.githubusercontent.com/45866787/208417902-665443a7-f437-42ed-af32-29032999833b.png)

Is this a bug or something expected ? 

I think it would be a nice feature that the module does not disappear even if the upgrade number is 0.

**Comment by patrick96** [comment]
I was looking at the wrong version of the code, so I couldn't see why this is happening :facepalm:

This is the same issue as #2636. It is triggered because the `exec` command produces the exact same output **and** exits with a non-zero exit code. This will be fixed in the next release.

For now use `exec = dnf check-update --refresh --q --downloadonly | grep -c . || true` to make sure the command never has a non-zero exit code.

**Comment by seVenVo1d** [comment]
Thanks a lot. Sorry for the duplicate issue...
