### ISSUE TITLE
[Bug]: Dropping characters from loaded fonts

### ISSUE THREAD

**Issue by ikbenlike** [polybar/polybar#2902]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Install Noto Sans and Droid Sans Mono
2. Refresh font cache
3. Load the bar with `polybar example` and the provided minimal config

### Minimal config

```dosini
[bar/example]
; font-N = <fontconfig pattern>;<vertical offset>
font-0 = "Noto Sans:style=Regular:size=12"
font-1 = "Droid Sans Mono:style=Regular:size=12;2"
modules-left = cpu
bottom = false
monitor = HDMI-0

[module/cpu]
type = internal/cpu
interval = 0.5
format = <label> <ramp-coreload>
label = CPU %percentage%%
label-warn = CPU %percentage%%
ramp-coreload-spacing = 1
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █
```

### Polybar log

```text
notice: Parsing config file: /home/thewatcher/.config/polybar/config.ini
- config_parser: Parsing /home/thewatcher/.config/polybar/config.ini
* Loaded monitor HDMI-0 (2560x1080+1920+0)
* Configured DPI = 96x96
* Bar geometry: 2560x24+1920+0; Borders: 0,0,0,0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Setup user-defined modules
notice: Loading module 'cpu' of type 'internal/cpu'
notice: Loaded 1 modules
* Starting application
- controller: Main thread id = 1
* Starting module/cpu
* Entering event loop (thread-id=1)
- bar: Create renderer
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- module/cpu: Thread id = 2
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- renderer: Load fonts
notice: Loaded font "Noto Sans:style=Regular:size=12" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
notice: Loaded font "Droid Sans Mono:style=Regular:size=12" (name=Droid Sans Mono, offset=2, file=/usr/share/fonts/droid/DroidSansMono.ttf)
* Bar window: 0x0c00001
- bar: Reconfigure window
- bar: Set window WM_NAME
- bar: Set window _NET_WM_WINDOW_TYPE
- bar: Set window _NET_WM_STATE
- bar: Set window _NET_WM_DESKTOP
- bar: Set window _NET_WM_PID
- bar: Map window
- bar: Draw empty bar
- bar: Setup tray manager
* Disabling tray manager (reason: missing `tray-position`)
* module/cpu: Rebuilding cache
- bar: Force update
* Redrawing bar window
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
warn: Dropping unmatched character ▁ (U+2581) in 'CPU 0% ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁ ▁'
- renderer: flush(1 geom=106x24+0+0, falloff=0)
```

### Expected behavior

It is expected for the bar to display the CPU usage ramps, as the example description found [in the wiki](https://github.com/polybar/polybar/wiki/Module:-cpu) is described to do. 

### Actual behavior

Every time the bar updates the CPU usage ramps, it displays a warning in the terminal that the specified character is being dropped. This is despite loading both fonts specified in the config successfully. The characters render perfectly fine in my terminal and `font-1` in the example config is the same as my terminal font. Refreshing `fc-cache` does not change this behaviour. Using `gucharmap` I found the dropped characters do exist in both the font specified as `font-0` as well as in `font-1`. Swapping `font-0` and `font-1` as well as using only one of the specified fonts does not alter this behaviour in any way.

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Arch Linux

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug/polybar -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by patrick96** [comment]
> Using gucharmap I found the dropped characters do exist in both the font specified as font-0 as well as in font-1

Are you sure you set `View > Show only glyphs from this font` in `gucharmap` because for me (also arch), that character is not present in either of those fonts.

`Noto Sans Mono` does seem to have that character though.

**Comment by ikbenlike** [comment]
> > Using gucharmap I found the dropped characters do exist in both the font specified as font-0 as well as in font-1
> 
> Are you sure you set `View > Show only glyphs from this font` in `gucharmap` because for me (also arch), that character is not present in either of those fonts.
> 
> `Noto Sans Mono` does seem to have that character though.

I just rechecked again and you seem to be right. I must have forgotten to re-check that option after `gucharmap` froze on me, but regardless, thanks for your help.
