### ISSUE TITLE
[Bug]: 'Send to workspace' just send apps to second monitor

### ISSUE THREAD

**Issue by iiSpidey** [polybar/polybar#2904]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Whenever I use the send to given desktop shortcut, it sends the app to my second monitor, not to the workspace I chose.
I have workspaces 1-5 on my primary one and 6-10 on my secondary one, and when I do super + shift + 2, it sends it to the second workspace but from my secondary monitor (which actually is 7).

### Minimal config

```dosini
#Dual Monitor Setup
if [[ $(xrandr -q | grep 'DisplayPort-1 connected') ]]; then
  xrandr --output DisplayPort-0 --primary --mode 2560x1440 --rotate normal --rate 170 --output DisplayPort-1 --mode 1920x1080 --rotate normal --rate 144 --left-of DisplayPort-0
fi

#Workspaces
bspc monitor DisplayPort-0 -d I II III IV V &
bspc monitor DisplayPort-1 -d VI VII VIII IX X &

[bar/top]
monitor = DisplayPort-0

[bar/external]
monitor = DisplayPort-1

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = false
enable-click = true
enable-scroll = true
reverse-scroll = true
fuzzy-match = true

# Send to workspace
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'
```

### Expected behavior

I'd like it to send it to the workspace number I select.

### Actual behavior

Sends it to secondary monitor workspaces.

### Window Manager and Version

bspwm

### Linux Distribution

Arch

### Polybar version

```text
polybar 3.6.3
Build type: Release
```

**Comment by patrick96** [comment]
This has nothing to do with polybar. Polybar just displays the list of workspaces, the send to workspace functionality comes from bspwm
