### ISSUE TITLE
[Bug]: Alsa module failed to start for the first time

### ISSUE THREAD

**Issue by QingyaoLin** [polybar/polybar#2915]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

When I enter bspwm from lightdm, the alsa module doesn't show up.

### Minimal config

```dosini
[bar/mybar]
module-light = alsa
;module-right = alsa
;module-center = alsa

[module/alsa]
type = internal/alsa

; Interval for volume increase/decrease (in percent points)
interval = 1

label-volume = %percentage%%
label-muted = 婢 Muted

format-volume = <ramp-volume> <label-volume>
format-volume-foreground = ${colors.yellow}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
```

### Polybar log

```text
polybar|notice:  Parsing config file: /home/lqy/.config/polybar/config.ini
polybar|info:  Created legacy ipc fifo at '/tmp/polybar_mqueue.1083'
polybar|info:  Opening ipc socket at '/run/user/1000/polybar/ipc.1083.sock'
polybar|notice:  Listening for IPC messages (PID: 1083)
polybar|info:  Loaded monitor eDP-1 (1920x1080+0+0)
polybar|info:  Configured DPI = 96x96.2526
polybar|info:  Bar geometry: 1920x32+0+0; Borders: 0,0,0,0
polybar|notice:  Loading module 'alsa' of type 'internal/alsa'
polybar|error: Disabling module "alsa" (reason: Cannot find simple element)
polybar|error: Uncaught exception, shutting down: No modules created
polybar|info:  Waiting for spawned processes to end
polybar|info:  Reached end of application...
```

### Expected behavior

When I enter bspwm from lightdm, the alsa module shows normally.

### Actual behavior

When I enter bspwm from lightdm, the alsa module doesn't show up.

### Window Manager and Version

bspwm-0.9.10

### Linux Distribution

nixos-22.11

### Polybar version

```text
polybar 3.6.3

Features: +alsa -curl -i3 -mpd +network(libnl) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gcc-wrapper-11.3.0/bin/g++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags:  -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by QingyaoLin** [comment]
When I restart polybar, the alsa module is displayed normally

**Comment by patrick96** [comment]
How are you starting polybar on login?

Most likely, alsa is not setup fully once polybar starts and thus the alsa module can't find the alsa elements it needs. This is weird though because I assumed the sound system would already be running when lightdm starts.

Are you using pulseaudio on your system? If so, I would really recommend compiling polybar with pulseaudio support and use the module for that.

**Comment by QingyaoLin** [comment]
> How are you starting polybar on login?

I started polybar with the launch.sh script.

> Are you using pulseaudio on your system? If so, I would really recommend compiling polybar with pulseaudio support and use the module for that.

I use alsa and pipewire.

**Comment by patrick96** [comment]
Alright, I guess in that case there is probably no way around delaying the start of your bar by a few seconds with `sleep` to make sure alsa has started up.

**Comment by QingyaoLin** [comment]
> 好吧，我想在这种情况下，可能没有办法将酒吧的开始延迟几秒钟以确保 alsa 已启动。`sleep`

That's a good idea
