### ISSUE TITLE
[Bug]: Polybar border disappears when compositor is enabled

### ISSUE THREAD

**Issue by andreykaere** [polybar/polybar#2922]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Run `polybar bar`. You will see the border, as expected. However, when enabling a compositor (tested with `compton` and `picom`), this border disappears.

### Minimal config

```dosini
[colors]
background = #252737
background-alt = #383b54
foreground = #dfdfdf
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40


[bar/bar]
width = 100%
height = 27
radius = 6.0

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 4
border-color = #00000000

font-0 = fixed:pixelsize=10;2

override-redirect = true
modules-left = text


[module/text]
type = custom/text
content = "foo"
```

### Expected behavior

Border not changing when running compositor.

### Actual behavior

Border vanishes as soon as compositor is run.

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Ubuntu 22.04.1

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags:
```

**Comment by patrick96** [comment]
This is expected. The border you defined is completely transparent, but if you don't have any type of transparency support enabled (compositor or pseudo-transparency), it cannot be rendered as transparent and is instead rendered as black.

**Comment by andreykaere** [comment]
Why is my border transparent if I specified color to be black?

**Comment by patrick96** [comment]
The color is `#00000000`, which is black, but fully transparent (the first two hex digits are the alpha channel). Opaque black would be `#ff000000` or `#000000`.

**Comment by andreykaere** [comment]
Thank you, I didn't notice it!
