### ISSUE TITLE
Better output formatting

### ISSUE THREAD

**Issue by d125q** [polybar/polybar#294]
Maybe it is just me, but I find the output formatting of `poylbar` to be very lacking.  For example, is there a way for the keyboard module to display `layout [modifier_1, modifier_2, ..., modifier_n]`?  Also, is there a way to separate modules with ` | ` or something similar?

I am not sure why this approach was taken rather than, for example, the one used by [`xmobar`](https://github.com/jaor/xmobar).  For example, my `xmobar` looks like this:
![d125q's xmobar](https://cloud.githubusercontent.com/assets/7765538/21583732/d6af6bae-d08d-11e6-8e9a-9ebffea6b5fe.png)

And I would like to come up with a similar configuration for `polybar`, too.

**Comment by jaagr** [comment]
Can't see how it could be a problem to format the bar like the one in your image. It looks very plain to me. The wiki contains all information you need. Not really following your idea on the keyboard output.

As documented in the wiki, you would set the separator using:

~~~ dosini
[bar/name]
...
separator = |
...
~~~

How you find xmoand's formatting superior is beyond me though.

**Comment by d125q** [comment]
Thank you.

The problem is that the separator is global.  I don't want that.

> Not really following your idea on the keyboard output.

I want the LED indicators separated by commas, not by spaces (i.e. `Caps Lock, Num Lock` instead of `Caps Lock  Num Lock`).  I have not found a way to do this and assume that it is not possible.

**Comment by jaagr** [comment]
No, that is not possible at the moment. We could maybe implement a local separator for format tags that gets replaced with multiple items. There are other modules (for example the bspwm, xworkspaces and i3 modules) that would benefit from this. If you have any ideas on how it would be specified in the configuration, I'd appreciate the input.

**Comment by patrick96** [comment]
Closing in favor of #452
