### ISSUE TITLE
[Bug]: Polybar did not detect the configuration of spelling errors, and ignore the error

### ISSUE THREAD

**Issue by awarewen** [polybar/polybar#2943]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

polybar -c ./polybar_test/polybar_2.ini mybar& > /dev/null

### Minimal config

```dosini
[bar/mybar]
...
modules-left = sep sep1
modules-center = sep sep2
;; Here were ignored
module-right = sep sep3
...
```

### Polybar log

```text
❯ polybar -c ./polybar_test/polybar_2.ini mybar& > /dev/null
[1] 2929365
notice: Parsing config file: ./polybar_test/polybar_2.ini
notice: Loading module 'sep' of type 'custom/text'
notice: Loading module 'sep1' of type 'custom/text'
notice: Loading module 'sep' of type 'custom/text'
notice: Loading module 'sep2' of type 'custom/text'
notice: Loaded 4 modules
notice: Loaded font "iosevka:pixelsize=12" (name=Iosevka, offset=0, file=/home/awarewen/.local/share/fonts/iosevka_nerd_font.ttf)
```

### Expected behavior

Grammar parser should detect the spelling mistakes here

### Actual behavior

The spelling errors are skipped, although configured properly run but to look for in the complex configuration such errors will be a waste of time.

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Arch Linux 

### Polybar version

```text
❯ polybar -v
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

### Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/53365857/231829778-c56acf66-6b41-48ae-b669-937443750eb5.png)

**Comment by patrick96** [comment]
There is really no good way for the parser to know which config values are valid and which are not.

I thought about maybe tracking which config values are accessed and producing a warning for unused settings. But even that may not be 100% accurate since some settings are valid, but only used under certain circumstances.
