### ISSUE TITLE
[Bug]: Polybar not supporting Nerdfont V 3.0

### ISSUE THREAD

**Issue by greeid** [polybar/polybar#2962]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Try to use , 󰮯, 󰊠 as xworspace fonts

### Minimal config

```dosini
[module/xworkspaces]
type = internal/xworkspaces

label-active = 󰮯 
label-active-foreground = ${colors.battery}
; label-active-background = ${colors.battery}
label-active-padding = 1
label-active-font = 1

label-occupied = 󰊠
label-occupied-padding = 1
label-occupied-foreground = ${colors.volume}
label-occupied-font = 1

label-urgent = 

label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-urgent-font = 2

label-empty = 
```

### Polybar log

```text
loaded modules and fonts successfully 
...
warn: Dropping unmatched character 󰊠 (U+f02a0) in '󰊠'
warn: Dropping unmatched character 󰮯 (U+f0baf) in '󰮯'
warn: Dropping unmatched character 󰊠 (U+f02a0) in '󰊠'
warn: Dropping unmatched character 󰊠 (U+f02a0) in '󰊠'
warn: Dropping unmatched character 󰊠 (U+f02a0) in '󰊠'
.....
```

### Expected behavior

No warning after modules are loaded 

### Actual behavior

Polybar not rendering some fonts properly

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Arch Linux 6.3.1-zen2-1-zen

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug/polybar -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

https://github.com/polybar/polybar/assets/58597122/a4514996-6151-44e9-86af-bf11176eda3c

**Comment by patrick96** [comment]
> loaded modules and fonts successfully 

Please also show that part of the log. I am pretty sure polybar did not load the nerd fonts, otherwise you wouldn't be having this issue. Please also read the [font debugging guide](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues).

**Comment by Speculative** [comment]
For my configuration, this was due to a [breaking change in Nerd Font 3.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0). Material Design Icon codepoints were changed, so you need to go on the [Nerd Font Cheatsheet](https://www.nerdfonts.com/cheat-sheet) and find the new codepoints. I can confirm that after I switched to the new code points, the correct glyphs render and I don't see any warnings of unmatched characters.
