### ISSUE TITLE
[Bug]: Polybar overlaps fullscreen windows after bspwm restart

### ISSUE THREAD

**Issue by Qurcaivel** [polybar/polybar#2972]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. `bspc wm -r`
2. run `polybar -q main -c /path/to/mininal/cfg` from bspwmrc

### Minimal config

```dosini
[bar/main]
wm-restack = bspwm
bottom = false
fixed-center = true
enable-ipc = false
background = ${color.BACKGROUND}
foreground = ${color.FOREGROUND}
border-color = ${color.FOREGROUND}
radius = 12
line-size = 0
border-size = 0

width = 1908
height = 35
offset-x = 6
offset-y = 6

padding = 12px
module-margin = 14px

font-0 = "JetBrainsMono Nerd Font:size=12;3"
font-1 = "Iosevka Nerd Font:size=13;3"
font-2 = "google\-mdi:size=13;3"
font-3 = "Iosevka:style=bold:"size=13;3"

#modules-left = bspwm
modules-center = xwindow

[module/bspwm]
type = internal/bspwm
# ...

[module/xwindow]
type = internal/xwindow
# ...
```

### Polybar log

```text
notice: Parsing config file: /home/inqognitoo/.config/bspwm/polybar/config.ini
error: /home/inqognitoo/.config/bspwm/polybar/config.ini:27: Value '"google\-mdi:size=13;3"' of key 'font-2' contains one or more unescaped backslashes, please prepend them with the backslash escape character.
notice: Loading module 'bspwm' of type 'internal/bspwm'
notice: Loading module 'xwindow' of type 'internal/xwindow'
notice: Loading module 'tray' of type 'internal/tray'
notice: Loading module 'network' of type 'internal/network'
notice: Loading module 'battery' of type 'internal/battery'
notice: Loading module 'xkeyboard' of type 'internal/xkeyboard'
notice: Loading module 'date' of type 'internal/date'
notice: Loaded 7 modules
notice: Loaded font "JetBrainsMono Nerd Font:size=12" (name=JetBrainsMono Nerd Font, offset=3, file=/usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf)
notice: Loaded font "Iosevka Nerd Font:size=13" (name=Iosevka, offset=3, file=/usr/share/fonts/archcraft/nerd-fonts/Iosevka Nerd Font Complete.ttf)
notice: Loaded font "google\-mdi:size=13" (name=google-mdi, offset=3, file=/usr/share/fonts/archcraft/icon-fonts/google-mdi.ttf)
notice: Loaded font "Iosevka:style=bold:"size=13" (name=Iosevka, offset=3, file=/usr/share/fonts/archcraft/normal-fonts/Iosevka/iosevka-bold.ttf)
```

### Expected behavior

Polybar works fine after bspwm reload.

### Actual behavior

Polybar overlaps fullscreen windows after bspwm reload.

### Window Manager and Version

bspwm 0.9.10-3

### Linux Distribution

Arch Linux (6.3.5-arch1-1)

### Polybar version

```text
polybar 3.6.3-206-g2cd0809a

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
```

### Additional Context / Screenshots

Interesting observation: this problem occurs with all internal modules like `internal/xwindow` but doesn't occurs when only `internal/bspwm` module is active.

The problem arose when switching from `polybar` to `polybar-git` package.

Note: the only one error in logs belongs to font's 'issue', but but is not influencing at all sutuation.

![image](https://github.com/polybar/polybar/assets/52575966/bff8878c-c05a-4e4a-b726-98023f7cc7b8)

**Comment by patrick96** [comment]
Could you run polybar with trace logging (`-l trace`) and post the output of that? This may be something I broke in #2961

**Comment by Qurcaivel** [comment]
```

**Comment by patrick96** [comment]
Sorry, forgot about this. Can you also run `xwininfo -root -tree` and post the output. This will show where polybar positioned itself in the window stack.
Note that this will show us the titles of all open windows.

**Comment by patrick96** [comment]
Well crap. bspwm puts the window we use to anchor polybar above other user windows and so polybar is above those windows again.

**Comment by Qurcaivel** [comment]
@patrick96, are there any changes?

**Comment by KrulYuno** [comment]
I have noticed this since 2021 of August with `polybar` (not polybar-git`. Just shrugged it off since I didn't bother looking for a fix or wondering if others have this issue.
The issue itself is from bspwm rather than polybar?

**Comment by Qurcaivel** [comment]
> Just add those two lines at the end of your polybar launch script. `sleep 0.2` (Give polybar a chance to load its config) `xdo lower -N "Polybar" ` This problem is so annoying, I've tried many things and I think this is the best solution.

this sounds good, but I just now noticed that breaks input interaction like tray clicks etc.

**Comment by KrulYuno** [comment]
> this sounds good, but I just now noticed that breaks input interaction like tray clicks etc.
I tried this just yesterday, it works perfectly and no issues with the trays so far. I expected I'd get that issue since you had that one.

**Comment by JAMmIKA1** [comment]
> > Just add those two lines at the end of your polybar launch script. `sleep 0.2` (Give polybar a chance to load its config) `xdo lower -N "Polybar" ` This problem is so annoying, I've tried many things and I think this is the best solution.
> 
> this sounds good, but I just now noticed that breaks input interaction like tray clicks etc.

There are no issues with mine; I think it's because I'm using the [tray as a module](https://github.com/polybar/polybar/issues/2689).

**Comment by KrulYuno** [comment]
> 

There is issue on my end, not the same as @Qurcaivel, but the tray icons remains on top just like the previous issue. Polybar itself is fixed, except the tray icons and a small bar portion of it. It's clickable though.

An image below for reference:
![image](https://github.com/polybar/polybar/assets/19298806/1f8c22fd-1e42-46e2-b56e-b28a3417f0a8)
