### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KlapenHz** [polybar/polybar#2977]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Moving second screen above primary screen in my screen settings.

### Minimal config

```dosini
This is example config from  /usr/share/doc/polybar/config  with changed option for monitor and fonts.
[bar/top]
;monitor = ${env:MONITOR:HDMI-1}
monitor = XWAYLAND1

font-0 = FiraCode Nerd Font:size10;1
;font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1
```

### Polybar log

```text
Only information about logs and systray (FC_DEBUG=1)
warn: Systray selection already managed (window=0x08005b9)
```

### Expected behavior

Should run without problems on internal screen (laptop)

### Actual behavior

After starting it's changing working area on my second screen

### Window Manager and Version

Gnome

### Linux Distribution

Ubuntu 22.04

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

### Additional Context / Screenshots

I have dual screen, one is primary (laptop), second one is ultrawide. Changing resolution don't change anything. Polybar is set to appears only on primary screen.
When I have:
![image](https://github.com/polybar/polybar/assets/110558378/9e105e96-8e48-4c1b-889f-b71056034432)
it works fine. But when I chenge position of my screens to this:
![image](https://github.com/polybar/polybar/assets/110558378/ce6d56b8-25f1-404f-b9f2-d6e50402f186)
or any different position, where bigger screen is above the primary screen it change working area on the bigger one:
![image](https://github.com/polybar/polybar/assets/110558378/fc84aa53-a8ce-40e6-9ad0-26012305c284)

**Comment by patrick96** [comment]
I think you are suffering from #2769 (also see [this reddit post](https://www.reddit.com/r/Polybar/comments/vz9271/comment/igdlltu/) where this was first reported).

There will be an option in the next release to turn off these struts that cause this. For now you can try playing around with the `override-redirect` setting in the bar section.

**Comment by KlapenHz** [comment]
Ok, Thank you for this info :)
