### ISSUE TITLE
[Bug]: Systray module icon always white, unable to change the color 

### ISSUE THREAD

**Issue by rainer2208** [polybar/polybar#2992]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I am on Arch Linux and use polybar for quite a while. Today I am using the bar with xmonad, but I have used it with other WMs and always had the same issue. 

The one things I could never clarify is how to configure the color of the systray icons. 

On my bar, they are always white. 

I can change the background color of the tray, but the color of the icons is always white, and with a white bar, the icons become indistinguishable. 

How can I change the foreground color of the systray icons?

![polybarerr](https://github.com/polybar/polybar/assets/23400899/4a689ae7-8ada-486c-885b-7e06f136b868)

### Minimal config

```dosini
[global/wm]

margin-top = 5
margin-bottom = 5
include-file = ~/.config/polybar/colors
include-file = ~/.config/polybar/modules
include-file = ~/.config/polybar/system

[settings]
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Define fallback values used by all module formats
format-foreground = #FF0000
format-background = #00FF00

[bar/mainbar-xmonad]
;monitor = ${env:MONITOR}
;monitor-fallback = HDMI1
monitor-strict = false
override-redirect = false
width = 99.5%
height = 30
offset-x = 5
offset-y = 5
radius = 0.0
fixed-center = true
bottom = false
separator = |

background = ${colors.white}
foreground = ${colors.black}

line-size = 2
line-color = #f00

border-size = 4
;border-left-size = 25
;border-right-size = 25
;border-top-size = 0
;border-bottom-size = 25
border-color = ${colors.white}

padding-left = 5
padding-right = 1

module-margin-left = 3
module-margin-right = 3

enable-ipc = true

font-0 = "Noto Sans:size=10;0"
font-1 = "FontAwesome:size=13;0"
font-2 = "Noto Sans:size=10;0"
font-3 = "Noto Sans Mono:size=10;0"
font-4 = "FontAwesome5Brands:size=13;0"

modules-left = xmonad
modules-center = ewmh
modules-right = filesystem memory pacman-updates pulseaudio date battery

tray-detached = false
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 2
tray-maxsize = 20
tray-scale = 1.0
tray-position = right
tray-background = #13ff00ff
tray-foreground = ${colors.black}
```

### Polybar log

```text
no error output when running polybar
```

### Expected behavior

show systray icons in black, or any other color than white 

### Actual behavior

systray icons never change color, they are always white

### Window Manager and Version

xmonad

### Linux Distribution

Arch Linux

### Polybar version

```text
polybar 3.6.3
```

**Comment by patrick96** [comment]
The color of the icons themselves can not really be changed from polybar. The icons are drawn by their respective applications, not polybar. `tray-foreground` can give some hint about the icon color, but it is only supported by some applications and doesn't have to be honored.

I never played around with this myself but what should affect the look of icons is your system's icon theme.

**Comment by rainer2208** [comment]
That actually did the trick, many thanks . 

I have started  to locate the icons in the icon theme and paint them with gimp. First one is Variety .... looking cool now.

![systray](https://github.com/polybar/polybar/assets/23400899/06dec4f4-b615-4c95-9813-d98b2db818a4)
