### ISSUE TITLE
[Bug]: Icon rendered half when background is colored

### ISSUE THREAD

**Issue by rew1nter** [polybar/polybar#3012]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Have a binary/script print this ```%{F#606060}   %{F- }Haze```
2. Create a module and call it in bar
```ini
[module/weather]
type = custom/script


label = %output% 
; label-background = #302A36

exec = fakeweather
interval = 960

```

This will fully print the emoji like here:
![image](https://github.com/polybar/polybar/assets/64508791/d770a0e7-d746-42fa-ac41-6570121ce78d)

but if you uncomment the `label-background` line and load this again, the emoji will not be fully rendered:
![image](https://github.com/polybar/polybar/assets/64508791/89964b36-41f9-4d8e-accd-28a4279a9e3a)

### Minimal config

```dosini
[module/weather]
type = custom/script


label = %output% 
; label-background = #302A36

exec = fakeweather
interval = 960
```

### Expected behavior

Show full emoji as usual when background is colored 

### Actual behavior

Emoji is not fully shown when background is colored

### Window Manager and Version

Plasma 5.27.8

### Linux Distribution

6.5.4-arch2-1 Endeavour os

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug/polybar -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by patrick96** [comment]
See #991

**Comment by rew1nter** [comment]
I think I've most of the workarounds already in place. I'm using the official jetbrains monospaced font, which is not a nerd font, as the original post suggests and I'm also using the icon fonts separately like this:

```ini
# Text
font-0 = "JetBrains Mono:style=Bold:pixelsize=9;3"
font-1 = "Font Awesome 6 Free Solid:size=10;3"
font-2 = "Material Design Icons Desktop:size=11;3"
font-3 = "Material Design Icons Desktop:size=15;5"
# Glyphs
font-4 = "MesloLGS NF:style=Regular:size=15;4"
```
yet this issue persists when the background is colored

**Comment by rew1nter** [comment]
[this](https://github.com/gh0stzk/dotfiles/blob/master/config/bspwm/rices/emilia/config.ini) is the full config I'm using

**Comment by patrick96** [comment]
All nerd fonts except their monospaced variants have this issue, it doesn't matter if you use a different font for text, it matters which fonts the icons come from. I would recommend using `Symbols Nerd Font Mono` as your icon font

**Comment by rew1nter** [comment]
> All nerd fonts except their monospaced variants have this issue

I don't understand. The jetbrains mono font I'm using is not a nerd font. It's the official font
