### ISSUE TITLE
[Bug]: keeps dropping a font for no reason

### ISSUE THREAD

**Issue by RealMrCactus** [polybar/polybar#3013]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Use jetbrainsmononerd
try to use the arch glyph as a text module
polybar drops it

### Minimal config

```dosini
[bar/bar]
font-0 = JetBrainsMonoNerd:style=bold
modules-left = arch

[module/arch]
type = custom/text
content-padding = 2
content = "a"
```

### Polybar log

```text
notice: Parsing config file: /home/rmc/.config/polybar/config.ini
notice: Listening for IPC messages (PID: 2479)
warn: No monitor specified, using "HDMI-0"
notice: Loading module 'arch' of type 'custom/text'
notice: Loading module 'xworkspaces' of type 'internal/xworkspaces'
notice: Loading module 'xwindow' of type 'internal/xwindow'
notice: Loading module 'pulseaudio' of type 'internal/pulseaudio'
notice: pulseaudio: using default sink alsa_output.usb-Razer_Razer_Kraken_V3_HyperSense_000000000001-00.analog-stereo
notice: Loading module 'memory' of type 'internal/memory'
notice: Loading module 'cpu' of type 'internal/cpu'
notice: Loading module 'wlan' of type 'internal/network'
notice: module/wlan: Discovered wireless interface wlan0
notice: Loading module 'date' of type 'internal/date'
notice: Loaded 8 modules
notice: Loaded font "JetBrainsMonoNerd:style=bold" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Bold.ttf)
notice: Loaded font "JetBrainsMonoNerd:size=14" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
warn: Dropping unmatched character  (U+f303) in '  a  '
```

### Expected behavior

the arch glyph displays fine

### Actual behavior

glyph is dropped

### Window Manager and Version

i3 version 4.22 (2023-01-02)

### Linux Distribution

Arch Linux 023.09.01

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

### Additional Context / Screenshots

Terminal uses same font
![image](https://github.com/polybar/polybar/assets/36554881/59287443-c23e-4e74-9dae-84200a4cdc45)

**Comment by patrick96** [comment]
> notice: Loaded font "JetBrainsMonoNerd:style=bold" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Bold.ttf)
notice: Loaded font "JetBrainsMonoNerd:size=14" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)

Polybar isn't actually loading the nerd font (look at the actual font loaded in brackets. Please read the [font debugging guide](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues)

**Comment by RealMrCactus** [comment]
> > notice: Loaded font "JetBrainsMonoNerd:style=bold" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Bold.ttf)
> > notice: Loaded font "JetBrainsMonoNerd:size=14" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
> 
> Polybar isn't actually loading the nerd font (look at the actual font loaded in brackets. Please read the [font debugging guide](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues)

i know and i looked at the guide and nothing fixed it

**Comment by patrick96** [comment]
You need to figure out how the font is actually called on your system. `fc-list` will list all the fonts (file path and name) in your system.

On my system the name is `JetBrainsMono Nerd Font Mono:style=Regular`, but it may be different for yours

**Comment by RealMrCactus** [comment]
> You need to figure out how the font is actually called on your system. `fc-list` will list all the fonts (file path and name) in your system.
> 
> On my system the name is `JetBrainsMono Nerd Font Mono:style=Regular`, but it may be different for yours

It is correct as the font shows correctly latin characters

**Comment by patrick96** [comment]
No, polybar is currently loading `NotoSans-Bold.ttf`, that's why the latin characters work
