### ISSUE TITLE
[Bug]: polybar -r fails when there are multiple bars

### ISSUE THREAD

**Issue by icf20** [polybar/polybar#3025]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

```
polybar -r      
notice: Parsing config file: /home/user/.config/polybar/config.ini
error: Uncaught exception, shutting down: The config file contains multiple bars, but no bar name was given. Available bars: left, right

```

it fails to reload the config 

### Minimal config

```dosini
not relevant to my problem
```

### Expected behavior

to reload the config duh 

### Actual behavior

jesus fing crist what is this friction? u add this BS template to add friction so people dont report bugs?

### Window Manager and Version

not relevant

### Linux Distribution

not relevant

### Polybar version

```text
polybar 3.6.3
```

### Additional Context / Screenshots

holy f i try to tell you how the program have a failure not making a mortgage application 

> Thanks for taking the time to fill out this bug report! ❤️

thx for having bullshit template

**Comment by patrick96** [comment]
If there are multiple bars you need to specify which bar to launch as part of the `polybar` command. Otherwise how would it know which bar to start?

**Comment by icf20** [comment]
1. -r was supposed to reload the config, so just reload the config and dont ask additional stuff 
2. the old bar is still in place and another is created so not really a reload more like duplicate

**Comment by patrick96** [comment]
That's not what `-r` does. When you start a bar and also add `-r`, that bar will restart if its config file changes. It does not restart other bars.
