### ISSUE TITLE
[Bug] Polybar tray background is not transparent

### ISSUE THREAD

**Issue by brainwo** [polybar/polybar#3027]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Have Polybar instance already running (`polybar <bar-name>`)
2. Open some app
3. Put that app behind the bar
4. The tray icons are not actually transparent as it supposed to be (image below)

### Minimal config

```dosini
[bar/bar]
modules-right = tray

[module/tray]
type = internal/tray
tray-spacing = 4pt
tray-size = 15pt
```

### Polybar log

```text
(not applicable)
```

### Expected behavior

It should be transparent especially when there is a background layer app (below the bar) opened.

### Actual behavior

Not quite transparent as the tray icon background faking it transparency by following the wallpaper color instead.

### Window Manager and Version

bspwm 0.9.10-3

### Linux Distribution

Arch Linux

### Polybar version

```text
polybar 3.6.3-216-g278584fa

Features: -alsa +curl -i3 -mpd -network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/clang++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override -Wno-error=parentheses-equality -Wno-zero-length-array
Linker flags:  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override -Wno-error=parentheses-equality -Wno-zero-length-array  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override -Wno-error=parentheses-equality -Wno-zero-length-array
```

### Additional Context / Screenshots

Only background app is wallpaper (fehbg)
![image](https://github.com/polybar/polybar/assets/45139213/589b883f-406a-4390-97fb-ebe894fad64f)

An app (mpv using xwinwrap) is opened and it's rendered below/behind the bar. The tray icon background color is the color coming wallpaper behind it, same color with the bar in the previous image.
![image](https://github.com/polybar/polybar/assets/45139213/719c82c4-896c-455c-8921-fb9e3485d53f)

**Comment by patrick96** [comment]
The tray uses pseudo-transparency for its background. Meaning, it uses the wallpaper contents at that position as the background to mimic transparency. This of course no longer looks right if you put something else behind the bar.

This is the intended behavior. I have not found a way to achieve true transparency for the tray icons.
