### ISSUE TITLE
[Bug]: text module looking ignoring "format" and "label", looking for "content" instead

### ISSUE THREAD

**Issue by n0noob** [polybar/polybar#3040]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Define a minimal text module with following lines:
```
[module/text0]
type = custom/text 
format = <label>
label = "text0"
```

Polybar fails to render the module with error:
```
error: Disabling module "text0" (reason: module/text0.content is empty or undefined)
```

### Minimal config

```dosini
[bar/example]
modules-center = text0

[module/text0]
type = custom/text 
format = <label>
label = "text0"
```
```


### Polybar log

_No response_

### Expected behavior

`text0` module should be rendered with`format` and `label` alone since `content` is deprecated property.

### Actual behavior

Module `text0` is not rendered.

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

EndeavourOS Linux x86_64

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug/polybar -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```
```


### Additional Context / Screenshots

_No response_

**Comment by patrick96** [comment]
Format and label were introduced to the text module in version 3.7.0, you're still using an older version which only had `content`
