### ISSUE TITLE
[Bug]: The last version makes the label show up regardless if the exec had any output.

### ISSUE THREAD

**Issue by Samueru-sama** [polybar/polybar#3047]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I'm using polybar with Arch linux and i3wm.

I have this custom module in my polybar config: 

```
[module/SONG]
type = custom/script
label = %{F#F0C674}♫%{F-} %output:5:30:…%
exec = playerctl metadata --format '{{ title }}' 2>/dev/null
interval = 1
format-padding = 1
click-left = playerctl next
click-right = playerctl previous
click-middle = playerctl play-pause
scroll-up = playerctl volume 0.10+
scroll-down = playerctl volume 0.10-

```

Which prints the titlle of the current playing song, along with a ♫ symbol. 

When no music is playing, the symbol is still being printed even though there is no output from the exec. Downgrading to version 3.6.3 fixes the issue. 

### Minimal config

```dosini
[bar/example]
width = 100%
height = 12pt
radius = 0
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 1pt
module-margin = 1
separator = |
separator-foreground = ${colors.disabled}
font-0 = Droid Sans:size=9:style=Bold;2
font-1 = FontAwesome:size=14;3
modules-left = CPU RAM GPU DISK
modules-center = xwindow xworkspaces SONG
modules-right = pulseaudio xkeyboard eth DATE
tray-position = right
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/SONG]
type = custom/script
label = %{F#F0C674}♫%{F-} %output:5:30:…%
exec = playerctl metadata --format '{{ title }}' 2>/dev/null
interval = 1
format-padding = 1
click-left = playerctl next
click-right = playerctl previous
click-middle = playerctl play-pause
scroll-up = playerctl volume 0.10+
scroll-down = playerctl volume 0.10-
```

### Expected behavior

The label symbol shouldn't be printed if there is no output from the script. 

### Actual behavior

The label gets printed regardless. 

### Window Manager and Version

i3wm v4.23

### Linux Distribution

Archlinux

### Polybar version

```text
Polybar 3.7.0
```

### Additional Context / Screenshots

Here you can see what shows up in the bar in the older and newer versio nof polybar where the music symbol is still seen even though there is nothing playing. 

https://imgur.com/iYHRJQO.png
https://imgur.com/WKq6jUN.png

**Comment by patrick96** [comment]
This was one of the breaking changes in the [3.7 release](https://github.com/polybar/polybar/releases/tag/3.7.0):
If the `exec` command fails and doesn't produce output, the module no longer disappears.

This was done to make it possible to properly use `format-fail` and `label-fail`.

So in your case, either set `format-fail = ""` or make sure your script never fails (e.g. `exec = playerctl metadata --format '{{ title }}' 2>/dev/null || true`).
