### ISSUE TITLE
[Bug]: Tray Icons too small when using the new tray module. 

### ISSUE THREAD

**Issue by Samueru-sama** [polybar/polybar#3050]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I'm trying to migrate my config to use the tray module, this is what I get now: https://imgur.com/D0SYaDA.png

This is how it used to look with ''tray-position = right'': https://imgur.com/uJ0hMxM.png

### Minimal config

```dosini
[bar/example]
modules-right = pulseaudio xkeyboard eth DATE tray

[module/tray]
type = internal/tray
format = <tray>
```

### Expected behavior

The tray should look like it did before.

### Actual behavior

The tray icons are too small and misplaced.

### Window Manager and Version

i3wm v4.23

### Linux Distribution

Archlinux

### Polybar version

```text
Polybar 3.7.0
```

**Comment by patrick96** [comment]
> The tray should look like it did before.

We don't guarantee this.

The icon size calculations have changed in the tray module, icons are now 66% of the bar height. I found that to go well together with the other defaults.

You can control the size of the icons using [`tray-size`](https://polybar.readthedocs.io/en/stable/user/modules/tray.html#poly-setting-tray-size)
