### ISSUE TITLE
[Bug]: Battery’s `label-low` not shown even if battery level is under `low-at`

### ISSUE THREAD

**Issue by victorbnl** [polybar/polybar#3058]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

```
polybar -c minimal.ini top
```

### Minimal config

```dosini
[bar/top]
width = 100%
height = 45
modules-left = battery

[module/battery]
type = internal/battery

battery = BAT0
adapter = AC

low-at = 99

label-charging = "CHARGING %percentage%%"
label-discharging = "DISCHARGING %percentage%%"

label-full = "FULL %percentage%%"
label-low = "LOW  %percentage%%"
```

### Polybar log

```text
notice: Parsing config file: config.ini
notice: Loading module 'battery' of type 'internal/battery'
notice: Loaded 1 modules
warn: No fonts specified, using fallback font "fixed"
notice: Loaded font "fixed" (name=Ubuntu, offset=0, file=/usr/share/fonts/ubuntu/Ubuntu-R.ttf)
```

### Expected behavior

My battery module shows, “LOW”.

### Actual behavior

It shows, “DISCHARGING” instead.

### Window Manager and Version

i3-wm 4.23-1

### Linux Distribution

Arch

### Polybar version

```text
polybar 3.7.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug/polybar -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
```

### Additional Context / Screenshots

![image](https://github.com/polybar/polybar/assets/39555268/971ed088-ace7-4011-b591-59f6b2fbe2ba)

**Comment by patrick96** [comment]
From the [wiki](https://github.com/polybar/polybar/wiki/Module:-battery):

> Format used when battery level drops to low-at
If not defined, format-discharging is used instead.

You did not define `format-low`, so polybar uses `format-discharging`, which is defined by default and used `label-discharging`
