### ISSUE TITLE
[Bug] internal/battery: percentage is not detected, even though the file is present

### ISSUE THREAD

**Issue by Pato05** [polybar/polybar#3059]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Start the bar
No battery module is present

### Minimal config

```dosini
[module/battery]
type = internal/battery
battery = "surface-rt-battery"
adapter = "surface-rt-ac-adapter"
```

### Polybar log

```text
polybar|notice:  Loading module 'battery' of type 'internal/battery'
polybar|error: Disabling module "battery" (reason: No suitable way to get current capacity value)
```

### Expected behavior

The battery percentage is shown

### Actual behavior

The battery percentage is not shown, and the error "No suitable way to get current capacity value" is presented

### Window Manager and Version

i3 4.23-r0

### Linux Distribution

PostmarketOS (Alpine Linux)

### Polybar version

```text
polybar 3.6.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/g++
Compiler flags: -Os -fomit-frame-pointer  -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,--as-needed,-O1,--sort-common -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

The path `/sys/class/power_supply/surface-rt-battery` and the adapter ones are obviously present, but by looking into the code I saw that polybar is trying to get either the `charge_now` or `energy_now` files, which, in my case, are not present (probably due to the driver being likely incomplete).
Though, the battery percentage is still available inside the `capacity` file, and I noticed that it contains the battery percentage on my laptop as well, so I'm guessing that the `capacity` file may be a substitute to the raw percentage calculation between `charge_now`/`charge_full`. That would be my suggested solution, though I cannot submit a PR as I have poor knowledge in C++..

**Comment by patrick96** [comment]
This came up again in #3184. I'm closing this issue on favor of the other one.
