### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by thealio** [polybar/polybar#3066]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Hi
I don't know if this is a behavior depending by polybar itself or not.

Referring to this issue on xmonad github

https://github.com/xmonad/xmonad-contrib/issues/849

I use xmonad + polybar.

On polybar, I wrote a custum module that shows the current layout on the bar . The module is the following: 

### Minimal config

```dosini


[module/xmonad-layout]
type = custom/script
format-prefix = " "
format-foreground = ${colors.color07}
format-background = ${colors.color00}
exec = xprop -root _XMONAD_CURRENT_LAYOUT | awk '{print $NF}' | tr -d "\""
tail = true
```
It extract the layout with `xprop -root _XMONAD_CURRENT_LAYOUT | awk '{print $NF}' | tr -d "\""`

It seems that this caused the unusual high CPU consumption , I don't know exactly why this happens. 

I wonder if this is caused by a issue regarding polybar itself, or it depends by the way I wrote the module, or something else.
If I wrote the module badly, I'd like to know if there's a way to write that to avoid the CPU usage leak
```


### Polybar log

_No response_

### Expected behavior

No CPU High usage

### Actual behavior

High CPU Usage

### Window Manager and Version

.xmonad 0.17.1

### Linux Distribution

Arch Linux

### Polybar version

```text
Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug/polybar -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
```

**Comment by thealio** [comment]
> ### Checklist
> 
>     * [x]  I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
> 
>     * [x]  I believe this issue is a problem with polybar itself and not a misconfiguration on my part
> 
>     * [x]  I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
> 
>     * [x]  I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
> 
>     * [x]  I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.
> 
> 
> ### Steps to reproduce
> 
> Hi I don't know if this is a behavior depending by polybar itself or not.
> 
> Referring to this issue on xmonad github
> 
> [xmonad/xmonad-contrib#849](https://github.com/xmonad/xmonad-contrib/issues/849)
> 
> I use xmonad + polybar.
> 
> On polybar, I wrote a custum module that shows the current layout on the bar . The module is the following:
> ### Minimal config
> 
> ```ini
> [module/xmonad-layout]
> type = custom/script
> format-prefix = " "
> format-foreground = ${colors.color07}
> format-background = ${colors.color00}
> exec = xprop -root _XMONAD_CURRENT_LAYOUT | awk '{print $NF}' | tr -d "\""
> tail = true
> ```
> 
> It extract the layout with `xprop -root _XMONAD_CURRENT_LAYOUT | awk '{print $NF}' | tr -d "\""`
> 
> It seems that this caused the unusual high CPU consumption , I don't know exactly why this happens.
> 
> I wonder if this is caused by a issue regarding polybar itself, or it depends by the way I wrote the module, or something else. If I wrote the module badly, I'd like to know if there's a way to write that to avoid the CPU usage leak
> 
> ```
> 
> 
> ### Polybar log
> 
> _No response_
> 
> ### Expected behavior
> 
> No CPU High usage
> 
> ### Actual behavior
> 
> High CPU Usage
> 
> ### Window Manager and Version
> 
> .xmonad 0.17.1
> 
> ### Linux Distribution
> 
> Arch Linux
> 
> ### Polybar version
> 
> ```text
> Build type: Release
> Compiler: /usr/bin/c++
> Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/polybar/src=/usr/src/debug/polybar -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
> Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
> ```
> 
> ### Additional Context / Screenshots
> 
> _No response_

UPDATE:
setting
tail = false
or commenting it avoids memory leak
However, the layout showing delays about to 3-5 seconds

**Comment by thealio** [comment]
UPDATE 3
Setting `interval = 1` or above didn't causes CPU overload
Setting `interval =` under 1 ( ex. `0,5 `) causes CPU overload

**Comment by patrick96** [comment]
`tail = true` should only be used if the command you execute is continuously producing new output that the module should display. For one-off scripts that just run and produce one line of output, it has no benefit and in this case causes high CPU usage because with `tail = true` the default value for `interval` is 0.

With an interval of `0`, polybar will re-run the `exec` command as soon as it finishes and with the `exec` command running basically all the time, it will use up an entire CPU thread.

Keep in mind that the lower you set `interval`, the more CPU the module will use, because it runs more often.
In your case, `xprop -root _XMONAD_CURRENT_LAYOUT` is probably more resource efficient (use it with `tail = true`), because the script itself sleeps until there is an update and then produces some new output.
