### ISSUE TITLE
[Bug]: Polybar on linux mint does not have default config in /etc

### ISSUE THREAD

**Issue by ahmad-reza619** [polybar/polybar#3088]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Install polybar with
```sh
sudo apt install polybar
```

### Minimal config

```dosini
no config yet
```

### Expected behavior

I expected that there is a sample polybar config in /etc/polybar/config.ini or /etc/xdg/polybar/config.ini as per docs [here](https://github.com/polybar/polybar/wiki)

### Actual behavior

there is no polybar folder in /etc or /etc/xdg

### Window Manager and Version

i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors

### Linux Distribution

Linux Mint

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Debian package, build flags removed from output for reproducibility
You can refer to the build logs at:
https://buildd.debian.org/status/package.php?p=polybar
```

**Comment by ahmad-reza619** [comment]
After some search, i found out that on apt installation it does not create a config.ini file, so when i tried to compile it manually, it works now. I got the info about this from an external blog, maybe it would be nice to add disclaimer in wiki for this

**Comment by patrick96** [comment]
Polybar only started providing a default config in version 3.6. Once polybar is updated to that version or later in your distribution, you should also see a default config in `/etc`
