### ISSUE TITLE
[Bug]: module/pulseaudio does not preserve audio balance on volume change

### ISSUE THREAD

**Issue by kdato** [polybar/polybar#3123]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I have polybar-3.7.1 from here. In my .config/pulse/default.pa I have this line to set the audio balance on my speakers: set-sink-volume 0 +0% +35%.

When I start my DE, polybar loads fine and the default balance if fine. Using the mouse wheel on polybar to change the audio volume changes each audio channel by a different percentage. This does not preserve the audio balance.

### Minimal config

```dosini
[bar/DP-2]
monitor = ${env:MONITOR:DP-2}
background = ${colors.background}
foreground = ${colors.foreground}

modules-right = pulseaudio date

font-0 = Noto Sans Mono:size=11:weight=bold;2
font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
font-2 = siji:pixelsize=10;1
font-3 = Font Awesome 6 Free:style=Solid:pixelsize=11;2

override-redirect = true
cursor-click = pointer
cursor-scroll = ns-resize


[module/pulseaudio]
type = internal/pulseaudio
click-right = pavucontrol
label-muted-foreground = #FFBF00
label-volume-foreground = ${root.foreground}

format-volume = <label-volume> <bar-volume>
label-volume =  %percentage%%
label-muted = "   "
```

### Expected behavior

Using the mouse wheel on polybar to change the volume, both audio channels should change by the same amount to preserve the volume balance.

### Actual behavior

When I use the mouse wheel on polybar to change the volume, the right audio channel changes by +5% or -5%. But the left channel changes by only +3% or -3%, which means that module/pulseaudio does not preserve the volume balance.

To confirm, using the volume wheel on my keyboard, or using the mouse wheel directly in pulsemixer, does preserve the balance as expected.

### Window Manager and Version

labwc-0.7.1 or enlightenment-0.26.0

### Linux Distribution

Slackware-current

### Polybar version

```text
polybar-3.7.1
```

**Comment by patrick96** [comment]
So what is currently happening is that when we change the volume, it preserves the proportion of the channels. For example if you are at (50%, 25%) and increase by 10%, you get to (60%, 30%), so the 2-1 proportion is preserved. I suspect the main reason we do it this way is that pulseaudio has an API for this (`pa_cvolume_inc` and `pa_cvolume_dec`) but not for changing volume while preserving balance.

I have no idea what the natural/intuitive/correct way to handle this is. But it probably makes sense if we match the behavior of pactl and pulsemixer here.

I don't really have the capacity to work on this, but PRs are welcome.
The code for this is in `inc_volume` in` src/adapters/pulseaudio.cpp`
