### ISSUE TITLE
[Bug]: bars not displaying at all 

### ISSUE THREAD

**Issue by CarlosGT7274** [polybar/polybar#3126]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

in my bspwmrc file i put this:

`. ~/.config/polybar/Theme.sh
`

there is mi launch script:
```
launch_bars() {
	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		(MONITOR=$mon polybar -q pam1 -c ~/.config/polybar/config.ini 2> ~/logpol.log) &
		(MONITOR=$mon polybar -q pam2 -c ~/.config/polybar/config.ini 2> ~/logpol.log) &
                (MONITOR=$mon polybar -q pam3 -c ~/.config/polybar/config.ini 2> ~/logpol.log) &
		(MONITOR=$mon polybar -q pam4 -c ~/.config/polybar/config.ini 2> ~/logpol.log) &
		(MONITOR=$mon polybar -q pam5 -c ~/.config/polybar/config.ini 2> ~/logpol.log) &
		(MONITOR=$mon polybar -q pam6 -c ~/.config/polybar/config.ini 2> ~/logpol.log) &
	done
}
```

### Minimal config

```dosini
[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../bspwm/scripts/system.ini
include-file = modules.ini

[color]
bg = #2f354b
bg-alt = #BF1D1F28
fg = #FDFDFD

trans = #00000000
white = #FFFFFF
black = #000000

red = #F37F97
pink = #EC407A
purple = #C574DD
blue = #8897F4
cyan = #79E6F3
teal = #00B19F
green = #5ADECD
lime = #B9C244
yellow = #F2A272
amber = #FBC02D
orange = #E57C46
brown = #AC8476
grey = #8C8C8C
indigo = #6C77BB
blue-gray = #6D8895

[bar/pam1]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 2.5%
height = 40

offset-x = 2%
offset-y = 10

background = ${color.bg-alt}
foreground = ${color.fg}

radius = 6

line-size = 2
line-color = ${color.blue}

border-size = 2
border-color = ${color.bg}

padding = 0

module-margin-left = 0
module-margin-right = 0

font-0 = "Material Design Icons Desktop:size=14;3"

modules-left = 
modules-center = launcher
modules-right = 

separator =
dim-value = 1.0

;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer 
cursor-scroll = ns-resize

[bar/pam2]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = false

width = 17%
height = 40

offset-x = 5%
offset-y = 10

background = ${color.bg-alt}
foreground = ${color.fg}

radius = 6

line-size = 2
line-color = ${color.blue}

border-size = 2
border-color = ${color.bg}

padding = 2

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono:style=Regular:pixelsize=8;2"
; Icons
font-1 = "Material Design Icons Desktop:size=12;3"

modules-left =
modules-center = bspwm
modules-right = 

separator =
dim-value = 1.0

;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer 
cursor-scroll = ns-resize

[bar/pam3]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 22%
height = 40

offset-x = 38.5%
offset-y = 10

background = ${color.bg-alt}
foreground = ${color.fg}

radius = 6

line-size = 2
line-color = ${color.blue}

border-size = 2
border-color = ${color.bg}

padding = 2

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono:style=Bold:pixelsize=8;2"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"

modules-left = mplayer 
modules-center = 
modules-right = 

separator =
dim-value = 1.0

;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer 
cursor-scroll = ns-resize

[bar/pam4]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 26.5%
height = 40

offset-x = 61%
offset-y = 10

background = ${color.bg-alt}
foreground = ${color.fg}

radius = 6

line-size = 2
line-color = ${color.blue}

border-size = 2
border-color = ${color.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono:style=Bold:pixelsize=9;2"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"

modules-left = 
modules-center = filesystem sep cpu_bar sep memory_bar sep network sep pulseaudio
modules-right = 

separator =
dim-value = 1.0

;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer 
cursor-scroll = ns-resize

[bar/pam5]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = false

width = 10%
height = 40

offset-x = 88%
offset-y = 10

background = ${color.bg-alt}
foreground = ${color.fg}

radius = 6

line-size = 2
line-color = ${color.blue}

border-size = 2
border-color = ${color.bg}

padding = 2

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono:style=Bold:pixelsize=9;2"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"

modules-left = date
modules-center =
modules-right = power

separator =
dim-value = 1.0

;locale = 

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer 
cursor-scroll = ns-resize

[bar/pam6]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 15.5%
height = 40

offset-x = 22.5%
offset-y = 10

background = ${color.bg-alt}
foreground = ${color.fg}

radius = 6

line-size = 2
line-color = ${color.blue}

border-size = 2
border-color = ${color.bg}

padding = 2

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono:style=Bold:pixelsize=9;3"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"

modules-left = r00t updates 
modules-center =
modules-right = tray

separator = " "
dim-value = 1.0

;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer 
cursor-scroll = ns-resize

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
```

### Polybar log

```text
there is no log errors
```

### Expected behavior

it should be like this:

![imagen](https://github.com/polybar/polybar/assets/116324770/8b475b0f-8afa-4f6e-9fad-716cb6d8a2d2)

### Actual behavior

it displays like this:

![imagen](https://github.com/polybar/polybar/assets/116324770/115ed600-85bf-4560-a399-39f6d7ac2e35)

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Arch linux 6.9.3-zen1-1-zen

### Polybar version

```text
polybar 3.7.1-11-g11b522c3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/home/carlos/.cache/yay/polybar-git/src=/usr/src/debug/polybar-git -flto=auto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
Linker flags: -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override  -Wall -Wextra -Wpedantic -Wdeprecated-copy-dtor -Wsuggest-override
```

### Additional Context / Screenshots

When I run ./Theme.sh it shows correctly but in the bspwmrc file it doesn't

**Comment by patrick96** [comment]
Please post the log of the bars that don't show

**Comment by CarlosGT7274** [comment]
> Please post the log of the bars that don't show

there is no log.... 
![imagen](https://github.com/polybar/polybar/assets/116324770/10045905-455a-4fe5-b849-8892331705f5)

**Comment by CarlosGT7274** [comment]
> Please post the log of the bars that don't show

there is no log
![imagen](https://github.com/polybar/polybar/assets/116324770/582f4330-107e-4904-8401-bf9628ff6dbc)

and... like i said in bspwmrc call doesnt work but when i run the script separately it works 
 even when I restart bspwm it doesn't work either and it's sort of random which ones are shown and which ones aren't... that is, on a restart the 3rd time it works but on the next reboot it doesn't...
 
 first reboot of bspwmrc:
 
![imagen](https://github.com/polybar/polybar/assets/116324770/e1c369c5-70ce-4415-acd2-b4b0ae313b4e)

second 

![imagen](https://github.com/polybar/polybar/assets/116324770/9c9990bb-a2aa-4ba5-9511-350de35ccfab)

third

![imagen](https://github.com/polybar/polybar/assets/116324770/afca158c-8643-4f54-b0ac-23f63f16f40e)

is xorg...???
 
 ```
 Section "Monitor"
    Identifier     "DP-1"
    Option         "Primary" "true"
EndSection

Section "Monitor"
    Identifier     "HDMI-1"
    Modeline "1920x1080" 172.80 1920 2040 2248 2576 1080 1081 1084 1118
    Option "PreferredMode" "1920x1080"
    Option "RightOf" "DP-1"
EndSection
 ```

**Comment by patrick96** [comment]
Ah, you're running in quiet mode (`-q`) and are only redirecting stderr to the log file.

For testing, use the following instead inside the loop of your launch script:

```
(MONITOR=$mon polybar -l trace pam1 -c ~/.config/polybar/config.ini > ~/logpol1.log 2>&1) &
(MONITOR=$mon polybar -l trace pam2 -c ~/.config/polybar/config.ini > ~/logpol2.log 2>&1) &
(MONITOR=$mon polybar -l trace pam3 -c ~/.config/polybar/config.ini > ~/logpol3.log 2>&1) &
(MONITOR=$mon polybar -l trace pam4 -c ~/.config/polybar/config.ini > ~/logpol4.log 2>&1) &
(MONITOR=$mon polybar -l trace pam5 -c ~/.config/polybar/config.ini > ~/logpol5.log 2>&1) &
(MONITOR=$mon polybar -l trace pam6 -c ~/.config/polybar/config.ini > ~/logpol6.log 2>&1) &
```

This should put all output produced (including some more debug logging) to separate files.
When you then run this from your bspwmrc, I need the log files from any of the bars that are not displaying to debug anything.

I don't think your xorg config is breaking anything.

**Comment by CarlosGT7274** [comment]
> Ah, you're running in quiet mode (`-q`) and are only redirecting stderr to the log file.
> 
> For testing, use the following instead inside the loop of your launch script:
> 
> ```
> (MONITOR=$mon polybar -l trace pam1 -c ~/.config/polybar/config.ini > ~/logpol1.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam2 -c ~/.config/polybar/config.ini > ~/logpol2.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam3 -c ~/.config/polybar/config.ini > ~/logpol3.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam4 -c ~/.config/polybar/config.ini > ~/logpol4.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam5 -c ~/.config/polybar/config.ini > ~/logpol5.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam6 -c ~/.config/polybar/config.ini > ~/logpol6.log 2>&1) &
> ```
> 
> This should put all output produced (including some more debug logging) to separate files. When you then run this from your bspwmrc, I need the log files from any of the bars that are not displaying to debug anything.
> 
> I don't think your xorg config is breaking anything.

log: 
```
polybar|notice:  Parsing config file: /home/carlos/.config/polybar/config.ini
polybar|trace: config_parser: Parsing /home/carlos/.config/polybar/config.ini
polybar|trace: config_parser: Parsing /home/carlos/.config/bspwm/scripts/system.ini
polybar|trace: config_parser: Parsing /home/carlos/.config/polybar/modules.ini
polybar|info:  Created legacy ipc fifo at '/tmp/polybar_mqueue.933'
polybar|info:  Opening ipc socket at '/run/user/1000/polybar/ipc.933.sock'
polybar|notice:  Listening for IPC messages (PID: 933)
polybar|info:  Environment var reference ${MONITOR} found (value=DP-1)
polybar|info:  Loaded monitor DP-1 (1920x1080+0+0)
polybar|info:  Configured DPI = 96x96
polybar|info:  Bar geometry: 508x44+1171+10; Borders: 2,2,2,2
polybar|trace: bar: Attach X event sink
polybar|trace: bar: Attach signal receiver
polybar|trace: controller: Setup user-defined modules
polybar|notice:  Loading module 'filesystem' of type 'internal/fs'
polybar|notice:  Loading module 'sep' of type 'custom/text'
polybar|notice:  Loading module 'cpu_bar' of type 'internal/cpu'
polybar|notice:  Loading module 'sep' of type 'custom/text'
polybar|notice:  Loading module 'memory_bar' of type 'internal/memory'
polybar|notice:  Loading module 'sep' of type 'custom/text'
polybar|notice:  Loading module 'network' of type 'internal/network'
polybar|notice:  Loading module 'sep' of type 'custom/text'
polybar|notice:  Loading module 'pulseaudio' of type 'internal/pulseaudio'
polybarpolybar|trace: pulseaudio: started mainloop
```

**Comment by CarlosGT7274** [comment]
> Ah, you're running in quiet mode (`-q`) and are only redirecting stderr to the log file.
> 
> For testing, use the following instead inside the loop of your launch script:
> 
> ```
> (MONITOR=$mon polybar -l trace pam1 -c ~/.config/polybar/config.ini > ~/logpol1.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam2 -c ~/.config/polybar/config.ini > ~/logpol2.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam3 -c ~/.config/polybar/config.ini > ~/logpol3.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam4 -c ~/.config/polybar/config.ini > ~/logpol4.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam5 -c ~/.config/polybar/config.ini > ~/logpol5.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam6 -c ~/.config/polybar/config.ini > ~/logpol6.log 2>&1) &
> ```
> 
> This should put all output produced (including some more debug logging) to separate files. When you then run this from your bspwmrc, I need the log files from any of the bars that are not displaying to debug anything.
> 
> I don't think your xorg config is breaking anything.

log: 
```
polybar|notice:  Parsing config file: /home/carlos/.config/polybar/config.ini
polybar|trace: config_parser: Parsing /home/carlos/.config/polybar/config.ini
polybar|trace: config_parser: Parsing /home/carlos/.config/bspwm/scripts/system.ini
polybar|trace: config_parser: Parsing /home/carlos/.config/polybar/modules.ini
polybar|info:  Created legacy ipc fifo at '/tmp/polybar_mqueue.933'
polybar|info:  Opening ipc socket at '/run/user/1000/polybar/ipc.933.sock'
polybar|notice:  Listening for IPC messages (PID: 933)
polybar|info:  Environment var reference ${MONITOR} found (value=DP-1)
polybar|info:  Loaded monitor DP-1 (1920x1080+0+0)
polybar|info:  Configured DPI = 96x96
polybar|info:  Bar geometry: 508x44+1171+10; Borders: 2,2,2,2
polybar|trace: bar: Attach X event sink
polybar|trace: bar: Attach signal receiver
polybar|trace: controller: Setup user-defined modules
polybar|notice:  Loading module 'filesystem' of type 'internal/fs'
polybar|notice:  Loading module 'sep' of type 'custom/text'
polybar|notice:  Loading module 'cpu_bar' of type 'internal/cpu'
polybar|notice:  Loading module 'sep' of type 'custom/text'
polybar|notice:  Loading module 'memory_bar' of type 'internal/memory'
polybar|notice:  Loading module 'sep' of type 'custom/text'
polybar|notice:  Loading module 'network' of type 'internal/network'
polybar|notice:  Loading module 'sep' of type 'custom/text'
polybar|notice:  Loading module 'pulseaudio' of type 'internal/pulseaudio'
polybarpolybar|trace: pulseaudio: started mainloop
```

**Comment by CarlosGT7274** [comment]
> Ah, you're running in quiet mode (`-q`) and are only redirecting stderr to the log file.
> 
> For testing, use the following instead inside the loop of your launch script:
> 
> ```
> (MONITOR=$mon polybar -l trace pam1 -c ~/.config/polybar/config.ini > ~/logpol1.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam2 -c ~/.config/polybar/config.ini > ~/logpol2.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam3 -c ~/.config/polybar/config.ini > ~/logpol3.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam4 -c ~/.config/polybar/config.ini > ~/logpol4.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam5 -c ~/.config/polybar/config.ini > ~/logpol5.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam6 -c ~/.config/polybar/config.ini > ~/logpol6.log 2>&1) &
> ```
> 
> This should put all output produced (including some more debug logging) to separate files. When you then run this from your bspwmrc, I need the log files from any of the bars that are not displaying to debug anything.
> 
> I don't think your xorg config is breaking anything.

i think is a pulseaudio error, cause i remove it from config.ini and it work fine....

**Comment by CarlosGT7274** [comment]
> Ah, you're running in quiet mode (`-q`) and are only redirecting stderr to the log file.
> 
> For testing, use the following instead inside the loop of your launch script:
> 
> ```
> (MONITOR=$mon polybar -l trace pam1 -c ~/.config/polybar/config.ini > ~/logpol1.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam2 -c ~/.config/polybar/config.ini > ~/logpol2.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam3 -c ~/.config/polybar/config.ini > ~/logpol3.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam4 -c ~/.config/polybar/config.ini > ~/logpol4.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam5 -c ~/.config/polybar/config.ini > ~/logpol5.log 2>&1) &
> (MONITOR=$mon polybar -l trace pam6 -c ~/.config/polybar/config.ini > ~/logpol6.log 2>&1) &
> ```
> 
> This should put all output produced (including some more debug logging) to separate files. When you then run this from your bspwmrc, I need the log files from any of the bars that are not displaying to debug anything.
> 
> I don't think your xorg config is breaking anything.

nigga help me please

**Comment by patrick96** [comment]
Hmm looks like polybar is waiting for a signal from pulseaudio that it never received, which blocks the whole thing.

How does your audio setup look like? Does your system use pulseaudio?

**Comment by CarlosGT7274** [comment]
> Hmm looks like polybar is waiting for a signal from pulseaudio that it never received, which blocks the whole thing.
> 
> How does your audio setup look like? Does your system use pulseaudio?

i use pipewire:
![imagen](https://github.com/polybar/polybar/assets/116324770/8fa4f312-48e5-446c-8cb1-cc73bac24ec7)

**Comment by CarlosGT7274** [comment]
> Hmm looks like polybar is waiting for a signal from pulseaudio that it never received, which blocks the whole thing.
> 
> How does your audio setup look like? Does your system use pulseaudio?

nigga???

**Comment by CarlosGT7274** [comment]
> Hmm looks like polybar is waiting for a signal from pulseaudio that it never received, which blocks the whole thing.
> 
> How does your audio setup look like? Does your system use pulseaudio?

![image](https://github.com/polybar/polybar/assets/116324770/b0c9acca-37cf-4884-84d3-be8c391c555b)

**Comment by CarlosGT7274** [comment]
> Hmm looks like polybar is waiting for a signal from pulseaudio that it never received, which blocks the whole thing.
> 
> How does your audio setup look like? Does your system use pulseaudio?

gay if you dont help me

**Comment by ACR-Jeff** [comment]
With that attitude I doubt anyone's going to help you solve your issue, Yet I will give you some information that I found recently with BSPWM, I recently installed and tested BSPWM for the first time and I found it to be acting strange with pipewire along with polybar, while polybar was launched it would lag the entire window manager (Not saying it's polybar's fault, Something in that setup causes the WM issues, Also noticed that the autostart's had to be placed at the bottom of the config file to even launch everything properly. Maybe some of that will help you solve your issue.

**Comment by CarlosGT7274** [comment]
> With that attitude I doubt anyone's going to help you solve your issue, Yet I will give you some information that I found recently with BSPWM, I recently installed and tested BSPWM for the first time and I found it to be acting strange with pipewire along with polybar, while polybar was launched it would lag the entire window manager (Not saying it's polybar's fault, Something in that setup causes the WM issues, Also noticed that the autostart's had to be placed at the bottom of the config file to even launch everything properly. Maybe some of that will help you solve your issue.

Nobody helps me anyway nigga so it don't matter and I'm a nigga too

**Comment by CarlosGT7274** [comment]
> With that attitude I doubt anyone's going to help you solve your issue, Yet I will give you some information that I found recently with BSPWM, I recently installed and tested BSPWM for the first time and I found it to be acting strange with pipewire along with polybar, while polybar was launched it would lag the entire window manager (Not saying it's polybar's fault, Something in that setup causes the WM issues, Also noticed that the autostart's had to be placed at the bottom of the config file to even launch everything properly. Maybe some of that will help you solve your issue.

thanks for the information

**Comment by CarlosGT7274** [comment]
> With that attitude I doubt anyone's going to help you solve your issue, Yet I will give you some information that I found recently with BSPWM, I recently installed and tested BSPWM for the first time and I found it to be acting strange with pipewire along with polybar, while polybar was launched it would lag the entire window manager (Not saying it's polybar's fault, Something in that setup causes the WM issues, Also noticed that the autostart's had to be placed at the bottom of the config file to even launch everything properly. Maybe some of that will help you solve your issue.

i pull up w [polybar-pipewire-control](https://github.com/claudius-kienle/polybar-pipewire-control) module and it work,  but I still have problems w/ the audio like the Shazam not recognizing anything and the audio mix, the porn can be heard through the microphone nigga wtf

![imagen](https://github.com/polybar/polybar/assets/116324770/0d8cd60c-0531-46b2-a2c9-16b539ff053a)

**Comment by patrick96** [comment]
Closing and locking this issue, this kind of language has no place here.

Please stay respectful and keep in mind that people don't *have* to help you. Calling them slurs will not make them more likely to help you.
