### ISSUE TITLE
[Bug]: Module: xwindow display Chinese missing

### ISSUE THREAD

**Issue by ixianjia** [polybar/polybar#3136]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I'm trying to configure module/xwindow，I run xprop to get WM_NAME(UTF8_STRING) ，the information obtained by the output is in Chinese, but the module/xwindow  %title%  shows that Chinese is missing.
like this： ![2024-07-29_22-49](https://github.com/user-attachments/assets/b54df839-e1ae-4577-a1a0-62fcb4293ede)

### Minimal config

```dosini
[module/title]
type = internal/xwindow

; Available tags:
;   <label> (default)
format = <label>
format-prefix = 
format-foreground = ${color.white}

;locale = "zh_CN.UTF-8"

; Available tokens:
;   %title%
; Default: %title%
label = "%title%"
label-maxlen = 200

; Used instead of label when there is no window title
label-empty = " Desktop"
```

### Expected behavior

I also set  locale in Module/bspwm , but it doesn't work.
Module/xwindow can show same as  WM_NAME(UTF8_STRING) from command xprop .

### Actual behavior

polybar  Module/xwindow print  %title%  information with missing Chinese characters

### Window Manager and Version

bspwm -v 0.9.10

### Linux Distribution

debian 13

### Polybar version

```text
jazu@debian:~$ polybar -vvv
polybar 3.7.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Debian package, build flags removed from output for build reproducibility
You can refer to the build logs of your package at:
https://buildd.debian.org/status/package.php?p=polybar
```

### Additional Context / Screenshots

The following figure shows the specific configuration
![2024-07-29_22-40_1](https://github.com/user-attachments/assets/8aa128c0-b48b-41ed-9c38-743c2aabeed7)
![2024-07-29_22-40](https://github.com/user-attachments/assets/03f0727e-8214-4d2c-a00f-875cdaf94c79)

**Comment by patrick96** [comment]
I don't think any of your fonts support chinese characters. Polybar probably produces a bunch of warnings for that.
You should use a font that support chinese characters, e.g. [Noto CJK](https://github.com/notofonts/noto-cjk).

Also have a look at our [font debugging page](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues)
