### ISSUE TITLE
systray as a module

### ISSUE THREAD

**Issue by eoli3n** [polybar/polybar#314]
Systray is placed by var ``tray = right|left``

I think that it could be a nice thing to make it as a module. To be able to place it where we want, and to duplicate it (don't think it is possible, just wondering).

**Comment by jaagr** [comment]
it's not possible to duplicate it, but I've started to work on a systray module...

**Comment by kevlar1818** [comment]
@jaagr I'm eagerly awaiting this feature. Any word on its progress?

**Comment by jaagr** [comment]
@kevlar1818 I've been very busy lately so I haven't had much time over for development, but I will try to finish it once I get some bugs fixed. I might also commit my work-in-progress branch for the feature so that others may help complete it.

**Comment by SuperPrower** [comment]
Hi, any updates on systray as module? I understand it's probably is most painful module for you to work on, but making it module will fix so much problems, like actual centering of modules in center or ability to place it somewhere in right, but not in the edge of the screen.

**Comment by 132ikl** [comment]
@jaagr Any update on the systray module? It's been quite a while now.

**Comment by mhham** [comment]
Yes, this feature would be a very nice addition to polybar !

**Comment by kevlar1818** [comment]
@jaagr Any updates on this?

**Comment by Arignir** [comment]
Would be a cool feature, yep

**Comment by zjeffer** [comment]
@jaagr Still working on this module? I'd really like this feature :)

**Comment by Alekaei** [comment]
Commenting to show support and need for this feature

**Comment by patrick96** [comment]
I think NBonaparte did some work on this (see #913). This also relies on us finishing #1088 first.

**Comment by jjzmajic** [comment]
Any updates on this in 2020?

**Comment by chief-wrench** [comment]
Came here to vote for this feature.

**Comment by Masacaai** [comment]
Commenting to show support for this feature!

**Comment by tpurde** [comment]
Any news on this?

**Comment by TaylanTatli** [comment]
Please make this possible.

**Comment by BRA1L0R** [comment]
Bump as this would be super useful

**Comment by ignaudioz** [comment]
bump

**Comment by iPocket** [comment]
Bumping to help this feature request get acknowledged :)

**Comment by Vlek** [comment]
Bumping. Is there a bounty on this or should I make a new one?

**Comment by patrick96** [comment]
@Vlek Sorry for not replying to this earlier. We never issued bounties before. There is currently an effort by @raffael0 to make the current tray a module. Once that is finished, I'd be happy to coordinate a bounty payout between the two of you through our [collective](https://opencollective.com/polybar).

You would then make a one-time donation and @raffael0 would submit an expense for that amount that we then pay out.

**Comment by SamuelGogarty** [comment]
Looking forward to this, the normal systray is buggy on fluxbox. using this module would likely solve my issues.

**Comment by Prayag2** [comment]
Any updates on this?

**Comment by Kyesarri** [comment]
> Bumping in 2023.
> 
> Using KDE and i get the error that the systray is already managed in another window. Would love to have the ability to show it in polybar

Run this as a startup script:

#!/bin/sh
sleep 10 &
killall xembedsniproxy

Happily running polybar under KDE with the systray

**Comment by patrick96** [comment]
@Vlek Yes, this has now finally made into a stable release in version 3.7.0.

The tracking issue for the feature is #2689 and the initial modularization work was done in #2595.

@raffael0 Do you want to receive this bounty through the [polybar collective](https://opencollective.com/polybar/)? It seems to be really easy, they even auto-generate the invoice for you. Payouts can be made through direct bank transfer or paypal.

@Vlek Appreciate you paying out a bounty for this 😃. If Raffael accepts, you can make a one-time donation to the collective with the desired amount and I will coordinate this being paid out through the collective's expense system.

**Comment by raffael0** [comment]
Wow. Yeah i'll gladly take the bounty in any way that is easiest for you.
Thank you! Just let me know what I have to do

**Comment by patrick96** [comment]
That's great! Once @Vlek sends the money, I can create an invoice invitation for you and you simply have to fill out the payment details. Is your protonmail email ok?

@Vlek You can now make a "Custom Contribution" with the desired amount here: https://opencollective.com/polybar/contribute

**Comment by Vlek** [comment]
@patrick96 @raffael0 sent. $100 for the bounty, $20 toward Polybar. Thank you both!

![image](https://github.com/polybar/polybar/assets/15008772/a5a94928-889d-46d8-b382-883bf57d1da3)

**Comment by patrick96** [comment]
That's very generous, thank you very much!

@raffael0 I have sent you an invoice invitation, let me know if everything works out.

**Comment by raffael0** [comment]
I just wanted to let you know that I received the money. Thank you @Vlek for the generous bounty and @patrick96 for being a great maintainer and organizing the payout!
