### ISSUE TITLE
Can you add keyboard layout variant?

### ISSUE THREAD

**Issue by ChoiZ** [polybar/polybar#316]
When I write in French I use Bépo layout (like dvorak for french language)

$ setxkbmap -query                
rules:      evdev
model:      pc105
layout:     fr
variant:    bepo

How can I display "fr (bepo)" in my polybar?

I can see there's 3 variables in the module/xkeyboard.cpp:
%name%
%layout%
%number%

Is it possible to add the variant variable?

Regards

**Comment by jaagr** [comment]
Hi,

Isn't it visible when using the `%name%` token?

~~~ dosini
label-layout = %name%
~~~

**Comment by ChoiZ** [comment]
Nope :(

**Comment by jaagr** [comment]
Mine says `French (Bepo, ergonomic, Dvorak way)`... a bit long but you can create your own keyboard def and change it to whatever you like. See `man setxkbmap` and `man xkbcomp`

**Comment by jaagr** [comment]
> I like how it says ergonomic... for someone who never used dvorak it sure is painful (took a while to get back ;P)

**Comment by ChoiZ** [comment]
Ok when I run `setxkbmap fr bepo` I've got the same thing `French (Bepo, ergonomic, Dvorak way)`.

Is it easy to get only "bepo" value, but how can assign this value thanks to `setxkbmap -query |grep variant|cut -d ' ' -f 5` to the variable %variant% in you xkeyboard.cpp ?

**Comment by jaagr** [comment]
The xkb extension doesn't expose a way to specifically get the variant used from what I can see.

**Comment by NBonaparte** [comment]
One solution to this is to parse whatever is in the parentheses and set that to a `%variant%` token.

**Comment by acarril** [comment]
> One solution to this is to parse whatever is in the parentheses and set that to a `%variant%` token.

How would you do this? I'm sorry, but I don't know much about Polybar module config.

**Comment by patrick96** [comment]
@acarril This was a comment about how this could be implemented. This is not a feature in polybar yet.

**Comment by acarril** [comment]
Oh ok, thanks!
