### ISSUE TITLE
[Bug]: polybar disables second screen when placed on bottom

### ISSUE THREAD

**Issue by thebl1985** [polybar/polybar#3171]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I just installed polybar, default config with the bar placed on bottom.
```
bottom = true
```
After this, I cannot change or move windows to the second monitor, which is placed below the primary one.

I tried `override-redirect = true`, which fixes the issue, but with this option polybar covers the windows.

### Minimal config

```dosini
I am using the default configuration generated by polybar and copied from `/etc/polybar/config.ini`
```

### Polybar log

```text
notice: Listening for IPC messages (PID: 19226)
notice: Loading module 'xworkspaces' of type 'internal/xworkspaces'
notice: Loading module 'xwindow' of type 'internal/xwindow'
notice: Loading module 'filesystem' of type 'internal/fs'
notice: Loading module 'pulseaudio' of type 'internal/pulseaudio'
notice: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
notice: Loading module 'xkeyboard' of type 'internal/xkeyboard'
notice: Loading module 'memory' of type 'internal/memory'
notice: Loading module 'cpu' of type 'internal/cpu'
notice: Loading module 'wlan' of type 'internal/network'
notice: module/wlan: Discovered wireless interface wlp0s20f3
notice: Loading module 'eth' of type 'internal/network'
notice: module/eth: Discovered wired interface enp0s31f6
notice: Loading module 'date' of type 'internal/date'
notice: Loading module 'systray' of type 'internal/tray'
notice: Loaded 11 modules
```
```


### Expected behavior

I want to be able to move and start windows in the second monitor, which is placed underneath the primary monitor.

### Actual behavior

polybar blocks windows from start or being moved to the second monitor unless I use the option `override-redirect = true`, but that makes polybar covers the screen.

### Window Manager and Version

GNOME Shell 46.0

### Linux Distribution

Ubuntu 24.04

### Polybar version

```text
polybar 3.7.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

### Additional Context / Screenshots

Edit - found a relevant (but 2 years old) comment online with this issue

http://reddit.com/r/Polybar/comments/vz9271/polybar_restricts_my_windows_to_only_one_monitor/

**Comment by patrick96** [comment]
This is a fundamental limitation of the so-called ["struts" specification](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html#id-1.6.11) that polybar uses to tell window managers to leave space for its window.

There is an `enable-struts` option in the bar section that can be used to turn them off.

Those struts basically define how many pixels from the edge of the screen should be reserved. Unfortunately, "screen" here is not a monitor, but your entire screen real-estate. So with your two monitors and polybar at the bottom of your upper monitor (in the middle of the entire "screen") will tell your window manager to reserve everything from the bottom to the top-edge of the bar.

Relevant discussion in #2769 and the reddit post you linked.
