### ISSUE TITLE
network module : dynamic interface

### ISSUE THREAD

**Issue by eoli3n** [polybar/polybar#339]
Is there a way to add var ```%default_interface%``` to auto detect which interface connects to internet with network module ?
```
[module/networkspeedup]
type = internal/network
interface = %default_interface%
label-connected = "%upspeed:7%"
format-connected = <label-connected>
format-connected-prefix = " "
format-connected-prefix-foreground = #5b

[module/networkspeeddown]
type = internal/network
interface = %default_interface%
label-connected = "%downspeed:7%"
format-connected = <label-connected>
format-connected-prefix = " "
format-connected-prefix-foreground = #5b
```
as
```
%default_interface% = $(ip route | grep '^default' | awk '{print $5}')
```

**Comment by TaylanTatli** [comment]
+1 for this.

**Comment by rosshadden** [comment]
[This](https://github.com/acleverpun/i3-blocks-contrib/blob/master/network#L19-L22) is what I did in i3blocks, which allows interfaces to be specified with wildcards.   This let me make the instances `instance=wlp*` and `instance=enp*`.

**Comment by BurhanDanger** [comment]
+1.
Until it is implemented I'm using this dirty hack....

```
..........
modules-right = up-speed_eth down-speed_eth up-speed_wifi down-speed_wifi volume cpu battery date
..........
[module/up-speed_eth]
interface = enp8s0
..............
[module/down-speed_eth]
interface = enp8s0
.........
[module/up-speed_eth]
interface = wlo1
..............
[module/down-speed_eth]
interface = wlo1
..............
```
When one interface is down no output is shown for that module.

**Comment by dkasak** [comment]
I just encountered this problem and this would be great to have. I also thought of doing

```
[module/netspeed]
type = module/network
interface = <any interface>
format-disconnected = up: %upspeed% down: %downspeed%
accumulate-stats = true
```

But alas, it doesn't work because `%upspeed%` and `%downspeed%` aren't available in `format-disconnected`.

**Comment by dannycolin** [comment]
In the meantime, if you're distro use `systemd` you can rename your network interface to whatever you want. Have a look to those links : 

- https://www.freedesktop.org/wiki/Softwarae/systemd/PredictableNetworkInterfaceNames/
- https://www.freedesktop.org/software/systemd/man/systemd.link.html

**Comment by dkasak** [comment]
@patrick96 Note the `accumulate-stats = true` in my example, which in my understanding accumulates all bandwidths across all interfaces. The intent was to create a module which always shows the total traffic across all interfaces, regardless of whether the (arbitrary) interface it is bound to is offline or not.

**Comment by patrick96** [comment]
Ah, I understand, maybe we should add those tokens to the disconnected format

**Comment by sflip** [comment]
I found another solution to the problem.

As stated [in the wiki](https://github.com/jaagr/polybar/wiki/Configuration), environment variables can be used in the configuration. So, if you've got a [startup script that launches polybar](https://github.com/jaagr/polybar/wiki#launching-the-bar-in-your-wms-bootstrap-routine), you can set a variable dynamically like this:
```bash
DEFAULT_NETWORK_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n1)
```
and just use it in the configuration like this:
```ini
interface = ${env:DEFAULT_NETWORK_INTERFACE:wlp2s0}
```
where `wlp2s0` is some fallback value.

Hope this helps somebody.

**Comment by patrick96** [comment]
@sflip that's the workaround I would have used as well. If you have a startup script anyway, that would be the way to go in my opinion.

**Comment by soullivaneuh** [comment]
Great solution @sflip, but how are you setting the variable?

I could put this on my `.profile`, but it is not dynamic and could be a problem for laptop switching between eth and wifi.

**Comment by sflip** [comment]
Hey @soullivaneuh! I use [a script](https://github.com/sflip/dotfiles/blob/master/i3/bin/i3-polybar.sh) to start, stop and restart polybar. This script is executed [on startup](https://github.com/sflip/dotfiles/blob/master/i3/config#L233) and on a [window manager keybinding](https://github.com/sflip/dotfiles/blob/master/i3/config#L271).

**Comment by souravdas142** [comment]
> I found another solution to the problem.
> 
> As stated [in the wiki](https://github.com/jaagr/polybar/wiki/Configuration), environment variables can be used in the configuration. So, if you've got a [startup script that launches polybar](https://github.com/jaagr/polybar/wiki#launching-the-bar-in-your-wms-bootstrap-routine), you can set a variable dynamically like this:
> 
> ```shell
> DEFAULT_NETWORK_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n1)
> ```
> 
> and just use it in the configuration like this:
> 
> ```ini
> interface = ${env:DEFAULT_NETWORK_INTERFACE:wlp2s0}
> ```
> 
> where `wlp2s0` is some fallback value.
> 
> Hope this helps somebody.

can't we left it for handling with network-manager hook? something like I made a bash script for xfce4panel [netload](https://github.com/souravdas142/dot_config_shell_files/blob/master/xfce4Config/setNetloadIface.sh) . so when ever network-manager connects to a ssid throgh some interface, then that interface will only updated to the polybar config file.

**Comment by patrick96** [comment]
@souravdas142 That is also possible, but it may be a bit overkill to let your script do a search and replace inside your config file.

**Comment by souravdas142** [comment]
@patrick96  ok... take a look on i3-block contrib [bandwidth2](https://github.com/vivien/i3blocks-contrib/tree/master/bandwidth2) module.  how he implemnted : [#305530276](https://github.com/polybar/polybar/issues/339#issuecomment-305530276). I just [patched](https://github.com/souravdas142/dot_config_shell_files/tree/master/dotfiles/polybar/modules/bandwidth2) his code and removed all  pango markup for now. and using that module in my polybar. Though  I can't see any colors dynamically changing with the value increased decrease but thats not an issue for me. I kindly request you to bring **pango markup** support for polybar  to support his original module directly.

**Comment by beanaroo** [comment]
Would this enhancement address the use case of network interfaces that don't exist yet when starting polybar?

I have an ethernet port on my laptop dock and currently the module is disabled if the laptop is not docked when starting polybar.

**Comment by zampierilucas** [comment]
hey guys, this is my attempt to it, #2084, it works by setting "interface=<default-interface>", tell me what you think.

Can a maintainer move [this card](https://github.com/polybar/polybar/projects/1#card-5508350) to in progress? :smile:

**Comment by awsms** [comment]
> @patrick96 ok... take a look on i3-block contrib [bandwidth2](https://github.com/vivien/i3blocks-contrib/blob/master/bandwidth2/bandwidth2.c#L99-L112) module. how he implemnted : [#305530276](https://github.com/polybar/polybar/issues/339#issuecomment-305530276) He is monitoring on all interface available in a compuer. I just [patched](https://github.com/souravdas142/dot_config_shell_files/blob/master/dotfiles/polybar/modules/bandwidth2/bandwidth2.c#L97-L109) his code and removed all pango markup for now. and using that module in my polybar. Though I can't see any colors dynamically changing with the value increased decrease but thats not an issue for me. I kindly request you to bring **pango markup** support for polybar to support his original module directly.

hey, do you still have that patch?

**Comment by souravdas142** [comment]
@awsms  yes I have and still I am using it. see [bandwidth2](https://github.com/souravdas142/dotfiles/tree/master/.config/polybar/modules/bandwidth2)
