### ISSUE TITLE
Dynamic background color (battery)

### ISSUE THREAD

**Issue by mikeroll** [polybar/polybar#415]
Is there any option of having different background color of a label depending on battery percentage?
I know can have different background colors with a ramp, but I cannot display a percentage value on top of that:
```ini
ramp-capacity-0-background = #75D18581
ramp-capacity-1-background = #75D48F81
...
ramp-capacity-0 = "%percentage%" ; no way :(
```

**Comment by jaagr** [comment]
That's currently not supported, but it's a good idea to add it.

**Comment by fikovnik** [comment]
It would be actually great to have this for other values as well - cpu, memory, etc.

**Comment by julio-b** [comment]
If anyone is still interested for this, I have been using this workaround:

```dosini
[module/battery]
type = internal/battery
...
format-charging = <ramp-capacity> <label-charging>%{B-}
format-discharging = <ramp-capacity> <label-discharging>%{B-}
ramp-capacity-0 = %{B#e01212}
ramp-capacity-1 = %{B#e06912}
ramp-capacity-2 = %{B#e0b412}
ramp-capacity-3 = %{B#b7e012}
ramp-capacity-4 = %{B#3be012}
...

```

![2019-10-10-021157_65x36_scrot](https://user-images.githubusercontent.com/16379308/66527260-fda1d880-eaea-11e9-9855-abbaacb8c6a7.png) ![2019-10-10-021330_62x31_scrot](https://user-images.githubusercontent.com/16379308/66527265-04c8e680-eaeb-11e9-800d-2a1bac976b33.png)

As you can see, it is possible to achieve the desired behavior by combining format-tags with ramps.

**Comment by patrick96** [comment]
Closing in favor of #1752 and #2223
