### ISSUE TITLE
Referencing another module from menu-module

### ISSUE THREAD

**Issue by szymonmaszke** [polybar/polybar#421]
Hello, I would like to know whether (and if so, than how) it's possible to do it.
Example: Menu including temperature, CPU usage etc., opened via click.

Haven't seen in it in the wiki, tried to reference variable 'lable' from temperature module, but it doesn't display it. 

Cheers for great bar, much respect.

**Comment by jaagr** [comment]
It is currently not supported, but I'm planning on adding module control to the ipc which would make this possible.

**Comment by DrumsnChocolate** [comment]
This would be very great if supported. I just tried to incorporate wlan and eth in one menu, which I could then expand and collapse instead of having it take up space all the time. I guess a quick solution for now would be leaving either format empty when they are disconnected

**Comment by alkaef** [comment]
Bump

**Comment by MonAaraj** [comment]
It has been about 4 years since this issue was made, any updates?

**Comment by patrick96** [comment]
In version 3.6 you can now control module visibility through [module actions](https://polybar.readthedocs.io/en/stable/user/actions.html#all-modules). So something like this should be doable now, though the menu module may not be the best thing to use here. I'd recommend a single text module that toggles the target module with `click-left`.
