### ISSUE TITLE
number of open windows in a specific workspace

### ISSUE THREAD

**Issue by N4d4** [polybar/polybar#604]
Is possible to add the number of open windows per workspace  in the xworkspace module?

I want to do something like this
![istantanea_2017-06-02_19-09-44](https://cloud.githubusercontent.com/assets/19915501/26736631/3c9894c6-47c7-11e7-8036-8e86b797831b.png)

**Comment by patrick96** [comment]
There is currently no way to do this.
Feel free to implement it though and send a pull-request ;)

**Comment by lepisma** [comment]
Hey, this is exactly what I was looking for and have a personal fork [here](https://github.com/lepisma/polybar/tree/nwin-for-xworkspaces).

Looks like the following

![Screenshot_20200809_115623](https://user-images.githubusercontent.com/2487306/89726388-b8667400-da37-11ea-950d-d13653b9c529.png)

Not sure if the code is of good quality but doing a PR to take from here.
