### ISSUE TITLE
Label Gradient

### ISSUE THREAD

**Issue by mlamberti** [polybar/polybar#682]
Hey, thanks for the awesome work!

Using the CPU/Memory modules with gradient bars I noticed that the bar's foreground color overflows to the next module, unless it's foreground color is explicitly defined.

This gave me the idea that it would be nice to have a label-gradient, just like the bar gradient, but coloring the label.

While my CPU is idle there will be written "CPU 0%" in white, and when the load rises it get's red following a defined gradient. By this one could have pretty small indicators, just using a color instead of bars and numbers.

**Comment by patrick96** [comment]
The thing with the overflowing colors is a known issue and is discussed in #666 and #639 (tl;dr use the latest release)

I think the label gradient is a great idea, I didn't even know that the progressbar could do that.
However I don't have time at the moment to implement new features, and I think jaagr is quite busy as well. If you want to take a stab at it, I'd say go for it, unfortunately I cannot guarantee that it will be merged.

**Comment by patrick96** [comment]
I think the ability to use tokens inside the ramp (#2223) would make this achievable.

**Comment by patrick96** [comment]
Closing in favor of #2223
