### ISSUE TITLE
Wrong icons displayed in the tray

### ISSUE THREAD

**Issue by Nikki1993** [polybar/polybar#794]
The whole situation is confusing as hell. I am using i3 + Polybar on a XPS 15 9560 laptop 4k display. Naturally, HiDPI is a nightmare of mine so I "fixed" it by appending following lines to the 
`/etc/profile`
file
```
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
```
However, I also use papirus icons that seem to be recognized everywhere except for polybar tray. 

Whats even more interesting is that if I remove my modifications to profile, the correct papirus wifi tray icon is used by obviously my HIDPI is messed up. Menus scale correctly but application titlebar and icons run at native 4k resolution. 

Here is the screenshot of an "wrong" icon when scaling enabled (see wifi icon) 

![tray](https://user-images.githubusercontent.com/1446529/31316049-df28f012-ac2d-11e7-9703-8396f4b9134e.png)

Any idea how to make polybar use correct icon with scaling set via profile?

**Comment by patrick96** [comment]
You can probably disable the scaling for polybar only, by executing the following before starting polybar
```bash
unset GDK_SCALE
unset GDK_DPI_SCALE
```

**Comment by Nikki1993** [comment]
Hm, I seem to be having troubles unsetting env variables. I tried appending unset to i3 config before running the script, polybar won't start.

I tried adding unset to the script I use to launch and restart polybar 

```
#!/usr/bin/env sh

unset HERE

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch polybar
MONITOR=eDP-1 polybar top &
```

Bar stay the same with incorrect icons. How would I go about executing unset @patrick96 ?

**Comment by patrick96** [comment]
Try running polybar manually, this way you can verify that the values were actually unset.

**Comment by Nikki1993** [comment]
I ran unset on both and then ran my polybar script, bar still shows wrong icons so I am assuming it did not work.

**Comment by patrick96** [comment]
This is very strange. If `GDK_SCALE` and `GDK_DPI_SCALE` are set in `/etc/profile` then polybar displays the wrong icon, even if the variables are not set for the polybar process.
I don't really know how polybar handles the tray, but this makes me think that it relies on an external process that has those variables set and which then returns some wrong values.

**Comment by Nikki1993** [comment]
Well, anyway I can help debug the situation let me know. For now, living with fugly icons :D

**Comment by patrick96** [comment]
Thanks for the offer. Right now I don't really have time to go into this. Also I think at some point we need to just rewrite the whole tray thing because there are so many issues with it (Just look at the [`tray`](https://github.com/jaagr/polybar/labels/tray) tag)

**Comment by patrick96** [comment]
We have recently implemented a new tray that runs as a module where we rewrote a lot of the rendering code (#2609, #2689).

Some of these rendering issues may be fixed by this, but there are still some that may occur (I have been struggling to fix the dropbox icon using arbitrary images as its background data).
I am going to close this issue, if you experience rendering issues like these while using the new tray module (the old tray using `tray-position` still has the same issues), please report the application and your polybar version (`polybar -v`) together with a screenshot in #2933.
