### ISSUE TITLE
xmonad with pin-workspaces

### ISSUE THREAD

**Issue by sl0thentr0py** [polybar/polybar#840]
Firstly, thanks a lot for this wonderful bar!

When using `xworkspaces` with `pin-workspaces = true` in xmonad, I get the following error.

```
error: Disabling module "xworkspaces" (reason: The WM does not support _NET_DESKTOP_VIEWPORT (required when `pin-workspaces = true`))
```

Has anybody made this work with xmonad?

Digging around a bit, I found xmonad/xmonad-contrib#150 and it's unclear if they are going to support it. If someone can clarify the terminology and how `polybar` uses the `_NET_DESKTOP_VIEWPORT` property, I could attempt to modify the corresponding xmonad `logHook`.

**Comment by patrick96** [comment]
I actually don't know why `pin-workspaces` requires `_NET_DESKTOP_VIEWPORT`. Can you try to remove the check that disables the module, if  `_NET_DESKTOP_VIEWPORT` is not supported, and try to run polybar on xmonad with `pin-workspaces = true` and see if it works?

The check is located here:
https://github.com/jaagr/polybar/blob/1158d5d889fa9b4ed3a9ae36867ef2c45330f21b/src/modules/xworkspaces.cpp#L46-L48

**Comment by jaagr** [comment]
`_NET_DESKTOP_VIEWPORT` is used because it's as far as I know the only standard way of figuring out what monitor the workspace belongs to.

It might be better to create a new module for xmonad if it has some internal ipc or something similar.

**Comment by sl0thentr0py** [comment]
Hey, thanks for the replies! I only have access to an external monitor at work and I haven't been able to find  time to test this in the last 2 weeks. :/

I'm going to first try just removing the check and test this on Monday. 
I also found your patch for bspwm [here](https://github.com/baskerville/bspwm/commit/51732195796f1b4c97cfacdd6ddb8937a5c73bff). If the disabling doesn't work, I will try to get xmonad to spew out the same info. Will update after I test this.
