### ISSUE TITLE
xworkspace Improvements

### ISSUE THREAD

**Issue by kronn** [polybar/polybar#874]
I recently switched from xmobar/trayer to polybar and so far, I like it. The only thing I am missing is support for "occupied workspaces" in the xworkspaces module. Given the choice between complaining and demanding or rolling up the sleeves and improve things myself, I opt for the later. 

I shortly looked into the existing code and I have a vague feeling that there is no technical blocker preventing this. 

My plan is to go over the complete list of windows and lookup the given workspace it is assigned to. Since this already asks xproperties of every window, it could also lead to a solution for #448. It also seems that I could build upon the work for the urgency-handling (#449). The urgency-handling seems to implement all building blocks I would need.

Before I go ahead, I want to make sure if this plan is sound or if I am missing something.

**Comment by NBonaparte** [comment]
That was the way I planned to implement it, and it seemed to be possible when I looked into it a while back.
