### ISSUE TITLE
interval option for exec-if

### ISSUE THREAD

**Issue by Nervengift** [polybar/polybar#943]
I would like to have an additional parameter to the `custom/script` module that allows me to set an interval for the `exec-if` command that is different from the standard interval (a backoff timer for when the command fails).

One of my use cases wowuld be [my script for showing information about the train I'm in](https://gist.github.com/Nervengift/6a49faecfc561297ddfe71f32a1c996c): While I want the information to be refreshed every few seconds, most of the time I'm not on a train and so the check should not run too often.

My implementation idea would be:

* add a `exec-if-backoff` parameter (or maybe `interval-exec-if`, `interval-backoff`?)
* if the `exec-if` command fails and `exec-if-backoff` is present, wait for the configured backoff time (instead of `interval`) before runing it again
* when `exec-if` succeeds, execute `exec` then wait for `interval`

**Comment by patrick96** [comment]
Added to the list.
For now you can probably implement the same functionality inside the script itself.
